Azure/iotedge

builds/checkin/dotnet.yaml
* Adds windows as a platform for the dotnet checkin tests
=> Add windows build to dotnet check

edge-agent/docker/linux/amd64/Dockerfile, edge-agent/docker/linux/arm32v7/Dockerfile, edge-agent/docker/linux/arm32v7/base/Dockerfile, edge-agent/docker/windows/amd64/Dockerfile, edge-hub/docker/linux/amd64/Dockerfile, edge-hub/docker/linux/arm32v7/Dockerfile, edge-hub/docker/linux/arm32v7/base/Dockerfile, edge-hub/docker/windows/amd64/Dockerfile, edge-modules/SimulatedTemperatureSensor/docker/linux/amd64/Dockerfile, edge-modules/SimulatedTemperatureSensor/docker/linux/arm32v7/Dockerfile, edge-modules/SimulatedTemperatureSensor/docker/linux/arm32v7/base/Dockerfile, edge-modules/SimulatedTemperatureSensor/docker/windows/amd64/Dockerfile, edge-modules/TemperatureFilter/docker/linux/amd64/Dockerfile, edge-modules/TemperatureFilter/docker/linux/arm32v7/Dockerfile, edge-modules/TemperatureFilter/docker/linux/arm32v7/base/Dockerfile, edge-modules/TemperatureFilter/docker/windows/amd64/Dockerfile, edge-modules/load-gen/docker/linux/amd64/Dockerfile, edge-modules/load-gen/docker/linux/arm32v7/Dockerfile, edge-modules/load-gen/docker/windows/amd64/Dockerfile
Updating dotnet base images to 2.1.2. Also updating the base image of the arm image to preview009.
=> Update dotnet base image to 2.1.2

Microsoft.Azure.Devices.Edge.sln, edge-modules/MessagesAnalyzer/Controllers/ReportController.cs, edge-modules/MessagesAnalyzer/DeviceReport.cs, edge-modules/MessagesAnalyzer/MessageDetails.cs, edge-modules/MessagesAnalyzer/MessagesAnalyzer.csproj, edge-modules/MessagesAnalyzer/MessagesCache.cs, edge-modules/MessagesAnalyzer/MissedMessagesDetails.cs, edge-modules/MessagesAnalyzer/ModuleReport.cs, edge-modules/MessagesAnalyzer/PartitionReceiverHandler.cs, edge-modules/MessagesAnalyzer/Program.cs, edge-modules/MessagesAnalyzer/Reporter.cs, edge-modules/MessagesAnalyzer/Settings.cs, edge-modules/MessagesAnalyzer/Startup.cs, edge-modules/MessagesAnalyzer/StatusCode.cs, edge-modules/MessagesAnalyzer/config/settings.json, edge-modules/MessagesAnalyzer/docker/linux/amd64/Dockerfile, edge-modules/MessagesAnalyzer/docker/linux/arm32v7/Dockerfile, edge-modules/MessagesAnalyzer/docker/windows/amd64/Dockerfile, edge-modules/load-gen/Program.cs, scripts/linux/buildBranch.sh
Analyzer module:
- analyzes messages that were sent by modules that are not in the exclude list and contain in properties sequenceNumber and batchId.
- based on sequenceNumber checks if there are messages that were not received by IoTHub.
- HTTP endpoint returns the report with count for all messages received and count of missed messages if any were missed.
=> Analyzer module

scripts/linux/buildBranch.sh, smoke/IotEdgeQuickstart/Program.cs, smoke/IotEdgeQuickstart/Quickstart.cs, smoke/IotEdgeQuickstart/details/Details.cs, stress/deployment.template.json
- Added a deployment template for stress testing
- Modified quick start to use a deployment file if provided as input
=> Add a deployment template and modify quickstart to take a deployment file

scripts/windows/setup/IotEdgeSecurityDaemon.ps1
This change adds several parameters to the installer script, all of which give you more control over the contents of `config.yaml`. We anticipate that these parameters will not be used in the typical scenario, but they will allow us to bring up the smoke tests on Windows.
The options are:
- `ArchivePath`: The path to a local folder or a .zip file containing all the installation files. If this parameter is not given, then the script will download the .zip file from a known location as it does today.
- `AgentImage`: The full name of the IoT Edge Agent image to pull and start. If not given, then the script will use the default image, `mcr.microsoft.com/azureiotedge-agent:1.0`.
- `Username`, `Password`: These two parameters must be used together or not at all. If given, then `AgentImage` must …
=> Add more granular options to daemon installer script for Windows

edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/linkhandlers/EventsLinkHandler.cs, edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Amqp.Test/EventsLinkHandlerTest.cs
Small fix to the logic to create the individual AMQP messages from a batched AMQP message.
Added tests for the scenario as well.
=> Fix AMQP Batch message processing

edge-modules/MessagesAnalyzer/MessagesAnalyzer.csproj, edge-modules/MessagesAnalyzer/PartitionReceiverHandler.cs, edge-modules/MessagesAnalyzer/Program.cs, edge-modules/MessagesAnalyzer/Reporter.cs, stress/deployment.template.json
Changed deployment template to add snitch, analyzer, influxdb modules
Changed logging in analyzer to use logging class from Util
=> Add modules to deployment template & use edge util logging

tools/snitch/Cargo.lock, tools/snitch/snitcher/Cargo.toml, tools/snitch/snitcher/src/client.rs, tools/snitch/snitcher/src/docker.rs, tools/snitch/snitcher/src/error.rs, tools/snitch/snitcher/src/lib.rs, tools/snitch/snitcher/src/main.rs, tools/snitch/snitcher/src/report.rs, tools/snitch/snitcher/src/settings.rs, tools/snitch/snitcher/src/settings.yaml, tools/snitch/snitcher/src/uds/mod.rs, tools/snitch/snitcher/src/uds/uri.rs
- Add backtrace logging when env var RUST_BACKTRACE is 1
- Add additional logging
- Bug fixes
=> Various fixes in snitch module

scripts/windows/setup/IotEdgeSecurityDaemon.ps1
Not doing so seems to cause an issue on some systems.
=> create iotedge directory before calling expand-archive

smoke/IotEdgeQuickstart/details/Details.cs, smoke/IotEdgeQuickstart/e2e_deployment_files/module_to_functions_deployment.template.json
This contains Functions e2e test template + GetDevice Async after creating the device to make sure identity got created and cache updated.
=> Adding Functions e2e test template

builds/checkin/edgelet.yaml
Comment out edgelet arm build since it is failing consistently on vsts due to some infrastructure issue.
=> Temporarily disable iotedged arm build

edgelet/edgelet-core/src/error.rs
When a user accidentally uses a device that is not an edge device, this error message is generated, so it's very useful to have the error message ask if this is an edge device.
=> Is this an Edge device?

edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Test/CloudConnectionProviderTest.cs, edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.E2E.Test/ProtocolHeadFixture.cs
=> Fix EdgeHub CI Tests

edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudProxy.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/DeviceScopeIdentitiesCache.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/TwinManager.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/device/DeviceMessageHandler.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/routing/RoutingEdgeHub.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/DeviceProxy.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/MessagingServiceClient.cs
Add some additional logs
Some exceptions are expected when device is offline. Convert those to debug.
=> EdgeHub: Clean up logs

edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/DeviceScopeApiClient.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/authenticators/CloudTokenAuthenticator.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/authenticators/DeviceScopeTokenAuthenticator.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/ConnectionReauthenticator.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/DeviceScopeIdentitiesCache.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/EdgeHubConnection.cs
Add more logs, and convert some logs to information to get enough information for debugging.
=> EdgeHub: Add additional logs 

edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.IoTHub.Test/EdgeAgentConnectionTest.cs, edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.E2E.Test/EdgeToDeviceMethodTest.cs
* Increases delay for direct method tests
=> Improve flaky CI tests

edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.E2E.Test/EdgeToDeviceMethodTest.cs
This should address the CI method test failures.
=> Create new devices for the device/module method tests

edge-modules/functions/binding/src/Microsoft.Azure.WebJobs.Extensions.EdgeHub/Microsoft.Azure.WebJobs.Extensions.EdgeHub.csproj, nuget.config
Update functions runtime to rc1 and remove myget source
=> Update functions runtime nuget package

scripts/windows/setup/IotEdgeSecurityDaemon.ps1
Adds an optional -Proxy parameter to the Install-SecurityDaemon command.
=> Support proxy server in Windows install script

edge-hub/README.md
Add steps to run direct method sample app with Edge hub using Visual Studio in Edge hub readme
=> Update Edge hub readme

edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/Microsoft.Azure.Devices.Edge.Agent.IoTHub.csproj, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/Microsoft.Azure.Devices.Edge.Hub.Amqp.csproj, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.csproj, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/Microsoft.Azure.Devices.Edge.Hub.Core.csproj, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Http/Microsoft.Azure.Devices.Edge.Hub.Http.csproj, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/Microsoft.Azure.Devices.Edge.Hub.Mqtt.csproj, edge-modules/DirectMethodReceiver/DirectMethodReceiver.csproj, edge-modules/DirectMethodSender/DirectMethodSender.csproj, edge-modules/MessagesAnalyzer/MessagesAnalyzer.csproj, edge-modules/SimulatedTemperatureSensor/SimulatedTemperatureSensor.csproj, edge-modules/TemperatureFilter/TemperatureFilter.csproj, edge-modules/functions/binding/src/Microsoft.Azure.WebJobs.Extensions.EdgeHub/Microsoft.Azure.WebJobs.Extensions.EdgeHub.csproj, edge-modules/load-gen/load-gen.csproj, smoke/IotEdgeQuickstart/IotEdgeQuickstart.csproj, smoke/LeafDevice/LeafDevice.csproj
Update C# and PG nugets for the 1.0.3 release
=> Update SDKs for 1.0.3 release

edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/Microsoft.Azure.Devices.Edge.Agent.IoTHub.csproj, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/Microsoft.Azure.Devices.Edge.Hub.Amqp.csproj, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.csproj, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/Microsoft.Azure.Devices.Edge.Hub.Core.csproj, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Http/Microsoft.Azure.Devices.Edge.Hub.Http.csproj, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/Microsoft.Azure.Devices.Edge.Hub.Mqtt.csproj, edge-modules/DirectMethodReceiver/DirectMethodReceiver.csproj, edge-modules/DirectMethodSender/DirectMethodSender.csproj, edge-modules/MessagesAnalyzer/MessagesAnalyzer.csproj, edge-modules/SimulatedTemperatureSensor/SimulatedTemperatureSensor.csproj, edge-modules/TemperatureFilter/TemperatureFilter.csproj, edge-modules/functions/binding/src/Microsoft.Azure.WebJobs.Extensions.EdgeHub/Microsoft.Azure.WebJobs.Extensions.EdgeHub.csproj, edge-modules/load-gen/load-gen.csproj, smoke/IotEdgeQuickstart/IotEdgeQuickstart.csproj, smoke/LeafDevice/LeafDevice.csproj
* Update C# SDKs - Device to version 1.18.1 and Service to 1.17.1
* Update PG nuget
=> Update SDKs for new release

edge-agent/README.md
1. fix config source option
2. add default behavior for network id
=> update edge agent readme

edgelet/hsm-sys/azure-iot-hsm-c/src/edge_pki_openssl.c, edgelet/hsm-sys/azure-iot-hsm-c/tests/edge_openssl_pki_ut/edge_openssl_pki_ut.c
Changes here obtain the user supplied SAN entries and adds these to the certificate signing request. The SAN entries in the certificate have to comply RFC https://tools.ietf.org/html/rfc5280#section-4.2.1.6.  In case the user passes in an incorrect string, we expected the underlying library to error out. Changes also include supporting tests.
=> Add capability to add SAN entries during certificate generation

smoke/IotEdgeQuickstart/IotEdgeQuickstart.csproj, smoke/IotEdgeQuickstart/Quickstart.cs, smoke/IotEdgeQuickstart/details/IotedgedWindows.cs
Implement Start method of iotedged on Windows for Windows RS4
=> Quickstart for Windows RS4

scripts/windows/build/Publish-Branch.ps1, smoke/IotEdgeQuickstart/details/IotedgedWindows.cs
Add status message and publish e2e template files.
=> E2E tests changes for Windows

edgelet/edgelet-http-mgmt/src/error.rs, edgelet/edgelet-http-mgmt/src/server/module/mod.rs
We recently began seeing a problem where iotedged couldn't restart if it didn't give edgeAgent time to gracefully shutdown all modules before it went down. This is a problem on Windows where iotedged as a Windows service is terminated by the OS after five seconds.
The problem was that some error translation logic in our iotedged management endpoint was looking in the wrong part of the error coming from our core, and therefore not finding what it was expecting (304 not modified) and returning 500 (internal server error). The fix was to update the translation logic to look in the right place.
I also added a unit test for the 304 error specifically, and updated the existing ones.
=> iotedged should return 304 not 500

builds/ci/libiothsm.yaml
fix CI build; update to run sudo for clean package step as build agent changed to Ubuntu agent pool.
=> fix Libiothsm CI

smoke/IotEdgeQuickstart/details/IotedgedWindows.cs
already set execution policy in machine level; remove it.
=> Update for windows E2E tests

scripts/windows/build/Publish-Branch.ps1
remove x86 build of IotEdgeQuickstart and LeafDevice from publish branch script
=> Fix publish branch script

scripts/windows/setup/IotEdgeSecurityDaemon.ps1
If a user runs `Uninstall-SecurityDaemon -Force` and `C:\ProgramData\iotedge-moby` does not exist (e.g., because the user previously uninstalled), the script will call `docker -SwitchDaemon`, which configures Docker for Windows to use Linux containers. This means that uninstalling our moby can potentially mess with the customer's existing Docker for Windows installation.
The root cause was a function with multiple responsibilities. `Test-IsDockerRunning` checked to see whether a docker service is installed and running, but also switched the daemon to use Linux containers as a side effect. This behavior is only desireable in the install case, not uninstall.
I fixed the bug by sprouting a new function, `Set-ContainerOs`, which gets called immediately after `Test-IsDockerRunning` in the …
=> Don't switch to Linux containers on 2nd uninstall

edgelet/edgelet-http/tests/systemd.rs, edgelet/systemd/src/lib.rs, edgelet/systemd/src/linux.rs
Also deleted a bunch of code that was commented out in
326ef8c0075e66834c82b36fc5551b8ef74f0098
=> Unignore some systemd tests and add pointer to upstream issue.

edge-agent/docker/windows/arm32v7/Dockerfile, edge-agent/docker/windows/arm32v7/base/Dockerfile, edge-hub/docker/windows/amd64/Dockerfile, edge-hub/docker/windows/arm32v7/Dockerfile, edge-hub/docker/windows/arm32v7/base/Dockerfile, edge-modules/DirectMethodReceiver/docker/linux/arm32v7/base/Dockerfile, edge-modules/DirectMethodReceiver/docker/windows/amd64/Dockerfile, edge-modules/DirectMethodReceiver/docker/windows/arm32v7/Dockerfile, edge-modules/DirectMethodSender/docker/linux/arm32v7/base/Dockerfile, edge-modules/DirectMethodSender/docker/windows/amd64/Dockerfile, edge-modules/DirectMethodSender/docker/windows/arm32v7/Dockerfile, edge-modules/MessagesAnalyzer/docker/windows/amd64/Dockerfile, edge-modules/MessagesAnalyzer/docker/windows/arm32v7/Dockerfile, edge-modules/SimulatedTemperatureSensor/docker/windows/amd64/Dockerfile, edge-modules/SimulatedTemperatureSensor/docker/windows/arm32v7/Dockerfile, edge-modules/SimulatedTemperatureSensor/docker/windows/arm32v7/base/Dockerfile, edge-modules/TemperatureFilter/docker/windows/amd64/Dockerfile, edge-modules/TemperatureFilter/docker/windows/arm32v7/Dockerfile, edge-modules/load-gen/docker/windows/amd64/Dockerfile, edge-modules/load-gen/docker/windows/arm32v7/Dockerfile, scripts/windows/build/Create-ArmBase.ps1, scripts/windows/build/Publish-Branch.ps1, scripts/windows/build/Publish-DockerImage.ps1, scripts/windows/build/Publish-DockerImageSuite.ps1
1. build ARM version of iotedgequickstart and leafdevice
2. script to build and push ARM base docker image
3. create docker files for windows ARM images
=> Windows ARM docker images

edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/AmqpWebSocketListener.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/ClientConnectionHandler.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/Authenticator.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/IWebSocketListener.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/identity/service/ServiceAuthentication.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/routing/RoutingEdgeHub.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Http/Adapters/HttpsExtensionConnectionAdapter.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Http/Extensions/HttpContextExtensions.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Http/Extensions/ITlsConnectionFeatureExtended.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Http/Extensions/TlsConnectionFeatureExtended.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Http/middleware/AuthenticationMiddleware.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Http/middleware/WebSocketHandlingMiddleware.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/DeviceIdentityProvider.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/MqttProtocolHead.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/MqttWebSocketListener.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/CommonModule.cs, edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/AuthenticatorTest.cs, edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Http.Test/WebSocketHandlingMiddlewareTest.cs, edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Mqtt.Test/DeviceIdentityProviderTest.cs, edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Mqtt.Test/IdentityTest.cs, edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Mqtt.Test/MqttWebSocketListenerTest.cs, edge-util/src/Microsoft.Azure.Devices.Edge.Util/CertificateHelper.cs
Cleanup of unaddressed comments and resharper warnings.
No functional changes.
=> EdgeHub: Cleanup 

edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.E2E.Test/EdgeHubConnectionTest.cs, edge-modules/TemperatureFilter/docker/windows/amd64/Dockerfile, edge-modules/TemperatureFilter/docker/windows/arm32v7/Dockerfile, scripts/windows/build/Publish-DockerImageSuite.ps1, smoke/IotEdgeQuickstart/details/Details.cs, smoke/IotEdgeQuickstart/details/IotedgedWindows.cs
1. fix temp filter docker file to ensure that pid 1 is used for running temp filter.
2. increase timeout for result verification.
3. add log messages.
4. remove username and password when print out configure command for debugging.
=> Fix Iot Edge Quickstart E2E tests

scripts/linux/buildBranch.sh, scripts/linux/runTests.sh
build solution in build step instead of test step; consistently with Windows build.  Tested with https://msazure.visualstudio.com/One/_build%2Fresults?buildId=19037619&_a=summary.  Will update the pipeline now since it is already broken.
=> Fix CI build on Linux

scripts/windows/setup/IotEdgeSecurityDaemon.ps1
=> Fix windows unistall when there are containers not installed by edge

scripts/windows/setup/IotEdgeSecurityDaemon.ps1
Fixes #655
---
Note: I wasn't able to reproduce the original issue even after changing system locale and display language of my VM - `Get-Acl | % Access | fl * -fo` still listed the identities in English, and the `System.Security.AccessControl.FileSystemAccessRule` constructor still accepted English names.
=> Use SIDs instead of account names when modifying ACLs

builds/misc/images.yaml, builds/misc/templates/image-linux.yaml, builds/misc/templates/image-windows.yaml
* Combines the "build images linux" and "build images windows" builds
* Adds yaml definition for this new build
* Adds step to publish manifest images
* Adds "latest" tag to the image
=> Add "build images" yaml definition

edge-modules/TemperatureFilter/Program.cs
The TempFilter has a wait in the async main method. This causs the threads to block and the callback to receive messages never comes through. 
Changing that to use await.
=> Fix TempFilter module

edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/Microsoft.Azure.Devices.Edge.Agent.IoTHub.csproj, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/Microsoft.Azure.Devices.Edge.Hub.Amqp.csproj, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.csproj, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/Microsoft.Azure.Devices.Edge.Hub.Core.csproj, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Http/Microsoft.Azure.Devices.Edge.Hub.Http.csproj, edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Test/DeviceClientMessageConverterTest.cs, edge-modules/DirectMethodReceiver/DirectMethodReceiver.csproj, edge-modules/DirectMethodSender/DirectMethodSender.csproj, edge-modules/MessagesAnalyzer/MessagesAnalyzer.csproj, edge-modules/SimulatedTemperatureSensor/SimulatedTemperatureSensor.csproj, edge-modules/TemperatureFilter/TemperatureFilter.csproj, edge-modules/functions/binding/src/Microsoft.Azure.WebJobs.Extensions.EdgeHub/Microsoft.Azure.WebJobs.Extensions.EdgeHub.csproj, edge-modules/load-gen/load-gen.csproj, smoke/IotEdgeQuickstart/IotEdgeQuickstart.csproj, smoke/LeafDevice/LeafDevice.csproj
This reverts commit 38ad63d3538a967c7d9b54ea5ccc638cd7a831d4.
=> Revert "Update IoTHub Client/Service SDKs (#698)"

edgelet/Cargo.lock, edgelet/Cargo.toml, edgelet/build/windows/openssl.ps1, edgelet/kube-client/Cargo.toml, edgelet/kube-client/examples/pod-list.rs, edgelet/kube-client/src/client.rs, edgelet/kube-client/src/config.rs, edgelet/kube-client/src/error.rs, edgelet/kube-client/src/kube.rs, edgelet/kube-client/src/lib.rs
This crate adds 3 functions (create/delete deployment, list pods) to be used by a ModuleRuntime for k8s.
=> Adding a kubernetes client for iotedged ModuleRuntime implementation.

edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/routing/CloudEndpoint.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/routing/ModuleEndpoint.cs, edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/routing/CloudMessageProcessorTests.cs, edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/routing/ModuleMessageProcessorTest.cs
* Add messages to failed when processing is cancelled
* Add messages to failed when send to cloud is cancelled
* Clean up
* Address review comments
* Code cleanup
=> Fix missing messages (#722)

edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/modules/AgentModule.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/modules/EdgeletModule.cs
Fix module constructor and calls in Agent Service Program.cs
=> Fix module constructor

edgelet/iotedged/src/lib.rs
Ref #688
---
```
<6>2019-02-01T19:52:53Z [INFO] - Detected HTTPS proxy server https://username:******@example.com/
```
=> Mask the password in the proxy URI before logging it

edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ClientProvider.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ConnectivityAwareClientProvider.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs, edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Test/ClientProviderTest.cs, edge-modules/DirectMethodReceiver/src/Program.cs, edge-modules/DirectMethodSender/src/Program.cs, edge-modules/SimulatedTemperatureSensor/src/Program.cs, edge-modules/functions/binding/src/Microsoft.Azure.WebJobs.Extensions.EdgeHub/EdgeHubAsyncCollector.cs, edge-modules/functions/binding/src/Microsoft.Azure.WebJobs.Extensions.EdgeHub/EdgeHubTriggerBindingProvider.cs, edge-modules/functions/binding/src/Microsoft.Azure.WebJobs.Extensions.EdgeHub/ModuleClientCache.cs, edge-modules/functions/samples/EdgeHubTrigger-Csharp/EdgeHubTriggerCSharp.cs, edge-modules/load-gen/Program.cs, edge-util/src/Microsoft.Azure.Devices.Edge.Util/ClientTokenProvider.cs, edge-util/src/Microsoft.Azure.Devices.Edge.Util/uds/HttpBufferedStream.cs, edge-util/src/Microsoft.Azure.Devices.Edge.Util/uds/HttpRequestResponseSerializer.cs, edge-util/src/Microsoft.Azure.Devices.Edge.Util/uds/HttpUdsMessageHandler.cs, smoke/LeafDevice/details/Details.cs
Remove ConfigureAwait(false) except generated code.
=> Remove ConfigureAwait(false)

edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/Microsoft.Azure.Devices.Edge.Agent.IoTHub.csproj, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/Microsoft.Azure.Devices.Edge.Hub.Amqp.csproj, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.csproj, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/Microsoft.Azure.Devices.Edge.Hub.Core.csproj, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Http/Microsoft.Azure.Devices.Edge.Hub.Http.csproj, edge-modules/DirectMethodReceiver/DirectMethodReceiver.csproj, edge-modules/DirectMethodSender/DirectMethodSender.csproj, edge-modules/MessagesAnalyzer/MessagesAnalyzer.csproj, edge-modules/ModuleLib/Microsoft.Azure.Devices.Edge.ModuleUtil.csproj, edge-modules/SimulatedTemperatureSensor/SimulatedTemperatureSensor.csproj, edge-modules/TemperatureFilter/TemperatureFilter.csproj, edge-modules/functions/binding/src/Microsoft.Azure.WebJobs.Extensions.EdgeHub/Microsoft.Azure.WebJobs.Extensions.EdgeHub.csproj, edge-modules/load-gen/load-gen.csproj, smoke/IotEdgeQuickstart/IotEdgeQuickstart.csproj
Update Edge codebase to use private drop of C# SDK with bug fixes for testing.
=> Update C# SDK to private version for testing

scripts/linux/runX509Tests.sh
Fixes to the script which were needed after running this on the E2E test taks.
=> Fixes to E2E script

scripts/windows/setup/IotEdgeSecurityDaemon.ps1
This is cleaning up logging further and improving prereq testing. No functional breaks.
=> Cleanup logging

THIRDPARTYNOTICES
Updated to master as of 02/21/2019
=> Update third party licenses.

e2e_deployment_files/long_haul_deployment.template.json
=> fix long haul deployment

edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Docker.E2E.Test/AgentTests.cs
You can see this CI Build, https://msazure.visualstudio.com/One/_build/results?buildId=20580302 is passed.
=> Fix Agent Tests

edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.IoTHub.Test/EdgeAgentConnectionTest.cs, edge-hub/test/Microsoft.Azure.Devices.Routing.Core.Test/endpoints/StoringAsyncEndpointExecutorTest.cs
Fix these 2 tests; StoringAsyncEndpointExecutorTest.PumpMessagesWithLargeIncomingBatchTest and EdgeAgentConnectionTest.EdgeAgentPingMethodTest.
=> fix broken CI build

e2e_deployment_files/stress_deployment.template.json
update stress deployment file to have architecture tag.
=> update stress deployment file

edge-hub/docker/linux/amd64/Dockerfile, edge-hub/docker/windows/arm32v7/Dockerfile, edge-hub/docker/windows/arm32v7/base/Dockerfile
- Set edgehubuser uid to 1000 
- Use ContainerUser on windows arm 32
=> Set edgehubuser uid and use ContainerUser on windows

scripts/linux/runE2ETest.sh
fix architecture value in case statement and minor refactor to ensure error message will be printed out when architecture is not matched.
=> fix script for arm e2e test.

edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/IRuntimeInfoProvider.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/logs/LogsProvider.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Docker/RuntimeInfoProvider.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/IModuleManager.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/ModuleManagementHttpClient.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/RuntimeInfoProvider.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2019_01_30/generatedCode/EdgeletHttpClient.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/versioning/ModuleManagementHttpClientVersioned.cs, edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/logs/LogsProviderTest.cs, edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Docker.Test/RuntimeInfoProviderTest.cs, edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Edgelet.Test/ModuleManagementHttpClientTest.cs, edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Edgelet.Test/RuntimeInfoProviderTest.cs
Plumb since parameter when getting logs from EdgeAgent to Docker/Edgelet
=> EdgeAgent: Plumb since parameter when getting module logs to Edgelet

builds/misc/packages.yaml, edgelet/build/windows/iotedge.wm.xml, edgelet/build/windows/package.ps1, scripts/windows/setup/IotEdgeSecurityDaemon.ps1, scripts/windows/test/Run-E2ETest.ps1, smoke/IotEdgeQuickstart/Program.cs, smoke/IotEdgeQuickstart/details/IotedgedWindows.cs
This is a cherry-pick of the following changes from master:
https://github.com/Azure/iotedge/commit/fe99dbb9968e6c61f59c9ef4543ace7a6c0a67c9
https://github.com/Azure/iotedge/commit/3cf21af3c813a6620b4d256e32901aed1942e1e5
https://github.com/Azure/iotedge/commit/8e846eefc182770fbcade138967148c469b21534
https://github.com/Azure/iotedge/commit/067e31ed490e0556cd1d70ab59f65f8d8e549576
https://github.com/Azure/iotedge/commit/462ebc1f5f533ee552d36763a8ef9fc0b635d376
https://github.com/Azure/iotedge/commit/ced642140a2a6ea0c3698bc65614d0fe33eec760
While the following two changes are also touch files created for the new packaging, I do not believe they are required for the release from the packaging point of view and therefore are not being cherry-picked by this PR: …
=> Windows packaging changes

edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/requests/LogsUploadRequest.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/requests/LogsUploadRequestHandler.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/blob/AzureBlobLogsUploader.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/modules/AgentModule.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/modules/EdgeletModule.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/modules/FileConfigSourceModule.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/modules/TwinConfigSourceModule.cs, edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/requests/LogsUploadRequestHandlerTest.cs
Add a method to upload logs from the EdgeAgent to Azure blob store.
=> Add Logs upload method request handler

edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/logs/ILogMessageParser.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/logs/ILogsProcessor.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/logs/LogMessageParser.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/logs/LogsProcessor.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/logs/LogsProvider.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/logs/ModuleLogFilter.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/logs/ModuleLogMessage.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/logs/ModuleLogMessageData.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/logs/ModuleLogOptions.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/requests/LogsUploadRequestHandler.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/stream/LogsStreamRequestHandler.cs, edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/logs/DockerFraming.cs, edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/logs/LogsProcessorTest.cs, edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/logs/LogsProviderTest.cs, edge-util/src/Microsoft.Azure.Devices.Edge.Util/Option.cs, edge-util/test/Microsoft.Azure.Devices.Edge.Util.Test/OptionTest.cs
Adds support for filtering logs based on 
1. regex
2. loglevel
3. tail
Adding support for since in next PR.
=> Add filtering support for logs

edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/Constants.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/stream/NullStreamRequestListener.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/modules/TwinConfigSourceModule.cs
Adding a flag to disable streams by default, since device streams are not yet supported in most regions.
=> EdgeAgent: Add flag to disable streams

builds/e2e/longhaul.yaml
disable pr trigger and move variables section out of jobs.
=> Fix long haul yaml

builds/ci/dotnet.yaml, builds/misc/images.yaml
Fix agent pool to use vmImage only for hosted agent.
=> Fix agent pool in YAML

e2e_deployment_files/stress_deployment.template.json, scripts/linux/runE2ETest.sh, scripts/windows/test/Run-E2ETest.ps1
1. upgrade influx from 1.5 to 1.7 in stress deployment file.
2. Remove internal default values from e2e scripts.
=> Clean up test script and deployment

scripts/linux/runE2ETest.sh, scripts/windows/test/Run-E2ETest.ps1
fix logic to update OptimizeForPerformance flag to false for ARM32 and true for AMD64.
=> Fix OptimizeForPerformance flag in E2E script

builds/e2e/longhaul.yaml
Update arm long haul deployment file name in yaml
=> Fix Long Haul for ARM devices

edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/logs/ILogsProcessor.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/logs/LogsProcessor.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/logs/LogsProvider.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/logs/ModuleLogFilter.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/logs/ModuleLogMessage.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/stream/LogsStreamRequest.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/stream/LogsStreamRequestHandler.cs, edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/logs/LogsProcessorTest.cs, edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/logs/LogsProviderTest.cs, edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.IoTHub.Test/stream/LogsStreamRequestHandlerTest.cs, edge-util/src/Microsoft.Azure.Devices.Edge.Util/json/OptionConverter.cs
This PR adds support for processing logs that are being transmitted with streams - 
- filtering on log level
- filtering on regex
- compression
=> Add support for filtering/processing log streams

builds/e2e/longhaul.yaml, builds/e2e/stresstest.yaml, builds/e2e/templates/stresstest-deploy.yaml, e2e_deployment_files/long_haul_deployment.template.arm32v7.amqp.json, e2e_deployment_files/long_haul_deployment.template.arm32v7.mqtt.json, e2e_deployment_files/long_haul_deployment.template.json, e2e_deployment_files/stress_deployment.template.json
1. Update long haul and stress test to support running against different branch.
2. Update to use latest influx db docker image.
3. re-order modules in long haul.
=> Update long haul and stress test

edgelet/doc/devguide.md, edgelet/edgelet-http/src/lib.rs, edgelet/edgelet-http/src/pid.rs, edgelet/edgelet-http/src/unix.rs, edgelet/hsm-sys/azure-iot-hsm-c/CMakeLists.txt, edgelet/hsm-sys/build.rs
Fixed several issues preventing from building iotedged on a mac os machine. The only supported mode to communicate with daemon is HTTP due to docker for mac implementation details.
=> Added support of iotedged to build and run on a mac os

edge-agent/README.md, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/appsettings_agent.json
Allow the ability to mount a custom configuration source file for edge agent.
=> Allow the ability to mount a custom configuration source file for edge agent.

scripts/windows/setup/IotEdgeSecurityDaemon.ps1
Cherry-pick of fe8457f12e3fdf6ad01400bafd83bbc1fb827e1c from master.
=> Block installation on Windows ARM32 until it's ready for preview

scripts/windows/setup/IotEdgeSecurityDaemon.ps1
Cherry-pick of a7e0319b90953626bfc947dee12618b712004c52 from master.
=> Add a warning to the installer that battery-powered devices won't be able to sleep

edgelet/mini-sntp/src/lib.rs
We had a CI failure in the mini-sntp test that indicated that
one of the pool.ntp.org servers returns VN=4 even though the client request
has VN=3. This change works around such servers.
Also fixes a couple of typos in the file.
=> Work around bad SNTP servers that return VN=4 responses

builds/misc/images.yaml, edgelet/build/windows/build-diagnostics.ps1, scripts/linux/buildDiagnostics.sh
allow to pass build configuration for image build; default value is "Release"
=> support pass-in build configuration for image build

scripts/linux/runE2ETest.sh, scripts/windows/test/Run-E2ETest.ps1
merge latest e2e test script in order to run e2e in vsts pipeline for release 1.0.7
=> Merge latest e2e test scripts

edgelet/hsm-sys/azure-iot-hsm-c/src/edge_hsm_client_store.c, edgelet/hsm-sys/azure-iot-hsm-c/tests/edge_hsm_crypto_int/edge_hsm_crypto_int.c
Remove unneeded check as well.
=> Fix idempotent master key create integration test

edge-modules/MessagesAnalyzer/Reporter.cs, smoke/LeafDevice/details/Details.cs
Add more log message in Leaf device and analyzer for troubleshooting.
=> Add more log messages

scripts/linux/runE2ETest.sh
add optimize for performance argument explicitly for quickstart cert and tempSensor test.
=> fix quickstart cert on RPi

edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/Agent.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/ModuleClient.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/AmqpProtocolHead.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/AmqpRuntimeProvider.cs, edge-util/src/Microsoft.Azure.Devices.Edge.Util/edged/version_2018_06_28/WorkloadClient.cs, edge-util/src/Microsoft.Azure.Devices.Edge.Util/edged/version_2019_01_30/WorkloadClient.cs
Did not change any test code or test modules code (such as LeafDevice).
=> Fix rethrowing exceptions to preserve the original stack trace

edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/Agent.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2018_06_28/ModuleManagementHttpClient.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2019_01_30/ModuleManagementHttpClient.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/versioning/ModuleManagementHttpClientVersioned.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs, edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Edgelet.Test/ModuleManagementHttpClientTest.cs, edge-util/src/Microsoft.Azure.Devices.Edge.Util/PeriodicTask.cs, edge-util/test/Microsoft.Azure.Devices.Edge.Util.Test/TaskExTest.cs
Cherry-pick #9c354fff4960292e13c7cb390fe00e3204cf9830 to release/1.0.7
=> Add timeout to EdgeAgent - iotedged operations, and add more logs

builds/e2e/longhaul.yaml, builds/e2e/stresstest.yaml, e2e_deployment_files/long_haul_deployment.template.arm64v8.amqp.json, e2e_deployment_files/long_haul_deployment.template.arm64v8.mqtt.json, scripts/linux/runE2ETest.sh
Update long haul and stress tests yaml for ARM64v8; and update e2e script to use new ARM64 deployment  files.
=> Long haul and stress test for ARM64v8

builds/e2e/stresstest.yaml
Fix typo in ARM64v8 job condition in stress test yaml
=> Fix typo in stress test yaml

scripts/windows/test/Run-E2ETest.ps1
fix switch statement to use regex instead of wildcard.
=> fix PS E2E script

test/Microsoft.Azure.Devices.Edge.Test.Common/EdgeAgent.cs, test/Microsoft.Azure.Devices.Edge.Test.Common/EdgeConfiguration.cs, test/Microsoft.Azure.Devices.Edge.Test.Common/EdgeDaemon.cs, test/Microsoft.Azure.Devices.Edge.Test.Common/EdgeDevice.cs, test/Microsoft.Azure.Devices.Edge.Test.Common/EdgeModule.cs, test/Microsoft.Azure.Devices.Edge.Test.Common/EnvironmentVariable.cs, test/Microsoft.Azure.Devices.Edge.Test.Common/IotHub.cs, test/Microsoft.Azure.Devices.Edge.Test.Common/ModuleTwin.cs, test/Microsoft.Azure.Devices.Edge.Test.Common/Profiler.cs, test/Microsoft.Azure.Devices.Edge.Test.TempSensor/Program.cs, test/Microsoft.Azure.Devices.Edge.Test.TempSensor/Test.cs
Resolve stylecop issues in newly created test projects.
=> Resolve stylecop issues

edgelet/iotedge/src/main.rs
... instead of assuming it's `C:\ProgramData`. For example, it has
a different value on IoT Core.
=> Fix `iotedge check` on Windows to use `PROGRAMDATA` env var

edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudProxy.cs, edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Test/CloudProxyTest.cs
With the new AMQP refactor, the SDK client can go into a bad state and start throwing ObjectDisposed exceptions. In such a case, throw away the client and create a new one.
We already do this for Null ref exceptions. Adding ObjectDisposedException to the list.
=> EdgeHub: Dispose client on getting an Object Disposed exception

edgelet/Cargo.lock, edgelet/contrib/config/linux/config.yaml, edgelet/contrib/config/linux/debian/config.yaml, edgelet/contrib/config/windows/config.yaml, edgelet/edgelet-config/Cargo.toml, edgelet/edgelet-config/src/lib.rs, edgelet/edgelet-config/test/linux/sample_settings.yaml, edgelet/edgelet-config/test/linux/sample_settings1.yaml, edgelet/edgelet-config/test/linux/sample_settings2.yaml, edgelet/edgelet-config/test/windows/sample_settings.yaml, edgelet/edgelet-config/test/windows/sample_settings1.yaml, edgelet/edgelet-config/test/windows/sample_settings2.yaml, edgelet/edgelet-core/src/lib.rs, edgelet/edgelet-core/src/watchdog.rs, edgelet/iotedged/src/error.rs, edgelet/iotedged/src/lib.rs, edgelet/iotedged/src/main.rs
Return different process exit codes from iotedged after configured retry count has been exceeded
=> Return different process exit codes from iotedged after configured retry count has been exceeded

edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/ConnectionManager.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/HubCoreEventIds.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/cloud/RetryingCloudProxy.cs, edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/RetryingCloudProxyTest.cs
Also change RetryCount from 3 to 2 (basically retry once).
=> Add logs to RetryingCloudProxy

edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/ModuleClient.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudProxy.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/ConnectionManager.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/cloud/ICloudProxy.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/cloud/RetryingCloudProxy.cs, edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Test/CloudProxyTest.cs, edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Test/CloudProxyUnitTest.cs, edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/ConnectionManagerTest.cs, edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/RetryingCloudProxyTest.cs, scripts/windows/setup/IotEdgeSecurityDaemon.ps1
Cherry-pick https://github.com/Azure/iotedge/commit/f7c14b18a4748e6fb1d8cb2fedf421945c5c96bd
* Add support for retrying CloudProxy
* Add Tests
* Add / fix tests
* Cleanup and fix test
* Fix build
* Update RetryingCloudProxyTest.cs
* Fix build
* Fix RetryCount usage
* Fix RetryingCloudProxy loop
* Update RetryingCloudProxy.cs
=> EdgeHub: Add support for a RetryingClient to handle SDK issues (#1239)

edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/ConnectionManager.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/HubCoreEventIds.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/cloud/RetryingCloudProxy.cs, edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/RetryingCloudProxyTest.cs
Cherry-pick https://github.com/Azure/iotedge/commit/396bbd11361d107852e9a6e38abc74e753b2f4dc
=> Add logs to RetryingCloudProxy (#1250)

edgelet/contrib/config/linux/config.yaml, edgelet/contrib/config/linux/debian/config.yaml, edgelet/contrib/config/windows/config.yaml
Remove the x.509 examples from the DPS config in `config.yaml`.
=> Remove x509 DPS config settings

edgelet/provisioning/src/provisioning.rs
* No reconfigure when DPS reprovisioning from backup
* Format
=> Should not reconfigure when DPS reprovisioning from backup (#1306)

builds/e2e/stresstest.yaml, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/MqttProtocolHead.cs
* Update Mqtt protocol default thread count to processor * 2 instead of 200.
* combine ARM stress test into 1
=> Update Mqtt thread count (#1299)

edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/commands/KubernetesCrdCommand.cs, edgelet/build/charts/edge-kubernetes/templates/edge-agent-deployment.yaml
remove some extraneous  prints
=> Pass runtime log level

edge-modules/DirectMethodCloudSender/src/Program.cs, edge-modules/DirectMethodReceiver/src/Program.cs, edge-modules/DirectMethodSender/src/Program.cs, edge-modules/TemperatureFilter/Program.cs
clean up and pass logger to shutdown handler.
=> Clean up and pass logger to shutdown handler in edge modules

edgelet/build/charts/edge-kubernetes/templates/edge-agent-deployment.yaml
For Helm template, only define user controlled environment variables when set in Values.yaml.
=> [k8s][preview]Only define user controlled environment variables

edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/NullDeviceConnectivityManager.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/DependencyManager.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/RoutingModule.cs, edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.E2E.Test/DependencyManager.cs
Cherry-pick https://github.com/Azure/iotedge/commit/7026fd370e7d89b4754f1aa83e5b5d9358cc9de1
=> Add NullDeviceConnectivityManager (#1332)

edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/logs/LogsProvider.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/requests/LogsUploadRequest.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/requests/LogsUploadRequestHandler.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/requests/RequestManager.cs, edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/logs/LogsProviderTest.cs
Cherry pick https://github.com/Azure/iotedge/commit/655fbdd33af6f1934a6e67d4013a2cb56c245465
=> 1.0.8: EdgeAgent: Fix log upload formatting

edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/EdgeAgentConnection.cs, edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.IoTHub.Test/EdgeAgentConnectionTest.cs
Cherry-pick https://github.com/Azure/iotedge/commit/85f7887fb823ac66679a50baed8822d5bf86ee48
=> 1.0.8: EdgeAgent: Fix error handling in GetTwin

edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2019_01_30/generatedCode/EdgeletHttpClient.cs, edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Docker.E2E.Test/test-config-x64.json, edgelet/api/managementVersion_2019_01_30.yaml, edgelet/edgelet-kube/src/convert/to_k8s.rs, edgelet/edgelet-kube/src/runtime.rs
Use the right ImagePullPolicy value in EdgeAgent while calling the Mgmt endpoint
=> Use the right ImagePullPolicy value in EdgeAgent while calling the Mgmt endpoint

builds/misc/packages.yaml, edgelet/build/linux/docker/cross-compile/Dockerfile.ubuntu18.04.aarch64-unknown-linux-gnu, edgelet/build/linux/docker/cross-compile/README.md, edgelet/build/linux/docker/cross-compile/apt/qemu.sh, edgelet/build/linux/docker/cross-compile/toolchain.sh, edgelet/build/linux/docker/cross-compile/ubuntu18.04/build_arm64_toolchain_container.sh, edgelet/build/linux/docker/cross-compile/ubuntu18.04/openssl.sh, edgelet/build/linux/ubuntu18.04/aarch64/package-iotedged.sh, edgelet/build/linux/ubuntu18.04/aarch64/package-libiothsm.sh, edgelet/build/linux/ubuntu18.04/aarch64/test-iotedged.sh
Added iotedge package build for ubuntu 18.04 arm64 with OpenSSL 1.1
=> Add iotedge package build for ubuntu 18.04 arm64

edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/Microsoft.Azure.Devices.Edge.Agent.IoTHub.csproj, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/Microsoft.Azure.Devices.Edge.Hub.Amqp.csproj, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.csproj, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/Microsoft.Azure.Devices.Edge.Hub.Core.csproj, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Http/Microsoft.Azure.Devices.Edge.Hub.Http.csproj, edge-modules/DirectMethodCloudSender/DirectMethodCloudSender.csproj, edge-modules/DirectMethodReceiver/DirectMethodReceiver.csproj, edge-modules/DirectMethodSender/DirectMethodSender.csproj, edge-modules/MessagesAnalyzer/MessagesAnalyzer.csproj, edge-modules/ModuleLib/Microsoft.Azure.Devices.Edge.ModuleUtil.csproj, edge-modules/SimulatedTemperatureSensor/SimulatedTemperatureSensor.csproj, edge-modules/TemperatureFilter/TemperatureFilter.csproj, edge-modules/functions/binding/src/Microsoft.Azure.WebJobs.Extensions.EdgeHub/Microsoft.Azure.WebJobs.Extensions.EdgeHub.csproj, edge-modules/load-gen/load-gen.csproj, samples/dotnet/EdgeDownstreamDevice/EdgeDownstreamDevice.csproj, smoke/IotEdgeQuickstart/IotEdgeQuickstart.csproj, smoke/LeafDevice/LeafDevice.csproj, test/Microsoft.Azure.Devices.Edge.Test.Common/Microsoft.Azure.Devices.Edge.Test.Common.csproj
Update Client SDK to 1.20.2 and Server SDK to 1.18.0
=> Update C# SDK version in Edge codebase

edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/blob/AzureBlobLogsUploader.cs, edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.IoTHub.Test/blob/AzureBlobLogsUploaderTest.cs
* Fix extension for gzip files
* Update AzureBlobLogsUploaderTest.cs
Cherry-pick https://github.com/Azure/iotedge/commit/d77f5375ef94c599b6f05cdbb1c4db82d71db500
=> 1.0.8: EdgeAgent logs upload - fix file extension for gzip files

edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/AgentEventIds.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/requests/LogsUploadRequestHandler.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/requests/TaskStatusRequest.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/requests/TaskStatusRequestHandler.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/requests/TaskStatusResponse.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/modules/TwinConfigSourceModule.cs, edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/requests/LogsUploadRequestHandlerTest.cs, edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/requests/TaskStatusRequestHandlerTest.cs, edge-util/src/Microsoft.Azure.Devices.Edge.Util/BackgroundTask.cs, edge-util/src/Microsoft.Azure.Devices.Edge.Util/BackgroundTaskRunStatus.cs, edge-util/src/Microsoft.Azure.Devices.Edge.Util/BackgroundTaskStatus.cs, edge-util/test/Microsoft.Azure.Devices.Edge.Util.Test/BackgroundTaskTest.cs
Cherry pick https://github.com/Azure/iotedge/commit/4e8e00543f3816ce0e1964a2849abba7fb3a4e5d
=> 1.0.8: EdgeAgent: Get status of logs upload request

Microsoft.Azure.Devices.Edge.sln, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/AgentEventIds.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/InvalidKubernetesName.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/KubeUtils.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/KubernetesEventIds.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/KubernetesResponseException.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/KubernetesRuntimeInfoProvider.cs, edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/K8sRuntimeInfoProviderTest.cs, edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/KubeUtilsTest.cs, edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test.csproj, edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/MockKubeApiServer.cs, edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/podwatch.txt
Create a IRuntimeInfoProvider implementation for Kubernetes pods.
Add some KubeUtils for the Runtime to use.
Add tests.
=> [k8s]Create an IRuntimeInfo for Kubernetes.

edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/CustomObjectDefinition.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/EdgeDeploymentDefinition.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/IEdgeDeploymentDefinition.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/KubernetesModule.cs
Port both classes over, and refactor Kubernetes Module to utilize IModule.
=> Kubernetes Module and EdgeDeploymentDefinition

edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/Microsoft.Azure.Devices.Edge.Agent.IoTHub.csproj, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/Microsoft.Azure.Devices.Edge.Hub.Amqp.csproj, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.csproj, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/Microsoft.Azure.Devices.Edge.Hub.Core.csproj, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Http/Microsoft.Azure.Devices.Edge.Hub.Http.csproj, edge-modules/DirectMethodCloudSender/DirectMethodCloudSender.csproj, edge-modules/DirectMethodReceiver/DirectMethodReceiver.csproj, edge-modules/DirectMethodSender/DirectMethodSender.csproj, edge-modules/MessagesAnalyzer/MessagesAnalyzer.csproj, edge-modules/ModuleLib/Microsoft.Azure.Devices.Edge.ModuleUtil.csproj, edge-modules/SimulatedTemperatureSensor/SimulatedTemperatureSensor.csproj, edge-modules/TemperatureFilter/TemperatureFilter.csproj, edge-modules/functions/binding/src/Microsoft.Azure.WebJobs.Extensions.EdgeHub/Microsoft.Azure.WebJobs.Extensions.EdgeHub.csproj, edge-modules/load-gen/load-gen.csproj, samples/dotnet/EdgeDownstreamDevice/EdgeDownstreamDevice.csproj, smoke/IotEdgeQuickstart/IotEdgeQuickstart.csproj, smoke/LeafDevice/LeafDevice.csproj, test/Microsoft.Azure.Devices.Edge.Test.Common/Microsoft.Azure.Devices.Edge.Test.Common.csproj
SDK Client - 1.20.3
SDK Service - 1.18.1
AMQP - 2.4.2
=> 1.0.8: Update SDK version

edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/K8sRuntimeInfoProviderTest.cs, edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/KubeUtilsTest.cs, edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/MockKubeApiServer.cs
Changes to fix CI build. Tests are still failing, needs investigation.
=> Cleanup code on kube tests project to fix CI build

edgelet/iotedged/src/lib.rs
Decode SAS key from base64 in the external provisioning mode.
=> Decode SAS key from base64 in the external provisioning mode.

edgelet/api/workloadVersion_2018_06_28.yaml, edgelet/api/workloadVersion_2019_01_30.yaml
=> Update HTTP response status code for identity cert create

scripts/windows/test/Setup-Env.ps1
Switch to using environment variable.
=> Fix ProgramData path

edgelet/edgelet-kube/src/convert/to_k8s.rs, edgelet/edgelet-kube/src/lib.rs, edgelet/edgelet-kube/src/module/trust_bundle.rs
Fix failing unit tests after merging conflicting changes in 2 concurrent PR.
=> [k8] Fix failing test

builds/e2e/templates/deploy-iotuap.yaml
Allow for device to go offline (starts rebooting).
=> Halt and allow for device to start rebooting

edgelet/edgelet-http/src/pid.rs
Cherry-pick from master of fd019afecc915e577be2ee6817bba7cbf60e288e
=> Fix build for new Rust stable 1.37 (#1575)

edgelet/iotedge/src/check/mod.rs
Cherry-pick from master of 466535645aae945a88f0e913fff065af3c70088d
=> Add docs URL for storage-mounted-on-host check

edgelet/edgelet-http/src/certificate_manager.rs, edgelet/hsm-sys/azure-iot-hsm-c/src/edge_pki_openssl.c
Some ASN1 decoders expect DER encoded TRUE value (=0xff), and refuse validating certificates with 0x01
=> Changed ASN1 encoding of Basic Constrains/CA. 

edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/Constants.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/CrdWatchOperator.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/CrdWatcher.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/modules/KubernetesModule.cs
In order to establish secure communication between module and iotedged each pod should contain volume with iotedged trust bundle attached.
=> [k8s] Add trust bundle for each module

edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudProxy.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/SubscriptionProcessor.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/device/DeviceMessageHandler.cs, edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/DeviceMessageHandlerTest.cs, edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/SubscriptionProcessorTest.cs
Cherry-pick https://github.com/Azure/iotedge/commit/f9d1e07a57fba5e171d1956e012e901a8427b72c
=> Set client subscriptions when cloud connection is re-created

edgelet/iotedged/docker/linux/amd64/Dockerfile, edgelet/iotedged/docker/linux/arm32v7/Dockerfile, edgelet/iotedged/docker/linux/arm32v7/base/Dockerfile, edgelet/iotedged/docker/linux/arm64v8/Dockerfile, edgelet/iotedged/docker/linux/arm64v8/base/Dockerfile
Add a system user and set the user context for iotedged docker images.
=> Have iotedged execute as system user in container

edgelet/iotedge-proxy/src/error.rs, edgelet/iotedge-proxy/src/lib.rs, edgelet/iotedge-proxy/src/proxy/client.rs, edgelet/iotedge-proxy/src/proxy/config.rs, edgelet/iotedge-proxy/src/proxy/service.rs, edgelet/iotedge-proxy/src/routine.rs, edgelet/iotedge-proxy/src/settings.rs
Refactored error handling for proxy server
=> [k8s] iotedge-proxy: refactor error handling

builds/checkin/edgelet.yaml, edgelet/edgelet-kube/src/convert/to_docker.rs, edgelet/edgelet-kube/src/convert/to_k8s.rs, edgelet/edgelet-kube/src/error.rs, edgelet/edgelet-kube/src/module/authentication.rs, edgelet/edgelet-kube/src/module/create.rs, edgelet/edgelet-kube/src/module/trust_bundle.rs, edgelet/edgelet-kube/src/runtime.rs, edgelet/edgelet-kube/src/settings.rs
Refactor error handling for edgelet-kube crate.
=> [k8s] edgelet-kube: refactor error handling

builds/e2e/e2e.yaml
Avoid git clean step fail if it is first time and git repository doesn't exist yet.
Tested in E2E vsts pipeline and it get through git clean step.
https://dev.azure.com/msazure/One/_build/results?buildId=24749467
=> Update E2E test yaml

edgelet/docker-rs/src/apis/container_api.rs, edgelet/edgelet-docker/src/runtime.rs
Honor configured stop timeout of modules.
=> Honor configured stop timeout of modules (Fixes #1618)

edgelet/edgelet-core/src/lib.rs, edgelet/iotedged/src/error.rs, edgelet/iotedged/src/lib.rs, edgelet/provisioning/src/error.rs, edgelet/provisioning/src/lib.rs, edgelet/provisioning/src/provisioning.rs
Support X.509 authentication type in external provisioning.
=> Support X.509 authentication type in external provisioning.

doc/ExternalProvisioning.md
Add documentation for the external provisioning mode in IoT edge.
=> Add documentation for the external provisioning mode in IoT edge.

edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/CrdWatcher.cs, edgelet/edgelet-kube/src/convert/mod.rs, edgelet/edgelet-kube/src/convert/to_k8s.rs, edgelet/edgelet-kube/src/error.rs
=> Do not deleted service accounts if deloyment is updated, fix hubname in

edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/Constants.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/CrdWatchOperator.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/CrdWatcher.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/KubernetesModelBuilder.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/KubernetesPodBuilder.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/PodExtensions.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/modules/KubernetesModule.cs, edgelet/edgelet-kube/src/constants.rs, edgelet/edgelet-kube/src/convert/to_k8s.rs
Service account names match original module id in annotations
=> Config map names given to EdgeAgent

edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ConnectivityAwareClient.cs, edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Test/ConnectivityAwareClientTest.cs, edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Test/DeviceConnectivityManagerTest.cs
* Update ConnectivityAwareClient.cs
* Update ConnectivityAwareClient.cs
* Add tests
* Update DeviceConnectivityManagerTest.cs
=> Fix leaking event handlers in offline scenario (#1412)

edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/ProductInfoStore.cs, edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/ProductInfoStoreTest.cs, edge-util/src/Microsoft.Azure.Devices.Edge.Storage/SerDeExtensions.cs, edge-util/test/Microsoft.Azure.Devices.Edge.Storage.Test/SerDeExtensionsTest.cs
Cherry-pick from master of bb31324b90caa7ac28b9526034f289dd5551d2fa
=> EdgeHub: Fix error if client does not send product info

builds/e2e/templates/longhaul-deploy.yaml, scripts/linux/runE2ETest.sh
Remove long haul protocol head argument from e2e script for cleanup.
=> Clean up long haul

edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/CombinedDockerModule.cs, edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/CombinedDockerModuleTest.cs
This fixes the comparison for the Kubernetes/CombinedDockerConfig class.
=> [k8s] Combined docker config comparison.

builds/checkin/edgelet.yaml, edgelet/edgelet-hsm/src/certificate_properties.rs, edgelet/edgelet-http-workload/src/server/cert/mod.rs, edgelet/edgelet-http-workload/tests/dns-san.rs, edgelet/edgelet-http/src/lib.rs, edgelet/edgelet-http/src/util/connector.rs, edgelet/edgelet-kube/src/convert/mod.rs, edgelet/edgelet-kube/src/convert/to_docker.rs, edgelet/hsm-rs/src/crypto.rs, edgelet/hsm-rs/src/tpm.rs, edgelet/hsm-rs/src/x509.rs, edgelet/iotedged/src/app.rs, edgelet/kube-client/src/client.rs, edgelet/kube-client/src/config.rs
=> Fix for Rust 1.38 (#1758)

kubernetes/doc/create-options.md
Add spec describing Kubernetes experimental extensions for createOptions:
- volumes
- resources
- nodeSelector
=> [k8s] Spec: Kubernetes experimental extensions for createOptions

edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/Agent.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/IReporter.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/reporters/NullReporter.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/reporters/IoTHubReporter.cs, edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/AgentTests.cs, edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.IoTHub.Test/reporters/IoTHubReporterTest.cs
* Update deployment status to success if there is no deployment change
* use DeploymentStatus type instead of option<DeploymentStatus> as deployment status should be set in all code paths.
=> Fix deployment status

edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/Agent.cs
Invert if for better readability
=> Improve Agent

.config/CredScanSuppressions.json, edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/CombinedDockerModuleTest.cs
Add a rule to suppress CredScan errors in unit tests
=> Suppress fake passwords from CredScan

edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/CombinedKubernetesConfigProvider.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/CreatePodParameters.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/KubernetesExperimentalCreatePodParameters.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/edgedeployment/deployment/KubernetesDeploymentMapper.cs, edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/KubernetesDeploymentMapperTest.cs, edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/KubernetesExperimentalPodParametersTest.cs
Add support to apply resources section of experimental createOptions to module container spec.
=> [k8s] Add support for container resources create option

edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/CombinedKubernetesConfigProvider.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/CreatePodParameters.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/KubernetesExperimentalCreatePodParameters.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/KubernetesModuleVolumeSpec.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/edgedeployment/EdgeDeploymentController.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/edgedeployment/EdgeDeploymentDefinition.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/edgedeployment/IEdgeDeploymentController.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/edgedeployment/IEdgeDeploymentDefinition.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/edgedeployment/deployment/KubernetesDeploymentMapper.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/edgedeployment/diff/Diff.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/edgedeployment/service/PortExtensions.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/planners/KubernetesPlanner.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/modules/KubernetesModule.cs, edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/CombinedKubernetesConfigProviderTest.cs, edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/EdgeDeploymentCommandTest.cs, edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/KubernetesDeploymentMapperTest.cs, edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/KubernetesExperimentalPodParametersTest.cs, edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/KubernetesModuleTest.cs, edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/KubernetesServiceMapperTest.cs, edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/edgedeployment/pvc/KubernetesPvcMapperTest.cs
Add support for volumes create option
=> [k8s] Add support for volumes create option

kubernetes/charts/edge-kubernetes/templates/_helpers.tpl, kubernetes/charts/edge-kubernetes/values.yaml
Add experimental k8s create option feature flags to helm
- enableExperimentalFeatures
- enableK8sExtensions
=> [k8s] Add experimental k8s create option feature flags to helm

edgelet/iotedge/src/support_bundle.rs
This adds a test to verify the structure of the output zip.
=> Add test to support-bundle

scripts/windows/setup/IotEdgeSecurityDaemon.ps1
support manufacturing flows that deploy the .cab into the image with different mechanism then the script but still need the script for the remaining initialization.
=> support manufacturing flows

kubernetes/charts/edge-kubernetes/templates/_helpers.tpl
Make sure helm adds quotes for edge agent env when enabling experimental features.
=> [k8s] Add quotes for enabling k8s experimental features in helm

edgelet/iotedge/src/main.rs, edgelet/iotedge/src/support_bundle.rs
Changing output to include location per venkat's request
=> Add location to support bundle output

scripts/linux/runTests.sh, scripts/windows/test/Test-Branch.ps1
fix test result path to remove test dll source folder.
=> Fix test result path

kubernetes/charts/edge-kubernetes/templates/_helpers.tpl, kubernetes/charts/edge-kubernetes/values.yaml
Add upstream protocol to Helm charts.
=> [k8s] Add "UpstreamProtocol" to possible environment variables for edgeAgent.

builds/ci/dotnet.yaml, scripts/linux/runTests.sh, scripts/windows/test/Test-Branch.ps1
update text result file name with random text to avoid overwrite; and use publish test result task v2 to avoid warning.
=> Fix CI test result

edge-util/src/Microsoft.Azure.Devices.Edge.Util/CertificateHelper.cs, edge-util/src/Microsoft.Azure.Devices.Edge.Util/edged/HttpHsmSignatureProvider.cs, edge-util/src/Microsoft.Azure.Devices.Edge.Util/edged/WorkloadClient.cs
Client version and server version were passed in the wrong order.
=> Fix iotedge client versioning

scripts/windows/setup/IotEdgeSecurityDaemon.ps1
Support dynamic reprovisioning configuration in the IotEdgeSecurityDaemon.ps1 script
=> Support dynamic reprovisioning configuration in the IotEdgeSecurityDaemon.ps1 script

edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs
=> [k8s] Fix proxy image pull secret

scripts/windows/setup/IotEdgeSecurityDaemon.ps1
Fix regex in IotEdgeSecurityDaemon.ps1
=> Fix regex in IotEdgeSecurityDaemon.ps1

.github/workflows/stale.yml
Update stale action yaml to exempt issue labelled with "enhancement'.
=> Exemption for Stale action

edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/config/StoreLimits.cs
Fix StoreLimits param name to be consistent with property.
=> Fix StoreLimits param name to be consistent with property.

builds/misc/packages.yaml
Remove docker login step as docker images are in public repo.
=> Clean up Edgelet package build

kubernetes/charts/edge-kubernetes/templates/_helpers.tpl, kubernetes/charts/edge-kubernetes/values.yaml
changed the location of iotedged
This change will prevent edgeAgent from complaining about not being able to write to /app/backup.json
=> Set the backup path to a writeable location.

edge-util/src/Microsoft.Azure.Devices.Edge.Util/CertificateHelper.cs, edge-util/src/Microsoft.Azure.Devices.Edge.Util/edged/HttpHsmSignatureProvider.cs, edge-util/src/Microsoft.Azure.Devices.Edge.Util/edged/WorkloadClient.cs
=> Fix iotedge version passed instead of client version (#1955)

edgelet/Cargo.lock, edgelet/iotedge/Cargo.toml, edgelet/iotedge/src/support_bundle.rs
add raspbian fix to 1.0.9
improve readability of support bundle output
=> Get disk space for arm32 and print support bundle full location

builds/e2e/templates/deploy-iotuap.yaml
Fixes failing stress build due to missing backtick in yaml
=> Fix iotuap stress build

builds/misc/images.yaml
Increase timeout for Build Images on Windows.
=> Build Images Timeout

kubernetes/charts/edge-kubernetes/templates/edge-rbac.yaml, kubernetes/charts/edge-kubernetes/templates/iotedged-config-secret.yaml, kubernetes/charts/edge-kubernetes/templates/iotedged-pvc.yaml
* Sanitize helm chart name
* Add missed labels to force helm to delete resources it creates
=> [k8s] Sanitize helm chart name (#2084)

THIRDPARTYNOTICES, edgelet/Cargo.lock, edgelet/edgelet-docker/Cargo.toml, edgelet/edgelet-docker/src/runtime.rs
Move uptime logic into edgelet-docker
=> Fix uptime on win32 builds

edge-modules/ModuleLib/AnalyzerClient.cs, edge-modules/TestAnalyzer/swagger.yaml
fix createdAt field to be mandatory in Swagger file; and regenerated AnalyzerClient.cs
=> fix swagger file

edgelet/edgelet-docker/src/runtime.rs
Fix broken build for non-windows non-linux host OS
=> Fix broken build for macos

edge-modules/ModuleLib/TestConstants.cs, edge-modules/Relayer/Program.cs, edge-modules/TestAnalyzer/PartitionReceiverHandler.cs, edge-modules/load-gen/Program.cs, test/modules/TestResultCoordinator/PartitionReceiverHandler.cs, test/modules/TestResultCoordinator/Settings.cs
Changes to clean up and integrate all pieces for connectivity test.
=> Clean up loadGen and Relayer modules for connectivity tests

.gitignore, Microsoft.Azure.Devices.Edge.sln, test/modules/Modules.Test/Modules.Test.csproj, test/modules/Modules.Test/TestResultCoordinator/CountingReportGeneratorTest.cs, test/modules/Modules.Test/TestResultCoordinator/CountingReportTest.cs, test/modules/Modules.Test/TestResultCoordinator/SimpleTestOperationResultComparerTest.cs, test/modules/TestResultCoordinator/AssemblyInfo.cs, test/modules/TestResultCoordinator/CountingReport.cs, test/modules/TestResultCoordinator/CountingReportGenerator.cs, test/modules/TestResultCoordinator/ITestResultComparer.cs, test/modules/TestResultCoordinator/ITestResultReport.cs, test/modules/TestResultCoordinator/ITestResultReportGenerator.cs, test/modules/TestResultCoordinator/SimpleTestOperationResultComparer.cs, test/modules/TestResultCoordinator/TestResultReportBase.cs
Continue to work on messaging scenario in connectivity test.  Add ITestResultReportGenerator inteface with CountingReportGenerator implementation; plus add tests for related changes.
=> Report generator for messaging scenario in Connectivity test

test/modules/TestResultCoordinator/Program.cs, test/modules/TestResultCoordinator/Settings.cs
Update TestResultCoordinator to run report after test duration.
=> Trigger to run test reports

test/modules/TestResultCoordinator/Program.cs, test/modules/TestResultCoordinator/Settings.cs
Generating reports and sending to logAnalytics.
=> Adding LogAnalytics

edge-modules/load-gen/Settings.cs
Fix bug where empty string passed as default.
=> Fix LoadGen fail to report status

test/modules/TestResultCoordinator/Program.cs
Output test result reports to log in TestResultCoordinator.
=> Output test result reports

edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/edgedeployment/deployment/KubernetesDeploymentMapper.cs, edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/KubernetesDeploymentMapperTest.cs
* Set replica count to zero if module is stopped.
* Add comment and change logic to assume Running.
=> [k8s] Set replica count to zero if module is stopped. (#2121)

edge-modules/Relayer/Program.cs, edge-modules/TestAnalyzer/ReportingCache.cs, edge-modules/load-gen/BufferPool.cs, edge-modules/load-gen/Program.cs, test/modules/TestResultCoordinator/report/CountingReportGenerator.cs, test/modules/TestResultCoordinator/report/TestReportGeneratorFactory.cs, test/modules/TestResultCoordinator/service/PartitionReceiverHandler.cs
Clean up, fix warnings and add more log for connectivity test investigation.
=> Connectivity Test clean up

test/modules/TestResultCoordinator/Controllers/TestOperationResultController.cs, test/modules/TestResultCoordinator/storage/TestOperationResultStorage.cs
Resolve controller dependency injection issue in a hacky way (short term) to unblock testing.
=> Unblock connectivity test

test/modules/TestResultCoordinator/Controllers/TestOperationResultController.cs, test/modules/TestResultCoordinator/Startup.cs, test/modules/TestResultCoordinator/storage/TestOperationResultStorage.cs
Resolve dependency injection issue in WebHost ConfigureServices method; which should be implemented synchronously.
=> web host troubleshooting

test/modules/TestResultCoordinator/service/PartitionReceiverHandler.cs
=> Correct the indentation

edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/MetricsScraper.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/storage/MetricsStorage.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/modules/DiagnosticsModule.cs
This reverts commit f9ad608cfd047f4426beddaa48b8e0cd9d742530 because causes edgeAgent startup crash.
=> Revert "Ensure Metrics Ordering (#2167)"

edge-modules/ModuleLib/TwinTestResult.cs, edge-modules/TwinTester/DesiredPropertyUpdater.cs, edge-modules/TwinTester/ITwinTestResultHandler.cs, edge-modules/TwinTester/Program.cs, edge-modules/TwinTester/ReportedPropertyUpdater.cs, edge-modules/TwinTester/Settings.cs, edge-modules/TwinTester/StatusCode.cs, edge-modules/TwinTester/TwinAllOperationsResultHandler.cs, edge-modules/TwinTester/TwinEdgeOperationsResultHandler.cs, edge-modules/TwinTester/TwinTestMode.cs, edge-modules/TwinTester/config/settings.json, test/modules/Modules.Test/TestResultCoordinator/TwinCountingReportGeneratorTest.cs, test/modules/TestResultCoordinator/Controllers/TestOperationResultController.cs, test/modules/TestResultCoordinator/Settings.cs, test/modules/TestResultCoordinator/TwinCountingReportMetadata.cs, test/modules/TestResultCoordinator/TwinTestPropertyType.cs, test/modules/TestResultCoordinator/report/CloudTwinTestResultCollection.cs, test/modules/TestResultCoordinator/report/TestReportGeneratorFactory.cs, test/modules/TestResultCoordinator/report/TestReportHelper.cs, test/modules/TestResultCoordinator/report/TestReportType.cs, test/modules/TestResultCoordinator/report/TwinCountingReport.cs, test/modules/TestResultCoordinator/report/TwinCountingReportGenerator.cs
Add twin report generation to the TestResultCoordinator
=> Twin test results validation

builds/misc/packages.yaml
Sign the windows installer PowerShell script.
Cherry-pick from master of 84f028bebf25fe95beeac6d23439b161fb90ab67
=> Add the windows powershell installer to be signed

Microsoft.Azure.Devices.Edge.sln, builds/misc/images.yaml, edge-util/src/Microsoft.Azure.Devices.Edge.Util/json/JsonExtensions.cs, scripts/linux/buildBranch.sh, scripts/windows/build/Publish-Branch.ps1, test/modules/DeploymentTester/DeploymentTester.csproj, test/modules/DeploymentTester/DeploymentTesterMode.cs, test/modules/DeploymentTester/Program.cs, test/modules/DeploymentTester/Settings.cs, test/modules/DeploymentTester/config/settings.json, test/modules/DeploymentTester/docker/linux/amd64/Dockerfile, test/modules/DeploymentTester/docker/linux/arm32v7/Dockerfile, test/modules/DeploymentTester/docker/linux/arm64v8/Dockerfile, test/modules/DeploymentTester/docker/windows/amd64/Dockerfile, test/modules/DeploymentTester/docker/windows/arm32v7/Dockerfile, test/modules/ModuleLib/DeploymentTestResult.cs, test/modules/ModuleLib/ModuleUtil.cs, test/modules/ModuleLib/TestOperationResultType.cs
Module to test deployment update in connectivity test.  Connectivity deployment file will be updated in next PR.
=> Deployment test

edge-util/test/Microsoft.Azure.Devices.Edge.Util.Test.Common/TokenHelper.cs
* refresh sas token for CI tests
* change expiry to 2025
=> Refresh SAS token for CI tests (#2217)

edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Test/CloudProxyTest.cs, edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Test/EventHubReceiver.cs, edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Test/MessageHelper.cs
Cherry pick of #[2114](https://github.com/Azure/iotedge/pull/2114).
=> Fix flaky CI tests - Overloaded consumer group partitions

edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/DeviceScopeIdentitiesCacheTest.cs
* Disabling flakey test
* removing ID
=> Disabling flakey test - RefreshCacheWithRefreshRequestTest (#2143)

edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/Constants.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/EdgeHubCertificates.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs, edge-util/src/Microsoft.Azure.Devices.Edge.Util/CertificateHelper.cs
Cherry-pick 4f85dcc7d3fd6d4772d4a9b86ec3ecad651938fd
=> Install Trust Bundle in EdgeAgent and EdgeHub

smoke/IotEdgeQuickstart/details/Details.cs, smoke/LeafDevice/details/Details.cs
Cherry pick of #2173 
* increase timeout for slow registry manager device creation
=> E2E flake - Increase timeouts for slow registry manager device creation

edge-modules/DirectMethodCloudSender/src/Program.cs, edge-modules/MessagesAnalyzer/Settings.cs, edge-modules/MessagesAnalyzer/config/settings.json, edge-modules/ModuleRestarter/src/Settings.cs
Cherry pick of #1973 
* device id fix
* add preconditions
=> 109 - Port analyzer default device id fix

builds/e2e/longhaul.yaml, builds/e2e/stresstest.yaml, builds/e2e/templates/deploy-iotuap.yaml, builds/e2e/templates/longhaul-deploy-windows.yaml, builds/e2e/templates/longhaul-deploy.yaml, builds/e2e/templates/stresstest-deploy-windows.yaml, builds/e2e/templates/stresstest-deploy.yaml, e2e_deployment_files/long_haul_deployment.template.json, e2e_deployment_files/long_haul_deployment.template.windows.json, e2e_deployment_files/stress_deployment.template.json, e2e_deployment_files/stress_deployment.template.windows.json, edge-modules/MessagesAnalyzer/Controllers/ReportController.cs, edge-modules/MessagesAnalyzer/Settings.cs, edge-modules/MessagesAnalyzer/config/settings.json, edge-util/src/Microsoft.Azure.Devices.Edge.Util/azureLogAnalytics/AzureLogAnalytics.cs, scripts/linux/runE2ETest.sh, scripts/windows/test/Run-E2ETest.ps1
Cherry pick #1929 
1. Introducing Log Analytic communication from Message Analyzer module.
2. Introducing Log Analytic parameters to VSTS build pipeline for Stress test & Long Haul.
=> Enable log analytic in Analyzer

edge-hub/docker/linux/amd64/Dockerfile
=> Revert change to edgehub amd64 Dockerfile

builds/e2e/longhaul.yaml, builds/e2e/stresstest.yaml, builds/e2e/templates/deploy-iotuap.yaml, builds/e2e/templates/longhaul-deploy-windows.yaml, builds/e2e/templates/longhaul-deploy.yaml, builds/e2e/templates/stresstest-deploy-windows.yaml, builds/e2e/templates/stresstest-deploy.yaml, e2e_deployment_files/long_haul_deployment.template.json, e2e_deployment_files/long_haul_deployment.template.windows.json, e2e_deployment_files/stress_deployment.template.json, e2e_deployment_files/stress_deployment.template.windows.json, edge-modules/MessagesAnalyzer/Controllers/ReportController.cs, edge-modules/MessagesAnalyzer/Program.cs, edge-modules/MessagesAnalyzer/Settings.cs, edge-modules/MessagesAnalyzer/config/settings.json, edge-modules/ModuleRestarter/src/Settings.cs, edge-util/src/Microsoft.Azure.Devices.Edge.Util/azureLogAnalytics/AzureLogAnalytics.cs, scripts/linux/runE2ETest.sh, scripts/windows/test/Run-E2ETest.ps1
=> 109 - Backport refactor of log analytics naming

builds/e2e/templates/deploy-iotuap.yaml
Cherry pick #2029 
Fixing missing backtick
=> Fix iotuap stress build (#2029)

edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/Microsoft.Azure.Devices.Edge.Hub.Core.csproj
Update lang version to fix broken build from queue length metric PR.
=> Update lang version to fix windows build (#2191)

edge-util/src/Microsoft.Azure.Devices.Edge.Util/metrics/prometheus.net/MetricsProvider.cs
Taking part of commit #2014 to fix edgeHub crash when using experimental features.
=> Fix edgeHub crash when using experimental features

THIRDPARTYNOTICES, edgelet/Cargo.lock, edgelet/edgelet-docker/Cargo.toml, edgelet/edgelet-docker/src/runtime.rs
=> 109 - Port fix for uptime on win32 builds

test/modules/TestResultCoordinator/report/CountingReport.cs, test/modules/TestResultCoordinator/report/ITestResultReport.cs, test/modules/TestResultCoordinator/report/TestResultReportBase.cs, test/modules/TestResultCoordinator/report/TestSummary.cs, test/modules/TestResultCoordinator/report/TwinCountingReport.cs, test/modules/TestResultCoordinator/service/TestResultReportingService.cs
Add IsPassed in TestReports and Create a TestSummary to wrap all test result and provide AreAllTestsPassed property.
=> Add IsPassed Property in Test Reports

scripts/windows/test/Run-E2ETest.ps1
=> Cherry pick device id fix from master to release/1.0.9

e2e_deployment_files/connectivity_deployment.template.json, test/connectivity/scripts/connectivityTest.sh, test/modules/DeploymentTester/Program.cs, test/modules/DeploymentTester/Settings.cs
Add deployment test module in connectivity test deployment.
=> Enable deployment test

edge-modules/SimulatedTemperatureSensor/src/MessageBody.cs, test/modules/DeploymentTester/DeploymentTesterMode.cs, test/modules/DeploymentTester/Program.cs, test/modules/DeploymentTester/Settings.cs, test/modules/ModuleLib/TestResults/DeploymentTestResult.cs, test/modules/ModuleRestarter/src/Settings.cs, test/modules/Modules.Test/TestResultCoordinator/Reports/DeploymentTestReportGeneratorTest.cs, test/modules/Modules.Test/TestResultCoordinator/Reports/DeploymentTestReportTest.cs, test/modules/Relayer/Settings.cs, test/modules/TemperatureFilter/MessageBody.cs, test/modules/TestAnalyzer/MessageDetails.cs, test/modules/TestAnalyzer/Settings.cs, test/modules/TestAnalyzer/Startup.cs, test/modules/TestResultCoordinator/Reports/ITestResultCollection.cs, test/modules/TestResultCoordinator/Settings.cs, test/modules/TestResultCoordinator/storage/TestOperationResultStorage.cs, test/modules/TwinTester/Settings.cs, test/modules/TwinTester/TwinState.cs, test/modules/TwinTester/TwinTestMode.cs, test/modules/load-gen/BufferPool.cs, test/modules/load-gen/Settings.cs
1. make environment variable readonly in DeploymentTestResult
2. use internal access modifier for class if possible
=> Tests clean up

e2e_deployment_files/connectivity_deployment.template.json
Update deployment test module name in connectivity test
=> Update connectivity test deployment

test/modules/TestResultCoordinator/Reports/ITestResultCollection.cs
Fix unit test by making ITestResultCollection public for mocking
=> Fix unit test

test/connectivity/modules/NetworkController/Settings.cs, test/modules/DeploymentTester/Settings.cs, test/modules/DirectMethodSender/Settings.cs, test/modules/ModuleRestarter/src/Settings.cs, test/modules/Relayer/Settings.cs, test/modules/TestAnalyzer/Settings.cs, test/modules/TestResultCoordinator/Reports/TestReportHelper.cs, test/modules/TestResultCoordinator/Settings.cs, test/modules/TestResultCoordinator/Startup.cs, test/modules/TestResultCoordinator/storage/TestOperationResultStorage.cs, test/modules/TwinTester/Settings.cs, test/modules/load-gen/Settings.cs
1. Refactor Settings class in test module projects to use static variable for Singleton instead of Lazy.
2. Refactor Settings class in TRC for calling GetTwin to get report metadatas later.
=> Update settings in Test modules

test/modules/TestResultCoordinator/Reports/CountingReportGenerator.cs, test/modules/TestResultCoordinator/Reports/DeploymentTestReportGenerator.cs, test/modules/TestResultCoordinator/Reports/TestReportGeneratorFactory.cs, test/modules/TestResultCoordinator/Reports/TwinCountingReportGenerator.cs
Update class access modifier in report generators
=> Update class access modifier

e2e_deployment_files/connectivity_deployment.template.json
=> fix connection string key

builds/e2e/connectivity.yaml, builds/e2e/templates/connectivity-deploy.yaml, test/connectivity/scripts/connectivityTest.sh
update connectivity test script to wait for test complete  in order to show test result in VSTS pipeline.
Verified with Connectivity Test: https://msazure.visualstudio.com/One/_build/results?buildId=27867503&view=logs&j=7745b47e-e2a2-549a-b47a-b50c2a0d5e6c&t=ddd08a52-8c2a-57b6-3587-e2d73b1904a3
=> update connectivity test script to wait for test complete

test/connectivity/scripts/connectivityTest.sh, test/connectivity/scripts/testHelper.sh
Add hash suffix in device id in connectivity test
=> Add hash suffix in device id

test/connectivity/scripts/connectivityTest.sh
Fix examine test result function in connectivity test script.
=> Fix examine test result function

e2e_deployment_files/connectivity_deployment.template.json, test/modules/Modules.Test/TestResultCoordinator/TestReportUtilTest.cs, test/modules/TestResultCoordinator/Reports/CountingReport.cs, test/modules/TestResultCoordinator/Reports/CountingReportGenerator.cs, test/modules/TestResultCoordinator/Reports/CountingReportMetadata.cs, test/modules/TestResultCoordinator/Reports/DeploymentTestReport.cs, test/modules/TestResultCoordinator/Reports/DeploymentTestReportGenerator.cs, test/modules/TestResultCoordinator/Reports/DeploymentTestReportMetadata.cs, test/modules/TestResultCoordinator/Reports/DirectMethod/DirectMethodReport.cs, test/modules/TestResultCoordinator/Reports/DirectMethod/DirectMethodReportMetadata.cs, test/modules/TestResultCoordinator/Reports/NetworkControllerReport.cs, test/modules/TestResultCoordinator/Reports/NetworkControllerReportGenerator.cs, test/modules/TestResultCoordinator/Reports/NetworkControllerReportMetadata.cs, test/modules/TestResultCoordinator/Reports/TestReportGeneratorFactory.cs, test/modules/TestResultCoordinator/Reports/TestReportType.cs, test/modules/TestResultCoordinator/Reports/TwinCountingReport.cs, test/modules/TestResultCoordinator/Settings.cs, test/modules/TestResultCoordinator/TestReportUtil.cs
Add network controller report and generator; will enable in another PR.
=> Add Network Test Report

edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ConnectivityAwareClient.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/DeviceClientWrapper.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ModuleClientWrapper.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/ConnectionManager.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/RoutingModule.cs, edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Test/ClientTokenCloudConnectionTest.cs, edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/ConnectionManagerTest.cs, edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/RetryingCloudProxyTest.cs, edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/routing/RoutingEdgeHubTest.cs, edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/routing/RoutingTest.cs, edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.E2E.Test/EdgeHubConnectionTest.cs
=> Dispose all clients when network disconnection (#2291)

test/connectivity/scripts/connectivityTest.sh
fix if condition in exame_test_result method and use sed to handle multiple lines search.
=> connectivity script fix

edge-agent/docker/windows/amd64/Dockerfile, edge-agent/docker/windows/arm32v7/Dockerfile, edge-hub/docker/windows/amd64/Dockerfile, edge-hub/docker/windows/arm32v7/Dockerfile, edge-modules/DirectMethodCloudSender/docker/windows/amd64/Dockerfile, edge-modules/DirectMethodCloudSender/docker/windows/arm32v7/Dockerfile, edge-modules/DirectMethodReceiver/docker/windows/amd64/Dockerfile, edge-modules/DirectMethodReceiver/docker/windows/arm32v7/Dockerfile, edge-modules/DirectMethodSender/docker/windows/amd64/Dockerfile, edge-modules/DirectMethodSender/docker/windows/arm32v7/Dockerfile, edge-modules/MessagesAnalyzer/docker/windows/amd64/Dockerfile, edge-modules/MessagesAnalyzer/docker/windows/arm32v7/Dockerfile, edge-modules/SimulatedTemperatureSensor/docker/windows/amd64/Dockerfile, edge-modules/SimulatedTemperatureSensor/docker/windows/arm32v7/Dockerfile, edge-modules/TemperatureFilter/docker/windows/amd64/Dockerfile, edge-modules/TemperatureFilter/docker/windows/arm32v7/Dockerfile, edge-modules/load-gen/docker/windows/amd64/Dockerfile, edge-modules/load-gen/docker/windows/arm32v7/Dockerfile
Get latest windows base images for security fix
=> Update windows base images

edgelet/Cargo.lock
=> update url to 1.7.2

CHANGELOG.md
Correcting the incorrect security issue link
=> Edit changelog for release 1.0.8.5

e2e_deployment_files/connectivity_deployment.template.json, test/modules/TwinTester/TwinAllOperationsInitializer.cs, test/modules/TwinTester/TwinCloudOperationsInitializer.cs, test/modules/TwinTester/TwinEdgeOperationsInitializer.cs
Typo in connectivity deployment template. Rectifying.
=> Fixing Connectivity Deployment typo

edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/util/PrometheusMetricsParser.cs, edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Diagnostics.Test/util/PrometheousMetricsParserTest.cs
This changes the tags regex from + to *, to allow empty tag values
=> make parser accept empty tag values

edgelet/iotedge-proxy/src/error.rs, edgelet/iotedge-proxy/src/proxy/client.rs, edgelet/iotedge-proxy/src/proxy/service.rs, edgelet/iotedge-proxy/src/routine.rs
- Include proxy request URL even in case of an error in logs
- Fix the way how proxy builds destination URL for the service
=> [k8s] Improve proxy logging

edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/ConnectionManager.cs, edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/ConnectionManagerTest.cs
* Added test to connection manager and use readerwriterlock
=> Fix Connect to cloud lock (#2338)

test/modules/CloudToDeviceMessageTester/CloudToDeviceMessageTester.csproj
We should use dotnet 3.0 for arm64
=> Fix the build

builds/e2e/connectivity.yaml, builds/e2e/templates/connectivity-deploy.yaml, e2e_deployment_files/connectivity_deployment.template.json, test/connectivity/scripts/connectivityTest.sh, test/modules/TestResultCoordinator/Reports/TestSummary.cs, test/modules/TestResultCoordinator/Services/TestResultReportingService.cs, test/modules/TestResultCoordinator/Settings.cs, test/modules/TestResultCoordinator/TestReportUtil.cs, test/modules/TestResultCoordinator/TestResultCoordinator.csproj
After test completes, send upload log request from TRC to edgeAgent; and add log blob container uri in test summary.
Tested and it can successfully upload the log to azure blob container.
=> upload logs in TRC

edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/EdgeHubConnection.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/HubCoreEventIds.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/ITwinManager.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/TwinManager.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/config/ConfigUpdater.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/config/EdgeHubConfigParser.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/config/EdgeHubDesiredProperties.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/config/LocalTwinConfigSource.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/twin/ITwinStore.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/twin/PassThroughTwinManager.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/twin/StoringTwinManager.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/twin/TwinStore.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/RoutingModule.cs, edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/EdgeHubConnectionTest.cs, edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/config/ConfigUpdaterTest.cs
Cherry picked the changes without the EdgeHubConnection refactor
=> Backport fix offline restart edgeHub

edgelet/build/windows/check-arm32-patch.ps1, edgelet/dps/src/lib.rs, edgelet/dps/src/registration.rs, edgelet/edgelet-core/src/lib.rs, edgelet/edgelet-docker/src/lib.rs, edgelet/edgelet-hsm/src/lib.rs, edgelet/edgelet-http-external-provisioning/src/lib.rs, edgelet/edgelet-http-mgmt/src/lib.rs, edgelet/edgelet-http/src/certificate_manager.rs, edgelet/edgelet-http/src/lib.rs, edgelet/edgelet-kube/src/lib.rs, edgelet/edgelet-utils/src/lib.rs, edgelet/hsm-rs/src/lib.rs, edgelet/hyper-named-pipe/src/lib.rs, edgelet/iotedge-proxy/src/lib.rs, edgelet/iotedge/src/check/checks/container_engine_ipv6.rs, edgelet/iotedge/src/lib.rs, edgelet/iotedged/src/lib.rs, edgelet/iothubservice/src/lib.rs, edgelet/kube-client/src/lib.rs, edgelet/mini-sntp/src/lib.rs, edgelet/provisioning/src/lib.rs, edgelet/systemd/src/lib.rs, edgelet/tokio-named-pipe/src/lib.rs, edgelet/win-logger/src/lib.rs
Also update the Windows ARM32 check for winapi 0.2 to support
the new lockfile format in addition to the old one.
=> Fix build for new Rust stable 1.41.0

CHANGELOG.md
Link to specific security vulnerability
=> 108 Changelog.md: Link to specific security vulnerability

edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Docker/Microsoft.Azure.Devices.Edge.Agent.Docker.csproj, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/Microsoft.Azure.Devices.Edge.Agent.IoTHub.csproj, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/Microsoft.Azure.Devices.Edge.Hub.Amqp.csproj, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.csproj, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/Microsoft.Azure.Devices.Edge.Hub.Core.csproj, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Http/Microsoft.Azure.Devices.Edge.Hub.Http.csproj, edge-modules/DirectMethodCloudSender/DirectMethodCloudSender.csproj, edge-modules/DirectMethodReceiver/DirectMethodReceiver.csproj, edge-modules/DirectMethodSender/DirectMethodSender.csproj, edge-modules/ModuleLib/Microsoft.Azure.Devices.Edge.ModuleUtil.csproj, edge-modules/ModuleRestarter/ModuleRestarter.csproj, edge-modules/SimulatedTemperatureSensor/SimulatedTemperatureSensor.csproj, edge-modules/TemperatureFilter/TemperatureFilter.csproj, edge-modules/TestAnalyzer/TestAnalyzer.csproj, edge-modules/TwinTester/TwinTester.csproj, edge-modules/functions/binding/src/Microsoft.Azure.WebJobs.Extensions.EdgeHub/Microsoft.Azure.WebJobs.Extensions.EdgeHub.csproj, edge-modules/functions/samples/EdgeHubTrigger-Csharp/EdgeHubTriggerCSharp.csproj, edge-modules/load-gen/load-gen.csproj, edge-util/src/Microsoft.Azure.Devices.Edge.Util/Microsoft.Azure.Devices.Edge.Util.csproj, edge-util/test/Microsoft.Azure.Devices.Edge.Util.Test.Common/Microsoft.Azure.Devices.Edge.Util.Test.Common.csproj, smoke/IotEdgeQuickstart/IotEdgeQuickstart.csproj, smoke/LeafDevice/LeafDevice.csproj, test/Microsoft.Azure.Devices.Edge.Test.Common/Microsoft.Azure.Devices.Edge.Test.Common.csproj
Cherry-pick from https://github.com/Azure/iotedge/pull/2446 for 1.0.9 release
=> Update SDK on 1.0.9 branch

test/connectivity/scripts/connectivityTest.sh, test/modules/TestResultCoordinator/Reports/TestSummary.cs, test/modules/TestResultCoordinator/Services/TestResultReportingService.cs
Fix examine function in script and add device id in test summary
=> Fix script and update test summary

e2e_deployment_files/connectivity_deployment.template.json, test/connectivity/modules/NetworkController/Program.cs, test/modules/ModuleLib/TestConstants.cs, test/modules/ModuleLib/TestOperationResultType.cs, test/modules/ModuleLib/TestResults/TestInfoResult.cs, test/modules/Modules.Test/TestResultCoordinator/TestReportUtilTest.cs, test/modules/TestResultCoordinator/Reports/TestInfoReportMetadata.cs, test/modules/TestResultCoordinator/Reports/TestReportGeneratorFactory.cs, test/modules/TestResultCoordinator/Reports/TestReportType.cs, test/modules/TestResultCoordinator/TestReportUtil.cs
Add new test info report and report network frequencies from network controller module.
=> Test Info report in connectivity test

test/connectivity/scripts/connectivityTest.sh
return exit code 1 if examine test result method return 0 and vice versa.
=> Fix exit code

edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/CombinedKubernetesConfigProvider.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/CreatePodParameters.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/KubernetesExperimentalCreatePodParameters.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/edgedeployment/deployment/KubernetesDeploymentMapper.cs, edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/KubernetesDeploymentMapperTest.cs, edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/KubernetesExperimentalPodParametersTest.cs, kubernetes/doc/create-options.md
* Add pod security context to create options
=> [k8s] Add pod security context to create options (#2008)

builds/e2e/proxy.md
=> Fix formatting in proxy.md

kubernetes/charts/edge-kubernetes-crd/Chart.yaml, kubernetes/charts/edge-kubernetes/Chart.yaml, kubernetes/charts/edge-kubernetes/requirements.yaml, kubernetes/charts/edge-kubernetes/values.yaml
Co-authored-by: kodiakhq[bot] <49736102+kodiakhq[bot]@users.noreply.github.com>
=> [k8s] helm chart changes for public preview branch 

scripts/windows/test/Run-E2ETest.ps1
typo is failing the longhaul build
=> Fix longhaul windows typo

tools/IoTEdgeDevOps/DemoApp/Program.cs, tools/IoTEdgeDevOps/DevOpsLib/AgentDemandSet.cs, tools/IoTEdgeDevOps/DevOpsLib/BuildExtension.cs, tools/IoTEdgeDevOps/DevOpsLib/BuildManagement.cs, tools/IoTEdgeDevOps/DevOpsLib/IoTEdgeAgent.cs, tools/IoTEdgeDevOps/DevOpsLib/ValidationUtil.cs, tools/IoTEdgeDevOps/DevOpsLibTest/BuildExtensionTest.cs, tools/IoTEdgeDevOps/DevOpsLibTest/BuildManagementTest.cs, tools/IoTEdgeDevOps/DevOpsLibTest/ValidationUtilTest.cs, tools/IoTEdgeDevOps/IoTEdgeDashboard/Controllers/HomeController.cs, tools/IoTEdgeDevOps/VstsPipelineSync/Program.cs, tools/IoTEdgeDevOps/VstsPipelineSync/VstsBuildBatchUpdate.cs
import vsts builds from branches other than master to test dashboard database.
=> import vsts build data for test dashboard

tools/IoTEdgeDevOps/DevOpsLib/AgentCapability.cs, tools/IoTEdgeDevOps/DevOpsLib/AgentMatrix.cs, tools/IoTEdgeDevOps/IoTEdgeDashboard/.config/dotnet-tools.json
allow agent capability with empty value and add connectiviyt test column in agent matrix
=> Fix agent matrix

tools/IoTEdgeDevOps/DevOpsLib/AgentMatrix.cs, tools/IoTEdgeDevOps/DevOpsLib/IoTEdgePipelineTask.cs, tools/IoTEdgeDevOps/DevOpsLib/IoTEdgeReleaseDeployment.cs, tools/IoTEdgeDevOps/DevOpsLib/IoTEdgeReleaseEnvironment.cs, tools/IoTEdgeDevOps/DevOpsLib/ReleaseManagement.cs, tools/IoTEdgeDevOps/DevOpsLib/VstsModels/VstsDeploymentStatus.cs, tools/IoTEdgeDevOps/DevOpsLib/VstsModels/VstsPipelineTask.cs, tools/IoTEdgeDevOps/DevOpsLib/VstsModels/VstsReleaseDeployment.cs, tools/IoTEdgeDevOps/DevOpsLib/VstsModels/VstsReleaseEnvironment.cs, tools/IoTEdgeDevOps/DevOpsLibTest/AgentCapabilityTest.cs, tools/IoTEdgeDevOps/DevOpsLibTest/AgentMatrixTest.cs, tools/IoTEdgeDevOps/DevOpsLibTest/BuildExtensionTest.cs, tools/IoTEdgeDevOps/DevOpsLibTest/IoTEdgeReleaseEnvironmentTest.cs, tools/IoTEdgeDevOps/DevOpsLibTest/IoTEdgeReleaseTest.cs, tools/IoTEdgeDevOps/DevOpsLibTest/ReleaseManagementTest.cs, tools/IoTEdgeDevOps/DevOpsLibTest/TestUtil.cs, tools/IoTEdgeDevOps/VstsPipelineSync/VstsBuildBatchUpdate.cs, tools/IoTEdgeDevOps/VstsPipelineSync/db/dbo.UpsertVstsReleaseDeployment.sql, tools/IoTEdgeDevOps/VstsPipelineSync/db/dbo.UpsertVstsReleaseTask.sql, tools/IoTEdgeDevOps/VstsPipelineSync/db/dbo.VstsReleaseDeployment.sql, tools/IoTEdgeDevOps/VstsPipelineSync/db/dbo.VstsReleaseEnvironment.sql, tools/IoTEdgeDevOps/VstsPipelineSync/db/dbo.VstsReleaseTask.sql
Import deployments and tasks from vsts release envrionments for test dashboard.
=> Import more data for test dashboard

builds/e2e/templates/deploy-iotuap.yaml, builds/e2e/templates/longhaul-deploy-windows.yaml, builds/e2e/templates/longhaul-deploy.yaml, builds/e2e/templates/stresstest-deploy-windows.yaml, builds/e2e/templates/stresstest-deploy.yaml
Add host platform to report for test dashboard consumption
=> Longhaul/Stress: Add host platform to report for test dashboard consumption

test/modules/TestAnalyzer/AggregateCloudOperationReport.cs
=> Longhaul / Stress: Fix isPassed for twins/dm

edgelet/contrib/config/linux/config.yaml, edgelet/contrib/config/linux/debian/config.yaml, edgelet/contrib/config/windows/config.yaml
1. Fix inconsistent place-holder text
2. Improve instructions for DPS+Edge Scenarios
=> Port fixes for config files

kubernetes/charts/edge-kubernetes-crd/Chart.yaml, kubernetes/charts/edge-kubernetes/Chart.yaml, kubernetes/charts/edge-kubernetes/values.yaml
* Update charts to use beta5
* Update to 0.2.3
=> [k8s] Update Helm charts to use beta5 (#2606)

doc/BuiltInMetrics.md
Metrics behavior on windows wasn't clearly documented
=> Update Metrics Doc

edge-agent/docker/linux/arm32v7/base/Dockerfile, edge-agent/docker/linux/arm64v8/base/Dockerfile, edge-hub/docker/linux/arm32v7/base/Dockerfile, edge-hub/docker/linux/arm64v8/base/Dockerfile, edge-modules/SimulatedTemperatureSensor/docker/linux/arm32v7/base/Dockerfile, edge-modules/SimulatedTemperatureSensor/docker/linux/arm64v8/base/Dockerfile, edge-modules/TestAnalyzer/docker/linux/arm32v7/base/Dockerfile, edge-modules/TestAnalyzer/docker/linux/arm64v8/base/Dockerfile
Fix base image vulnerability issue for Linux ARM32 and ARM64.
=> Fix base image vulnerability issue

builds/e2e/connectivity.yaml, builds/e2e/templates/connectivity-deploy.yaml
stop running tasks if any previous task is failed in connectivity test.
=> Update connectivity yamls

edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/Constants.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/edgedeployment/deployment/KubernetesDeploymentMapper.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/edgedeployment/pvc/KubernetesPvcMapper.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/modules/KubernetesModule.cs, edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/KubernetesDeploymentMapperTest.cs, edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/edgedeployment/pvc/KubernetesPvcMapperTest.cs, edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/podwatch.txt, kubernetes/charts/edge-kubernetes/templates/_helpers.tpl, kubernetes/charts/edge-kubernetes/values.yaml, kubernetes/doc/edge-deployment-to-k8s-translations.md
=> [k8s] Remove pv name at startup and replace with "useMountSourceForVolumeName"

builds/checkin/dotnet.yaml, builds/checkin/mqtt.yaml, mqtt/build/linux/build.sh, mqtt/build/linux/clippy.sh, mqtt/build/linux/format.sh, mqtt/build/linux/install.sh, mqtt/build/linux/test.sh, mqtt/build/windows/build.ps1, mqtt/build/windows/clippy.ps1, mqtt/build/windows/install.ps1, mqtt/build/windows/test.ps1, mqtt/build/windows/util.ps1
Add a new checkin pipeline for mqtt broker
=> [mqtt] Add a new checkin pipeline for mqtt broker

mqtt/build/linux/mqtt-fuzz-rerun.sh, mqtt/build/linux/mqtt-fuzz.sh, mqtt/mqtt3/README.md
Add scripts and description to run `cargo afl` tool for fuzz testing
=> [mqtt] Add afl fuzz testing scripts

kubernetes/charts/edge-kubernetes-crd/Chart.yaml, kubernetes/charts/edge-kubernetes/Chart.yaml, kubernetes/charts/edge-kubernetes/values.yaml
Cherry-pick from master into public preview branch.
=> [k8s][Public preview] Increase chart version and use beta6 as new image url (#2665)

mqtt/mqtt3/src/client/connect.rs, mqtt/mqtt3/src/client/publish.rs, mqtt/mqtt3/src/client/subscriptions.rs
* Replace `mem::replace(T, T::default)` with `mem::take(T)`
=> [mqtt] Fix build for new Rust stable 1.42.0

test/modules/TestResultCoordinator/Reports/CountingReportGenerator.cs
Fix null reference exception in counting report generator.
=> Connectivity tests: Fix null ref exception

doc/built-in-logs-pull.md, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/modules/KubernetesModule.cs, kubernetes/charts/edge-kubernetes-crd/Chart.yaml, kubernetes/charts/edge-kubernetes/Chart.yaml, kubernetes/charts/edge-kubernetes/values.yaml
Update helm chart version, update image versions to beta7
=> [k8s] Prepare charts for beta7

edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/modules/KubernetesModule.cs, edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/KubeUtilsTest.cs, edgelet/edgelet-kube/src/convert/mod.rs, edgelet/edgelet-kube/src/convert/to_k8s.rs, edgelet/edgelet-kube/src/error.rs, kubernetes/charts/edge-kubernetes-crd/Chart.yaml, kubernetes/charts/edge-kubernetes/Chart.yaml, kubernetes/charts/edge-kubernetes/templates/iotedged-deployment.yaml, kubernetes/charts/edge-kubernetes/values.yaml
pick changes from master to put into beta7 image:
[k8s] add ability set fsGroup and nodeSelector for iotedged deployment (#2696)
[k8s] Device and hubname can start with numerical values. (#2701)
[k8s] Prepare charts for beta7 (#2716)
=> [k8s public preview] Cherry pick changes for beta7

test/modules/DirectMethodSender/Program.cs, test/modules/TemperatureFilter/docker/linux/amd64/Dockerfile, test/modules/TemperatureFilter/docker/linux/arm32v7/Dockerfile, test/modules/TemperatureFilter/docker/linux/arm64v8/Dockerfile
We have some erroneous logging.
=> Fix logging in TempFilter and DirectMethodSender

mqtt/mqtt-broker/src/broker.rs, mqtt/mqttd/src/main.rs
Unblock any operation in mqtt broker. Fix some redundancy in the code
=> [mqtt] Quickfix for mqtt default authorization

edge-agent/docker/manifest.yaml.template, edge-hub/docker/manifest.yaml.template, edge-modules/SimulatedTemperatureSensor/docker/manifest.yaml.template, edgelet/iotedge-diagnostics/docker/manifest.yaml.template
Remove Windows ARM in manifest templates
=> Fix image build

builds/checkin/edgelet.yaml
There is a strange linker error
=> disable edgelet code coverage

mqtt/mqtt-broker/src/broker.rs
A quick fix to make complience test pass.
=> [mqtt] Fix compliance test when broker unable to dispatch messages to offline session

mqtt/mqtt-broker/src/auth/authentication.rs, mqtt/mqtt-broker/src/auth/authorization.rs, mqtt/mqtt-broker/src/broker.rs, mqtt/mqtt-broker/src/configuration.rs, mqtt/mqtt-broker/src/lib.rs, mqtt/mqtt-broker/src/persist.rs, mqtt/mqtt-broker/src/session.rs, mqtt/mqtt-broker/src/subscription.rs, mqtt/mqtt3/src/client/mod.rs
This PR fixes clippy warnings related to wildcard imports.
=> Fixed clippy warnings

edgelet/dps/src/lib.rs, edgelet/dps/src/model.rs, edgelet/dps/src/registration.rs, edgelet/iotedged/src/lib.rs, edgelet/provisioning/src/provisioning.rs
Move progress on DPS feature to an azure owned feature branch.
=> Handoff - DPS to feature branch

mqtt/mqtt-broker/tests/common.rs, mqtt/mqtt-broker/tests/smoke.rs
This PR adds:
- Retained messages w/ zero-length payload test
- Some TestClient improvements
=> [mqtt]: Retained messages zero payload integration tests

mqtt/mqtt-broker/benches/dispatch_messages.rs, mqtt/mqtt-broker/src/broker.rs
Refactored dispatch messages benches to collect execution time more precisely without time that acknowledgement that broker processed a message waited in the channel.
It appeared that `fan-in` and `one-to-one` scenarios mean the same thing considering single threaded. Introduced 2 new scenarios that operates with 2 variables: number of subscribers and number of topic broker will dispatch messages to for a single publication.
Scenarios are:
1. all subscribers receive messages on their own topic
2. all subscribers receive messages on shared topic
=> [mqtt] Update perf strategy and bench groups

mqtt/mqtt-broker/tests/smoke.rs
There was a race condition in the `will_message` test where Client A could terminate before Client B subscription is ready, so Client B would never receive the will.
This PR fixes that.
=> Fix flaky will_message test.

test/modules/DirectMethodSender/DirectMethodCloudSender.cs
Reverts "Introduce ConnectionTimeout and MethodTimeout to CloudDirectMethodSender" (#2878)
=> Revert "Introduce ConnectionTimeout and MethodTimeout to CloudDirectMethodSender"

e2e_deployment_files/long_haul_deployment.template.json, e2e_deployment_files/long_haul_deployment.template.windows.json
Log Rotation for moduleRestarter
=> Log Rotation for moduleRestarter

mqtt/mqtt-broker/src/auth.rs, mqtt/mqtt-edgehub/Cargo.toml, mqtt/mqttd/Cargo.toml
This PR fixes an issue where CI pipeline for perf tests cannot build MQTT broker without EdgeHub integration.
=> [mqtt] Fix mqttd build feature

edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/AuthAgentProtocolHead.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/AuthAgentStartup.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.csproj
- changed routing setup
- set Newtonsoft as json serializer, which is not the default in 3.1 anymore
=> fixed Auth endpoint broken by aspnet 3.1 upgrade

builds/e2e/connectivity.yaml, builds/e2e/templates/connectivity-deploy.yaml, test/connectivity/scripts/connectivityTest.sh
Changing connectivity tests to be able to configure debug logs from the pipeline variable.
=> Let Debug logs be configurable for connectivity test pipeline

mqtt/mqtt-broker/src/auth.rs, mqtt/mqtt-broker/src/error.rs, mqtt/mqtt-broker/src/lib.rs, mqtt/mqtt-broker/src/server.rs, mqtt/mqtt-broker/src/transport.rs
Print whole stack of inner error messages in the log when broker failed to start working.
=> [mqtt] Print detailed error messages in the log when failed to start

mqtt/mqtt-broker-core/src/auth/mod.rs, mqtt/mqtt-broker-core/src/lib.rs, mqtt/mqtt-broker/benches/dispatch_messages.rs, mqtt/mqtt-broker/src/connection.rs, mqtt/mqtt-broker/src/error.rs, mqtt/mqtt-broker/src/subscription.rs
Make std::fmt import instead of FQNs
=> [mqtt] Fix std::fmt imports

edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/Microsoft.Azure.Devices.Edge.Agent.Diagnostics.csproj, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/Microsoft.Azure.Devices.Edge.Agent.IoTHub.csproj, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/Microsoft.Azure.Devices.Edge.Hub.Amqp.csproj, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.csproj, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/Microsoft.Azure.Devices.Edge.Hub.Core.csproj, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Http/Microsoft.Azure.Devices.Edge.Hub.Http.csproj, edge-modules/MetricsCollector/MetricsCollector.csproj, edge-modules/SimulatedTemperatureSensor/SimulatedTemperatureSensor.csproj, edge-modules/functions/binding/src/Microsoft.Azure.WebJobs.Extensions.EdgeHub/Microsoft.Azure.WebJobs.Extensions.EdgeHub.csproj, samples/dotnet/EdgeDownstreamDevice/EdgeDownstreamDevice.csproj, samples/dotnet/EdgeX509AuthDownstreamDevice/EdgeX509AuthDownstreamDevice.csproj, smoke/IotEdgeQuickstart/IotEdgeQuickstart.csproj, smoke/LeafDevice/LeafDevice.csproj, test/Microsoft.Azure.Devices.Edge.Test.Common/Microsoft.Azure.Devices.Edge.Test.Common.csproj, test/modules/CloudToDeviceMessageTester/CloudToDeviceMessageTester.csproj, test/modules/DeploymentTester/DeploymentTester.csproj, test/modules/DirectMethodReceiver/DirectMethodReceiver.csproj, test/modules/DirectMethodSender/DirectMethodSender.csproj, test/modules/EdgeHubRestartTester/EdgeHubRestartTester.csproj, test/modules/MetricsValidator/MetricsValidator.csproj, test/modules/ModuleLib/Microsoft.Azure.Devices.Edge.ModuleUtil.csproj, test/modules/ModuleRestarter/ModuleRestarter.csproj, test/modules/Relayer/Relayer.csproj, test/modules/TemperatureFilter/TemperatureFilter.csproj, test/modules/TestAnalyzer/TestAnalyzer.csproj, test/modules/TestResultCoordinator/TestResultCoordinator.csproj, test/modules/TwinTester/TwinTester.csproj, test/modules/load-gen/load-gen.csproj
Update SDK to 1.26.0 on master branch. The update includes the following packages:
- Microsoft.Azure.Devices.1.21.0
- Microsoft.Azure.Devices.Client.1.26.0
=> Update SDK to 1.26.0 on master branch

edge-agent/docker/linux/arm32v7/Dockerfile, edge-agent/docker/linux/arm64v8/Dockerfile, kubernetes/charts/edge-kubernetes-crd/Chart.yaml, kubernetes/charts/edge-kubernetes/Chart.yaml, kubernetes/charts/edge-kubernetes/values.yaml
Release new public preview images, This updated the agent base image and updated the Helm charts.  This PR puts these changes to the master branch.
=> [k8s] update helm charts to beta9 in master branch

edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/EdgeAgentConnection.cs, edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.IoTHub.Test/EdgeAgentConnectionTest.cs
Merge EdgeAgent AMQP link fix from master (PR#3101) to 1.0.10 branch.
=> Merge EdgeAgent AMQP link fix

edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/ConnectionManager.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/DependencyManager.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/RoutingModule.cs, edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/ConnectionManagerTest.cs
Fix ConnectionManager tests since RemoveDeviceConnection will remove cloud connection as well in https://github.com/Azure/iotedge/pull/3100
=> Fix ConnectionManager tests

edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/ConnectionManager.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/DependencyManager.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/RoutingModule.cs, edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/ConnectionManagerTest.cs, edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.E2E.Test/DependencyManager.cs
Fix EdgeHub cloud connection.  Merge PR#3100 from release/1.0.9 to master.
=> Fix EdgeHub cloud connection

CHANGELOG.md, versionInfo.json
* Remove device cloud connection upon device disconnection ([60b125e](https://github.com/Azure/iotedge/commit/60b125ee5116e23fc4ba6d86a1bb4971f231d6ce))
* Upgrade Microsoft.Azure.Devices.Client from 1.23.1 to 1.23.2 ([0e58900](https://github.com/Azure/iotedge/commit/0e58900f58251ddfd6e69dc09484ea798f266f10))
* Remove device cloud connection upon device disconnection ([fb33e62](https://github.com/Azure/iotedge/commit/fb33e62cb58937009fa2c491021e9629b99cbe29))
* Upgrade Microsoft.Azure.Devices.Client from 1.23.1 to 1.23.2 ([0e58900](https://github.com/Azure/iotedge/commit/0e58900f58251ddfd6e69dc09484ea798f266f10))
=> Prepare for release 1.0.9.3

edge-agent/docker/linux/amd64/Dockerfile, edge-hub/docker/linux/amd64/Dockerfile, test/modules/EdgeHubRestartTester/docker/linux/amd64/Dockerfile, test/modules/EdgeHubRestartTester/docker/windows/amd64/Dockerfile, test/modules/ModuleRestarter/docker/windows/arm32v7/Dockerfile, test/modules/TestAnalyzer/docker/linux/amd64/Dockerfile, test/modules/TestResultCoordinator/docker/linux/amd64/Dockerfile, test/modules/TwinTester/docker/linux/amd64/Dockerfile
Fix docker file for wrong tag and adding comment to specify base docker file location
=> fix docker files

edge-agent/docker/linux/amd64/Dockerfile, edge-hub/docker/linux/amd64/Dockerfile, test/modules/EdgeHubRestartTester/docker/linux/amd64/Dockerfile, test/modules/EdgeHubRestartTester/docker/windows/amd64/Dockerfile, test/modules/ModuleRestarter/docker/windows/arm32v7/Dockerfile, test/modules/TestAnalyzer/docker/linux/amd64/Dockerfile, test/modules/TestResultCoordinator/docker/linux/amd64/Dockerfile, test/modules/TwinTester/docker/linux/amd64/Dockerfile
=> Reverts Azure/iotedge#3141

edgelet/edgelet-hsm/tests/crypto_get_random.rs, edgelet/edgelet-iothub/src/lib.rs, edgelet/iotedge-proxy/src/lib.rs, edgelet/iotedge/src/lib.rs
Allow Clippy's similar_names warning
Cherry-Pick from: https://github.com/Azure/iotedge/commit/84a7907a4c7ccfc812b7465da9b4e0825da2764d
=> Allow Clippy's similar_names warnings

edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Http/middleware/RegistryProxyMiddleware.cs, edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.Http.Test/RegistryProxyMiddlewareTest.cs
fix regex in registry proxy middleware and add tests.
=> fix registry proxy middleware

edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/EdgeAgentConnection.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/sdkClient/WrappingSdkModuleClient.cs
Removed the check for TimeoutException
Call dispose instead of close on the module sdk
=> Fix edge agent connection 1.0.9

edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/EdgeAgentConnection.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/sdkClient/WrappingSdkModuleClient.cs, edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.IoTHub.Test/EdgeAgentConnectionTest.cs
* Recreate connection after every exception
=> Fix edge agent connection (#3172)

mqtt/mqtt-edgehub/src/auth/authorization/edgehub.rs, mqtt/mqtt-edgehub/src/topic/translation.rs
Add topics translation rules for module-to-module communication 
Add corresponding authz rules
=> [mqtt] Ensure module-to-module topics translation and authz

edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/Microsoft.Azure.Devices.Edge.Agent.Diagnostics.csproj, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/Microsoft.Azure.Devices.Edge.Agent.IoTHub.csproj, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/Microsoft.Azure.Devices.Edge.Hub.Amqp.csproj, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.csproj, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/Microsoft.Azure.Devices.Edge.Hub.Core.csproj, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Http/Microsoft.Azure.Devices.Edge.Hub.Http.csproj, edge-modules/MetricsCollector/MetricsCollector.csproj, edge-modules/SimulatedTemperatureSensor/SimulatedTemperatureSensor.csproj, edge-modules/functions/binding/src/Microsoft.Azure.WebJobs.Extensions.EdgeHub/Microsoft.Azure.WebJobs.Extensions.EdgeHub.csproj, samples/dotnet/EdgeDownstreamDevice/EdgeDownstreamDevice.csproj, samples/dotnet/EdgeX509AuthDownstreamDevice/EdgeX509AuthDownstreamDevice.csproj, smoke/IotEdgeQuickstart/IotEdgeQuickstart.csproj, smoke/LeafDevice/LeafDevice.csproj, test/Microsoft.Azure.Devices.Edge.Test.Common/Microsoft.Azure.Devices.Edge.Test.Common.csproj, test/modules/CloudToDeviceMessageTester/CloudToDeviceMessageTester.csproj, test/modules/DeploymentTester/DeploymentTester.csproj, test/modules/DirectMethodReceiver/DirectMethodReceiver.csproj, test/modules/DirectMethodSender/DirectMethodSender.csproj, test/modules/EdgeHubRestartTester/EdgeHubRestartTester.csproj, test/modules/MetricsValidator/MetricsValidator.csproj, test/modules/ModuleLib/Microsoft.Azure.Devices.Edge.ModuleUtil.csproj, test/modules/ModuleRestarter/ModuleRestarter.csproj, test/modules/Relayer/Relayer.csproj, test/modules/TemperatureFilter/TemperatureFilter.csproj, test/modules/TestAnalyzer/TestAnalyzer.csproj, test/modules/TestResultCoordinator/TestResultCoordinator.csproj, test/modules/TwinTester/TwinTester.csproj, test/modules/load-gen/load-gen.csproj
Update SDK version {Microsoft.Azure.Devices.Edge.Hub.Amqp.2.4.4, Microsoft.Azure.Devices.1.22.0, Microsoft.Azure.Devices.Client.1.27.0}
=> Update SDK Client 1.27.0

mqtt/mqtt-edgehub/src/edgelet/workload/client.rs, mqtt/mqttd/src/broker/bootstrap/edgehub.rs
Two fixes:
- Expect 201 response
- Fix env var name casing
=> Broker workload client fixes

edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Docker/models/HostConfig.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/Constants.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/edgedeployment/deployment/KubernetesDeploymentMapper.cs, edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/KubernetesDeploymentMapperTest.cs, kubernetes/doc/edge-deployment-to-k8s-translations.md
Add IpcMode to HostConfig, if IpcMode is "host", set the podspec "hostIpc" to true
=> [k8s] Map docker "IpcMode" to k8s "HostIPC"

edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Docker/models/HostConfig.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/Constants.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/edgedeployment/deployment/KubernetesDeploymentMapper.cs, edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/KubernetesDeploymentMapperTest.cs, kubernetes/doc/edge-deployment-to-k8s-translations.md
Add IpcMode to HostConfig, if IpcMode is "host", set the podspec "hostIpc" to true
=> [k8s public preview] Map docker "IpcMode" to k8s "HostIPC" (#3247)

e2e_deployment_files/connectivity_deployment.template.json, e2e_deployment_files/edgehub_restart_deployment.template.json, e2e_deployment_files/long_haul_deployment.template.json, e2e_deployment_files/long_haul_deployment.template.windows.json, e2e_deployment_files/stress_deployment.template.json, e2e_deployment_files/stress_deployment.template.windows.json
Fixing the port 443 on Connectivity, Stress, and Long Haul
=> Fixing the port 443 on Connectivity, Stress, and Long Haul

e2e_deployment_files/long_haul_deployment.template.json, e2e_deployment_files/long_haul_deployment.template.windows.json, e2e_deployment_files/stress_deployment.template.json, e2e_deployment_files/stress_deployment.template.windows.json
Unmap port 443 for Long Haul and Stress Tests
=> Unmap port 443 for Long Haul and Stress Tests

mqtt/contrib/edgehub/broker.json, mqtt/mqtt-broker/src/tls.rs, mqtt/mqtt-broker/src/transport.rs, mqtt/mqtt-edgehub/src/settings.rs, mqtt/mqtt-generic/src/settings.rs, mqtt/mqttd/src/broker/bootstrap/edgehub.rs, mqtt/mqttd/src/broker/bootstrap/generic.rs, scripts/linux/generic-rust/build.sh
Read settings from ENV.
Use cert and private key pair instead of pksc12 file
=> [mqtt] Read settings from ENV 

edge-agent/docker/windows/arm32v7/Dockerfile, edge-hub/docker/windows/arm32v7/Dockerfile, edge-modules/DirectMethodCloudSender/docker/windows/arm32v7/Dockerfile, edge-modules/DirectMethodReceiver/docker/windows/arm32v7/Dockerfile, edge-modules/DirectMethodSender/docker/windows/arm32v7/Dockerfile, edge-modules/ModuleRestarter/docker/windows/arm32v7/Dockerfile, edge-modules/SimulatedTemperatureSensor/docker/windows/arm32v7/Dockerfile, edge-modules/TemperatureFilter/docker/windows/arm32v7/Dockerfile, edge-modules/TestAnalyzer/docker/windows/arm32v7/Dockerfile, edge-modules/TwinTester/docker/windows/arm32v7/Dockerfile, edge-modules/load-gen/docker/windows/arm32v7/Dockerfile, scripts/linux/createArmBase.sh, scripts/windows/build/Publish-DockerImage.ps1
Update dockerfiles to only pull image from docker hub
=> Update dockerfiles to only pull image from docker hub

mqtt/mqtt-broker/src/session/state/mod.rs, mqtt/mqtt-broker/src/session/state/queue.rs, mqtt/mqtt3/examples/publisher.rs
Adds a log message which was dropped due to queue limits.
=> [mqtt] Log message which was dropped due to queue limits

mqtt/Cargo.lock, mqtt/mqtt-edgehub/Cargo.toml, mqtt/mqtt-edgehub/src/auth/authentication/edgehub.rs
=> [mqtt] Add retry policy to authenticate client

edge-hub/src/Microsoft.Azure.Devices.Routing.Core/endpoints/StoringAsyncEndpointExecutor.cs
Cherry-pick from release/1.0.10 to master
=> Fix processed message priority for metrics (#3330)

edgelet/iotedge/src/check/checks/container_engine_is_moby.rs, edgelet/iotedge/src/check/mod.rs
Fixes #3295
Cherry-pick from master of 6c13ce0420efa8510b222b3a469767a99cca2714
=> Update Moby version check in iotedge-check for new Moby version scheme.

e2e_deployment_files/connectivity_deployment.template.json, e2e_deployment_files/dm_module_to_module_deployment.json, e2e_deployment_files/edgehub_restart_deployment.template.json, e2e_deployment_files/long_haul_deployment.template.json, e2e_deployment_files/long_haul_deployment.template.windows.json, e2e_deployment_files/module_to_functions_deployment.template.json, e2e_deployment_files/module_to_module_deployment.template.json, e2e_deployment_files/quickstart_deployment.template.json, e2e_deployment_files/runtime_only_deployment.template.json, e2e_deployment_files/stress_deployment.template.json, e2e_deployment_files/stress_deployment.template.windows.json, smoke/IotEdgeQuickstart/details/Details.cs
Since nested edge is now enabled, we should disable it for our single node tests. I also took this opportunity to format the json files. After this PR is merged we can cherry pick to preview/iiot.
=> Disable nested edge in tests

edgelet/build/windows/package.ps1
Update Windows Moby engine and cli to latest release
=> update moby win (#3350)

test/Microsoft.Azure.Devices.Edge.Test/Metrics.cs
The 'ValidateMetrics' test produces a _large_ test report. It has loads of great info, but when there's a failure I just want to see the failures. This change updates the `Report` serialization class to filter out the successes and only give us the failures.
=> Generate reduced output when ValidateMetrics fails

edgelet/edgelet-core/src/module.rs, edgelet/edgelet-docker/src/runtime.rs, edgelet/edgelet-http-mgmt/src/client/module.rs, edgelet/edgelet-kube/src/runtime.rs, edgelet/edgelet-test-utils/src/module.rs, edgelet/iotedged/src/error.rs, edgelet/iotedged/src/lib.rs
Cherry-picked from master 2d1a6098
=> Stop existing modules when iotedged starts

builds/e2e/e2e.yaml
We also need to be triggering E2E on edgelet changes.
=> Trigger E2E on edgelet changes

.github/ISSUE_TEMPLATE/issue-label-list.yml, .github/workflows/issue-labeler.yml
Auto labeling github issues with `iotedge` and `customer-reported`
=> Auto labeling github issues 

.github/workflows/issue-labeler.yml
Added enable-versioned-regex to github labeling
=> Added enable-versioned-regex to github labeling

.github/ISSUE_TEMPLATE/issue-label-list.yml, .github/workflows/issue-labeler.yml
Update regex syntax for github labeler
=> Update regex syntax for github labeller

builds/misc/images-mqtt.yaml, scripts/linux/cross-platform-rust-build.sh
We converted the broker build to same style as container build, but that doesn't support generic features.
=> MQTT Broker Perf Tests: build with generic features

edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/SubscriptionProcessor.cs
Adding Try Finally and refactor based on comments on last PR that got merged (https://github.com/Azure/iotedge/pull/3390)
=> Subscription Processing fix refactor

edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/Microsoft.Azure.Devices.Edge.Agent.Diagnostics.csproj, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/Microsoft.Azure.Devices.Edge.Agent.IoTHub.csproj, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/Microsoft.Azure.Devices.Edge.Hub.Core.csproj, edge-modules/MetricsCollector/MetricsCollector.csproj, edge-modules/SimulatedTemperatureSensor/SimulatedTemperatureSensor.csproj, edge-modules/functions/binding/src/Microsoft.Azure.WebJobs.Extensions.EdgeHub/Microsoft.Azure.WebJobs.Extensions.EdgeHub.csproj, samples/dotnet/EdgeDownstreamDevice/EdgeDownstreamDevice.csproj, samples/dotnet/EdgeX509AuthDownstreamDevice/EdgeX509AuthDownstreamDevice.csproj, smoke/LeafDevice/LeafDevice.csproj, test/Microsoft.Azure.Devices.Edge.Test.Common/Microsoft.Azure.Devices.Edge.Test.Common.csproj, test/modules/CloudToDeviceMessageTester/CloudToDeviceMessageTester.csproj, test/modules/DirectMethodReceiver/DirectMethodReceiver.csproj, test/modules/DirectMethodSender/DirectMethodSender.csproj, test/modules/EdgeHubRestartTester/EdgeHubRestartTester.csproj, test/modules/MetricsValidator/MetricsValidator.csproj, test/modules/ModuleLib/Microsoft.Azure.Devices.Edge.ModuleUtil.csproj, test/modules/ModuleRestarter/ModuleRestarter.csproj, test/modules/Relayer/Relayer.csproj, test/modules/TemperatureFilter/TemperatureFilter.csproj, test/modules/TwinTester/TwinTester.csproj, test/modules/load-gen/load-gen.csproj
Update the following SDK:
- Microsoft.Azure.Devices.Client.1.28.0
=> Update SDK version to Microsoft.Azure.Devices.Client.1.28.0

edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/Microsoft.Azure.Devices.Edge.Agent.Diagnostics.csproj, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/Microsoft.Azure.Devices.Edge.Agent.IoTHub.csproj, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/Microsoft.Azure.Devices.Edge.Hub.Core.csproj, edge-modules/MetricsCollector/MetricsCollector.csproj, edge-modules/SimulatedTemperatureSensor/SimulatedTemperatureSensor.csproj, edge-modules/functions/binding/src/Microsoft.Azure.WebJobs.Extensions.EdgeHub/Microsoft.Azure.WebJobs.Extensions.EdgeHub.csproj, samples/dotnet/EdgeDownstreamDevice/EdgeDownstreamDevice.csproj, samples/dotnet/EdgeX509AuthDownstreamDevice/EdgeX509AuthDownstreamDevice.csproj, smoke/LeafDevice/LeafDevice.csproj, test/Microsoft.Azure.Devices.Edge.Test.Common/Microsoft.Azure.Devices.Edge.Test.Common.csproj, test/modules/CloudToDeviceMessageTester/CloudToDeviceMessageTester.csproj, test/modules/DirectMethodReceiver/DirectMethodReceiver.csproj, test/modules/DirectMethodSender/DirectMethodSender.csproj, test/modules/EdgeHubRestartTester/EdgeHubRestartTester.csproj, test/modules/MetricsValidator/MetricsValidator.csproj, test/modules/ModuleLib/Microsoft.Azure.Devices.Edge.ModuleUtil.csproj, test/modules/ModuleRestarter/ModuleRestarter.csproj, test/modules/Relayer/Relayer.csproj, test/modules/TemperatureFilter/TemperatureFilter.csproj, test/modules/TwinTester/TwinTester.csproj, test/modules/load-gen/load-gen.csproj
Update the following SDK:
- Microsoft.Azure.Devices.Client.1.28.0
Cherry-picked from https://github.com/Azure/iotedge/commit/cdf36b01a7a18b0a4f9a1e3d5943fb9aa44029ea
=> Update SDK version to Microsoft.Azure.Devices.Client.1.28.0 (#3433)

edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/MetricsWorker.cs, edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Diagnostics.Test/MetricsWorkerTest.cs
=> Hash all instances of module ids in device telemetry

mqtt/mqtt-edgehub/Cargo.toml, mqtt/mqtt-edgehub/src/command.rs, mqtt/mqttd/src/broker/bootstrap/edgehub.rs
There are some cleanup improvements we can make to client disconnect. Also I added a few lines of logging.
=> [mqtt] Cleanup client disconnect and add logging

edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.IoTHub.Test/EdgeAgentConnectionTest.cs
Cherry-picked from:
https://github.com/Azure/iotedge/commit/6e7321fcb08d0aabf618a756eb58cad57758616c
=> Update agent schema version in E2E test (#3458)

mqtt/Cargo.lock, mqtt/mqtt-bridge/Cargo.toml, mqtt/mqtt-bridge/src/bridge.rs, mqtt/mqtt-bridge/src/controller.rs, mqtt/mqtt-bridge/src/lib.rs, mqtt/mqtt-bridge/src/settings.rs
Fix clippy warnings for mqtt-bridge
=> [mqtt] Fix clippy warnings for mqtt-bridge

edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/Microsoft.Azure.Devices.Edge.Agent.Diagnostics.csproj, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/Microsoft.Azure.Devices.Edge.Agent.IoTHub.csproj, edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/Microsoft.Azure.Devices.Edge.Hub.Core.csproj, edge-modules/MetricsCollector/MetricsCollector.csproj, edge-modules/SimulatedTemperatureSensor/SimulatedTemperatureSensor.csproj, edge-modules/functions/binding/src/Microsoft.Azure.WebJobs.Extensions.EdgeHub/Microsoft.Azure.WebJobs.Extensions.EdgeHub.csproj, samples/dotnet/EdgeDownstreamDevice/EdgeDownstreamDevice.csproj, samples/dotnet/EdgeX509AuthDownstreamDevice/EdgeX509AuthDownstreamDevice.csproj, smoke/LeafDevice/LeafDevice.csproj, test/Microsoft.Azure.Devices.Edge.Test.Common/Microsoft.Azure.Devices.Edge.Test.Common.csproj, test/modules/CloudToDeviceMessageTester/CloudToDeviceMessageTester.csproj, test/modules/DirectMethodReceiver/DirectMethodReceiver.csproj, test/modules/DirectMethodSender/DirectMethodSender.csproj, test/modules/EdgeHubRestartTester/EdgeHubRestartTester.csproj, test/modules/MetricsValidator/MetricsValidator.csproj, test/modules/ModuleLib/Microsoft.Azure.Devices.Edge.ModuleUtil.csproj, test/modules/ModuleRestarter/ModuleRestarter.csproj, test/modules/Relayer/Relayer.csproj, test/modules/TemperatureFilter/TemperatureFilter.csproj, test/modules/TwinTester/TwinTester.csproj, test/modules/load-gen/load-gen.csproj
Update to use Device.Client 1.28.1-NestedEdge
=> Update to use Device.Client 1.28.1-NestedEdge

edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/Constants.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/modules/AgentModule.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/Constants.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/DependencyManager.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/CommonModule.cs, edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.E2E.Test/DependencyManager.cs, edge-util/src/Microsoft.Azure.Devices.Edge.Storage.RocksDb/RocksDbOptionsProvider.cs, edge-util/test/Microsoft.Azure.Devices.Edge.Storage.RocksDb.Test/DbStoreProviderTest.cs, edge-util/test/Microsoft.Azure.Devices.Edge.Storage.RocksDb.Test/RockDbWrapperTest.cs, edge-util/test/Microsoft.Azure.Devices.Edge.Storage.RocksDb.Test/RocksDbOptionsProviderTest.cs, edge-util/test/Microsoft.Azure.Devices.Edge.Storage.RocksDb.Test/TestRocksDbStoreProvider.cs, test/modules/TestAnalyzer/TestStatusStorage.cs, test/modules/TestResultCoordinator/Startup.cs, test/modules/TwinTester/TwinEventStorage.cs
Expose the MaxOpenFiles setting in RocksDb to the user via the RocksDB_MaxOpenFiles environment variable.
=> [1.0.10]Add "RocksDB_MaxOpenFiles" to options we can pass to Agent and Hub.

mqtt/edgelet-client/src/lib.rs, mqtt/edgelet-client/src/workload/client.rs, mqtt/edgelet-client/src/workload/models/mod.rs, mqtt/edgelet-client/src/workload/models/sign_request.rs
Add call to sign api which is needed to create a token to connect to upstream
=> Add sign method to mqtt edgelet client 

edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/BrokerServiceIdentityTest.cs
Adding serde tests and a compare unit tests for BrokerServiceIdentity.
=> Adding unit tests for BrokerServiceIdentity

scripts/linux/runE2ETest.sh
Fix condition for bypassing clean-up.
=> Fix clean-up condition

builds/misc/images-release.yaml
Allow release image pipeline to use a custom CR
=> Allow release image pipeline to use a custom CR

edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs, mqtt/Cargo.lock
Resolve conflicts from master to iiot branch.
=> Fixed merge conflicts

edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.IoTHub.Test/EdgeAgentConnectionTest.cs
Looks like I missed a couple the first time around.
=> Update schema version for other failing tests

mqtt/mqtt-broker/src/settings/size.rs
Port of #3508 to `preview/iiot`
=>  Run some proptests only on 64bit platform

smoke/IotEdgeQuickstart/Program.cs, smoke/IotEdgeQuickstart/Quickstart.cs, smoke/IotEdgeQuickstart/details/Details.cs, smoke/IotEdgeQuickstart/details/IBootstrapper.cs, smoke/IotEdgeQuickstart/details/IotedgedLinux.cs, smoke/IotEdgeQuickstart/details/IotedgedWindows.cs, test/connectivity/scripts/connectivityTest.sh
Use parent hostname in connectivity test if provided
=> Enable connectivity test for nested edge scenario

doc/BuiltInMetrics.md, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/ProvisioningInfo.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/SystemInfo.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2020_07_07/ModuleManagementHttpClient.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2020_07_07/generatedCode/EdgeletHttpClient.cs, edgelet/Cargo.lock, edgelet/api/managementVersion_2020_07_07.yaml, edgelet/edgelet-core/src/lib.rs, edgelet/edgelet-core/src/module.rs, edgelet/edgelet-core/src/settings.rs, edgelet/edgelet-docker/src/runtime.rs, edgelet/edgelet-kube/src/runtime.rs, edgelet/edgelet-test-utils/src/module.rs
Cherry-picked from master 76ca4cb16fe019f58fb5c817f84d2b056ae3d042.
=> Report provisioning type in metrics

edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/INestedEdgeParentUrlParser.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/NestedEdgeParentUrlParser.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/requests/ModuleLogsUploadRequest.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/requests/SupportBundleRequest.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Docker/DockerConfig.cs, edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/NestedEdgeParentUrlParserTest.cs, edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Docker.Test/DockerConfigTest.cs, edge-modules/api-proxy-module/src/monitors/config_monitor.rs, edge-modules/api-proxy-module/templates/nginx_default_config.conf
Adding blob upload for nested edge.
Tested with 3 level of nesting:
Upload blob at level 2 and level 1 (deepest).
Download container at level 3, 2 and 1.
Upload support bundle at level 1.
=> Blob upload

mqtt/Cargo.lock, mqtt/policy/src/core/builder.rs, mqtt/policy/src/errors.rs, mqtt/policy/src/matcher.rs, mqtt/policy/src/validator.rs
- Added associated error type for `PolicyValidator`.
- Improved default validator
=> Some enhancements to the validation errors

scripts/windows/setup/IotEdgeSecurityDaemon.ps1
Built-in Moby engine is not used in LCOW configuration. However, the service remains active and consumes the DNS port (53) that caused WSL2 to fail (https://github.com/microsoft/WSL/issues/4929).
This PR makes two simple changes when running w/ LCOW:  (a) disables the built-in Moby engine  and (b) removes the iotedge service dependency. It also doesn't enable the "Containers" Windows feature which is only required for Windows containers.
(cherry picked from commit 25ec31c71d4d665d7f58390e7d2b42499c4c65a4)
=> Fix for wsl2 (#3574)

edgelet/support-bundle/src/support_bundle.rs
Before the upload support bundle direct method, support bundle was only called from the iotedge tool. This made it easy to get the iotedge executable using the first argument. Now that iotedged also calls support bundle, it needs to rely on the path to find the iotedge tool.
=> Fix check in support bundle (#3583)

edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2020_07_07/generatedCode/EdgeletHttpClient.cs
Fixing the JSON property name.
=> Systeminfo metric virtualized info (#3655)

edge-modules/api-proxy-module/rust-sdk/hyper-uds/src/lib.rs
Fixing clippy issue in API proxy
=> Fixing clippy issue in API proxy

edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/EdgeAgentConnection.cs, edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.IoTHub.Test/EdgeAgentConnectionTest.cs, edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/config/EdgeHubDesiredProperties.cs, edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/config/EdgeHubDesiredPropertiesTest.cs
Cherry-picked from https://github.com/Azure/iotedge/commit/4a4f880e800620c3c8b0e330a29252a54cf51496
=> Remove deployment manifest minor version strict validation (#3692)

mqtt/mqtt-bridge/src/persist/waking_state/rocksdb.rs
We need to handle offset correctly for persisted storage. I don't want to forget so am adding this note.
=> [mqtt] Add todo for persisted store

edgelet/edgelet-http/src/util/hyperwrap.rs
Fix for IoT Edge devices not provisioning with DPS when using X.509 via a proxy. The TLS connector (which contains the identity certificate) is now also used for the tunneling connector to DPS and IoT Hub. Tested locally using Squid proxy.
=> Proxy connector requires TLS connector

mqtt/mqtt-edgehub/src/topic/translation.rs, mqtt/mqtt-edgehub/tests/delivery.rs
Fix wrong m2m topic translation.
=> [mqtt] Fix m2m topic translation

edge-modules/api-proxy-module/build.sh, edge-modules/api-proxy-module/docker/linux/arm32v7/Dockerfile, edge-modules/api-proxy-module/templates/nginx_default_config.conf, scripts/linux/buildAPIProxy.sh
reduce size of arm image
https://dev.azure.com/msazure/One/_build/results?buildId=35786474&view=results
=> reduce size of arm image

edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/Constants.cs, edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/DependencyManager.cs, edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/ExperimentalFeatures.cs, edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs, edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/appsettings_hub.json, edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.E2E.Test/DependencyManager.cs, edge-hub/watchdog/src/main.rs
- Consolidate nested edge and mqtt broker feature flags in "experimentalFeatures"
- Default both feature flags to false
- Skip all MQTT broker components in both watchdog and EH core if it's disabled
- Skip MQTT protocol head if MQTT broker is enabled
=> IIOT feature flags

mqtt/mqtt-bridge/src/bridge.rs, mqtt/mqtt-bridge/src/messages.rs, mqtt/mqtt-bridge/src/persist/waking_state/memory.rs
While testing I noticed we had some logs that looked messy / inconsistent
=> [mqtt] Logging improvements

mqtt/mqtt-broker/src/ready.rs, mqtt/mqtt-edgehub/src/auth/authorization/edgehub.rs, mqtt/mqtt-edgehub/src/auth/authorization/policy.rs, mqtt/mqtt-edgehub/src/command/authorized_identities.rs, mqtt/mqtt-edgehub/src/command/policy_update.rs, mqtt/mqttd/src/broker/bootstrap/mod.rs, mqtt/policy/src/errors.rs
- Added `PolicyReady` event to indicate that authorization policy engine is ready
- A bugfix for deserializing policy update.
- Log messages fine tuning
=> Policy ready event + fine tuning of log messages.

mqtt/mqtt-edgehub/src/command/authorized_identities.rs, mqtt/mqtt-edgehub/src/command/bridge_update.rs, mqtt/mqtt-edgehub/src/command/disconnect.rs, mqtt/mqtt-edgehub/src/command/handler.rs, mqtt/mqtt-edgehub/src/command/policy_update.rs
=> Added a bit more logs.

mqtt/mqtt-broker/src/persist.rs
Those tests are running very slow on arm32 and often timeout.
=> Disable persist proptests on arm32

mqtt/mqtt-broker/src/persist.rs
Disable all persist tests on arm32
=> Disable all persist tests on arm32

builds/misc/addons-publish.yaml, builds/misc/addons-release.yaml, builds/misc/images.yaml, edge-modules/api-proxy-module/build.sh, edge-modules/api-proxy-module/docker/manifest.yaml.template, edge-modules/api-proxy-module/readme.md
=> change api proxy image name

mqtt/mqtt-edgehub/src/settings.rs
Serialized test using environment variables, to avoid race condition
=> serializing test

kubernetes/charts/edge-kubernetes-crd/Chart.yaml, kubernetes/charts/edge-kubernetes/Chart.yaml, kubernetes/charts/edge-kubernetes/values.yaml
New chart version, new image version.
New changes for beta12:
[k8s] Discovered some problems with createOptions parsing. (#3743)
[k8s] Environment Variables can be null or empty. (#3780)
=> [k8s] Helm chart update for beta12

mqtt/Cargo.lock, mqtt/mqtt-bridge/src/bridge.rs
Fixing the bridge client id to match edgehub expected system component structure.
=> [mqtt] Fix bridge client id error

mqtt/mqtt-bridge/src/bridge.rs
I was rushing and I accidentally flipped these around. Fixing.
=> [mqtt] Flip device id and settings in client id

mqtt/mqtt-bridge/src/client.rs, mqtt/mqtt-bridge/src/pump/egress.rs
=> [mqtt] Bridge Simple In Flight Management

mqtt/mqtt-broker/src/ready.rs, mqtt/mqttd/src/broker/bootstrap/edgehub.rs
This will enable policy engine by default when broker is enabled.
=> Enable policy engine by default.

mqtt/mqtt-bridge/src/settings.rs, mqtt/mqtt-bridge/tests/config.json
=> remove enableupstreambridge flag

edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/authenticators/DeviceScopeTokenAuthenticator.cs, edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/DeviceScopeAuthenticator.cs
- Make iothub hostname check case-insensitive
- Trigger on-demand refresh for updated identities
=> Token auth fixes

edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/authenticators/DeviceScopeTokenAuthenticator.cs, edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/DeviceScopeAuthenticator.cs
- Trigger on-demand refresh for updated identities
- Make iothub hostname check case-insensitive
=> Fixes for token based auth

mqtt/mqtt-bridge/src/config_update.rs, mqtt/mqtt-bridge/src/controller.rs, mqtt/mqtt-bridge/src/pump/mod.rs
Address some review comments from a merged PR
=> bridge address review comments

mqtt/edgelet-client/src/lib.rs, mqtt/mqtt-bridge/src/bridge.rs, mqtt/mqtt-bridge/src/client.rs, mqtt/mqtt-bridge/src/controller.rs, mqtt/mqtt-bridge/src/pump/egress.rs, mqtt/mqtt-bridge/src/upstream/connectivity.rs, mqtt/mqtt-bridge/src/upstream/events/local.rs, mqtt/mqtt-broker/src/connection/mod.rs, mqtt/mqtt-broker/src/server.rs, mqtt/mqtt-broker/src/snapshot.rs, mqtt/mqtt-broker/src/transport.rs, mqtt/mqtt3/src/client/subscriptions.rs, mqtt/mqttd/src/broker/bootstrap/edgehub.rs, mqtt/mqttd/src/broker/bootstrap/mod.rs, mqtt/mqttd/src/broker/mod.rs, mqtt/mqttd/src/broker/snapshot.rs, mqtt/mqttd/src/tracing/format.rs
Unify log formatting across all rust code:
- all lower case
- EdgeHub log entry format
- `error` as additional variable
Fix some log mistypings
=> [mqtt] Unify log formatting across all rust code

builds/e2e/templates/e2e-run.yaml, builds/e2e/templates/e2e-setup.yaml, test/Microsoft.Azure.Devices.Edge.Test/EdgeAgentDirectMethods.cs, test/Microsoft.Azure.Devices.Edge.Test/helpers/Context.cs, test/README.md
This adds a new test for uploading sb and fixes the upload module logs. It also moves the sas key to the kv
=> Test e2e fix

mqtt/mqtt-edgehub/src/auth/authorization/edgehub.rs
In this PR I corrected edgehub topic format to match what edgeHub actually expects for iothub primitives.
=> Corrected edgehub topic structure for authz

mqtt/mqtt-edgehub/src/auth/authorization/edgehub.rs
In this PR I corrected edgehub topic format to match what edgeHub actually expects for iothub primitives.
=> Corrected edgehub topic structure for authz (#3836)

mqtt/mqtt-policy/src/substituter.rs, mqtt/mqtt-policy/src/validator.rs
This PR fixes the issue where multiple vars in a string in policy definition didn't work.
=> Fixed multiple vars issue in policy definition (#3838)

mqtt/mqtt-bridge/src/bridge.rs, mqtt/mqtt-bridge/src/config_update.rs, mqtt/mqtt-bridge/src/controller.rs, mqtt/mqtt-bridge/src/controller/bridges.rs, mqtt/mqtt-bridge/src/controller/mod.rs, mqtt/mqtt-edgehub/src/command/bridge_update.rs, mqtt/mqttd/src/broker/bootstrap/edgehub.rs, mqtt/mqttd/src/broker/bootstrap/mod.rs
restart the upstream bridge when it is stopped unexpectedly.
=> [mqtt] Restart upstream bridge when stopped

mqtt/Cargo.lock, mqtt/mqtt-broker/Cargo.toml, mqtt/mqtt-broker/src/proptest.rs, mqtt/mqtt-policy/Cargo.toml, mqtt/mqtt-policy/src/substituter.rs
- Added proptests for `VariableIter`
- Fixed a bug found by proptests
=> Added proptests for VariableIter (#3849)

mqtt/mqtt-bridge/src/config_update.rs, mqtt/mqtt-bridge/src/controller.rs, mqtt/mqtt-bridge/src/pump/mod.rs
Address some review comments from a merged PR
=> bridge address review comments (#3798)

mqtt/mqtt-bridge/src/bridge.rs, mqtt/mqtt-bridge/src/client.rs, mqtt/mqtt-bridge/src/pump/builder.rs, mqtt/mqtt-bridge/src/settings.rs
Adding validation for input length in the mqtt client to avoid mqtt3 client user error
=> add client input validation (#3825)

builds/e2e/templates/e2e-run.yaml, builds/e2e/templates/e2e-setup.yaml, test/Microsoft.Azure.Devices.Edge.Test/EdgeAgentDirectMethods.cs, test/Microsoft.Azure.Devices.Edge.Test/helpers/Context.cs, test/README.md
This adds a new test for uploading sb and fixes the upload module logs. It also moves the sas key to the kv
=> Test e2e fix (#3785)

mqtt/mqtt-bridge/src/messages.rs, mqtt/mqtt-bridge/src/pump/messages.rs
- remove from topic_mappers when a unsub is received 
- insert top topic mappers updates before sending subscription
=> Fix subscription issues

mqtt/mqtt-bridge/src/upstream/rpc/local.rs
React on rpc topic subscription update with `LocalRpcMqttEventHandler`
=> [mqtt] Make rpc local handler to process rpc topic subscription update

mqtt/mqtt-bridge/src/messages.rs, mqtt/mqtt-bridge/src/pump/messages.rs
cherry-pick from release branch
=> Fix subscription issues (#3865)

mqtt/mqtt-bridge/src/upstream/rpc/local.rs
React on rpc topic subscription update with `LocalRpcMqttEventHandler`
cherry-pick of `993a4dc`
=> [mqtt] Make rpc local handler to process rpc topic subscription update (#3870)

edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/appsettings_hub.json, edge-hub/watchdog/src/main.rs
Cherry-pick from https://github.com/Azure/iotedge/commit/82431b72124e6451716fc3eb53fa8651ec76043a
=> Fix MQTT broker feature flags for ARM (#3873)

edge-modules/api-proxy-module/docker/linux/amd64/Dockerfile, edge-modules/api-proxy-module/readme.md, edge-modules/api-proxy-module/rust-sdk/azure-iot-mqtt/src/device.rs, edge-modules/api-proxy-module/rust-sdk/azure-iot-mqtt/src/module.rs, edge-modules/api-proxy-module/src/main.rs, edge-modules/api-proxy-module/src/monitors/certs_monitor.rs, edge-modules/api-proxy-module/src/monitors/config_monitor.rs, edge-modules/api-proxy-module/templates/nginx_default_config.conf, edgelet/iotedge/src/check/checks/connect_management_uri.rs, edgelet/iotedge/src/check/checks/container_connect_upstream.rs, edgelet/iotedge/src/check/checks/container_local_time.rs, edgelet/iotedge/src/check/checks/container_resolve_parent_hostname.rs, edgelet/iotedge/src/check/checks/host_connect_upstream.rs, edgelet/iotedge/src/check/checks/pull_agent_from_upstream.rs
cherry pick: 
https://github.com/Azure/iotedge/commit/3a8e2afdc11df5f989a04556a4faf7c3f077fd9d
https://github.com/Azure/iotedge/commit/830a5893fd145380a258fdf919550de90e798984
https://github.com/Azure/iotedge/commit/f7eaf02a3054a1dc63fcabfc79760b1508632b02
https://github.com/Azure/iotedge/commit/d55d30e753b9a44008c0b5c41d3e578d3ef98775
=> Cherry pick from master to release 1.2

mqtt/mqtt3/src/client/subscriptions.rs, mqtt/mqtt3/tests/subscriptions.rs
chherry-pick for Send subscriptions updates
=> Send subscriptions updates (#3869)

edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/upstream/BrokeredCloudProxyDispatcher.cs
modules were not handled for direct method calls
=> fixed direct method calls for modules

edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/upstream/BrokeredCloudProxyDispatcher.cs
(cherry picked from commit 315e7db22918f0b844a65b241346b3d2a18433d3)
(cherry picked from commit ad11d9b0865465806bf08bb14c78190b4853bdb0)
=> Fixed direct methods for modules

builds/e2e/templates/e2e-setup.yaml, test/Microsoft.Azure.Devices.Edge.Test/helpers/BaseFixture.cs, test/Microsoft.Azure.Devices.Edge.Test/helpers/CustomCertificatesFixture.cs, test/Microsoft.Azure.Devices.Edge.Test/helpers/SasManualProvisioningFixture.cs
Cherry picked from 22b224d0cd841de3707151da13fe7bf7f9a0d07b on master.
=> Fix first test intermittent failure on Pi

mqtt/mqtt-edgehub/src/auth/authorization/edgehub.rs
Added more test cases for `EdgeHubAuthorizer`
=> Added more EdgeHubAuthorizer tests.

edge-modules/api-proxy-module/docker/linux/amd64/Dockerfile
https://github.com/Azure/iotedge/commit/5b330276b73c7b46ce2069aa785b65d0b2683836
=> Cherry pick 3889

edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/DeviceScopeAuthenticator.cs, edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/ServiceIdentityTree.cs
Cherry-picked from https://github.com/Azure/iotedge/commit/a7166122fe8a88c452c43f63b41e41ef1e8d22d3
=> Minor logging improvements for auth and identities cache (#3913)

edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Http/controllers/RegistryController.cs, edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/appsettings_hub.json, edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.Http.Test/RegistryControllerTest.cs
change edgehub status to align with iot
=> change edgehub status to align with iot

edge-modules/iotedge-diagnostics-dotnet/src/Program.cs
* fix for iotedge check
* removing test function
* removing unused lib
* fixed comments
=> fix for iotedge check (#3924)

edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Http/controllers/RegistryController.cs
Cherry-picked from https://github.com/Azure/iotedge/commit/9b242b5d2ede084bea51c092f429ab6ce326b83a
=> Remove module SAS keys from RegistryController logs

edge-modules/iotedge-diagnostics-dotnet/src/Program.cs
tested on golden path.
All tests pass.
=> Fixing bug in iotedge check

builds/e2e/templates/e2e-run.yaml, builds/e2e/templates/e2e-setup.yaml, test/Microsoft.Azure.Devices.Edge.Test/EdgeAgentDirectMethods.cs, test/Microsoft.Azure.Devices.Edge.Test/helpers/Context.cs, test/README.md
Cherry-picked from https://github.com/Azure/iotedge/commit/2eae4cbdb2ed716e1d26f8e80ddbea06d8a25e6f
Fixing the following E2E tests:
- TestUploadModuleLogs
- TestUploadSupportBundle
=> Fix TestUpload* E2E tests

builds/checkin/api-proxy.yaml, builds/checkin/dotnet.yaml, builds/checkin/edgelet.yaml, builds/checkin/libiothsm.yaml, builds/checkin/mqtt.yaml, builds/checkin/watchdog.yaml
This reverts commit a72ef7f28a781129d8f3a788722dff95ccbb67ab.
=> Revert "Remove "precondition" task in checkin pipelines in favor of native filter (#3946)"

mqtt/mqtt-edgehub/src/auth/authorization/edgehub.rs
Added more test cases for `EdgeHubAuthorizer`
=> Added more EdgeHubAuthorizer tests. (#3902)

mqtt/mqtt-edgehub/src/auth/authorization/policy.rs, mqtt/mqtt-edgehub/src/command/mod.rs, mqtt/mqtt-edgehub/src/command/policy_update.rs, mqtt/mqtt-edgehub/tests/edgehub_authorizer.rs, mqtt/mqtt-edgehub/tests/policy_authorizer.rs
- Added policy authorizer integration tests.
- Minor refactoring to edge hub authorizer tests.
=> Added policy authorizer integration tests

mqtt/mqtt-broker/src/broker.rs, mqtt/mqtt-broker/src/connection/mod.rs, mqtt/mqtt-broker/src/server.rs, mqtt/mqtt-broker/src/session/connected.rs, mqtt/mqtt-broker/src/session/disconnecting.rs, mqtt/mqtt-broker/src/session/mod.rs, mqtt/mqttd/src/app/edgehub.rs, mqtt/mqttd/src/app/snapshot.rs
No functional changes. In preparation to some other work, I'd like to push out some minor refactoring to reduce mutability in the code.
=> Reduce mutability in the broker

edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/storage/MessageStore.cs, edge-hub/src/Microsoft.Azure.Devices.Routing.Core/MessageQueueIdHelper.cs, edge-hub/src/Microsoft.Azure.Devices.Routing.Core/checkpointers/Checkpointer.cs, edge-hub/src/Microsoft.Azure.Devices.Routing.Core/endpoints/StoringAsyncEndpointExecutor.cs, edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/DeviceMessageHandlerTest.cs, edge-hub/test/Microsoft.Azure.Devices.Routing.Core.Test/MessageQueueIdHelperTest.cs, edge-util/src/Microsoft.Azure.Devices.Edge.Storage/ISequentialStore.cs, edge-util/src/Microsoft.Azure.Devices.Edge.Storage/SequentialStore.cs
cherry pick from commit 43b735c5be0a7ddda32e7fc2f05f1180c0f773c6
=> [Fix 8419918]: fixed message counts metrics to release 1.0.10

edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/ServiceIdentityTree.cs
The stack overflow comes from us trying to clean up the children authchains when we detect that the hierarchy has exceeded maximum depth.  But the cleanup logic is also recursive, so this change limits our recursion maxDepth * 2, which would cover all valid scenarios.
=> Prevent stackflow when syncing circularly nested hierarchies

edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/storage/MessageStore.cs
cherry-pick https://github.com/Azure/iotedge/pull/4020
=> Cherry-pick Fix cleanup processor

edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/storage/MessageStore.cs, edge-hub/core/src/Microsoft.Azure.Devices.Routing.Core/MessageQueueIdHelper.cs, edge-hub/core/src/Microsoft.Azure.Devices.Routing.Core/checkpointers/Checkpointer.cs, edge-hub/core/src/Microsoft.Azure.Devices.Routing.Core/endpoints/StoringAsyncEndpointExecutor.cs, edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/DeviceMessageHandlerTest.cs, edge-hub/core/test/Microsoft.Azure.Devices.Routing.Core.Test/MessageQueueIdHelperTest.cs, edge-util/src/Microsoft.Azure.Devices.Edge.Storage/ISequentialStore.cs, edge-util/src/Microsoft.Azure.Devices.Edge.Storage/SequentialStore.cs
=> [Fix 8419918]: fixed message counts metrics to release 1.2

e2e_deployment_files/long_haul_deployment.template.json, e2e_deployment_files/nested_long_haul_deployment.template.json, e2e_deployment_files/stress_deployment.template.json, edgelet/Makefile, edgelet/contrib/centos/aziot-edge.spec, edgelet/contrib/config/linux/config.yaml, edgelet/contrib/config/linux/debian/config.yaml, edgelet/contrib/debian/postinst, edgelet/contrib/systemd/debian/aziot-edged.mgmt.socket, edgelet/contrib/systemd/debian/aziot-edged.workload.socket, edgelet/doc/testiotedgedapi.md, edgelet/edgelet-docker/config/unix/default.yaml, edgelet/edgelet-docker/src/runtime.rs, edgelet/edgelet-docker/tests/runtime.rs, edgelet/iotedge/src/main.rs, mqtt/edgelet-client/src/lib.rs, scripts/linux/runE2ETest.sh, test/connectivity/scripts/testHelper.sh, tools/snitch/snitcher/src/settings.yaml
Change /var/run/aziot/edged so that it's owned by iotedge and not root.
=> Fix default settings for edge sockets

mqtt/mqtt-bridge/src/messages.rs, mqtt/mqtt-bridge/src/settings.rs
=> outPrefix and inPrefix None when empty string (#3991)

mqtt/mqtt-bridge/src/bridge.rs
=> send initial disconnect state (#4030)

mqtt/mqtt-bridge/src/config_update.rs, mqtt/mqtt-bridge/src/controller/bridges.rs, mqtt/mqtt-bridge/src/controller/mod.rs
=> [mqtt] remove all sub when upstream bridge is missing from config update (#4010)

edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/EmptyProtocolHead.cs, edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs
cherry pick  (#4140)
* fixed protocol head start up order based if MQTT broker is enabled
* fixed style check and incorrect order
=> [8999293] modified protocol head start up order based on if MQTT broker is enabled 

CHANGELOG.md
We need to duplicate some items as they affect edge agent also.
=> Fix changelog for 1.2-rc3 release

mqtt/mqtt-bridge/src/lib.rs, mqtt/mqtt-bridge/src/persist/loader.rs, mqtt/mqtt-bridge/src/persist/waking_state/mod.rs, mqtt/mqtt-broker/src/persist.rs, mqtt/mqtt3/src/proto/packet.rs
=> Rust clippy fix

edge-modules/api-proxy-module/Cargo.toml
Fixing test case for API proxy
=> Fixing test case for API proxy

edgelet/dps/src/registration.rs, edgelet/edgelet-core/src/logs.rs, edgelet/edgelet-core/src/settings.rs, edgelet/edgelet-core/src/watchdog.rs, edgelet/edgelet-docker/src/runtime.rs, edgelet/edgelet-docker/tests/runtime.rs, edgelet/edgelet-hsm/tests/test_utils/mod.rs, edgelet/edgelet-http-mgmt/src/client/module.rs, edgelet/edgelet-http/src/pid.rs, edgelet/edgelet-http/src/util/hyperwrap.rs, edgelet/edgelet-iothub/src/lib.rs, edgelet/edgelet-kube/src/module/create.rs, edgelet/edgelet-kube/src/module/trust_bundle.rs, edgelet/edgelet-utils/src/lib.rs, edgelet/external-provisioning/src/apis/external_provisioning_api.rs, edgelet/hsm-rs/src/crypto.rs, edgelet/hsm-sys/build.rs, edgelet/iotedge-proxy/src/routine.rs, edgelet/iotedge/src/main.rs, edgelet/iotedged/src/lib.rs, edgelet/kube-client/src/client.rs, edgelet/systemd/src/linux.rs, edgelet/workload/src/apis/workload_api.rs
Fix Clippy "Errors" for release 1.1 branch Rust1.47.0 from Rust 1.44.1.
The fix is a subset combination of 
- https://github.com/Azure/iotedge/commit/d0803738c91b325ecddf981dc30d59ef7e4b35ab (https://github.com/Azure/iotedge/pull/3268/files)
- https://github.com/Azure/iotedge/commit/7831fc5ad76fa3bd33b1dc1e4630ac4db771e9ff (https://github.com/Azure/iotedge/pull/3696/files)
=> Fix Clippy for release 1.1

builds/e2e/e2e.yaml, test/Microsoft.Azure.Devices.Edge.Test.Common/linux/EdgeDaemon.cs, test/Microsoft.Azure.Devices.Edge.Test.Common/linux/PackageManagement.cs, test/Microsoft.Azure.Devices.Edge.Test/PriorityQueues.cs
Introducing E2E test on EFLOW machine
=> EFLOW on E2E test (#4165)

edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/ModuleClientProvider.cs, edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.IoTHub.Test/ModuleClientProviderTest.cs, edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudConnectionProvider.cs, edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Test/CloudConnectionProviderTest.cs
Cherry-picked from https://github.com/Azure/iotedge/commit/ca2fa428e3c61fc53ce4d9a58d4d6094e51c4e5c
=> Don't use http proxy for Amqp/Mqtt over TCP

edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/twin/ReportedPropertiesValidator.cs, edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/twin/ReportedPropertiesValidatorTest.cs
which is not allowed in reported properties by IotHub
=> Added checking for null values in arrays

edge-modules/api-proxy-module/src/main.rs
Fixing error message at startup of API proxy.
Refer to hug #9019166
=> Fixing error message at API proxy start

.config/CredScanSuppressions.json, mqtt/mqtt-bridge/tests/integration.rs
Need to add test pk to suppression list.
=> Suppress bridge test certificate warning.

scripts/linux/runE2ETest.sh, scripts/linux/trcE2ETest.sh, test/Microsoft.Azure.Devices.Edge.Test.Common/DaemonConfiguration.cs, test/Microsoft.Azure.Devices.Edge.Test.Common/linux/EdgeDaemon.cs
Makes parameters for long haul similar to connectivity.
=> Fixes for long haul pipeline

tools/TestAgents/CreateAzureVmForE2e.ps1, tools/TestAgents/e2eOneTimeDependencySetup.sh
Automate Vm Creation for Nested E2E:
- Create Azure VM with Ubuntu image
- Install E2E dependencies
- Enroll itself on test agent pool
=> Automate Vm Creation for Nested E2E 

edge-modules/api-proxy-module/docker/linux/amd64/Dockerfile, edge-modules/api-proxy-module/docker/linux/arm32v7/Dockerfile, edge-modules/api-proxy-module/docker/linux/arm64v8/Dockerfile
=> updating API proxy images

mqtt/mqtt-bridge/src/bridge.rs, mqtt/mqtt-bridge/src/client.rs, mqtt/mqtt-bridge/src/controller/mod.rs, mqtt/mqtt-bridge/src/pump/ingress.rs, mqtt/mqtt-bridge/src/pump/mod.rs, mqtt/mqtt-bridge/src/upstream/rpc/mod.rs, mqtt/mqtt-bridge/tests/integration.rs
Implements an integration test that emulates how  `EHCore` interacts with `upstream` via RPC commands.
=> [mqtt] implement rpc integration test

e2e_deployment_files/long_haul_deployment.template.json
Fixing a typo in the long haul deployment
=> Fix typo in long haul deployment

mqtt/mqtt-broker-tests-util/src/packet_stream.rs, mqtt/mqtt-broker/src/broker.rs, mqtt/mqtt-broker/tests/compliance.rs, mqtt/mqtt-edgehub/tests/command.rs, mqtt/mqtt-edgehub/tests/edgehub_authorizer.rs, mqtt/mqtt-edgehub/tests/policy_authorizer.rs
In this PR i've fixed the issue in the subj and added few more tests.
=> Make sure we send will on broker shutdown. (#4318)

test/modules/generic-mqtt-tester/src/message_initiator.rs, test/modules/generic-mqtt-tester/src/tester.rs
=> Generic mqtt test module: Fix bad test module shutdown

edgelet/Cargo.lock, edgelet/edgelet-http-workload/src/server/mod.rs, edgelet/iotedge/Cargo.toml, edgelet/iotedge/src/check/mod.rs, edgelet/iotedge/src/main.rs
I wasn't 100% sure what to set for the new KeyUsage parameter in `create_key_if_not_exists`, so let me know if that needs to be changed.
=> update aziot submodule

builds/ci/dotnet.yaml, builds/e2e/connectivity.yaml, builds/e2e/e2e.yaml, builds/e2e/nested-connectivity.yaml, builds/e2e/nested-e2e.yaml, builds/e2e/nested-longhaul.yaml, builds/misc/images.yaml, builds/misc/packages.yaml, nuget.config
Published Nested Edge SDK packages to AA stream, moving solution off the old MyGet stream.
https://dev.azure.com/iotedge/iotedge/_packaging?_a=feed&feed=azure-iotedge-packages
=> Move to Azure Artifacts nuget stream

builds/e2e/e2e.yaml
=> Demand update for E2E test agent CentOs

.gitmodules, builds/e2e/nested-e2e.yaml, edgelet/Cargo.lock, edgelet/Cargo.toml, edgelet/aziot-edged/Cargo.toml, edgelet/cert-client/Cargo.toml, edgelet/edgelet-docker/Cargo.toml, edgelet/edgelet-http-mgmt/Cargo.toml, edgelet/edgelet-http-workload/Cargo.toml, edgelet/identity-client/Cargo.toml, edgelet/iotedge/Cargo.toml, edgelet/iotedge/src/init/import/mod.rs, scripts/linux/nested-edge-deploy-agent.sh, scripts/local/test/DownloadIdentityService.ps1, smoke/IotEdgeQuickstart/details/IotedgedLinux.cs, test/Microsoft.Azure.Devices.Edge.Test.Common/DaemonConfiguration.cs, test/Microsoft.Azure.Devices.Edge.Test.Common/IOsPlatform.cs, test/Microsoft.Azure.Devices.Edge.Test.Common/linux/EdgeDaemon.cs, test/Microsoft.Azure.Devices.Edge.Test.Common/linux/OsPlatform.cs, test/Microsoft.Azure.Devices.Edge.Test/SetupFixture.cs
Updates tests to set principals for the required auth with KS and CS.
Changes git submodule of aziot to a cargo dependency.
=> Update tests for authorization required with KS and CS

edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ServiceProxy.cs
During the breadth-first expansion of the nested hierarchy, each call to get the device scope of a child Edge were previously serialized based on the queue implementation.  We can make this more optimized by concurrently firing off all currently enqueued calls, then merge the results together.  This effectively makes it so that we're fetching the hierarchy a full level at a time, instead of one device at a time.
=> Parallelize upstream REST calls during device scope cache refresh

mqtt/mqtt-bridge/src/persist/waking_state/ring_buffer/mod.rs
From comment from @dmolokanov on https://github.com/Azure/iotedge/pull/4442, created this PR to resolve dangling comments
=> Generalize find_first_block

e2e_deployment_files/long_haul_deployment.template.json, e2e_deployment_files/nestededge_bottomLayerBaseDeployment_long_haul_amqp.template.json, e2e_deployment_files/nestededge_bottomLayerBaseDeployment_long_haul_mqtt.template.json, e2e_deployment_files/nestededge_isa95_smoke_test_BaseDeployment.json, e2e_deployment_files/nestededge_middleLayerBaseDeployment_amqp.json, e2e_deployment_files/nestededge_middleLayerBaseDeployment_mqtt.json, e2e_deployment_files/nestededge_topLayerBaseDeployment_amqp.json, e2e_deployment_files/nestededge_topLayerBaseDeployment_mqtt.json, edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudConnectionProvider.cs, edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ServiceProxy.cs, edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/authenticators/DeviceScopeCertificateAuthenticator.cs, edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/authenticators/DeviceScopeTokenAuthenticator.cs, edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/Constants.cs, edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/DependencyManager.cs, edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/ExperimentalFeatures.cs, edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Test/ServiceProxyTest.cs, edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/ConnectionManagerTest.cs, edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.E2E.Test/DependencyManager.cs, test/Microsoft.Azure.Devices.Edge.Test.Common/EdgeRuntime.cs
=> Revert "Move NestedEdgeEnabled out of experimental features."

builds/e2e/longhaul.yaml
- Re-introduce the test.deploymentFileName
=> Re-introduce the test.deploymentFileName

builds/e2e/longhaul.yaml
- Re-introduce the test.deploymentFileName
=> Re-introduce the test.deploymentFileName (#4474)

builds/e2e/connectivity.yaml
- Self checkout for Connectivity test pipeline
=> Self checkout for Connectivity test pipeline

builds/e2e/connectivity.yaml
- Self checkout for Connectivity test pipeline
=> Self checkout for Connectivity test pipeline (#4478)

e2e_deployment_files/connectivity_deployment.template.json
- Remove sendReportFrequency setting from connectiviity deployment file
=> Remove sendReportFrequency setting from connectiviity deployment file

scripts/linux/nested-edge-deploy-agent.sh
Fixing bug in master branch
https://dev.azure.com/msazure/One/_build/results?buildId=39795964&view=logs&j=e8afecc0-c259-5cc1-62e0-5c5d1c2a3db4&t=f401ce77-605a-59dc-34fb-0bcc6cca03c5
=> Fixing bug in master branch

test/Microsoft.Azure.Devices.Edge.Test.Common/IotHub.cs, test/Microsoft.Azure.Devices.Edge.Test/AuthorizationPolicy.cs, test/Microsoft.Azure.Devices.Edge.Test/Device.cs, test/Microsoft.Azure.Devices.Edge.Test/DeviceWithCustomCertificates.cs, test/Microsoft.Azure.Devices.Edge.Test/EdgeAgentDirectMethods.cs, test/Microsoft.Azure.Devices.Edge.Test/Metrics.cs, test/Microsoft.Azure.Devices.Edge.Test/Module.cs, test/Microsoft.Azure.Devices.Edge.Test/PlugAndPlay.cs, test/Microsoft.Azure.Devices.Edge.Test/PriorityQueues.cs, test/Microsoft.Azure.Devices.Edge.Test/X509Device.cs, test/Microsoft.Azure.Devices.Edge.Test/helpers/ManualProvisioningFixture.cs, test/Microsoft.Azure.Devices.Edge.Test/helpers/SasManualProvisioningFixture.cs, test/Microsoft.Azure.Devices.Edge.Test/helpers/X509ManualProvisioningFixture.cs
Cherry-picked from a55edd6664e46cdecde30e5f0dec00ab37162fb3
=> Nested E2E - Disable/Reenable parent Edge (#4463)

builds/misc/images-release.yaml
Cherry-pick 1c60f376ad9b0f7155eddfb669a32e0b544e6114
=> Remove unused tasks from images release pipeline

edgelet/iotedge/src/check/checks/aziot_edged_version.rs, edgelet/iotedge/src/check/mod.rs, edgelet/iotedge/src/lib.rs, edgelet/iotedge/src/main.rs
Cherry pick into release 1.2. 
Original PR for reference: #4461
=> [release/1.2 cherry pick] [iotedge check] Skip latest version check in nested scenarios (#4461)

builds/misc/packages-release.yaml
Cherry-pick https://github.com/Azure/iotedge/commit/44916b96b1836481a9d81975e964d3db2410bba8
=> Introduce the dedicated Packages Release Pipeline

edge-modules/api-proxy-module/rust-sdk/azure-iot-mqtt/src/io.rs, edge-modules/api-proxy-module/rust-sdk/azure-iot-mqtt/src/iotedge_client.rs, edge-modules/api-proxy-module/rust-sdk/azure-iot-mqtt/src/lib.rs
Cherry pick: https://github.com/Azure/iotedge/commit/1d7e0a1bb68b783d075cada3a326c0daf420c09a
=> Cherry pick api proxy fix

mqtt/mqtt-bridge/src/persist/waking_state/ring_buffer/mod.rs
Fixes a bug in RingBuffer wrap around case
=> Fix wrap-around bug (#4518)

builds/e2e/e2e.yaml, test/Microsoft.Azure.Devices.Edge.Test/Provisioning.cs
The DPS tests were previously disabled to avoid a known DPS issue. 
Now the DSP issue is fixed. Time to bring back the tests!
=> Enable the Dps Tests

mqtt/edgelet-client/src/lib.rs, mqtt/mqtt-bridge/src/lib.rs, mqtt/mqtt-bridge/src/messages.rs, mqtt/mqtt-bridge/src/persist/waking_state/ring_buffer/flush.rs, mqtt/mqtt-bridge/src/upstream/rpc/local.rs, mqtt/mqtt-broker-tests-util/src/lib.rs, mqtt/mqtt-edgehub/src/auth/authentication/edgehub.rs, mqtt/mqtt-edgehub/src/lib.rs, mqtt/mqtt-generic/src/lib.rs, mqtt/mqtt-policy/src/lib.rs, mqtt/mqtt-util/src/lib.rs, mqtt/mqttd/src/lib.rs, mqtt/policy/src/lib.rs
=> Remove unnecessary (IMHO) clippy allowance

edgelet/Cargo.lock, test/Microsoft.Azure.Devices.Edge.Test/SetupFixture.cs
Fixing E2E test timing out: https://dev.azure.com/msazure/One/_build/results?buildId=40043423&view=results
=> Fixing E2E test timing out

CHANGELOG.md
Update the "Packaging" link in changelog
=> Update the "Packaging" link in changelog

builds/e2e/templates/e2e-setup.yaml
Fix an issue in nested pipeline were it would not pick custom image on lvl3.
Run:https://dev.azure.com/msazure/One/_build/results?buildId=40018749&view=results
=> Fixing custom image issue

builds/e2e/templates/e2e-setup.yaml, edge-modules/api-proxy-module/docker/linux/arm32v7/Dockerfile, edge-modules/api-proxy-module/docker/linux/arm64v8/Dockerfile, scripts/linux/buildAPIProxy.sh
Cherry picking:
https://github.com/Azure/iotedge/pull/4543
https://github.com/Azure/iotedge/pull/4547
https://github.com/Azure/iotedge/pull/4549
=> Cherrypick 4530 4543 4549

mqtt/edgelet-client/src/lib.rs, mqtt/mqtt-bridge/src/lib.rs, mqtt/mqtt-bridge/src/messages.rs, mqtt/mqtt-bridge/src/persist/waking_state/ring_buffer/flush.rs, mqtt/mqtt-bridge/src/upstream/rpc/local.rs, mqtt/mqtt-broker-tests-util/src/lib.rs, mqtt/mqtt-edgehub/src/auth/authentication/edgehub.rs, mqtt/mqtt-edgehub/src/lib.rs, mqtt/mqtt-generic/src/lib.rs, mqtt/mqtt-policy/src/lib.rs, mqtt/mqtt-util/src/lib.rs, mqtt/mqttd/src/lib.rs, mqtt/policy/src/lib.rs
=> Remove unnecessary (IMHO) clippy allowance (#4541)

edgelet/Cargo.lock
Cherry pick of bb6d7aeb0f068386774fc17045397e80d2280bb1
=> Bump aziot version (#4599)

CHANGELOG.md
- Update release date
- Include documentation update commit.
=> Prepare for Release 1.1.1 (pt2)

mqtt/mqtt-bridge/src/persist/waking_state/ring_buffer/mod.rs
The logic in RingBuffer for validating if an insert into buffer can take place can be simplified. We basically need to check two things:
1. That if write has wrapped around and we have a full buffer but both read and write pointers are equal. This is done with a variable that is already tracking this.
2. If read and write pointer are not equal, then we should check that we have enough free space available for the insert.
=> Simplify insert check logic in RingBuffer

Microsoft.Azure.Devices.Edge.sln, edge-modules/iotedge-diagnostics-dotnet/src/Program.cs, edge-util/src/Microsoft.Azure.Devices.Edge.Util/CertificateHelper.cs, edgelet/iotedge/src/check/checks/container_connect_upstream.rs, scripts/linux/buildBranch.sh
Cherry pick iotedge check improvements for nested edge: https://github.com/Azure/iotedge/commit/22819dd7fba0567a7273e3c3219630ccfef5ce50#diff-19e464394912465c1d2353939e9200464962e3bdf53b8bc8c0b2481b8be7bbab
=> Connect with trust bundle

edgelet/contrib/centos/aziot-edge.spec, edgelet/contrib/debian/control
This PR fix versioning constraints so versioning is more flexible for development.
=> Fix versioning scheme

edgelet/contrib/centos/aziot-edge.spec, edgelet/contrib/debian/control
Cherry-pick https://github.com/Azure/iotedge/pull/4650
=> Fix versioning scheme (#4650)

edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/edgedeployment/deployment/KubernetesDeploymentMapper.cs
Experiment to inject EdgeDeviceHostname into edge on k8s modules for nested edge capability
=> Inject EdgeDeviceHostname into edge on k8s modules for nested edge capability

builds/misc/images.yaml
Include release branches into image pipelines.
=> Include release branches into image pipelines.

edgelet/iotedge/src/main.rs, edgelet/iotedge/src/system.rs
cherry-pick to pull in the IS changes and add the iotedge system stop command
=> Iotedge system stop (#4683)

builds/e2e/templates/e2e-run.yaml, test/Microsoft.Azure.Devices.Edge.Test.Common/EdgeDevice.cs, test/Microsoft.Azure.Devices.Edge.Test/AuthorizationPolicy.cs, test/Microsoft.Azure.Devices.Edge.Test/Device.cs, test/Microsoft.Azure.Devices.Edge.Test/DeviceWithCustomCertificates.cs, test/Microsoft.Azure.Devices.Edge.Test/Provisioning.cs, test/Microsoft.Azure.Devices.Edge.Test/helpers/ManualProvisioningFixture.cs, test/Microsoft.Azure.Devices.Edge.Test/helpers/SasManualProvisioningFixture.cs, test/Microsoft.Azure.Devices.Edge.Test/helpers/X509ManualProvisioningFixture.cs
Introduce nested edge device connection to grandparent verification test
Cherry-pick: https://github.com/Azure/iotedge/commit/3b6fc094f26d8e5e5bd7c9f404692b50fba27dac
=> Introduce nested edge device connection to grandparent verification test

edge-modules/api-proxy-module/readme.md, edge-modules/api-proxy-module/src/monitors/config_parser.rs
Fixed bug #9617297
API proxy indirection was not working. Also fixed unit test that should have caught the issue.
Also added back documentation that was erased by mistake.
=> Fix api proxy indirection

edgelet/Cargo.lock, edgelet/iotedge/src/config/import/mod.rs, edgelet/iotedge/src/config/mp.rs
Cherry-pick from master of e021231b3d30080204dbf12135cd5d5faca01ec8
=> Prepend iotedge-config suggestions with sudo. (#4731)

edge-modules/api-proxy-module/readme.md, edge-modules/api-proxy-module/src/monitors/config_parser.rs
Tested Image: https://dev.azure.com/msazure/One/_build/results?buildId=40929607&view=results in nested edge with 3 devices.
It now works in nested hierarchy of 3 devices.
=> Fix api proxy indirection (#4725)

builds/e2e/templates/nested-agent-deploy.yaml, e2e_deployment_files/nestededge_middleLayerBaseDeployment_amqp.json, e2e_deployment_files/nestededge_topLayerBaseDeployment_amqp.json, e2e_deployment_files/nestededge_topLayerBaseDeployment_mqtt.json, scripts/linux/nested-edge-deploy-agent.sh, smoke/IotEdgeQuickstart/details/IotedgedLinux.cs, test/Microsoft.Azure.Devices.Edge.Test.Common/DaemonConfiguration.cs, test/Microsoft.Azure.Devices.Edge.Test/helpers/SasManualProvisioningFixture.cs, test/Microsoft.Azure.Devices.Edge.Test/helpers/X509ManualProvisioningFixture.cs
https://github.com/Azure/iotedge/commit/1152cb423c8833637390a99c5f88f70b85f03d27
=> Cherry pick #4733

builds/e2e/templates/e2e-run.yaml, e2e_deployment_files/nestededge_middleLayerBaseDeployment_amqp.json, test/Microsoft.Azure.Devices.Edge.Test/Device.cs, test/modules/Relayer/Program.cs, test/modules/Relayer/Settings.cs
=> Nested E2E - send message from L3 -> L4 (#4513)

edgelet/contrib/config/linux/template.toml
Cherry-pick from master of 28ec7b56a8298a99b7710a689290a7bfd477d793
=> Document the super-config's agent.config.createOptions value format more clearly. (#4729)

e2e_deployment_files/nestededge_middleLayerBaseDeployment_amqp.json, e2e_deployment_files/nestededge_middleLayerBaseDeployment_mqtt.json, e2e_deployment_files/nestededge_topLayerBaseDeployment_amqp.json, e2e_deployment_files/nestededge_topLayerBaseDeployment_mqtt.json
Fix amqp tests:
https://dev.azure.com/msazure/One/_build/results?buildId=40970480&view=logs&j=e8afecc0-c259-5cc1-62e0-5c5d1c2a3db4&t=a5111985-4f75-51bb-4ed8-1624e65f53ff
=> Fix pipeline deployment image

e2e_deployment_files/nestededge_middleLayerBaseDeployment_amqp.json, e2e_deployment_files/nestededge_middleLayerBaseDeployment_mqtt.json, e2e_deployment_files/nestededge_topLayerBaseDeployment_amqp.json, e2e_deployment_files/nestededge_topLayerBaseDeployment_mqtt.json
Fix amqp tests:
https://dev.azure.com/msazure/One/_build/results?buildId=40970480&view=logs&j=e8afecc0-c259-5cc1-62e0-5c5d1c2a3db4&t=a5111985-4f75-51bb-4ed8-1624e65f53ff
=> Fix pipeline deployment image (#4748)

edgelet/Cargo.lock
Updating cargo lock to pick the following PR: https://github.com/Azure/iot-identity-service/commit/e7c582a0c8b788751a6af99d76558ad7172be2f9
=> Updating cargo lock to pick latest change in iotedge check

scripts/linux/nested-edge-deploy-agent.sh
=> Set iothub hostname (#4758)

scripts/linux/nested-edge-deploy-agent.sh
Cherry pick https://github.com/Azure/iotedge/pull/4763
=> fix pipeline config (#4763)

edgelet/Cargo.lock, edgelet/iotedge/src/check/checks/up_to_date_config.rs, edgelet/iotedge/src/system.rs
=> [cherry pick] `aziotctl system` improvements + `system status` formatting changes (#4759)

edgelet/Cargo.lock
Required so that test pipelines use the correct package.
=> Update i-i-s dependency

CHANGELOG.md
- Update with yesterday commits.
=> Prepare for Release 1.2.0 (pt.2)

CHANGELOG.md, versionInfo.json
Update Security Vulnerability on the base images.
=> Prepare for Release 1.1.2

e2e_deployment_files/long_haul_deployment.template.json, e2e_deployment_files/nestededge_bottomLayerBaseDeployment_long_haul_amqp.template.json, e2e_deployment_files/nestededge_bottomLayerBaseDeployment_long_haul_mqtt.template.json
=> Longhaul: Run with debug logs for edge agent (#4821)

doc/devguide.md
=> Devguide: Fix error in docs for local edgehub build

scripts/linux/runE2ETest.sh, tools/snitch/snitcher/docker/linux/arm32v7/Dockerfile, tools/snitch/snitcher/docker/linux/arm64v8/Dockerfile, tools/snitch/snitcher/src/lib.rs
Update snitcher linux images and replace old tags with new tags in our test infra.
=> Longhaul: Update snitcher linux images

test/modules/Modules.Test/TestResultCoordinator/Reports/CountingReportGeneratorTest.cs, test/modules/Modules.Test/TestResultCoordinator/Reports/CountingReportTest.cs, test/modules/Modules.Test/TestResultCoordinator/TestReportUtilTest.cs, test/modules/TestResultCoordinator/Reports/CountingReport.cs, test/modules/TestResultCoordinator/Reports/CountingReportGenerator.cs
=> Longhaul: Track misordered actual results (#4862)

builds/misc/images-release.yaml
=> Allow release image pipeline to use a custom CR (#3507)

builds/e2e/e2e.yaml, builds/e2e/proxy/configure_runner.sh, builds/e2e/templates/e2e-run.yaml, builds/e2e/templates/e2e-setup.yaml, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2020_07_07/ModuleManagementHttpClient.cs, test/Microsoft.Azure.Devices.Edge.Test.Common/config/EdgeConfigBuilder.cs, test/Microsoft.Azure.Devices.Edge.Test.Common/config/HubModuleConfigBuilder.cs, test/Microsoft.Azure.Devices.Edge.Test.Common/config/ModuleConfigBuilder.cs, test/Microsoft.Azure.Devices.Edge.Test/AuthorizationPolicy.cs, test/Microsoft.Azure.Devices.Edge.Test/EdgeAgentDirectMethods.cs, test/Microsoft.Azure.Devices.Edge.Test/GenericMqtt.cs, test/Microsoft.Azure.Devices.Edge.Test/IoTEdgeCheck.cs, test/Microsoft.Azure.Devices.Edge.Test/MqttBridgeConfig.cs, test/Microsoft.Azure.Devices.Edge.Test/PlugAndPlay.cs, test/Microsoft.Azure.Devices.Edge.Test/PriorityQueues.cs, test/Microsoft.Azure.Devices.Edge.Test/helpers/Context.cs, test/Microsoft.Azure.Devices.Edge.Test/helpers/MqttBrokerUtil.cs, test/Microsoft.Azure.Devices.Edge.Test/helpers/TestResultCoordinatorUtil.cs, test/README.md, test/modules/generic-mqtt-tester/src/lib.rs, test/modules/generic-mqtt-tester/src/message_channel.rs, test/modules/generic-mqtt-tester/src/message_initiator.rs, test/modules/generic-mqtt-tester/src/settings.rs, test/modules/generic-mqtt-tester/src/tester.rs
Porting recent changes from master. All cherry picks.
=> E2E: Port recent changes

e2e_deployment_files/nestededge_bottomLayerBaseDeployment_long_haul_mqtt.template.json, test/modules/generic-mqtt-tester/src/message_channel.rs, test/modules/generic-mqtt-tester/src/settings.rs, test/modules/generic-mqtt-tester/src/tester.rs
=> Custom Mqtt Test Module: Add Initiate and Receive modes (#4883)

edge-modules/api-proxy-module/src/monitors/config_monitor.rs
Fixing issue:
https://github.com/Azure/iotedge/issues/4946
https://github.com/Azure/iotedge/issues/4948
Tested by going through the repro steps.
=> Change config on initial twin

edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/AmqpRuntimeProvider.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/ClientConnectionHandler.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/ClientConnectionsHandler.cs, edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Amqp.Test/ConnectionHandlerTest.cs
=> Close AMQP connection explicitly when no more links (removing links kept tcp level connection)

edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/storage/MessageStore.cs, edge-hub/core/src/Microsoft.Azure.Devices.Routing.Core/checkpointers/Checkpointer.cs, edge-util/src/Microsoft.Azure.Devices.Edge.Storage.RocksDb/ColumnFamilyDbStore.cs, edge-util/src/Microsoft.Azure.Devices.Edge.Storage/DbStoreDecorator.cs, edge-util/src/Microsoft.Azure.Devices.Edge.Storage/EncryptedStore.cs, edge-util/src/Microsoft.Azure.Devices.Edge.Storage/EntityStore.cs, edge-util/src/Microsoft.Azure.Devices.Edge.Storage/IKeyValueStore.cs, edge-util/src/Microsoft.Azure.Devices.Edge.Storage/ISequentialStore.cs, edge-util/src/Microsoft.Azure.Devices.Edge.Storage/InMemoryDbStore.cs, edge-util/src/Microsoft.Azure.Devices.Edge.Storage/KeyValueStoreMapper.cs, edge-util/src/Microsoft.Azure.Devices.Edge.Storage/NullKeyValueStore.cs, edge-util/src/Microsoft.Azure.Devices.Edge.Storage/SequentialStore.cs, edge-util/src/Microsoft.Azure.Devices.Edge.Storage/TimedEntityStore.cs
Cherry-pick of https://github.com/Azure/iotedge/pull/4952
=> Cherry-pick to Release/1.2: Fix edgehub queue len metric

edge-modules/azure-monitor/src/PrometheusMetricsParser.cs, edge-modules/azure-monitor/tests/Microsoft.Azure.Devices.Edge.Azure.Monitor.Test/PrometheusMetricParserTest.cs
Updating Azure Monitor Module Prometheus parser
Fixes #4361
=> Merge Prometheus parser fix.

tools/snitch/Cargo.lock
This updates the edgelet deps after fixing RUSTSEC issues with edgelet
=> Update edgelet deps for snitch

edge-modules/iotedge-diagnostics-dotnet/src/GetSocket.cs
Cherry-pick 5e3b60f from release/1.1
=> Cherry-pick - Fix potential instability in iotedged after UploadSupportBundle fails.

edge-modules/iotedge-diagnostics-dotnet/src/GetSocket.cs
Remove the extra socket connection that was created because of the merge process.
=> Fix merge problem.

edge-modules/azure-monitor/CHANGELOG.md
Adding a changelog here for better serviceability.
=> Metrics Collector: Add changelog for initial release

edge-modules/api-proxy-module/templates/nginx_default_config.conf
=> Fix user configuration

builds/e2e/templates/nested-longhaul-deploy.yaml, e2e_deployment_files/nestededge_bottomLayerBaseDeployment_long_haul_mqtt.template.json
=> Nested Longhaul Tests: Port #5047 and #5052

edgelet/edgelet-http-workload/src/server/manifest_trust_bundle.rs
Handling errors while processing manifest trust bundle.
=> handling Not found error for manifest trust bundle

edgelet/Cargo.lock, edgelet/Makefile, edgelet/contrib/centos/00-aziot-edged.preset, edgelet/contrib/centos/aziot-edge.spec
Enables aziot-edged during postinstall so that it starts automatically.
=> Enable aziot-edged in CentOS package

builds/e2e/templates/e2e-clear-docker-cached-images.yaml, builds/misc/addons-publish.yaml, builds/misc/addons-release.yaml, builds/misc/images-mqtt.yaml, builds/misc/images-release.yaml, builds/misc/images.yaml, builds/misc/templates/image-linux.yaml, builds/templates/install-dotnet2.yaml, scripts/linux/buildImage.sh, scripts/linux/buildManifest.sh
Replacing manual docker login with the service connection approach. There is one occurrence of manual docker login I could not replace as it happens through an ssh connection.
https://github.com/Azure/iotedge/blob/master/builds/misc/templates/mqtt-perf-setup.yaml#L44
=> Builds: Eliminate insecure docker login

builds/e2e/templates/e2e-clear-docker-cached-images.yaml, builds/misc/addons-publish.yaml, builds/misc/addons-release.yaml, builds/misc/images-mqtt.yaml, builds/misc/images-release.yaml, builds/misc/images.yaml, builds/misc/templates/image-linux.yaml, builds/templates/install-dotnet2.yaml, scripts/linux/buildImage.sh, scripts/linux/buildManifest.sh
Replacing manual docker login with the service connection approach. There is one occurrence of manual docker login I could not replace as it happens through an ssh connection.
https://github.com/Azure/iotedge/blob/master/builds/misc/templates/mqtt-perf-setup.yaml#L44
=> Builds: Eliminate insecure docker login (#5098)

edgelet/Cargo.lock, edgelet/iotedge/src/config/import/mod.rs, edgelet/iotedge/src/config/mp.rs
Brings in the latest DPS provisioning fixes from iot-identity-service.
=> Update cargo dependency

CHANGELOG.md
* Properly dispose UDS for Workload Client. ( [472cee5](https://github.com/Azure/iotedge/commit/472cee580101cfd5999492ef3760d5038679680e), [f9cdb59](https://github.com/Azure/iotedge/commit/f9cdb5902a8e13b80bbd8040323fb0729f085dc3) )
* Update Base Images for Security Vulnerability ( [d0e6113](https://github.com/Azure/iotedge/commit/d0e6113e4454ef5f23909c396f793833f14649e1) )
* Use Docker Timestamp When Log Timestamp is not Available in JSON-formatted log. ( [d336d08](https://github.com/Azure/iotedge/commit/d336d085f5503747fb5f194e3cd261c0d2b91aea) )
* Update Base Images for Security Vulnerability ( [d0e6113](https://github.com/Azure/iotedge/commit/d0e6113e4454ef5f23909c396f793833f14649e1) )
* Propagate back error code from edgeHub ( …
=> Prepare for Release 1.2.2 (pt2)

builds/e2e/templates/nested-create-identity.yaml
Update Azure CLI command in ISA95 pipeline
=> Update Azure CLI command in ISA95 pipeline

builds/e2e/connectivity.yaml, builds/e2e/nested-connectivity.yaml, builds/e2e/nested-e2e.yaml
Connectivity, nested connectivity, and nested e2e triggers are misconfigured. Fixing them here.
=> Devops: Fix triggers for connectivity and e2e

builds/e2e/nested-e2e.yaml, builds/e2e/templates/nested-agent-deploy.yaml, builds/misc/packages.yaml
Fix Nested E2E stuck on Edgelet installation
=> Fix Nested E2E stuck on Edgelet installation

builds/e2e/nested-e2e.yaml
No need for the capability anymore
=> No need for the capability anymore

builds/e2e/templates/nested-create-identity.yaml
Update Azure CLI command in Nested pipelines
Cherry-picked: https://github.com/Azure/iotedge/commit/9bb6faf4fb600842480f22c548fd454e9897a023
=> Update Azure CLI command in Nested pipelines (#5150)

edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/EdgeAgentConnection.cs, edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.IoTHub.Test/EdgeAgentConnectionTest.cs
Agent pulls twin on reconnect, so desired property changes will be learned if those happened while the device was disconnected. In certain circumstances it can happen that a device keeps connecting/disconnecting. One particular case is when two edge devices use the same identity and when one device connects, the other gets disconnected. In turn the disconnected device try to connect back and this makes the first device get disconnected. This fight over the connection can result in several twin pulls per seconds.
This solution delays subsequent twin pulls if those happen within a certain time window. The throttling applies only on connection, so if for some reason iothub sends frequent desired property changes, those are not throttled.
The solution below has a flaw: if the delay is e.g. 30 …
=> Fix: Delay frequent twin pulls on reconnect

edge-modules/api-proxy-module/readme.md
Add forgotten items to API proxy documentation
=> Fix API proxy doc

builds/e2e/connectivity.yaml
Update keyvault variable in Connectivity test
=> Update keyvault variable in Connectivity test

tools/BaseImageUpdate/baseImage.ps1
Automate OS image update for AMD64
=> Automate OS base image update for AMD64

builds/misc/images-publish.yaml
=> Adding approval gate

builds/misc/images-publish.yaml
Image Publication Pipeline Touchup
- No Trigger from PR & Builds
- Improve some of the display names
=> Image Publication Pipeline Touchup

builds/misc/images-publish.yaml
Image Publication Pipeline Touchup
- No Trigger from PR & Builds
- Improve some of the display names
=> Image Publication Pipeline Touchup (#5242)

edge-modules/api-proxy-module/Cargo.lock, edge-modules/api-proxy-module/Cargo.toml, edge-modules/api-proxy-module/rust-sdk/azure-iot-mqtt/Cargo.lock, edge-modules/api-proxy-module/rust-sdk/azure-iot-mqtt/Cargo.toml, mqtt/Cargo.lock, mqtt/mqttd/src/tracing/format.rs, test/modules/generic-mqtt-tester/Cargo.lock, test/modules/obsagent-client/Cargo.lock, test/modules/obsagent-client/Cargo.toml
Resolves a Component Governance error due to certain versions of tokio and hyper.
=> Update tokio and hyper dependencies

builds/e2e/connectivity.yaml, builds/e2e/nested-connectivity.yaml, builds/e2e/nested-e2e.yaml
Disable automatic triggers in favor of periodic triggers for:
1. Nested E2E
2. Connectivity
3. Nested Connectivity
Once this is checked in I will add the periodic triggers through the DevOps interface.
=> Medium Duration Tests: Disable automatic triggers in favor of periodic triggers (#5256)

builds/e2e/e2e.yaml
Update default E2E test artifacts for `release/1.1` branch.
=> Update default E2E test artifacts

edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.csproj, edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/DeploymentSecretBackupTest.cs, edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/EdgeDeploymentCommandTest.cs, edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/KubernetesServiceMapperTest.cs, edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/edgedeployment/EdgeDeploymentOperatorTest.cs, edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/edgedeployment/service/KubernetesServiceMapperTest.cs
Cherry-pick k8s change to 1.1.
* Update to latest k8s client to address vulnerabilities in dependencies.
=> [k8s] update k8s client. (#5210)

builds/e2e/isa-95-smoke-test.yaml
Run: https://msazure.visualstudio.com/One/_build/results?buildId=44846951&view=results
=> Fix ISA 95 tests

tools/IoTEdgeDevOps/DevOpsLib/BugManagement.cs, tools/IoTEdgeDevOps/DevOpsLib/BugWiqlQueries.cs
The path changed for our team area, which means we have to update some of our automation with the new paths. Fixing it here.
=> DevOps Sync Job: Update paths to correct service errors

builds/e2e/nested-e2e.yaml
No need for the capability anymore
=> No need for the capability anymore (#5169)

builds/e2e/nested-e2e.yaml
Adding the missing vars to get the tests to pass.
=> Nested E2E: Fix failure due to missing variables (#5289)

builds/e2e/templates/e2e-run.yaml, builds/e2e/templates/e2e-setup.yaml, test/Microsoft.Azure.Devices.Edge.Test/helpers/TestResultCoordinatorUtil.cs, test/connectivity/modules/NetworkController/Program.cs
Re-enabling priority queue tests for proxy and nested scenarios.
Cherry pick:
#5317 
#5303
=> E2E: Stabilize Priority Queue Tests

edge-modules/edgehub-proxy/Cargo.lock
=> RUSTSEC fixes

builds/e2e/connectivity.yaml, builds/e2e/templates/connectivity-deploy.yaml
Connectivity Test in 1ES hosted pool
=> Connectivity Test in 1ES hosted pool

edge-modules/api-proxy-module/docker/linux/amd64/Dockerfile
Fix file created for cache instead of a folder.
=> Fix API proxy cache

e2e_deployment_files/nestededge_middleLayerBaseDeployment_amqp.json, e2e_deployment_files/nestededge_middleLayerBaseDeployment_mqtt.json, e2e_deployment_files/nestededge_middleLayer_connectivity_mqtt.json, e2e_deployment_files/nestededge_middleLayer_e2e_amqp.json, e2e_deployment_files/nestededge_middleLayer_long_haul_mqtt.json, e2e_deployment_files/nestededge_topLayerBaseDeployment_amqp.json, e2e_deployment_files/nestededge_topLayerBaseDeployment_mqtt.json
Correct API proxy version is in master. Point branch 1.2 to correct API proxy version: 1.1.
Nested edge test: https://dev.azure.com/msazure/One/_build/results?buildId=45754511&view=logs&j=e72c11a7-9c6a-5635-f545-e6262c410c4f&t=fa2e3d39-456b-5edd-011a-3d687b66f326
=> use latest released API proxy

edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/ServiceIdentityTree.cs
Fixing #5155, it is now possible to connect device module through edgeHub as well as creating new modules.
Test:
Connected module through edgeHub using SAS token
Created new module through edgeHub.
=> Create identities for leaf

mqtt/mqtt-bridge/src/persist/waking_state/ring_buffer/mod.rs
Cherry-pick of https://github.com/Azure/iotedge/pull/5158
=> Fix find_first_block seek logic (#5158)

edge-modules/api-proxy-module/docker/linux/amd64/Dockerfile, edge-modules/api-proxy-module/docker/linux/arm32v7/Dockerfile, edge-modules/api-proxy-module/docker/linux/arm64v8/Dockerfile
updating images.
Tested nested edge with amd64 and arm32/arm64 with QEMU.
The s360 issue will be fixed:
Listing... Done
libx11-data/now 2:1.6.7-1+deb10u2 all [installed,local]
root@8ad08cbe7a1f:/app#
=> api proxy image update

builds/e2e/templates/e2e-run.yaml, edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Test/CloudProxyTest.cs, edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.E2E.Test/Cloud2DeviceTest.cs, edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.E2E.Test/EdgeToDeviceMethodTest.cs, edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.E2E.Test/InMemoryDbStoreLimitsTest.cs, edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.E2E.Test/TelemetryTest.cs, edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.E2E.Test/TwinDiffE2ETest.cs, test/Microsoft.Azure.Devices.Edge.Test/Device.cs, test/Microsoft.Azure.Devices.Edge.Test/DeviceWithCustomCertificates.cs, test/Microsoft.Azure.Devices.Edge.Test/EdgeAgentDirectMethods.cs, test/Microsoft.Azure.Devices.Edge.Test/Metrics.cs, test/Microsoft.Azure.Devices.Edge.Test/Module.cs, test/Microsoft.Azure.Devices.Edge.Test/PriorityQueues.cs, test/Microsoft.Azure.Devices.Edge.Test/Provisioning.cs, test/Microsoft.Azure.Devices.Edge.Test/X509Device.cs
Cherry pick:
#5444
#5449
#5469
=> E2E/CI: Port disables for flaky tests

builds/e2e/e2e.yaml, builds/e2e/templates/e2e-run.yaml, edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/MqttBrokerConnectorTest.cs
=> Port disabling of flaky E2E tests

edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Test/CloudProxyTest.cs
Disabling these three flaky tests.
=> CI Tests: Disable flaky tests in cloud proxy suite

e2e_deployment_files/nestededge_bottomLayerBaseDeployment_connectivity_mqtt.template.json, test/modules/Modules.Test/TestResultCoordinator/Reports/CountingReportGeneratorTest.cs, test/modules/Modules.Test/TestResultCoordinator/Reports/CountingReportTest.cs, test/modules/Modules.Test/TestResultCoordinator/Reports/DirectMethod/DirectMethodConnectivityReportDataWithSenderAndReceiverSource.cs, test/modules/Modules.Test/TestResultCoordinator/Reports/DirectMethod/DirectMethodConnectivityReportDataWithSenderSourceOnly.cs, test/modules/Modules.Test/TestResultCoordinator/Reports/DirectMethod/DirectMethodConnectivityReportGeneratorTest.cs, test/modules/Modules.Test/TestResultCoordinator/Reports/DirectMethod/DirectMethodLongHaulReportData.cs, test/modules/Modules.Test/TestResultCoordinator/Reports/DirectMethod/DirectMethodLongHaulReportGeneratorTest.cs, test/modules/Modules.Test/TestResultCoordinator/Reports/TwinCountingReportGeneratorTest.cs, test/modules/Modules.Test/TestResultCoordinator/TestReportUtilTest.cs, test/modules/TestResultCoordinator/Reports/CountingReport.cs, test/modules/TestResultCoordinator/Reports/CountingReportGenerator.cs, test/modules/TestResultCoordinator/Reports/DirectMethod/Connectivity/DirectMethodConnectivityReport.cs, test/modules/TestResultCoordinator/Reports/DirectMethod/Connectivity/DirectMethodConnectivityReportGenerator.cs, test/modules/TestResultCoordinator/Reports/DirectMethod/Connectivity/DirectMethodConnectivityReportMetadata.cs, test/modules/TestResultCoordinator/Reports/DirectMethod/LongHaul/DirectMethodLongHaulReport.cs, test/modules/TestResultCoordinator/Reports/TestReportGeneratorFactory.cs, test/modules/TestResultCoordinator/Reports/TwinCountingReport.cs, test/modules/TestResultCoordinator/Reports/TwinCountingReportGenerator.cs, test/modules/TestResultCoordinator/Reports/TwinCountingReportMetadata.cs, test/modules/TestResultCoordinator/Topology.cs
=> Connectivity / Nested Connectivity: Add tolerances for failure cases (#5512)

builds/e2e/isa-95-smoke-test.yaml
=> Cherry pick 5297

edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/ModuleManagementHttpClient.cs
This reverts commit 67386bb7156c28ee4f6310ce1bcd89ec8defbb2f.
=> Revert "Temporary solution to get around the iot-hub throttling problem (#5535)"

builds/e2e/nested-e2e.yaml
Original Bug in Identity Service Fixed in https://github.com/Azure/iot-identity-service/pull/286 .
=> Re-enable AMQP for Nested E2E Scenarios

builds/ci/dotnet.yaml, builds/ci/edgelet.yaml, builds/ci/mqtt.yaml, builds/e2e/connectivity.yaml, builds/e2e/e2e.yaml, builds/e2e/isa-95-smoke-test.yaml, builds/e2e/longhaul.yaml, builds/e2e/nested-connectivity.yaml, builds/e2e/nested-e2e.yaml, builds/e2e/nested-longhaul.yaml, builds/e2e/stresstest.yaml, builds/misc/addons-publish.yaml, builds/misc/addons-release.yaml, builds/misc/base-images-publish.yaml, builds/misc/images-mqtt.yaml, builds/misc/images-publish.yaml, builds/misc/images-release.yaml, builds/misc/images.yaml, builds/misc/mqtt-perf.yaml, builds/misc/packages-release.yaml, builds/misc/packages.yaml
After @vipeller 's PR #5530, we can remove the warning suppression.
=> Remove variable that suppressed Component Governance errors.

CHANGELOG.md
=> Prepare for Release 1.2.4 (Part 2)

test/Microsoft.Azure.Devices.Edge.Test/Metrics.cs
=> Disabling the ValidateMetrics test due to bug

edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.IoTHub.Test/EdgeAgentConnectionTest.cs
Cherry Pick Commit from Release/1.2
=> [CHERRY-PICK] Initial Attempt at Fixing Flaky FrequentTwin Pull Test (#5590)

builds/e2e/isa-95-smoke-test.yaml
Removed ISA 95 timeout on locking to be like nested E2E.
Increased timeout to unlock&clean up
=> ISA95, Remove timeout for lock, increase for unlock

builds/e2e/connectivity.yaml
Schedule Connectivity Test to be run every Sunday midnight for branch 1.1
=> Queue Up Connectivity Test for 1.1

builds/e2e/isa-95-smoke-test.yaml
=> ISA95, Remove timeout for lock, increase for unlock (#5607)

edgelet/Cargo.lock, edgelet/aziot-edged/src/provision.rs, edgelet/edgelet-docker/src/runtime.rs, edgelet/edgelet-http-mgmt/src/lib.rs, edgelet/edgelet-http-workload/src/lib.rs, edgelet/iotedge/src/system.rs
Passes the new max_retries parameter to the IS service clients. This will allow it to retry on connection closed errors.
=> Use IS client retries

edgelet/contrib/config/linux/config.yaml, edgelet/contrib/config/linux/debian/config.yaml, edgelet/contrib/config/windows/config.yaml
Fixing typo introduced in commit https://github.com/Azure/iotedge/commit/dcfcdc22ce148ebb9e627cacd2ef873ecc361e20 …
=> Fix typo in config.yaml

builds/e2e/e2e.yaml
On release 1.2 we re-enabled the proxy test suite (#5648) and everything is working fine. When this change was ported to master, the tests fail due to component governance. 
This wasn't caught in the tests because the test for my PR branch didn't use component governance. My current understanding is that it only gets auto-injected for branches in the iotedge repo (and thus not PR branches)
https://github.com/Azure/iotedge/pull/5648#issuecomment-942759541
The reason this works in release/1.2 is because we don't error on component governance. For master this was changed within the last month (#5572).
Waiting on this test run before merge:
https://dev.azure.com/msazure/One/_build/results?buildId=47839241&view=results
This checklist is used to make sure that common guidelines for a pull …
=> E2E: Don't error on component governance for proxy test suite

edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs
There is still an interdependency between the configuration fetch task and the protocol heads in the nested case. The pertinent PR is #5517.
=> Revert EdgeHub configuration waiting

test/README.md, test/doc/one-time-setup.md
=> Update E2E test docs for release/1.2

edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs
This reverts commit 421aa333c480b8db1bfc04db25b9d379bff0fa0a.
There is still an interdependency between the configuration fetch task and the protocol heads in the nested case. The pertinent PR is #5516.
=> Revert "[release/1.2] Wait for configuration before starting protocol heads (#5516)"

edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/versioning/ModuleManagementHttpClientVersioned.cs, edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Edgelet.Test/ModuleManagementHttpClientTest.cs, test/Microsoft.Azure.Devices.Edge.Test/EdgeAgentDirectMethods.cs
This is a straight cherry pick of #5793 
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes all the commits in the PR to a single commit. The net effect is that entire PR becomes a single commit. Please follow the best practices mentioned [here](https://chris.beams.io/posts/git-commit/#:~:text=The%20seven%20rules%20of%20a%20great%20Gi …
=> [Cherry-Pick] Enable Test Get Module Logs

builds/e2e/templates/e2e-run.yaml, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/versioning/ModuleManagementHttpClientVersioned.cs, edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Edgelet.Test/ModuleManagementHttpClientTest.cs, test/Microsoft.Azure.Devices.Edge.Test/EdgeAgentDirectMethods.cs
This is a cherry-pick for #5793 and #5811
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes all the commits in the PR to a single commit. The net effect is that entire PR becomes a single commit. Please follow the best practices mentioned [here](https://chris.beams.io/posts/git-commit/#:~:text=The%20seven%20rules%20of%20a%20great%20G …
=> [Cherry-Pick]Enable Test Get Module Logs

doc/devguide.md
Add Documentation for Running Code Coverage Checks Locally for Edge Runtime Components …
=> Documentation for Code Coverage Local Run

doc/NotaryContentTrust.md
AcrImageSigner role is missing in the document. Updated that and also the Notary's latest version to 0.6.1
=> [doc] Update notary SPN roles for the publisher

builds/misc/images-release.yaml, builds/misc/templates/build-images.yaml, builds/misc/templates/image-linux.yaml
Port changes previously made in #5547 from images.yaml to images-release.yaml. This is a quick port of the changes in order to support the 1.2.5 release.  A follow-on effort should be made to reduce duplication between build-images.yaml and images-release.yaml.
A pipeline was run in ADO to test these changes and the pipeline succeeded. As another test, the images produced by the test run of the pipeline (i.e. edge-agent, edge-hub, edge-simulated-temperature-sensor, and edge-diagnostics) were deployed manually to a VM edge device and all modules/containers launched and ran without any errors. I also ran an E2E pipeline using the edge-agent and edge-hub images built from this modified images-release pipeline and all tests passed.
This checklist is used to make sure that common guidelines …
=> Cherry-pick: Port parallelization changes from images pipeline to  images-release

test/Microsoft.Azure.Devices.Edge.Test/Metrics.cs
Re-enabling validate metrics as it is no longer flaky due to https://github.com/Azure/iotedge/pull/5799.
Waiting on this build before merge:
https://dev.azure.com/msazure/One/_build/results?buildId=49073879&view=results
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit …
=> E2E: Re-enable validate metrics

builds/e2e/isa-95-smoke-test.yaml, builds/e2e/templates/lock-test-agents.yaml, builds/e2e/templates/nested-get-secrets.yaml, builds/e2e/templates/unlock-test-agents.yaml, scripts/linux/nestedAgentLock.sh
This PR changes the PAT secret to be the one used elsewhere in the repository. It also adds an initial check that the script can retrieve agent data from the devops api, so the root cause will be more obvious if it happens again. 
I tested the fail path locally and the success path in the pipeline:
https://dev.azure.com/msazure/One/_build/results?buildId=48992747&view=logs&j=23024f98-a3b7-5786-11c6-69db2f5ae7ab&t=37796a81-43e1-5fe6-128f-b89b6495147b
_Note: We use the kodiakhq bot to merge PRs once the …
=> Nested Tests: Agent lock resiliency

builds/e2e/e2e.yaml, builds/e2e/templates/e2e-run.yaml, builds/e2e/templates/e2e-setup.yaml
Waiting for E2E Test Run : https://dev.azure.com/msazure/One/_build/results?buildId=49431372&view=logs&j=8520a43c-dcec-5ce4-f544-4575e5778c8d&t=2b9ef0bf-6d8c-5f29-043a-94bc7a30cb60
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes all the commits in the PR to a single commit. The net effect is that entire PR becomes a single commit. …
=> Add Ubuntu 20.04 E2E Test for ARM64

builds/e2e/e2e.yaml
E2E CI Build Run : https://dev.azure.com/msazure/One/_build/results?buildId=49470341&view=results
=> Run E2E Test on Ubuntu 20.04 Arm64 (#5875)

builds/e2e/templates/e2e-run.yaml, edgelet/Cargo.lock
A Change was made in IIS Repo to Add a Timeout to IoT Edge Host Connect Calls https://github.com/Azure/iot-identity-service/commit/d68e65dcee173ff4104a21eaca95a2296eb361f3.
This PR Ingests that change and Re-enables Support Bundle Test for Proxy Environment
Waiting for this E2E Run to complete : https://dev.azure.com/msazure/One/_build/results?buildId=49559250&view=results
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq …
=> Increment IIS Commit and Re-enable Support Bundle Test

test/Microsoft.Azure.Devices.Edge.Test/IoTEdgeCheck.cs
I have run ~7 instances each on ARM32 and ARM64 for IoT Edge Check Test and have not seen a failure. Re-enabling the test. …
=> Enable IoT Edge Check E2E Test (#5889)

builds/misc/addons-release.yaml
Port the parallelization changes from the image builder pipeline to the addons-release pipeline. This fixes the addons-release pipeline, which is currently broken because it depends on build-api-proxy.yaml, which was changed from a template containing   'tasks' to one containing 'jobs' as part of the parallelization changes to the image builder pipeline.
The changes have been tested with a successful test run of the addons-release pipeline. I then tested the resulting build of the API Proxy image by using it in a nested edge deployment and verifying that it worked; the lower layer device was able to pull the diagnostics image via the API proxy running on the top layer device.
- Description of the …
=> Port parallelization changes from images pipeline to addons-release

builds/misc/images-release.yaml
Waiting for this Pipeline Run to finish: https://dev.azure.com/msazure/One/_build/results?buildId=49747094&view=results …
=> [1.1] Update Images Release Pipeline to 1ES Agents

test/Microsoft.Azure.Devices.Edge.Test/Metrics.cs
This test is flaky on arm due to an SDK issue. We will followup on this root-cause bug, but to keep the test pipelines green we need to disable this test on arm.
For testing, the e2e checkin should be sufficient to validate this change.
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it …
=> E2E: ValidateMetrics test flaky on arm (#5912)

builds/misc/addons-publish.yaml
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes all the commits in the PR to a single commit. The net effect is that entire PR becomes a single commit. Please follow the best practices mentioned [here](https://chris.beams.io/posts/git-commit/#:~:text=The%20seven%20rules%20of%20a%20great%20Git%20commit,what%20and%20why%20vs.%20how%2 …
=> Use 1ES Agent for API Proxy Publish (#5914)

builds/misc/images-release.yaml, builds/misc/metrics-collector-images-release.yaml
Adds a SBOM generation task to each ADO pipeline that builds release bits. This includes libraries and executables contained in release builds of IoT Edge modules as well as IoT Edge Linux packages (i.e. the edgelet packages). The pipelines changed are:
1. images-release
2. metrics-collector-release
These changes were tested by running each of the above pipelines to confirm the SBOM task ran and generated the expected SBOM files. The Edgelet 1.1 release pipeline was also tested, but its changes were made through ADO and do not have a corresponding YAML file.
- …
=> Generate Software Bill of Materials (SBOM) in 1.1 release pipelines

edgelet/Cargo.lock
Updates the cargo dependency in edgelet to the latest version of i-i-s.
=> Update edgelet cargo dependency

test/Microsoft.Azure.Devices.Edge.Test/Metrics.cs, test/modules/MetricsValidator/src/Program.cs
Cherry Pick #5853
Test run with changes:
https://dev.azure.com/msazure/One/_build/results?buildId=50142524&view=results
https://msazure.visualstudio.com/One/_build/results?buildId=50142541&view=results
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the …
=> Nested E2E: Mitigate validate metrics getting dup dm calls (#5853)

builds/misc/packages-release.yaml, scripts/linux/publishReleasePackages.sh
This PR Manually Ports over changes from 
1. #5983 
2. #5963 
Waiting for this Test Run to pass
1. https://dev.azure.com/msazure/One/_build/results?buildId=50830892&view=results
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes all the commits in the PR to a single commit. The net effect is that entire PR becomes a single commit. …
=> Automate Release Package Publication

builds/checkin/edgelet.yaml
Same Changes as #6015 
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes all the commits in the PR to a single commit. The net effect is that entire PR becomes a single commit. Please follow the best practices mentioned [here](https://chris.beams.io/posts/git-commit/#:~:text=The%20seven%20rules%20of%20a%20great%20Git%20commit,what%20 …
=> [1.1]Fix Tarpaulin Version to 0.18.*

test/Microsoft.Azure.Devices.Edge.Test/IoTEdgeCheck.cs
Cherry Pick #5994 
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes all the commits in the PR to a single commit. The net effect is that entire PR becomes a single commit. Please follow the best practices mentioned [here](https://chris.beams.io/posts/git-commit/#:~:text=The%20seven%20rules%20of%20a%20great%20Git%20commit,what%20and% …
=> [Master]Disable Local Time Check IoT Edge Check E2E Test Run on ARM

builds/misc/images-publish.yaml, builds/misc/images-release.yaml, builds/misc/metrics-collector-images-publish.yaml, builds/misc/metrics-collector-images-release.yaml, builds/misc/packages-release.yaml, builds/misc/templates/build-images.yaml, builds/misc/templates/build-packages.yaml, builds/misc/templates/image-linux-rust-jobs.yaml
Per https://github.com/Azure/iotedge/pull/5987, the build pipelines should be updated to be using Ubuntu20.04 to keep OS dependency consistence.
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes all the commits in the PR to a single commit. The net effect is that entire PR becomes a single commit. Please follow the best practices …
=> Update build pipelines to be Ubuntu20.04

scripts/linux/publishReleasePackages.sh
Cherry Pick (#6022)
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes all the commits in the PR to a single commit. The net effect is that entire PR becomes a single commit. Please follow the best practices mentioned [here](https://chris.beams.io/posts/git-commit/#:~:text=The%20seven%20rules%20of%20a%20great%20Git%20commit,what%20and …
=> [1.1]Bugfix: Remove Double Quotes from Current Release Tag 

builds/misc/addons-publish.yaml, builds/misc/addons-release.yaml, builds/misc/images-publish.yaml, builds/misc/images-release.yaml, builds/misc/packages-release.yaml, builds/misc/templates/build-images.yaml, builds/misc/templates/build-packages.yaml
Per https://github.com/Azure/iotedge/commit/2ad61fa31f0baba86d9446cd3550cdd89abfa1da, the build pipelines should be updated to be using Ubuntu20.04 to keep OS dependency consistence.
This PR is equivalent: https://github.com/Azure/iotedge/pull/5964
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes all the commits in the PR to a …
=> Update build pipelines to be using Ubuntu20.04

builds/misc/templates/rust-test-module-images.yaml, test/modules/generic-mqtt-tester/docker/linux/arm32v7/Dockerfile, test/modules/generic-mqtt-tester/docker/linux/arm32v7/base/Dockerfile, test/modules/generic-mqtt-tester/docker/linux/arm64v8/Dockerfile, test/modules/generic-mqtt-tester/docker/linux/arm64v8/base/Dockerfile
This module was missed in the process of removing base images and using buildx to build ARM images. …
=> Use buildx for rust-test-module

builds/misc/templates/rust-test-module-images.yaml, test/modules/generic-mqtt-tester/docker/linux/arm32v7/Dockerfile, test/modules/generic-mqtt-tester/docker/linux/arm32v7/base/Dockerfile, test/modules/generic-mqtt-tester/docker/linux/arm64v8/Dockerfile, test/modules/generic-mqtt-tester/docker/linux/arm64v8/base/Dockerfile, test/modules/obsagent-client/docker/linux/arm32v7/Dockerfile, test/modules/obsagent-client/docker/linux/arm64v8/Dockerfile
Use buildImage.sh with buildx script for generic-mqtt-tester module.
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes all the commits in the PR to a single commit. The net effect is that entire PR becomes a single commit. Please follow the best …
=> Use buildx for rust-test-module (#6051)

platform-validation/scripts/compatibility.sh
Initial Check-in Code for
1. Template for Compatibility Tool Script
2. Helper functions for Text Formatting and Architecture Discovery
3. Capability Checks for Host and Container Level
Todos
1. Fill in the remaining checks
2. Integrate with E2E Test Pipeline
3. Test on OpenWRT, UbuntuCore - other incompatible platforms
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to …
=> Add Template Code for IoT Edge Compatibility Tool

builds/e2e/e2e-release.yaml, test/Microsoft.Azure.Devices.Edge.Test.Common/linux/PackageManagement.cs
Some cleanup from previous PR: https://github.com/Azure/iotedge/pull/6054
=> Clean up comments

edge-hub/watchdog/Cargo.lock, mqtt/Cargo.lock, test/modules/generic-mqtt-tester/Cargo.lock, test/modules/obsagent-client/Cargo.lock, tools/check_submodules/Cargo.lock, tools/check_submodules/Cargo.toml, tools/check_submodules/src/logging.rs
=> [master] Remove thread_local for non-edgelet projects

builds/e2e/templates/e2e-run-base-image-update.yaml, builds/e2e/templates/e2e-run.yaml
It can sometimes be that builds succeed but the resulting artifacts lead
to test timeouts, for example if edgeHub crashes upon execution.
Unconditionally publishing logs would make it easier to debug these
cases.
=> [release/1.2] Unconditionally publish logs

edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/AmqpProtocolHead.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/MqttProtocolHead.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/CertificateRenewal.cs, edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs, test/Microsoft.Azure.Devices.Edge.Test/Module.cs
=> Fix edgeHub shutdown for renew certificate (#6037)

edgelet/Cargo.lock, edgelet/aziot-edged/Cargo.toml, edgelet/docker-rs/Cargo.toml, edgelet/edgelet-docker/Cargo.toml, edgelet/edgelet-http-mgmt/Cargo.toml, edgelet/edgelet-http-workload/Cargo.toml, edgelet/edgelet-http/Cargo.toml, edgelet/edgelet-settings/Cargo.toml, edgelet/edgelet-test-utils/Cargo.toml, edgelet/iotedge/Cargo.toml
Updates configs with name of new branch.
=> Update branch names in config.toml

edge-util/src/Microsoft.Azure.Devices.Edge.Util/CertificateHelper.cs
This is a workaround for https://github.com/Azure/iotedge/issues/5087
When EdgeHub starts up and imports the certificates with their private keys, sometimes the private key does not get associated with the certificate. As a result, using the certificate object and accessing the private key throws an exception.
Because this certificate is handed over to Kestrel to provide a TLS connection, Kestrel tries to access the private key and throws an exception every time a client tries to connect. As a result, no client can connect to EdgeHub and it never recovers from this error.
We could not find the root cause that why the import fails sometimes and other times not, also it is not clear why only on windows. However, what we found is that retrying the import (with the same certificate and key …
=> retry importing certificate when windows fails to use assigned private key

edge-modules/TransactableModuleSample/README.md
Minor update to simplify the onboarding process for the private preview
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes all the commits in the PR to a single commit. The net effect is that entire PR becomes a single commit. Please follow the best practices mentioned [here](https://chris.beams.io/posts/git-commit/#:~:text=The%20seve …
=> Update prereq for transactable module readme

edgelet/Cargo.lock, mqtt/Cargo.lock, test/modules/obsagent-client/Cargo.lock
Resolves vulnerability in crossbeam-util. See crossbeam-rs/crossbeam#781 for details.
=> Update tokio, rayon, and crossbeam to latest compatible versions

builds/misc/templates/build-packages.yaml
The IIS RPM package is needed when constructed the iotedge mariner rpm file.
passing build here https://msazure.visualstudio.com/One/_build/results?buildId=52235287
=> Updated IIS Hash Used For Mariner RPM Build

edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/CbsNode.cs
This reverts commit 6055c6eeba47dcd564ab638444eb14ba90d225e8 until release
=> Revert "AMQP CBS token message dispose (#6057) (#6107)"

edge-modules/edgehub-proxy/Cargo.lock, edgelet/Cargo.lock, edgelet/edgelet-docker/Cargo.toml, edgelet/edgelet-docker/src/notary.rs, mqtt/Cargo.lock, tools/snitch/Cargo.lock
This reverts commit 6a807eb895b2bab29687e5fc2ce3e897c3fd4996.
> We don't have enough time to rerun long haul test to verify this code change. We decided to back off this commit so the release 1.2.8 may be released on a targeted date.
=> [release/1.2] Revert crossbeam-utils upgrade

platform-validation/scripts/compatibility.sh
This PR Adds a check 
1. To make sure the target device architecture is compatible with IoT Edge. 
2. To make sure that the target device supports a minimum version of docker API if docker engine is present on the device
3. I also ran a linter on the script for some minor formatting
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes …
=> Add Check for Architecture and Minimum Docker API Version

builds/checkin/compatibility-tool-checkin.yaml, platform-validation/scripts/compatibility.sh
shellcheck tool : https://github.com/koalaman/shellcheck for linting platform compatibility script tool.
=> [Tools] Shellcheck addition for platform compatibility script tool. 

platform-validation/scripts/compatibility.sh
[](https://user-images.githubusercontent.com/33068020/153299807-5dcb3058-ff2e-403d-9308-202e497701fb.png)[](https://user-images.githubusercontent.com/33068020/153298960-bc88d1ba-3d5a-4122-9afa-2a7150f4644d.png)he shared libraries that are part of OS distribution is checked by this tool.
The list of shared libraries that are needed for aziot-edge and aziot-identity-service are as follows
libcrypto.so.1.1
libssl.so.1.1
libdl.so.2
libpthread.so.0
libgcc_s.so.1
libc.so.6
ld-linux-x86-64.so.2
libm.so.6
Notes:
libaziot_keys.so is not part of OS but it's installed with aziot-identity-service. so skipped it in this check.
Specific version is checked as there is no minimum version research has been done with which IoT edge runtime works perfectly. Always using the latest version from the …
=> [Tools] Check for shared library dependency in Platform validation tool

edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/CbsNode.cs
Fixes #6036 
* dispose message
=> AMQP CBS token message dispose (#6057) (#6107)

edge-modules/edgehub-proxy/Cargo.lock, edgelet/Cargo.lock, edgelet/edgelet-docker/Cargo.toml, edgelet/edgelet-docker/src/notary.rs, mqtt/Cargo.lock, tools/snitch/Cargo.lock
*Cf.* #6136. The changes were previously reverted (#6160) due to conflicts with the release schedule.
=> [release/1.2] Update tokio, rayon, and crossbeam to latest compatible versions

scripts/linux/buildImage.sh
Cherry pick e375cd65817c5d15168dad9f94a012fa6100f09b
=> Fix aarch64 diagnostics module build

builds/checkin/compatibility-tool-checkin.yaml
This PR Adds a minimal run of the platform compatibility tool as a sanity check.
TODO's
1. Check for negative cases as part of the run …
=> Run Platform Compatibility Tool On Check-in

platform-validation/scripts/aziot-compatibility.sh
This PR adds a check to make sure the target device has minimum required storage space for installing azure iot edge binaries and runtime containers.  
1. Adds the check for Storage Space
2. Adds placeholders for storage binaries for each of the supported architectures. 
3. Refactors the Shared Library Check. 
4. Some minor formatting fixes
Todo: 
1. For every release, automatically make sure that the binary size and container size of iotedge match what's present in the script
2. Update numbers for AMD64 and ARM64
- Encountering multiple pipeline failures and working …
=> Implement Check for Storage Space for IoT Edge

builds/e2e/e2e.yaml
Cherry-pick: https://github.com/Azure/iotedge/commit/7db756c94e8d78eb1b64de5203a77846b725232c …
=> Upgrade end-to-end tests to run against Debian 10 & 11 arm32v7

edge-hub/watchdog/Cargo.lock, edge-modules/api-proxy-module/Cargo.lock, edge-modules/api-proxy-module/rust-sdk/azure-iot-mqtt/Cargo.lock, edge-modules/edgehub-proxy/Cargo.lock, edgelet/Cargo.lock, mqtt/Cargo.lock, test/modules/generic-mqtt-tester/Cargo.lock, test/modules/obsagent-client/Cargo.lock, tools/check_submodules/Cargo.lock
Contains mitigations for CVE-2022-24713.
https://www.whitesourcesoftware.com/vulnerability-database/CVE-2022-24713
=> [main] Update regex to 1.5.5

builds/e2e/templates/unlock-test-agents.yaml, scripts/linux/nestedAgentLock.sh
Cherry pick #6181 
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes all the commits in the PR to a single commit. The net effect is that entire PR becomes a single commit. Please follow the best practices mentioned [here](https://chris.beams.io/posts/git-commit/#:~:text=The%20seven%20rules%20of%20a%20great%20Git%20commit,what%20and% …
=> Nested E2E: Enhance lock/unlock logic (#6181)

platform-validation/scripts/aziot-compatibility.sh
1. defines the current numbers of memory usage
2. usage of `free` command to find the current free memory usage 
3. perform the memory check
=> [Tools] Checking the current free memory in the platform for IoT Edge memory compatibility check

platform-validation/scripts/aziot-compatibility.sh
Changing the memory check from free command to reading directly from the /proc/meminfo file.
=> [Tools] Change memory check from free command 

platform-validation/scripts/aziot-compatibility.sh
This PR Adds
1. Verbose logging to Platform Compatibility Tool
2. Removes dependency on higher level function "command -v" instead, now directly calls --help on command to verify if command exists. I tested this out on Tier 1 Platform as well as OpenWRT, SUSEEnterprise and it seems to work well
3. Uses Only POSIX Output from df command. Some distros do not have a -m or -h option
4. Cleanup of some log messages
5. Adds OS Information to Script Output
6. Adds an Exit Code and Output Detailing how many Checks Passed Failed, Raised Warnings
7. Display Warning Message if not running as root
- Work in progress or not …
=> Add Options for Verbose Logging and Some Bug Fixes to Platform Compatibility Tool

platform-validation/deployment/platform-compatibility.json, platform-validation/scripts/aziot-compatibility.sh, platform-validation/scripts/check-for-updates.sh
This is Step 1 of a 2 Step PR that runs a script to deploy IoT Edge Binaries and Containers to a device and then detects whether recorded Binary Size, Memory Usage in the platform compatibility tool is not less than or greater than the current runs Memory Usage, Binary Size (A Buffer of 50MB is provided)
The script will error out if there is a difference and prompt to update the compatibility tool. I am not choosing to auto update the tool because a significant difference in memory/size should be investigated before updating the compatibility tool
TODO:
1. Add Additional checks - Shared Library , Docker Version
2. Add a YAML for Scheduled CI Builds for ARM32, ARM64 and AMD64 
This checklist is used to make …
=> Add Script that Detects Changes required for Platform Compatibility Tool

builds/misc/packages-release.yaml
Introduce Buster & Bullseye automated artifacts publication
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes all the commits in the PR to a single commit. The net effect is that entire PR becomes a single commit. Please follow the best practices mentioned [here](https://chris.beams.io/posts/git-commit/#:~:text=The%20seven%20rules%20 …
=> Introduce Buster & Bullseye automated artifacts publication

builds/misc/packages-release.yaml
Introduce Buster & Bullseye automated artifacts publication
(Cherry-pick from https://github.com/Azure/iotedge/commit/0535bc22c2d8a764372ad571d97f2bb12ed2c6e7)
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes all the commits in the PR to a single commit. The net effect is that entire PR becomes a single commit. Please follow the …
=> Introduce Buster & Bullseye automated artifacts publication (#6217)

platform-validation/scripts/aziot-compatibility.sh, platform-validation/scripts/check-for-updates.sh
* Changes in the compatibility tool to help the execution of the update script for the tool
* Changes in the update script to look for any other libraries that are added in the new IoT edge package
=> [Tools] Automate shared library dependency check in platform compatibility tool

test/modules/TestResultCoordinator/Reports/CountingReport.cs
Cherry pick #6183
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes all the commits in the PR to a single commit. The net effect is that entire PR becomes a single commit. Please follow the best practices mentioned [here](https://chris.beams.io/posts/git-commit/#:~:text=The%20seven%20rules%20of%20a%20great%20Git%20commit,what%20and%2 …
=> Longhaul: Fix tolerance for broker enabled messaging (#6183)

.github/.kodiak.toml
In the main branch, we've set up the kodiak tool to remove the PR template text from merge commits. This change brings the same behavior to the release/1.2 branch.
=> Remove PR template body from commits

edgelet/Cargo.lock, edgelet/iotedge/Cargo.toml, edgelet/iotedge/src/check/checks/check_users.rs, edgelet/iotedge/src/check/checks/mod.rs, edgelet/iotedge/src/config/apply.rs, edgelet/iotedge/src/internal/common.rs, edgelet/iotedge/src/internal/mod.rs, edgelet/iotedge/src/lib.rs
This PR Adds a Check to ensure that system interaction with a device to get user information works as intended. The PR Does the following
1. Define a common function for querying user information.
2. Use the common function in iotedge config apply
3. Use the same function in IoT Edge Check to verify users for running IoT Edge are present
Todo: 
1. Add TPM User handling since it is a special scenario
Testing
1. Validated on Ubuntu 20.04 AMD64 , Installed IoT Edge and removed one user
_Note: We use the …
=> [Platform-Validation] Add Check to Verify Users

platform-validation/docs/aziot-compatibility-get-started.md
Documentation on usage of Compatibility script.
=> Document for IoT edge compatibility script

builds/checkin/api-proxy.yaml, builds/checkin/edgelet.yaml, builds/checkin/mqtt.yaml, builds/checkin/rust-test-modules.yaml, builds/checkin/watchdog.yaml, builds/ci/mqtt.yaml, edge-hub/watchdog/src/child.rs, mqtt/mqtt-broker/src/tls.rs, mqtt/mqtt-broker/tests/persist_failpoints.rs
Continuation of #6278.
Resolves clippy failures not caught due to pipelines not triggering on changes to `rust-toolchain.toml`.
=> [main] Rust toolchain upgrade fixes

edgelet/iotedge/src/check/checks/check_sockets.rs, edgelet/iotedge/src/check/checks/mod.rs, edgelet/iotedge/src/config/apply.rs
This PR Adds Checks for
1. Ensuring Workload Socket and Management Sockets Exists
2. Ensuring the sockets are owned by iotedge group
3. Ensuring the sockets have the correct permissions
TODO's in future PR's
1. Ensure we can communicate with Workload and Management Socket
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes all the …
=> [Platform Validation] Add Checks for Socket Permission

edge-modules/TransactableModuleSample/README.md
Only docs update to the private preview
=> Clarify sample

edgelet/iotedge/Cargo.toml, edgelet/iotedge/src/check/checks/check_compatibility.rs, edgelet/iotedge/src/check/checks/check_fs_calls.rs, edgelet/iotedge/src/check/checks/check_sockets.rs, edgelet/iotedge/src/check/checks/check_users.rs, edgelet/iotedge/src/check/checks/mod.rs
Recent Merge with Main had caused build errors. This PR Fixes them. Tested locally …
=> [ Platform Validation ] Fix Build Errors

builds/misc/packages-release.yaml, scripts/linux/publishReleasePackages.sh
Updated the automated GitHub artifact uploads:
- Remove the upload of *-debuginfo-*.rpm
- Upload IotEdgeSecurityDaemon.ps1
- Upload Microsoft-Azure-IoTEdge-amd64.cab
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes all the commits in the PR to a single commit. The net effect is that entire PR becomes a single commit. Please follow …
=> Update GitHub Artifacts Upload Automation

builds/misc/packages-release.yaml
Remove the Debian10 artifact publication from packages.microsoft.com
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes all the commits in the PR to a single commit. The net effect is that entire PR becomes a single commit. Please follow the best practices mentioned [here](https://chris.beams.io/posts/git-commit/#:~:text=The%20seven%2 …
=> Remove the publication of Deb10 to PMC

CHANGELOG.md
Remove mention of publishing Debian packages to packages.microsoft.com as this will be communicated elsewhere in the release notes. …
=> Fix changelog for 1.1.13

test/modules/CloudToDeviceMessageTester/CloudToDeviceMessageReceiver.cs
Add retry to connectivity tests c2d messaging receiver to stabilize tests.
Test run:
https://dev.azure.com/msazure/One/_build/results?buildId=54844970&view=results
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes all the commits in the PR to a single commit. The net effect is that entire PR becomes a single commit. Please follow …
=> Connectivity Tests: Retry failing cloud to device receiver connection

edge-modules/TransactableModuleSample/README.md
Docs only update for the private preview @ancaantochi
=> Clarify terms acceptance role and deploy command

builds/misc/packages-release.yaml
Remove the Debian10 artifact publication from packages.microsoft.com
Cherry-picked: https://github.com/Azure/iotedge/commit/d57a9a990cd8602f7b816eb96c96547f120ce280
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes all the commits in the PR to a …
=> Remove the publication of Deb10 to PMC 

scripts/linux/github/updateLatestVersion.sh, scripts/linux/publishReleasePackages.sh
- Use git `--force` 
- Use relative path to source helper bash functions.
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes all the commits in the PR to a single commit. The net effect is that entire PR becomes a single commit. Please follow the best practices mentioned [here](https://chris.beams.io/posts/git-commit/#:~:text=The%20se …
=> Path correction for #6351

edge-modules/functions/binding/src/Microsoft.Azure.WebJobs.Extensions.EdgeHub/Microsoft.Azure.WebJobs.Extensions.EdgeHub.csproj, edge-modules/functions/samples/EdgeHubTrigger-Csharp/EdgeHubTriggerCSharp.csproj, kubernetes/charts/edge-kubernetes-crd/Chart.yaml, kubernetes/charts/edge-kubernetes-crd/templates/crd.yaml, kubernetes/charts/edge-kubernetes/Chart.yaml
- Update to CRD.yaml to version v1 from v1beta1 and chart update
- Update the edge-module package version to resolve some pipeline problems
- Update Text.Encoding.Web version
=> K8s Refresh for 1.22 version

builds/misc/templates/build-packages.yaml
Disable Mariner 1.0 & Mariner 2.0 OS edglet build to unblock the check-in & stabilize the build process while we investigating the root cause of the Mariner build faliure.
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes all the commits in the PR to a single commit. The net effect is that entire PR becomes a single commit. Please …
=> Disable Mariner OSes

builds/e2e/templates/e2e-run.yaml, builds/e2e/upgrade-scenarios.yaml
Adds an ADO pipeline for testing various partial upgrade scenarios, all with a 1.2.x edge daemon (and corresponding aziot-identity-service) installed (this is for simplicity so that the 1.2 .NET E2E test framework could be used). Other scenarios are covered by similar pipelines on the other release branches.
These changes were tested by running test pipelines on the PR branch and validating the final parameters in context.json for each scenario as well as spot checking the support bundles to confirm the correct versions of aziot-edged and aziot-identity-service are installed during the run.
TODO in follow-on/backlogged PRs:
1. Test full upgrade scenarios
2. Reduce code duplication in upgrade-scenarios.yaml …
=> Test Upgrade Scenarios 1.2

builds/misc/packages-release.yaml
There is a known docker issue with Debian 10 which we will not support it as a tier 1 OS. However, some of our customers are still relying on our iot-identity-service components, which we are going to continue to support readily in Packages.Microsoft.Com for ARM32, Debian10.
cherry-picked: https://github.com/Azure/iotedge/pull/6390
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR …
=> Publish ARM32 iot-identity-service artifacts for Debian10 in PMC

scripts/linux/smokeTestHelper.sh
Helper functions for an upcoming smoke tests.
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes all the commits in the PR to a single commit. The net effect is that entire PR becomes a single commit. Please follow the best practices mentioned [here](https://chris.beams.io/posts/git-commit/#:~:text=The%20seven%20rules%20of%20a%20great …
=> Introduce smokeTestHelper.sh

edgelet/docker-rs/src/apis/client.rs, edgelet/docker-rs/src/apis/configuration.rs, edgelet/edgelet-core/src/module.rs, edgelet/edgelet-docker/src/runtime.rs
This was an oversight when forward-porting from release/1.2; configuration items for additional information are no longer renamed during merging.
=> [release/1.3] Do not rename configuration items for SystemInfo

builds/misc/packages-release.yaml
Disable Auto version increment for Initial 1.3 release
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes all the commits in the PR to a single commit. The net effect is that entire PR becomes a single commit. Please follow the best practices mentioned [here](https://chris.beams.io/posts/git-commit/#:~:text=The%20seven%20rules%20of%20 …
=> Disable Auto version increment for Initial 1.3 release

builds/misc/images-publish.yaml
Publish to `unlisted/azureiotedge-diagnostics` instead of `public/azureiotedge-diagnostics` to not cobble Discovery Portal with self-debugging module.
Related PR: https://github.com/microsoft/mcr/pull/2040
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes all the commits in the PR to a single commit. The net effect is that entire PR …
=> Update to `unlisted/azureiotedge-diagnostics`

builds/misc/packages-release.yaml, scripts/linux/github/updateLatestVersion.sh
Update the release1.3 automated release step.
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes all the commits in the PR to a single commit. The net effect is that entire PR becomes a single commit. Please follow the best practices mentioned [here](https://chris.beams.io/posts/git-commit/#:~:text=The%20seven%20rules%20of%20a%20great …
=> Update release to be compatible with 1.3

builds/misc/packages-release.yaml
Recently, Microsoft Linux Repository Admins required that RHEL8.X RPM packages to be signed before the packages be admitted to the packages.microsoft.com.  This PR improves our build pipeline to incorporate ESRP signing into our release process.
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes all the commits in the PR to a single …
=> ESRP Signing for RHEL8.X Packages

builds/e2e/isa-95-smoke-test.yaml, builds/e2e/templates/nested-isa95-lock.yaml
Correct the unlocking test agent name for ISA95 test pipeline
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes all the commits in the PR to a single commit. The net effect is that entire PR becomes a single commit. Please follow the best practices mentioned [here](https://chris.beams.io/posts/git-commit/#:~:text=The%20seven%20rules% …
=> Correct ISA95 test agent name

builds/misc/packages-release.yaml
Sign and publish iot-identity-service to packages.microsoft.com
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes all the commits in the PR to a single commit. The net effect is that entire PR becomes a single commit. Please follow the best practices …
=> ESRP Signing for RHEL8.X identity-service Packages (#6492)

scripts/linux/trcE2ETest.sh, smoke/IotEdgeQuickstart/details/Details.cs
There was a PR to attempt to mitigate some network related issues in connectivity tests:
https://github.com/Azure/iotedge/pull/6428/files
We are still seeing these problems:
1. Registry manager calls timing out, even those with retry policy
2. Test report not getting generated due to delays in edge agent starting up (due to bad network)
1 can be fixed by extending existing retry policy and adding new one. 2 can be fixed by extending already-extended validation time even more.
Will wait on connectivity tests to pass before merge:
https://dev.azure.com/msazure/One/_build/results?buildId=57729811&view=results
- Work in …
=> Connectivity Tests: Resolve networking related errors

builds/misc/images-publish.yaml
Change image publishing pipeline to publish the diagnostics module to the 'unlisted' MCR namespace instead of the 'public' namespace. …
=> Cherry-pick: Fix diagnostics module mcr publishing

builds/e2e/upgrade-scenarios.yaml
Update Upgrade Scenario to be release/1.3
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes all the commits in the PR to a single commit. The net effect is that entire PR becomes a single commit. Please follow the best practices mentioned [here](https://chris.beams.io/posts/git-commit/#:~:text=The%20seven%20rules%20of%20a%20great%20G …
=> Update Upgrade Scenario to be release/1.3

edgelet/iotedge/Cargo.toml, edgelet/iotedged/Cargo.toml
Update version and a few details so the `cargo bitbake` won't complain.
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes all the commits in the PR to a single commit. The net effect is that entire PR becomes a single commit. Please follow the best practices mentioned [here](https://chris.beams.io/posts/git-commit/#:~:text=The%20seve …
=> Update the version and details for bitbake

builds/mariner/SPECS/aziot-edge/aziot-edge.spec, builds/misc/templates/build-packages.yaml, edgelet/Makefile, edgelet/build/linux/package-mariner.sh, edgelet/contrib/systemd/mariner/aziot-edged.mgmt.socket, edgelet/contrib/systemd/mariner/aziot-edged.service, edgelet/contrib/systemd/mariner/aziot-edged.workload.socket
Bring changes from the PR here https://github.com/Azure/iotedge/commit/6ac5577fd8ba65ae15715e72933fe5eec66619b1 to the release/1.3 branch …
=> Cherry Pick Mariner Socket Activation

builds/misc/templates/build-packages.yaml
Increase Mariner edgelet build timout to be 90 min
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes all the commits in the PR to a single commit. The net effect is that entire PR becomes a single commit. Please follow the best practices mentioned [here](https://chris.beams.io/posts/git-commit/#:~:text=The%20seven%20rules%20of%20a%20 …
=> Increase Mariner edgelet build timout to be 90 min

edgelet/Cargo.lock, edgelet/contrib/config/linux/template.toml, edgelet/iotedge/src/config/import/mod.rs, edgelet/iotedge/src/config/mp.rs, edgelet/iotedge/test-files/config/ca-certs-est/super-config.toml, edgelet/iotedge/test-files/config/ca-certs-local-ca/super-config.toml, edgelet/iotedge/test-files/config/ca-certs/super-config.toml, edgelet/iotedge/test-files/config/ca-quickstart-custom/super-config.toml, edgelet/iotedge/test-files/config/ca-quickstart/super-config.toml, edgelet/iotedge/test-files/config/complex-agent-spec/super-config.toml, edgelet/iotedge/test-files/config/dps-no-reprovisioning-flags/super-config.toml, edgelet/iotedge/test-files/config/dps-symmetric-key/super-config.toml, edgelet/iotedge/test-files/config/dps-tpm/super-config.toml, edgelet/iotedge/test-files/config/dps-x509/super-config.toml, edgelet/iotedge/test-files/config/imported-master-encryption-key/super-config.toml, edgelet/iotedge/test-files/config/manual-connection-string-2/super-config.toml, edgelet/iotedge/test-files/config/manual-connection-string/super-config.toml, edgelet/iotedge/test-files/config/manual-x509/super-config.toml, edgelet/iotedge/test-files/config/moby-runtime-network-2/super-config.toml, edgelet/iotedge/test-files/config/moby-runtime-network/super-config.toml, edgelet/iotedge/test-files/config/nested-edge/super-config.toml, edgelet/iotedge/test-files/config/not-socket-activated-both-custom/super-config.toml, edgelet/iotedge/test-files/config/not-socket-activated-varlib/super-config.toml, edgelet/iotedge/test-files/config/not-socket-activated-varrun/super-config.toml, edgelet/iotedge/test-files/config/socket-activated-one-custom/super-config.toml
1. Updates edgelet to depend on the new version of aziot-identity-service, which supports sending custom allocation payloads during DPS registration. See https://github.com/Azure/iot-identity-service/pull/430.
2. Updates config.toml.edge.template with an example DPS payload setting
3. Update `iotedge config import` toml output to include new [payload] field, and update affected tests.
4. Update `iotedge config mp` toml output to include new [tpm] field and update affected tests.
Changes have been tested manually on an ubuntu 18.04 VM by modifying a device setup by the I-I-S E2E tests. The device was modified to be an Edge device and successfully reprovisioned with a custom DPS payload. 
- …
=> Support DPS custom allocation payloads

builds/misc/templates/build-packages.yaml, edgelet/build/linux/package-mariner.sh
Change the mariner arm64 build to select the correct iot-identity-service branch release/1.3 …
=> Mariner arm64 build use iot-identity-service branch 1.3

builds/misc/addons-release.yaml, builds/misc/templates/build-images.yaml, builds/misc/templates/build-packages.yaml, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/planrunner/ExecutionPrerequisiteException.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/planrunner/OrdererdRetryPlanRunner.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/commandfactories/ExecutionPrerequisiteCommandFactory.cs, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/commands/ExecutionPrerequisiteCommand.cs, edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/OrderedRetryPlanRunnerTest.cs, edgelet/build/linux/package-mariner.sh
*Cf.* https://github.com/microsoft/CBL-Mariner/issues/3483.
=> [main] Revert Mariner 2.0 to latest working version

builds/misc/templates/build-packages.yaml, edgelet/build/linux/package-mariner.sh
*Cf.* https://github.com/microsoft/CBL-Mariner/issues/3483.
=> [release/1.1] Revert Mariner 2.0 to latest working version

edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/Microsoft.Azure.Devices.Edge.Agent.Diagnostics.csproj, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Docker/Microsoft.Azure.Devices.Edge.Agent.Docker.csproj, edge-modules/functions/samples/EdgeHubTrigger-Csharp/EdgeHubTriggerCSharp.csproj, edge-modules/metrics-collector/src/Microsoft.Azure.Devices.Edge.Azure.Monitor.csproj, edge-util/src/Microsoft.Azure.Devices.Edge.Util/Microsoft.Azure.Devices.Edge.Util.csproj, edge-util/test/Microsoft.Azure.Devices.Edge.Util.Test.Common/Microsoft.Azure.Devices.Edge.Util.Test.Common.csproj, test/Microsoft.Azure.Devices.Edge.Test.Common/Microsoft.Azure.Devices.Edge.Test.Common.csproj, test/modules/TwinTester/TwinTester.csproj, test/modules/load-gen/load-gen.csproj
- Update SharpZipLib to 1.3.3
- Update Newtonsoft.Json to 13.0.1
=> [release/1.1] Resolve Component Governance alerts

builds/misc/packages-release.yaml
=> Disable auto version increment for initial 1.4 release

CHANGELOG.md
Update changelog for 1.4.0
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes all the commits in the PR to a single commit. The net effect is that entire PR becomes a single commit. Please follow the best practices mentioned [here](https://chris.beams.io/posts/git-commit/#:~:text=The%20seven%20rules%20of%20a%20great%20Git%20commit,wha …
=> Update changelog for 1.4.0

builds/misc/images-release.yaml
Disable docker detector for images release build
=> Disable docker detector for images release build

builds/misc/images-release.yaml
Disable docker detector for images release build
=> Disable docker detector for images release build (#6625)

builds/service/service-deployment.yaml
=> Upgrade service deployment pipeline to 1.4

builds/checkin/e2e-checkin.yaml
Update default edgelet artifact to be used in check-in E2E. 
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes all the commits in the PR to a single commit. The net effect is that entire PR becomes a single commit. Please follow the best practices mentioned [here](https://chris.beams.io/posts/git-commit/#:~:text=The%20seven%20rules%2 …
=> Update default edgelet artifact to be used in check-in E2E. 

builds/misc/images-publish.yaml, builds/misc/images-release.yaml
We need to publish Diagnostics module for release 1.4.1 as the module is highly coupled with edgelet artifacts and self-help.
The images were not part of the release 1.4.1; hence, the Diagonostic module was not updated causing a failure in the use cases.
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes all the commits in the PR to …
=> Only publishing the Diagnostics image (pt.2)

builds/misc/images-publish.yaml, builds/misc/images-release.yaml
=> Yophilav/diag module release1.4.1 1.4

builds/misc/images-publish.yaml, builds/misc/images-release.yaml
Revert the changes for Diagonostic module 1.4.1 release
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes all the commits in the PR to a single commit. The net effect is that entire PR becomes a single commit. Please follow the best practices mentioned [here](https://chris.beams.io/posts/git-commit/#:~:text=The%20seven%20rules%20of%2 …
=> Revert the changes for Diagonostic module 1.4.1 release

builds/misc/images-publish.yaml, builds/misc/packages-release.yaml
Use AAD to login to msint for our repoclient docker image pull.
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes all the commits in the PR to a single commit. The net effect is that entire PR becomes a single commit. Please follow the best practices mentioned [here](https://chris.beams.io/posts/git-commit/#:~:text=The%20seven%20rule …
=> AAD auth for Repoclient image 

edgelet/edgelet-docker/src/runtime.rs
Updated log message to add more clarity for better user experience and comprehension,
=> Fix confusing log message

builds/misc/packages-release.yaml
Use AAD to login to msint for our repoclient docker image pull.
Cherry-pick: https://github.com/Azure/iotedge/commit/4fc40c981054220e177a3e5af167c842befa987c
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes all the commits in the PR to a single commit. The net effect is that entire PR becomes a single commit. Please follow the best …
=> AAD auth for Repoclient image

edgelet/edgelet-docker/src/runtime.rs
Updated log message to add more clarity for better user experience and comprehension. 
(cherry picked from commit 50cc0ba73c0cb6a8b6e91448fb294355c0720e39)
=> Fix confusing log message in image garbage collection (#6690)

edge-modules/functions/samples/docker/linux/amd64/Dockerfile
The azure-functions/dotnet base image we're using in our Azure Functions sample (edge-modules/functions/samples) is not maintained (it is about 9 months old). The internal images we're using in our tests have security vulnerabilities. This change updates to a base image that is regularly serviced by the Azure Functions team.
To test, I built a new azureiotedge-functions-filter image, ran the end-to-end tests against it, and confirmed they passed.
=> Update Azure Functions sample's base image

edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/Microsoft.Azure.Devices.Edge.Hub.Core.csproj, edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/Microsoft.Azure.Devices.Edge.Hub.Mqtt.csproj
Cherry-pick 906786c52526cca4e90aaaec0de7c389e890a387.
=> Update dependency to fix OOM bug

builds/checkin/edgelet.yaml
=> Reduce Rust code coverage threshold

builds/e2e/connectivity.yaml
Let's scale back connectivity test frequency to once a week.
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes all the commits in the PR to a single commit. The net effect is that entire PR becomes a single commit. Please follow the best practices mentioned [here](https://chris.beams.io/posts/git-commit/#:~:text=The%20seven%20rules%2 …
=> Connectivity Tests: Decrease scheduled runs to once a week 

edge-modules/metrics-collector/src/CertificateGenerator/CertGenerator.cs
This switches to a better logging pattern that among other benefits, provides the timestamps for each log statement.
These changes were tested by building an image locally and using it in a test deployment.
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes all the commits in the PR to a single commit. The net effect is that entire …
=> MetricsCollector: Use Logger instead of Console.WriteLine

builds/misc/templates/build-packages.yaml, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/EdgeAgentConnection.cs, edgelet/Cargo.lock, edgelet/build/linux/package-mariner.sh
This PR will re-enable the release/1.4 Mariner package to be built using Mariner 2.0-stable. For This build to work the required changes to fix the iot-identity-service package for mariner must also be ingested, which is why the hash has been updated to reflect the most recent version of iot-identity-service release/1.4
The release/1.4 branch of iot-identity-service is being used for the mariner package's vendoring step. 
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals …
=> Add Mariner 2.0-stable back to 1.4 Branch

builds/misc/templates/build-packages.yaml
Adding support for the mariner 2.0-stable version toolkit. also changing to work with ubuntu 20.04 …
=> Added back Mariner 2.0-stable to Release/1.1

edge-modules/api-proxy-module/Cargo.lock, edge-modules/api-proxy-module/rust-sdk/azure-iot-mqtt/Cargo.lock, edge-modules/api-proxy-module/rust-sdk/azure-iot-mqtt/Cargo.toml, edge-modules/api-proxy-module/rust-sdk/azure-iot-mqtt/src/device.rs, edge-modules/api-proxy-module/rust-sdk/azure-iot-mqtt/src/iotedge_client.rs, edge-modules/api-proxy-module/rust-sdk/azure-iot-mqtt/src/lib.rs, edge-modules/api-proxy-module/rust-sdk/azure-iot-mqtt/src/module.rs, edge-modules/api-proxy-module/rust-sdk/azure-iot-mqtt/src/system_properties.rs, edge-modules/api-proxy-module/rust-sdk/azure-iot-mqtt/src/twin_state/mod.rs, edge-modules/edgehub-proxy/Cargo.lock, edge-modules/edgehub-proxy/Cargo.toml, edge-modules/edgehub-proxy/src/error.rs, edge-modules/edgehub-proxy/src/main.rs, edgelet/Cargo.lock, edgelet/aziot-edged/Cargo.toml, edgelet/aziot-edged/src/main.rs, edgelet/iotedge/Cargo.toml, edgelet/iotedge/src/error.rs, edgelet/iotedge/src/main.rs, edgelet/iotedge/src/support_bundle.rs, edgelet/support-bundle/src/support_bundle.rs, mqtt/mqtt3/Cargo.toml, mqtt/mqtt3/examples/common/mod.rs, mqtt/mqtt3/examples/publisher.rs, mqtt/mqtt3/examples/subscriber.rs, mqtt/mqtt3/examples/will.rs
`structopt` depends on `ansi_term`, which is now being flagged as unmaintained.
<details>
<summary>Tested commands:</summary>
<p>
```
check
check --help
check --verbose
check --output json
check --output text
check --output neither
check --aziot-edged /usr/libexec/aziot/aziot-edged --container-engine-config-file /etc/docker/daemon.json --dont-run 'keyd-running certd-running tpmd-running identityd-running' --expected-aziot-edged-version 1.4.2 --expected-aziot-version 1.4.1 --host unix:///var/run/iotedge/mgmt.sock --iothub-hostname "${IOTHUB_HOSTNAME}" --ntp-server pool.ntp.org:123
check-list
check-list --help
config
config apply
config apply --config-file /etc/aziot/config.toml
config mp --connection-string "${CONNECTION_STRING}"
config mp --connection-string "${CONNECTION_STRING}" --out …
```
=> Switch from clap 2 and structopt to clap 4

builds/e2e/connectivity.yaml
Let's scale back connectivity test frequency to once a week.
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes all the commits in the PR to a single commit. The net effect is that entire PR becomes a single commit. Please follow the best practices mentioned [here](https://chris.beams.io/posts/git-commit/#:~:text=The%20seven%20rules%2 …
=> Connectivity Tests: Decrease scheduled runs to once a week

edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/Microsoft.Azure.Devices.Edge.Agent.Diagnostics.csproj, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Docker/Microsoft.Azure.Devices.Edge.Agent.Docker.csproj, edge-modules/functions/binding/src/Microsoft.Azure.WebJobs.Extensions.EdgeHub/Microsoft.Azure.WebJobs.Extensions.EdgeHub.csproj, edge-modules/functions/samples/EdgeHubTrigger-Csharp/EdgeHubTriggerCSharp.csproj, edge-modules/metrics-collector/src/Microsoft.Azure.Devices.Edge.Azure.Monitor.csproj, edge-util/src/Microsoft.Azure.Devices.Edge.Util/Microsoft.Azure.Devices.Edge.Util.csproj, edge-util/test/Microsoft.Azure.Devices.Edge.Util.Test.Common/Microsoft.Azure.Devices.Edge.Util.Test.Common.csproj, samples/dotnet/EdgeDownstreamDevice/EdgeDownstreamDevice.csproj, samples/dotnet/EdgeX509AuthDownstreamDevice/EdgeX509AuthDownstreamDevice.csproj, test/Microsoft.Azure.Devices.Edge.Test.Common/Microsoft.Azure.Devices.Edge.Test.Common.csproj, test/modules/TwinTester/TwinTester.csproj, test/modules/load-gen/load-gen.csproj
Fixes vulnerability due to insecure defaults.
Ref: https://github.com/advisories/GHSA-5crp-9r3c-p9vr
=> [main] Update to Newtonsoft.Json 13.0.2

edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/Microsoft.Azure.Devices.Edge.Agent.Diagnostics.csproj, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Docker/Microsoft.Azure.Devices.Edge.Agent.Docker.csproj, edge-modules/functions/binding/src/Microsoft.Azure.WebJobs.Extensions.EdgeHub/Microsoft.Azure.WebJobs.Extensions.EdgeHub.csproj, edge-modules/functions/samples/EdgeHubTrigger-Csharp/EdgeHubTriggerCSharp.csproj, edge-util/src/Microsoft.Azure.Devices.Edge.Util/Microsoft.Azure.Devices.Edge.Util.csproj, edge-util/test/Microsoft.Azure.Devices.Edge.Util.Test.Common/Microsoft.Azure.Devices.Edge.Util.Test.Common.csproj, samples/dotnet/EdgeDownstreamDevice/EdgeDownstreamDevice.csproj, samples/dotnet/EdgeX509AuthDownstreamDevice/EdgeX509AuthDownstreamDevice.csproj, test/Microsoft.Azure.Devices.Edge.Test.Common/Microsoft.Azure.Devices.Edge.Test.Common.csproj, test/modules/TwinTester/TwinTester.csproj, test/modules/load-gen/load-gen.csproj
Fixes vulnerability due to insecure defaults.
Ref: https://github.com/advisories/GHSA-5crp-9r3c-p9vr
=> [release/1.4] Update to Newtonsoft.Json 13.0.2

edge-modules/api-proxy-module/Cargo.lock, edgelet/Cargo.lock, edgelet/edgelet-settings/src/base/image.rs, edgelet/support-bundle/src/shell_util.rs
Updates cargo dependencies to resolve CG issues with older dependencies.
=> Update cargo dependencies

builds/e2e/nested-e2e.yaml, e2e_deployment_files/nestededge_middleLayerBaseDeployment_mqtt.json, e2e_deployment_files/nestededge_topLayerBaseDeployment_mqtt.json
Cherry pick #6790 
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes all the commits in the PR to a single commit. The net effect is that entire PR becomes a single commit. Please follow the best practices mentioned [here](https://chris.beams.io/posts/git-commit/#:~:text=The%20seven%20rules%20of%20a%20great%20Git%20commit,what%20and% …
=> Nested E2E: Restore mqtt upstream (#6790)

builds/release/refresh-core-images.yaml, scripts/linux/release-tools.sh
Cherry-pick d7322af6f93d7f0c2e66c189a5c624f6afeeec22 and ceb3d310d9477376590a856de6e507b5795e0c23.
=> Fix jq logic in image refresh pipeline

scripts/linux/buildImage.sh
Cherry-pick f82a7d94f37a795ce908c67dca8192e626b38788.
=> Fix image builds

edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/metrics/DeploymentMetrics.cs
(cherry picked from commit 38759bbad1855075224d950af1a0d5864a891d3d)
=> Fix running and expected running values

scripts/linux/moveImage.sh
Cherry-pick 4db76e9c37de8c8822fb0c44484979a3de99c461
=> Use newer tooling to copy image between registries

CodeCoverage.runsettings, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/Microsoft.Azure.Devices.Edge.Agent.Core.csproj, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/ModuleClientProvider.cs, edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/storage/MessageStore.cs, edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/Microsoft.Azure.Devices.Edge.Hub.Mqtt.csproj, edge-hub/core/src/Microsoft.Azure.Devices.Routing.Core/Microsoft.Azure.Devices.Routing.Core.csproj, edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Test/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Test.csproj, edge-modules/SimulatedTemperatureSensor/SimulatedTemperatureSensor.csproj, edge-modules/functions/binding/src/Microsoft.Azure.WebJobs.Extensions.EdgeHub/Microsoft.Azure.WebJobs.Extensions.EdgeHub.csproj, edge-modules/functions/samples/EdgeHubTrigger-Csharp/EdgeHubTriggerCSharp.csproj, edge-modules/iotedge-diagnostics-dotnet/IotedgeDiagnosticsDotnet.csproj, edge-util/src/Microsoft.Azure.Devices.Edge.Storage.RocksDb/Microsoft.Azure.Devices.Edge.Storage.RocksDb.csproj, edge-util/src/Microsoft.Azure.Devices.Edge.Util/Microsoft.Azure.Devices.Edge.Util.csproj, edge-util/test/Microsoft.Azure.Devices.Edge.Util.Test.Common/Microsoft.Azure.Devices.Edge.Util.Test.Common.csproj, samples/dotnet/EdgeDownstreamDevice/EdgeDownstreamDevice.csproj, samples/dotnet/EdgeX509AuthDownstreamDevice/EdgeX509AuthDownstreamDevice.csproj, smoke/IotEdgeQuickstart/IotEdgeQuickstart.csproj, smoke/LeafDevice/LeafDevice.csproj, test/Microsoft.Azure.Devices.Edge.Test.Common/Microsoft.Azure.Devices.Edge.Test.Common.csproj, test/modules/ModuleLib/Microsoft.Azure.Devices.Edge.ModuleUtil.csproj, test/modules/TestAnalyzer/TestAnalyzer.csproj, test/modules/TestResultCoordinator/TestResultCoordinator.csproj
Cherry-pick a3e924346d25db497ce759b828fd369c0d6691ea
=> Patch vulnerabilities in .NET dependencies

edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/Microsoft.Azure.Devices.Edge.Agent.Diagnostics.csproj, edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/Microsoft.Azure.Devices.Edge.Agent.IoTHub.csproj, edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/Microsoft.Azure.Devices.Edge.Hub.Amqp.csproj, edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.csproj, edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/Microsoft.Azure.Devices.Edge.Hub.Core.csproj, edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Http/Microsoft.Azure.Devices.Edge.Hub.Http.csproj, edge-modules/SimulatedTemperatureSensor/SimulatedTemperatureSensor.csproj, edge-modules/functions/binding/src/Microsoft.Azure.WebJobs.Extensions.EdgeHub/Microsoft.Azure.WebJobs.Extensions.EdgeHub.csproj, edge-modules/iotedge-diagnostics-dotnet/IotedgeDiagnosticsDotnet.csproj, samples/dotnet/EdgeDownstreamDevice/EdgeDownstreamDevice.csproj, samples/dotnet/EdgeX509AuthDownstreamDevice/EdgeX509AuthDownstreamDevice.csproj, smoke/IotEdgeQuickstart/IotEdgeQuickstart.csproj, smoke/LeafDevice/LeafDevice.csproj, test/Microsoft.Azure.Devices.Edge.Test.Common/Microsoft.Azure.Devices.Edge.Test.Common.csproj, test/modules/CloudToDeviceMessageTester/CloudToDeviceMessageTester.csproj, test/modules/DeploymentTester/DeploymentTester.csproj, test/modules/DirectMethodReceiver/DirectMethodReceiver.csproj, test/modules/DirectMethodSender/DirectMethodSender.csproj, test/modules/EdgeHubRestartTester/EdgeHubRestartTester.csproj, test/modules/MetricsValidator/MetricsValidator.csproj, test/modules/ModuleLib/Microsoft.Azure.Devices.Edge.ModuleUtil.csproj, test/modules/ModuleRestarter/ModuleRestarter.csproj, test/modules/Relayer/Relayer.csproj, test/modules/TemperatureFilter/TemperatureFilter.csproj, test/modules/TestAnalyzer/TestAnalyzer.csproj, test/modules/TestMetricsCollector/TestMetricsCollector.csproj, test/modules/TestResultCoordinator/TestResultCoordinator.csproj, test/modules/TwinTester/TwinTester.csproj, test/modules/load-gen/load-gen.csproj
=> update sdk to 1.36.8

edgelet/iotedge/src/config/apply.rs
=> Update IoT Edge apply config message on hostname change (#6942)

e2e_deployment_files/connectivity_deployment.template.json, scripts/linux/trcE2ETest.sh
Cherry pick #6976
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes all the commits in the PR to a single commit. The net effect is that entire PR becomes a single commit. Please follow the best practices mentioned [here](https://chris.beams.io/posts/git-commit/#:~:text=The%20seven%20rules%20of%20a%20great%20Git%20commit,what%20and%2 …
=> Connectivity Tests: Mitigate hanging support bundle (#6976)

edgelet/Cargo.lock
Get the latest versions of crates from Azure/iot-identity-service.
=> Bump iot-identity-service package dependencies

.gitignore, edgelet/Cargo.lock, edgelet/Cargo.toml, edgelet/Makefile, edgelet/contrib/snap/command-chain/drop-privileges.sh, edgelet/contrib/snap/command-chain/make-socket-directory.sh, edgelet/contrib/snap/socat.sh, edgelet/edgelet-settings/src/base/aziot.rs, edgelet/iotedge/Cargo.toml, edgelet/iotedge/src/config/apply.rs, edgelet/iotedge/src/system.rs, edgelet/support-bundle/Cargo.toml, edgelet/support-bundle/src/support_bundle.rs, snap/hooks/configure, snap/hooks/install, snap/snapcraft.yaml
Converting all the snapping work from a PR against main to a PR against feature/snapping
=> feature/snapping: a working snap in strict confinement

doc/EnvironmentVariables.md, edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/CertificateRenewal.cs, edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs
Add a flag in EdgeHub for the interval after which EdgeHub will check for server cert expiry.
Manual tests done:
- Configured device to not use NTP, but set the correct time
- Configured IoT Edge to have a delayed start.
- Deployed EdgeHub with MaxCheckCertExpiryInMs=120s.
- Also deployed SimulatedTemperatureSensor
- Started IoT Edge. EdgeAgent, EdgeHub, SimulatedTemperatureSensor came up and was working fine.
- Restarted device
- When device restarted, set the time to 2018, before IoT Edge started.
- IoT Edge started, and EdgeHub came up. The server cert it obtained had an expiry date in 2018.
- Set the correct time to 2023. EdgeHub detected the expired cert in 120s, and restarted, got the correct cert.
- Simulated temperature sensor was able to continue.
***Please replace this line with …
=> Add support for MaxCheckCertExpiryInMs (#6938)

edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Docker/models/RestartPolicyKind.cs, edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Docker.Test/DockerConfigTest.cs
=> fixed restart policy serialization

edge-modules/edgehub-proxy/Cargo.lock, test/rust-test-util/test-result-reporting-client/Cargo.lock
=> updated hyper for edgehub proxy

e2e_deployment_files/nestededge_isa95_smoke_test_BaseDeployment.json, edgelet/build/linux/package.sh
Cherry-pick 16a82f6aab94c0107c7a9cc4d240d8061cdf25d6.
=> Fix test JSON and RHEL package build

builds/release/refresh-metrics-collector-images.yaml, builds/release/templates/publish-core-images.yaml, scripts/linux/release-tools.sh
Cherry-pick 27097fce57f35e041e6a504f536d747d86178ae3 from release/1.4 and fix the same problem in the Metrics Collector refresh pipeline.
=> Fix Metrics Collector refresh pipeline

builds/e2e/e2e.yaml
Cherry-pick fc1cb7ba8fa38ede9d690011d438fe6c5927b407.
=> Enable 1ES-hosted Ubuntu 22.04 amd64 agent

edge-util/src/es6numberserializer/NumberFastDToABuilder.cs
Cherry-pick baecc41e3afeda096b7b3a99ba0470e3632e2c57.
=> Remove Java header comment

edge-modules/api-proxy-module/docker/linux/amd64/Dockerfile, edge-modules/api-proxy-module/docker/linux/arm32v7/Dockerfile, edge-modules/api-proxy-module/docker/linux/arm64v8/Dockerfile
Update API proxy base image
Test
https://msazure.visualstudio.com/One/_build/results?buildId=77189201&view=results
=> Update api proxy

edgelet/Cargo.lock, edgelet/contrib/debian/postrm
=> Ignore daemon-reload errors in postrm

builds/misc/packages-release.yaml
- Enabled ESRP signing for DEB packages
- Update the existing ESRP signing to version 3
- Update the underlying infrastructure to the PMCv4 with the new AAD cred
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes all the commits in the PR to a single commit. The net effect is that entire PR becomes a single commit. Please follow the …
=> Signing DEB packages 

edgelet/iotedge/src/config/apply.rs
=> Fix error in warning message

builds/e2e/isa-95-smoke-test.yaml, builds/e2e/templates/nested-isa95-lock.yaml, builds/e2e/templates/nested-isa95-unlock.yaml
Cherry-pick 47e9643ce69d6ef5cc5d0e4452829931020d5a79.
=> Fix ISA95 smoke test pipeline

edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Docker/models/RestartPolicyKind.cs, edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Docker.Test/DockerConfigTest.cs
Cherry-pick 550dc0d1969432180fead892cdb77a324ac53dd0.
=> fixed restart policy deserialization (#7006)

builds/e2e/connectivity.yaml, builds/e2e/e2e.yaml, builds/e2e/templates/lock-test-agents.yaml, builds/misc/packages-release.yaml, builds/misc/templates/build-packages.yaml
Cherry-pick b4e7b13342c6896464fbdf706f75ac0e963cf889.
=> Use up-to-date, maintained agent images in pipelines

builds/misc/packages-release.yaml, scripts/linux/publishReleasePackages.sh
Fix prod release pipeline to use PMC v4 properly
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes all the commits in the PR to a single commit. The net effect is that entire PR becomes a single commit. Please follow the best practices mentioned [here](https://chris.beams.io/posts/git-commit/#:~:text=The%20seven%20rules%20of%20a%20gr …
=> Fix prod release pipeline to use PMC v4 properly

edgelet/build/linux/package-mariner.sh
Update Mariner build golang to 1.20
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes all the commits in the PR to a single commit. The net effect is that entire PR becomes a single commit. Please follow the best practices mentioned [here](https://chris.beams.io/posts/git-commit/#:~:text=The%20seven%20rules%20of%20a%20great%20Git%20c …
=> Update Mariner's golang to 1.20

builds/misc/templates/build-packages.yaml, edgelet/Cargo.lock
- Update the Mariner builds to be using Ubuntu22.04 as it is the official supported version
- Update the Mariner builds to be using iot-identity-service with golang 1.20
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes all the commits in the PR to a single commit. The net effect is that entire PR becomes a single commit. Please …
=> Update Mariner builds and its IIS deps

edgelet/build/linux/package-mariner.sh
Update golang to 1.20 for Mariner build toolkit.
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes all the commits in the PR to a single commit. The net effect is that entire PR becomes a single commit. Please follow the best practices mentioned [here](https://chris.beams.io/posts/git-commit/#:~:text=The%20seven%20rules%20of%20a%20gr …
=> Update golang to 1.20 for Mariner build toolkit.

builds/misc/packages-release.yaml
Cherry-pick 6dce12b99f2aad976c9cde152ee6080f44f771f4 from the release/1.4 branch to main.
=> Sign DEB packages

builds/misc/packages-release.yaml, scripts/linux/publishReleasePackages.sh
Cherry-pick 5d3616e814abe9b99e0d9c441c49c6952c336911 and 42d857495311e7c1d9471fd7f6c7f6747565ec2b from release/1.4 to main.
=> Fix prod release pipeline to use PMC v4

builds/misc/images-release.yaml, builds/release/refresh-core-images.yaml, builds/release/templates/dotnet-code-sign.yaml
- Update ESRP codesign to be using the new AAD auth connection
- Upgrade ESRP from V1 to V3 …
=> Update ESRP Codesign 

builds/misc/images-release.yaml, builds/release/refresh-core-images.yaml, builds/templates/force-dotnet21.yaml, builds/templates/restore-default-dotnet.yaml
Cherry-pick 8740a08d8d76c0efb9d97cd49fb2aad45ed396c5.
=> Remove unneeded yaml template from codesign pipeline

scripts/linux/publishReleasePackages.sh
Cherry-pick 32086c539e5acdfe98f8a053ee5833982bfcc4d4.
=> Fix variable reference in packages release script

edgelet/contrib/debian/control
Cherry-pick from main of 37b36839739b7a19affed2b8605eb072a4ae9d44
Ref: Azure/iot-identity-service#578
=> Add psmisc dependency to Debian package since the postrm script uses it.

edge-modules/api-proxy-module/docker/linux/amd64/Dockerfile, edge-modules/api-proxy-module/docker/linux/arm32v7/Dockerfile, edge-modules/api-proxy-module/docker/linux/arm64v8/Dockerfile
Cherry-pick eb15b74921f3b573ef9ae3a2f82d473c3ad3fd8a
=> Update api proxy images

edgelet/contrib/snap/command-chain/drop-privileges.sh, snap/snapcraft.yaml
A couple fixes above and beyond #7200
=> Additional core22 migration

edgelet/contrib/snap/command-chain/drop-privileges.sh, edgelet/contrib/snap/command-chain/handle-exit-status-153.sh, snap/snapcraft.yaml
First pass at emulating the systemd RestartPreventExitStatus=153 behavior using snap's command chain.
This will want a rebase when #7204 is merged.
=> Snap exit status 153

edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/MqttProtocolHead.cs, test/modules/TestAnalyzer/Controllers/ReportController.cs
When the .NET 6 and .NET 8 SDKs are both installed on the build machine, the compiler reports some code analysis issues in our .NET 6.0 code. This change fixes the errors.
=> Fix code analysis errors

builds/e2e/e2e.yaml, builds/e2e/templates/e2e-clear-docker-cached-images.yaml
Cherry-pick 4605c1a9a488e6d2ed32926288952d6c1cca4580
=> Get service connection name from pipeline variable

edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/MqttProtocolHead.cs, edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs, edgelet/aziot-edged/Cargo.toml, edgelet/iotedge/Cargo.toml
I found two changes in the release branch that are not found in main:
- #6743 was ported from release/1.1
- #6807 originated in the release branch
=> Port changes from the release branch back to main

edgelet/aziot-edged/src/provision.rs
During startup, if aziot-edged encounters an error when obtaining the device identity, it will attempt to reprovision the device. Sometimes, if aziot-identityd has not fully started yet, aziot-edged will receive an OS "Connection refused" or similar error and attempt to reprovision.
Normally, the extra reprovision doesn't matter if the device is online. But in offline scenarios, attempting to reprovision will fail and put the device in a bad state.
This PR modifies the startup of aziot-edged so that only errors returned by Identity Service cause a reprovision. OS errors such as connection refused, permissions, etc. are ignored because they generally mean that Identity Service has not yet fully started.
=> aziot-edged: Only reprovision on Identity Service errors

scripts/linux/release-tools.sh
Cherry-pick 8c1493ac04cad298e9e1538eff32ee6c85b86d82
=> Update changelog creation in auto-refresh image releases

snap/snapcraft.yaml
Cherry-pick 00e96edd02b2f5867aae96951087dbe22418d89a
=> Fix snap builds

builds/service/service-deployment.yaml, test/Microsoft.Azure.Devices.Edge.Test.Common/linux/PackageManagement.cs
Cherry-pick d92581cc5e5534e35bbefa38bf4099e1b74dfdf4 from main, but adapt it to v1.4, which still uses .NET 6.
=> Fix svc deploy 1.4

builds/misc/templates/build-packages.yaml, edgelet/build/linux/package.sh, scripts/linux/cross-platform-rust-build.sh
Cherry-pick 152cd953e479c2fe36604685529fae513aa7d51e
=> Reduce pulls from docker.io

edgelet/Cargo.lock
Update iotedge to intake iot-identity service update:
https://github.com/Azure/iot-identity-service/commit/0351353d852f59a270c7e4cd585138ee00caa5d8
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes all the commits in the PR to a single commit. The net effect is that entire PR becomes a single commit. Please follow the best practices …
=> Update Identity Service Dependency

edge-modules/api-proxy-module/Cargo.lock, edge-modules/api-proxy-module/rust-sdk/azure-iot-mqtt/Cargo.lock, edge-modules/api-proxy-module/rust-sdk/azure-iot-mqtt/Cargo.toml, edge-modules/api-proxy-module/rust-sdk/azure-iot-mqtt/src/io.rs
This PR fixed CG High priority alert by upgrading tungstenite to the latest 0.20.1 version -
https://msazure.visualstudio.com/One/_workitems/edit/28226217
=> Update `tungstenite` version to 0.20.1

edge-modules/api-proxy-module/Cargo.lock, edge-modules/api-proxy-module/rust-sdk/azure-iot-mqtt/Cargo.lock, edge-modules/api-proxy-module/rust-sdk/azure-iot-mqtt/Cargo.toml, edge-modules/api-proxy-module/rust-sdk/azure-iot-mqtt/src/io.rs
This PR fixed CG High priority alert by upgrading tungstenite to the latest 0.20.1 version -
https://msazure.visualstudio.com/One/_workitems/edit/28226217
Backported from #7305
=> Update tungstenite version (release/1.4)

edge-modules/api-proxy-module/Cargo.lock, edge-modules/api-proxy-module/rust-sdk/azure-iot-mqtt/Cargo.lock, edge-modules/edgehub-proxy/Cargo.lock, edgelet/Cargo.lock, test/rust-test-util/test-result-reporting-client/Cargo.lock
This PR fixed CG High priority alert by upgrading mio to the latest 0.8.11 version - https://msazure.visualstudio.com/One/_workitems/edit/27057941
=> Update 'mio' to the latest version

builds/e2e/templates/nested-get-root-ca.yaml, builds/e2e/templates/nested-get-secrets.yaml
Cherry-pick fda209887337cac32fd8b24f05b4582a67b53a46
=> Use AzureCLI task to download blob

builds/e2e/templates/e2e-setup.yaml
Straight cherry-pick of https://github.com/Azure/iotedge/pull/7309
=> Use SAS tokens to get an identity in E2E tests (cherry-pick of #7309)

builds/checkin/e2e-checkin.yaml, builds/e2e/e2e.yaml, builds/e2e/templates/e2e-run.yaml, builds/e2e/templates/e2e-setup.yaml, builds/e2e/templates/get-storage-uri.yaml
Straight cherry-pick of https://github.com/Azure/iotedge/pull/7331
=> Move storage URI generation to a template so agents don't need to be updated with azcli 2.x (#7331)

builds/e2e/connectivity.yaml, builds/e2e/templates/connectivity-deploy.yaml, builds/e2e/templates/get-storage-uri.yaml, e2e_deployment_files/connectivity_deployment.template.json, scripts/linux/trcE2ETest.sh, test/modules/TestResultCoordinator/Services/TestResultReportingService.cs, test/modules/TestResultCoordinator/Settings.cs
Straight cherry-pick of https://github.com/Azure/iotedge/pull/7313
=> Use SAS tokens to get an identity in Connectivity tests (Cherry-pick #7313)

builds/e2e/nested-e2e.yaml
Straight cherry-pick of https://github.com/Azure/iotedge/pull/7339
=> Add token support for nested E2E

edgelet/contrib/snap/socat.sh, snap/snapcraft.yaml, test/Microsoft.Azure.Devices.Edge.Test.Common/linux/PackageManagement.cs
Cherry-pick 80e3465c70a79893561a4b8ba432e0d5a37ace65 and 490aea6c4717b123bf12a956eddd75b56245e19b
=> Fix docker-proxy startup issues

CHANGELOG.md, edgelet/Cargo.lock
Update the 1.4.41 release to include last-minute snap fixes.
=> Update the 1.4.41 release

builds/checkin/dotnet.yaml, builds/checkin/edgelet.yaml, builds/ci/dotnet.yaml, builds/e2e/compare-compatibility.yaml, builds/e2e/connectivity.yaml, builds/e2e/templates/e2e-setup.yaml, builds/e2e/templates/longhaul-setup.yaml, builds/e2e/templates/nested-get-secrets.yaml, builds/misc/templates/build-packages.yaml, builds/service/service-deployment.yaml
Cherry-pick 95cabb51436be79332d8244c7232201b84a047a9, as well as changes to the code coverage task in builds/checkin/edgelet.yaml from 5b7d20f8ad2edf5219f43595430772f4e4919d13.
=> Upgrade deprecated pipeline tasks

builds/checkin/dotnet.yaml
Cherry-pick aaba3b92b71b6f4309a52034e6ceb0c5ceeb911b
=> Remove just-in-time install of code coverage report generator tool

edge-modules/api-proxy-module/docker/linux/amd64/Dockerfile, edge-modules/api-proxy-module/docker/linux/arm32v7/Dockerfile, edge-modules/api-proxy-module/docker/linux/arm64v8/Dockerfile
Updates the api-proxy module alpine and nginx images to use latest supported images.
=> Update versions of api-proxy dependencies
