Azure/iotedge

- mqtt/mqtt-policy/src/substituter.rs
- mqtt/mqtt-policy/src/validator.rs
This PR fixes the issue where multiple vars in a string in policy definition didn't work.
> Fixed multiple vars issue in policy definition

- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/DeviceProxy.cs
- edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/DeviceProxyTest.cs
This is  quick fix to the issue that direct clients (e.g. devices, modules) use a different dialect sending their messages (e.g. twin update) than messages connecting indirectly, where the broker/bridge transforms their topics to have identity information a consistent structure for multilevel messaging.
When a client connects "indirectly" (meaning that the fact of the connection will be noticed by not by the connected client events published by the broker, but that the clients send messages without prior connection), they get a flag, so when edgeHub sends mqtt messages to them, it uses the right dialect.
Child $edgeHub is an exception - the bridge uses its identity to connect, so the parent will receive a connection attempt and sets the flag for $edgeHub as a directly connecting device. …
> handle child $edgeHub as indirect client

- mqtt/mqtt-bridge/src/client.rs
- mqtt/mqtt-bridge/src/controller.rs
- mqtt/mqtt-bridge/src/messages.rs
- mqtt/mqtt-bridge/src/pump/ingress.rs
- mqtt/mqtt-bridge/src/pump/mod.rs
- mqtt/mqtt-bridge/src/upstream/events/remote.rs
- mqtt/mqtt-bridge/src/upstream/mod.rs
- mqtt/mqtt-bridge/src/upstream/rpc/local.rs
- mqtt/mqtt-bridge/src/upstream/rpc/mod.rs
- mqtt/mqtt-bridge/src/upstream/rpc/remote.rs
Implemented missed subscriptions to RPC command topic from Local Pump event handler. 
Refactor to **automatically** subscribe to default topics for both Pumps subscriptions from default settings and for RPC command
> [mqtt] Pump subscribes to initial topics for  (#3828)

- edgelet/edgelet-core/src/certificate_properties.rs
- edgelet/edgelet-http-workload/src/server/cert/identity.rs
- edgelet/edgelet-http-workload/src/server/cert/mod.rs
- edgelet/edgelet-http-workload/src/server/cert/server.rs
Server and identity certificates had their FQDNs incorrectly sanitized (dot character removed). Also, IPs were being dropped in certificate properties.
The method names have been refactored to match intent as well.
> Fixes for certificate properties

- edge-modules/iotedge-diagnostics-dotnet/src/Program.cs
There were 2 problems: 
* The diagnostics module was checking the body for the status code in addition to the headers. This is because in the socket case the entire response is read as a string, unlike the http case. This mistaken check was removed
* The uri to check was sometimes passed in with a trailing `/`. This extra `/` is now trimmed.
> Fix iotedge check for http endpoints

- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/ClientConnectionHandler.cs
- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/EdgeHubConnection.cs
- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/device/DeviceMessageHandler.cs
- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/device/IDeviceProxy.cs
- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/DeviceProxy.cs
- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/DeviceProxy.cs
- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/handlers/ConnectionHandler.cs
When a client connects/disconnects to the broker, the broker sends a connected client list. EdgeHub uses this list and compares with its state. When edgeHub has a connection in its registry, but the broker does not send that connection in its event, edgeHub removes the connection.
When a client connects through a child device, edgeHub creates a connection for that client when it first does something (e.g. sends a telemetry message or subscribes). That is because nothing else shows edgeHub that there was a connected client. A parent broker does not send connected events about devices from child edge devices.
It also means that when a broker sends the list of the connected devices, that list does not contain the indirectly connected devices. Because edgeHub reconciles this list with its own …
> fix: don't delete indirect client connections on broker connected events

- mqtt/mqtt-edgehub/src/auth/authorization/edgehub.rs
- mqtt/mqtt-edgehub/tests/authorization.rs
- mqtt/mqttd/src/broker/bootstrap/edgehub.rs
When we introduced on-behalf-of authorization logic, we had a wrong assumption about iothub topic structure.
- expected: `$iothub/clients/<device_id/modules/<module_id>/twin/get`
- actual: `$iothub/<device_id/<module_id>/twin/get`
Since the actual format does not contain useful "markers" (`clients`, `modules`), we can't simply split the string and extract device id and module id. We have to use regex now. As a result, the current logic for validation and caching of iothub topics is no longer needed, b/c Regex covers it.
Also, two more checks were added for the on-behalf-of scenario: 
- check that actor_id is in the auth chain for current edgehub.
- check that client_id is in the auth chain for current edgehub.
> Fixed on-behalf-of authorization

- mqtt/mqtt-edgehub/src/auth/authorization/edgehub.rs
- mqtt/mqtt-edgehub/tests/authorization.rs
- mqtt/mqttd/src/broker/bootstrap/edgehub.rs
When we introduced on-behalf-of authorization logic, we had a wrong assumption about iothub topic structure.
- expected: `$iothub/clients/<device_id/modules/<module_id>/twin/get`
- actual: `$iothub/<device_id/<module_id>/twin/get`
Since the actual format does not contain useful "markers" (`clients`, `modules`), we can't simply split the string and extract device id and module id. We have to use regex now. As a result, the current logic for validation and caching of iothub topics is no longer needed, b/c Regex covers it.
Also, two more checks were added for the on-behalf-of scenario: 
- check that actor_id is in the auth chain for current edgehub.
- check that client_id is in the auth chain for current edgehub.
> Fixed on-behalf-of authorization (#3874)

- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/appsettings_hub.json
- edge-hub/watchdog/src/main.rs
Nested env vars need to use double-underscore to denote levels (instead of colon) for consistent behavior across all platforms.  EdgeHub core already handles this implicitly via the ConfigurationBuilder, but the Rust implementation is trying to match the raw env var key string.
> Fix MQTT broker feature flags for ARM

- edge-modules/iotedge-diagnostics-dotnet/src/GetSocket.cs
- edge-modules/iotedge-diagnostics-dotnet/src/Program.cs
Cherry-pick #3871 
> There were 2 problems: 
> * The diagnostics module was checking the body for the status code in addition to the headers. This is because in the socket case the entire response is read as a string, unlike the http case. This mistaken check was removed
> * The uri to check was sometimes passed in with a trailing `/`. This extra `/` is now trimmed.
There is an additional fix for windows. When adding proxy support, I didn't realize windows could use unix domain sockets, so the check didn't work correctly for those. Check would error and say `(Only 'http' and 'https' schemes are allowed. (Parameter 'requestUri'))`. It works correctly now.
> Check fix 110

- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/handlers/SubscriptionChangeHandler.cs
Left a 'break' in the code when changed handling client specific subscriptions to 'in the name of' subscriptions. In case of client specific subscription it did not happen that a subscription list contained subscription to an operation (e.g. direct method), so once a fit found, breaking the loop had performance benefits.
In case of 'in the name of' subscriptions in can happen that edgeHub subscribes to direct method in the name of client_a and client_b, having two subscriptions with the same nature. 
The forgotten break exited the loop and the second subscription was not processed.
> remove early break from subscription processing

- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/brokerConnection/IMqttBrokerConnector.cs
- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/brokerConnection/MqttBrokerConnector.cs
- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/handlers/BrokerConfigUpdateHandler.cs
- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/handlers/ScopeIdentitiesHandler.cs
- edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/Cloud2DeviceMessageHandlerTest.cs
- edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/ConnectionHandlerTests.cs
- edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/DirectMethodHandlerTest.cs
- edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/MessageConfirmingBase.cs
- edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/ModuleToModuleMessageHandlerTest.cs
- edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/ScopeIdentitiesHandlerTest.cs
- edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/TwinHandlerTest.cs
- mqtt/mqtt-edgehub/tests/authorization.rs
Bridge, policy and identities must be sent as retained messages to the broker.
> Broker config must be sent as a retained message.

- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/brokerConnection/IMqttBrokerConnector.cs
- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/brokerConnection/MqttBrokerConnector.cs
- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/handlers/BrokerConfigUpdateHandler.cs
- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/handlers/ScopeIdentitiesHandler.cs
- edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/Cloud2DeviceMessageHandlerTest.cs
- edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/ConnectionHandlerTests.cs
- edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/DirectMethodHandlerTest.cs
- edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/MessageConfirmingBase.cs
- edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/ModuleToModuleMessageHandlerTest.cs
- edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/ScopeIdentitiesHandlerTest.cs
- edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/TwinHandlerTest.cs
- mqtt/mqtt-edgehub/tests/authorization.rs
Bridge, policy and identities must be sent as retained messages to the broker.
> Broker config must be sent as a retained message. (#3887)

- mqtt/mqtt-bridge/src/messages.rs
- mqtt/mqtt-bridge/src/settings.rs
- mqtt/mqtt-bridge/tests/config.json
when inPrefix or outPrefix are empty string it should work as None.
Note: I think would be nicer just to deserialize "" as None, but couldn't make it work with custom deserialization when field was missing. For now will go with this fix and will try in the meantime with custom deserialization
> bridge topics fix when inPrefix or outPrefix are empty

- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/ServiceIdentityDictionary.cs
When nested edge is turned off, there's no concept of auth-chains because all identities are immediate children of the Edge device.  But edgehub authorizer (in the broker) needs auth-chains to work even in the single-node configuration, so this change adds logic to construct simple auth chains for the children in the legacy code path.
> Construct valid auth-chains for children for non-nested mode

- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/ServiceIdentityDictionary.cs
When nested edge is turned off, there's no concept of auth-chains because all identities are immediate children of the Edge device.  But edgehub authorizer (in the broker) needs auth-chains to work even in the single-node configuration, so this change adds logic to construct simple auth chains for the children in the legacy code path.
> Construct valid auth-chains for children for non-nested mode (#3892)

- mqtt/mqttd/src/app/edgehub.rs
- mqtt/mqttd/src/lib.rs
- mqtt/mqttd/src/time.rs
When the server certificate expiration date is longer than 2y interval `tokio::time::delay_for` panics when try to schedule waiting.
`tokio::time::delay_for` and `tokio::time::delay_until` has a bug that prevents to schedule a very long timeout (more than 2 years). To mitigate this issue we split a long interval by the number of small intervals and schedule small intervals and waits for a small one until we reach a target.
> [mqtt] Fix certificate renewal timer

- mqtt/mqttd/src/app/edgehub.rs
- mqtt/mqttd/src/lib.rs
- mqtt/mqttd/src/time.rs
When the server certificate expiration date is longer than 2y interval `tokio::time::delay_for` panics when try to schedule waiting.
`tokio::time::delay_for` and `tokio::time::delay_until` has a bug that prevents to schedule a very long timeout (more than 2 years). To mitigate this issue we split a long interval by the number of small intervals and schedule small intervals and waits for a small one until we reach a target.
cherry-pick `83f750a`
> [mqtt] Fix certificate renewal timer (#3897)

- mqtt/mqtt-broker/src/persist.rs
- mqtt/mqtt-broker/src/proptest.rs
- mqtt/mqtt-broker/src/session/identifiers.rs
I found that most of the time is spent in input generation, so I reduced it.
On my box this reduced persistence proptests from from ~72s to ~14s.
> Speedup persist proptest

- mqtt/mqtt-bridge/src/messages.rs
- mqtt/mqtt-bridge/src/settings.rs
- mqtt/mqtt-bridge/tests/config.json
cherry-pick from release/1.2
when inPrefix or outPrefix are empty string it should work as None.
Note: I think would be nicer just to deserialize "" as None, but couldn't make it work with custom deserialization when field was missing. For now will go with this fix and will try in the meantime with custom deserialization
> bridge topics fix when inPrefix or outPrefix are empty (#3893)

- mqtt/mqtt-edgehub/src/settings.rs
replace : with __
Todo: make the change in master to only use new env variables format in broker without converting
> mqtt broker align env variables

- edge-modules/iotedge-diagnostics-dotnet/src/Program.cs
fix for iotedge check.
Test performed:
With proxy nested
On golden path setup, lvl 3: Ran iotedge check with new diagnostic image:
× container on the default network can connect to upstream HTTPS / WebSockets port - Error
× container on the IoT Edge module network can connect to upstream HTTPS / WebSockets port - Error
Upgrade lvl 4 with new edgehub that returns new header:
√ host can connect to and perform TLS handshake with upstream HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to upstream HTTPS / WebSockets port - OK
Without proxy nested
On golden path setup, lvl 4: Ran iotedge check with new diagnostic image:
× container on the default network can connect to upstream HTTPS / WebSockets port - Error
× container on the IoT Edge module network can …
> fix for iotedge check

- mqtt/mqtt-edgehub/src/settings.rs
cherry pick from release/1.2
replace : with __
Todo: make the change in master to only use new env variables format in broker without converting
> mqtt broker align env variables (#3916)

- edge-modules/api-proxy-module/readme.md
* Fix default port and remove inexistent env var
* 443 default
* typo
Co-authored-by: hugues bouvier <33438817+huguesBouvier@users.noreply.github.com>
> Fix default port and remove inexistent env var (#3919)

- mqtt/policy/src/core/mod.rs
**Scenario:**
- Have a policy with a custom identity matcher.
- Have two variable rules (deny and allow) for an identity, such that  both rules match a given request identity.
- But the two rules must be different in resources.
- The deny rule resources do not match the request.
- The allow rule resources do match the request.
Expected: "allow" the request.
**Fix:**
- The problem was in early return from a `eval_variable_rules` func, instead of going through all variable rules that match the identity.
> Fixed an issue where not all variable rules are evaluated

- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/authentication/AuthAgentController.cs
- mqtt/mqtt-broker/src/auth/mod.rs
- mqtt/mqtt-edgehub/src/auth/authorization/edgehub.rs
- mqtt/mqtt-edgehub/tests/authorization.rs
- mqtt/mqttd/src/app/edgehub.rs
When broker sends an authentication request to EH Core, it gets back the identity name without hub name prefix. As a result, customers have to use just device name in the policy engine, instead of FQN for device:
**Current:**
```
{
"identities": [
**"vakavali_leaf"**
],
"allow": [
{
"operations": [
"mqtt:publish",
"mqtt:subscribe"
],
"resources": [
"#"
]
}
]
}
```
**Expected:**
```
{
"identities": [
**"mytesthub.azure-devices.net/vakavali_leaf"**
],
"allow": [
{
"operations": [
"mqtt:publish",
"mqtt:subscribe"
],
"resources": [
"#"
]
}
]
}
```
**Notes:**
This is a quick fix solution. We may revisit it when we have story for local identities ready.
> MQTT: Use FQN for the authenticated identity

- test/modules/MetricsValidator/src/tests/ValidateDocumentedMetrics.cs
Fixing `edgeAgent_created_pids_total` for ValidateMetric
> Fixing edgeAgent_created_pids_total for ValidateMetric

- edge-modules/iotedge-diagnostics-dotnet/src/GetSocket.cs
When checking the workload api from a container, Windows needs to remove a leading /. Linux doesn't, and removing the / caused it to incorrectly fail. 
To fix this, the Uri class is used to correctly localize the path.
> Fix Linux Check

- test/modules/MetricsValidator/src/tests/ValidateDocumentedMetrics.cs
Fixing `edgeAgent_created_pids_total` for ValidateMetric
> Fixing edgeAgent_created_pids_total for ValidateMetric (#3944)

- edgelet/dps/src/dps.rs
- edgelet/dps/src/lib.rs
- edgelet/dps/src/registration.rs
- edgelet/provisioning/src/provisioning.rs
This commit replaces the "deviceDataUpdated" speculatively added by
1750d178585c1ae69c33893e6e7d15e1269e376b with the actual substatus that
DPS has added. The semantics are still the same.
> Recognize the new DPS registration substatus that indicates cloud identity did not change.

- edge-modules/api-proxy-module/templates/nginx_default_config.conf
nginx was resolving local hostname at startup. This would cause problem if the edgeHub or registry or blob storage was killed during run time.
If one of those container was killed and api proxy left running, then the container could come ack with a different IP and nginx would need to be restarted.
Fixing: https://msazure.visualstudio.com/One/_queries/edit/8682859/?triage=true
> Removing fix resolution for local hostnames

- mqtt/mqtt-edgehub/Cargo.toml
- mqtt/mqtt-edgehub/tests/translation.rs
There was a bug in feature declaration and translation integration tests did not compile and run for a while. 
The fix is:
- Add optional `proptest` dependency to `mqtt-edgehub` package. That will enable `proptest` feature.
- Import  `mqtt-broker` with `features = ["proptest"]` as a dev-dependency in `mqtt-edgehub`.
The rest of the changes is just to make tests compile after all the recent changes.
> Enable topic translation tests

- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/ModuleToModuleResponseTimeout.cs
- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/handlers/ModuleToModuleMessageHandler.cs
- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/MqttBrokerModule.cs
- edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/ModuleToModuleMessageHandlerTest.cs
- mqtt/mqtt-edgehub/src/auth/authorization/edgehub.rs
- mqtt/mqtt-edgehub/src/connection/delivery.rs
- mqtt/mqtt-edgehub/src/topic/translation.rs
- mqtt/mqtt-edgehub/tests/authorization.rs
- mqtt/mqtt-edgehub/tests/delivery.rs
- m2m pending confirmations are stored by lockToken not by identity - allowing multiple pending messages by identity
- fixed race condition when confirmation message gets back sooner than lockToken gets stored
m2m pending messages were stored by identity - it worked most of the time because only one message is getting sent to a client. However when that message timeouts a new message will be sent, overwriting the previous pending message. This caused problems when the old message with the timeout got confirmed, because edgeHub believed that it was the recent message. With this change every messageId (lockToken) is saved, so feedbacks cannot be mismatched.
Also there was a race condition when the lock token of the sent out message was stored after the 'send' call. It could happened that …
> Improving M2M feedback handling (#3960)

- mqtt/policy/src/core/mod.rs
**Scenario:**
- Have a policy with a custom identity matcher.
- Have two variable rules (deny and allow) for an identity, such that  both rules match a given request identity.
- But the two rules must be different in resources.
- The deny rule resources do not match the request.
- The allow rule resources do match the request.
Expected: "allow" the request.
**Fix:**
- The problem was in early return from a `eval_variable_rules` func, instead of going through all variable rules that match the identity.
> Fixed an issue where not all variable rules are evaluated (#3938)

- mqtt/mqtt-edgehub/Cargo.toml
- mqtt/mqtt-edgehub/tests/translation.rs
There was a bug in feature declaration and translation integration tests did not compile and run for a while. 
The fix is:
- Add optional `proptest` dependency to `mqtt-edgehub` package. That will enable `proptest` feature.
- Import  `mqtt-broker` with `features = ["proptest"]` as a dev-dependency in `mqtt-edgehub`.
The rest of the changes is just to make tests compile after all the recent changes.
> Enable topic translation tests (#3961)

- test/Microsoft.Azure.Devices.Edge.Test/AuthorizationPolicy.cs
A recent change in how we handle identities in the policy engine (#3945) broke the e2e tests. Needed to update the test.
> Fixed e2e tests after recent changes

- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/authentication/AuthAgentController.cs
- mqtt/mqtt-broker/src/auth/mod.rs
- mqtt/mqtt-edgehub/src/auth/authorization/edgehub.rs
- mqtt/mqtt-edgehub/tests/authorization.rs
- mqtt/mqttd/src/app/edgehub.rs
When broker sends an authentication request to EH Core, it gets back the identity name without hub name prefix. As a result, customers have to use just device name in the policy engine, instead of FQN for device:
**Current:**
```
{
"identities": [
**"vakavali_leaf"**
],
"allow": [
{
"operations": [
"mqtt:publish",
"mqtt:subscribe"
],
"resources": [
"#"
]
}
]
}
```
**Expected:**
```
{
"identities": [
**"mytesthub.azure-devices.net/vakavali_leaf"**
],
"allow": [
{
"operations": [
"mqtt:publish",
"mqtt:subscribe"
],
"resources": [
"#"
]
}
]
}
```
**Notes:**
This is a quick fix solution. We may revisit it when we have story for local identities ready.
> MQTT: Use FQN for the authenticated identity (#3945)

- builds/checkin/mqtt.yaml
- builds/ci/mqtt.yaml
- mqtt/build/linux/test.sh
Rust tests don't have native test results support in Azure Pipelines. In this PR I want to add [a 3rd party tool](https://github.com/johnterickson/cargo2junit) that converts cargo test output into junit format (Azure Pipelines compatible). As a result, we can enjoy test stats, can see flaky tests, trends.
Drawbacks:
- We have to use unstable cargo feature to generate json output. I believe this should not be a problem, since it does not affect production bits, but only tests.
- Console output in the pipeline becomes less readable, but not that bad, and still searchable. Can use "Tests" tab instead!
Another minor improvements in this PR:
- Don't checkout submodules for MQTT Broker. It doesn't use any.
- Shallow clone (speeds up checkout x4)
- Removed Style Check task from MQTT CI. I can …
> Added Publish Test Results task to MQTT Pipelines + other pipeline improvements

- edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/versioning/ModuleManagementHttpClientVersioned.cs
This was a simple fix. 
~~The new e2e tests currently do not test the http configuration for mgmt and workload sockets, so there may be a follow up to add tests.~~
Since http is not officially supported for mgmt and workload sockets, no tests will be added.
> GetModuleLogs works with http endpoints

- mqtt/mqtt-broker-tests-util/src/server.rs
- mqtt/mqtt-edgehub/tests/common/mod.rs
- mqtt/mqtt-edgehub/tests/edgehub_authorizer.rs
- mqtt/mqtt-edgehub/tests/policy_authorizer.rs
Our authorizers (EdgeHub and Policy) integraiton tests are flacky, because there were no way to deterministically wait until authorizer processes the update.
As a fix, instead of using time delay to wait for authorizer update (which is not deterministic way) , I have introduced a channel in `DummyAuthorizer` that signals when an update happens.
> MQTT Authz: Reduce test flakiness

- test/Microsoft.Azure.Devices.Edge.Test/AuthorizationPolicy.cs
I noticed that one of the policy e2e tests is flaky. 
The goal of the test is to verify that we can update the policy "on the fly".
Previous version of the test was unstable b/c there is no reliable way to notify the test when policy update actually finished, and when DeviceClient tries to connect again, it can still be authorized (when exception is expected) because new policy did not take effect.
So I'm changing a logic to be the opposite: 
- initial deployment denies the connection for device1
- DeviceClient for device1 tries to connect and fails (expected exception)
- update the deployment to allow the connection for device2
- DeviceClient for device2 is able to connect. (And this is the trick, since DeviceClient has retry strategy, it will retry until policy is updated and takes …
> Try to stabilize policy engine e2e tests.

- mqtt/policy/src/core/builder.rs
- mqtt/policy/src/core/mod.rs
This is a small refactoring to policy engine internals. No functional changes. Just addressing some feedback from previous PRs.
Before:
We had two similar enums:
- `Effect` (used in `PolicyDefinition`)
- `EffectImpl` - internal struct for calculating the policy decision. Very similar to `Effect` but had additional `Undefined` variant.
Now:
- Instead of `Undefined` variant, I can use `Option<Effect>`. So `EffectImpl` can be retired.
> Policy engine: getting rid of EffectImpl

- test/Microsoft.Azure.Devices.Edge.Test/AuthorizationPolicy.cs
Second attempt...
The goal of the test is to verify that we can update the policy "on the fly".
Previous version of the test was unstable b/c there is no reliable way to notify the test when policy update actually finished, and when DeviceClient tries to connect again, it can still be unauthorized.
So I've introduced explicit retry policy, b/c default retry policy in the `DeviceClient` does not handle authN/authZ exceptions.
> Try to stabilize policy e2e tests.

- .config/CredScanSuppressions.json
- edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.IoTHub.Test/ModuleIdentityLifecycleManagerTest.cs
- edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/ImagePullSecretTest.cs
- edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.Http.Test/DeviceScopeControllerTest.cs
- edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/AuthAgentListenerTest.cs
- edge-util/test/Microsoft.Azure.Devices.Edge.Util.Test.Common/CertificateHelper.cs
Several synthetic secrets have been added over time to the tests. This change updates the suppressions list to silence the associated CredScan errors.
I used inline suppression where possible to co-locate the suppression with the corresponding code, except in a few cases where I added the suppression to `.config/CredScanSuppressions.json`:
- A synthetic password in a JSON file. Although CredScan supports comments in JSON, I'm not sure about our test pipeline.
- A PEM file checked into the repo and used by the mqtt-broker tests. Again, CredScan supports suppression comments in PEM files, but I don't understand the ramifications to the test pipeline.
- A synthetic password in some markdown files from our submodules. We can't control the submodules, so I suppressed the files. CredScan docs …
> Add CredScan suppressions

- edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/versioning/ModuleManagementHttpClientVersioned.cs
This was a simple fix. 
~~The new e2e tests currently do not test the http configuration for mgmt and workload sockets, so there may be a follow up to add tests.~~
Since http is not officially supported for mgmt and workload sockets, no tests will be added.
> GetModuleLogs works with http endpoints (#3908)

- test/Microsoft.Azure.Devices.Edge.Test/Metrics.cs
- test/modules/MetricsValidator/src/tests/ValidateDocumentedMetrics.cs
Currently the `ValidateMetrics` parses [metric readme page](https://github.com/Azure/iotedge/blob/master/doc/BuiltInMetrics.md) to obtain all the metric keys. The test then deploy the system runtime modules and populate its metrics which then are compared against the parsed-document set.
There are a handful of not-so-positive metrics that are not being populated if the system modules operated on a happy path during the E2E test. These not-so-positive metrics are currently causing the `ValidateMetrics` to fail since they are not being populated.
Cherry-picked: https://github.com/Azure/iotedge/commit/f443dde70a7aea9ad6716cf61cc66f89b6642783
> Fixing ValidateMetrics E2E (#3767)

- edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/storage/MessageStore.cs
- edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/storage/MessageStoreTest.cs
Cherry-picking from main branch
This PR fixes a bug in product code where the cleanup task in MessageStore.cs can potentially start before all of its settings are set, resulting in it taking default values for its settings.
Also re-enables the MultipleTTL test in MessageStoreTest.cs and makes it run with polling vs a delay, which will speed up the test.
> Cherry-pick Fix multiple TTL test to release/1.0.10 branch (#4037)

- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/storage/MessageStore.cs
- edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/storage/MessageStoreTest.cs
Cherry-picking from main branch
This PR fixes a bug in product code where the cleanup task in MessageStore.cs can potentially start before all of its settings are set, resulting in it taking default values for its settings.
Also re-enables the MultipleTTL test in MessageStoreTest.cs and makes it run with polling vs a delay, which will speed up the test.
> Cherry-pick Fix multiple TTL test to release/1.2 branch (#4037)

- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/authentication/AuthAgentController.cs
- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/authentication/AuthAgentProtocolHead.cs
- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/AuthModule.cs
- edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/AuthAgentListenerTest.cs
Cherry-pick https://github.com/Azure/iotedge/commit/e0ae1c645eec8ab8e591ac125951745d2b2c6063
This PR enables PlugAndPlay through the broker by storing any given ModelId for the identity in the MetadataStore when that identity is authenticated by EdgeHub Core. The broker will ask EH Core for authentication, and the EH Core's AuthAgentProtocolHead will do the authentication and store the ModelId in the MetadataStore, if is authenticated.
The metadataStore is already checked for a ModelId when EH is connecting to the cloud on behalf of an identity, so no change is needed there.
This change does NOT enable PlugAndPlay for the Mqtt Bridge, so nested scenario + Mqtt broker will NOT work yet. More work will need to be done to send the ModelId (and all of the username add-ons) upstream through …
> Cherry-pick Enable PlugAndPlay for MQTT broker (#4028) from main branch to release/1.2

- edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.E2E.Test/StoreLimitsTestBase.cs
Cherry-pick from main branch to 1.2
https://github.com/Azure/iotedge/pull/4048
InMemoryDbStoreLimitsTest is flaky in the CI pipeline. I believe it is because we overuse the "sender1" name. The test keeps failing on "Amqp resource is disconnected," which I think we get because we're trying to access an AMQP resource that has previously closed. This would make sense if we are using the "sender1" name somewhere else around the same time.
So this pr just changes the name to be more specific to the test. I've run it ~8 times in the pipeline and haven't seen the failure, so it looks like it solves the problem.
> Cherry-Pick to 1.2: Fix InMemoryDbStoreLimitsTest (#4048)

- test/Microsoft.Azure.Devices.Edge.Test/PlugAndPlay.cs
Cherry-pick from main branch to release/1.2
https://github.com/Azure/iotedge/pull/4046
We just enabled PlugAndPlay for the MQTT broker. This PR adds e2e tests for this scenario
Also adding in AMQP tests for broker while I'm at it.
> Cherry-pick to 1.2: PlugAndPlay broker e2e tests (#4046)

- edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.E2E.Test/StoreLimitsTestBase.cs
Cherry-pick from main branch to 1.0.10
InMemoryDbStoreLimitsTest is flaky in the CI pipeline. I believe it is because we overuse the "sender1" name. The test keeps failing on "Amqp resource is disconnected," which I think we get because we're trying to access an AMQP resource that has previously closed. This would make sense if we are using the "sender1" name somewhere else around the same time.
So this pr just changes the name to be more specific to the test. I've run it ~8 times in the pipeline and haven't seen the failure, so it looks like it solves the problem.
> Cherry-pick to 1.0.10: Fix InMemoryDbStoreLimitsTest (#4048)

- builds/misc/images-mqtt.yaml
- mqtt/docker/linux/amd64/Dockerfile
- mqtt/docker/linux/arm32v7/Dockerfile
~~Since we use `busybox` as a base image for generic mqtt broker (used in perf tests), we need to use `alpine` and `armv7-unknown-linux-musleabihf` for building the image. If we try to build for `armv7-unknown-linux-gnueabihf`, it will fail to start on `busybox` since glibc is missing.~~
We need to align base images for mqtt perf tests with what we use in production.
> Align base images for mqtt perf tests with production images.

- test/Microsoft.Azure.Devices.Edge.Test/PlugAndPlay.cs
- test/Microsoft.Azure.Devices.Edge.Test/helpers/Context.cs
- test/Microsoft.Azure.Devices.Edge.Test/helpers/ManualProvisioningFixture.cs
- test/Microsoft.Azure.Devices.Edge.Test/helpers/SasManualProvisioningFixture.cs
- test/README.md
Cherry-picking part of this commit from main branch to 1.0.10: https://github.com/Azure/iotedge/pull/4064
This PR cleans up workarounds that were put in when the PlugAndPlay tests were first made.
Previously, we needed to use a preview version of IoTHub that supported PnP. Since then, they've gone GA, and we can use our normal IoTHub and normal EventHub endpoint.
> Removing preview iothub and eventhub endpoint from PnP tests for 1.0.10

- builds/misc/images-mqtt.yaml
- builds/misc/templates/consolidate-edgehub-artifacts.yaml
- builds/misc/templates/copy-rust-binaries.yaml
- edge-hub/docker/linux/amd64/Dockerfile
- edge-hub/docker/linux/arm32v7/Dockerfile
- edge-hub/docker/linux/arm64v8/Dockerfile
I thought I made this optimization a while ago when I did it for the mqtt image build, but I forgot. This change will copy only the executable into the build context instead of the whole target folder. This reduces the build context size and will trim some time off the build pipeline.
> Build Pipeline Optimization: Move only the rust executable into build context

- test/Microsoft.Azure.Devices.Edge.Test.Common/LeafDevice.cs
- test/Microsoft.Azure.Devices.Edge.Test/AuthorizationPolicy.cs
There was another issue in Policy tests that make them flaky. `LeafDevice.CreateAsync` appears to be not idempotent, so there is a race condition, when LeafDevice tries to connect before the policy is updated, and in case of failed authorization, it tries to delete and re-create the device. That screws up cached symmetric keys in EH. And since EH does not refresh the device scopes (and keys) more often that 2min, the test fails after several retries.
The solution is to not to use `LeafDevice` - not to remove the device in case of authorization error, but just retry again.
> Fix policy test flakiness

- mqtt/mqtt-edgehub/src/settings.rs
- mqtt/mqttd/src/app/edgehub.rs
cherry pick from 7f5c92d4c1d69a02363b27d7183bdd7400a219a1
Currently, the user is free to change whatever environment variables they want from the edgeHub container environment variables. This PR scopes it down to 4 public ones:
mqttBroker__max_queued_messages
mqttBroker__max_queued_bytes
mqttBroker__max_inflight_messages
mqttBroker__when_full
These are now the only broker variables that a user can set for the broker from the edgeHub container. The others are taken from the default config file we have hard coded into the broker.
We use the config::Source trait to accomplish the env var mapping
> Cherry pick to 1.2 lock in broker environment variables

- test/Microsoft.Azure.Devices.Edge.Test.Common/LeafDevice.cs
- test/Microsoft.Azure.Devices.Edge.Test/AuthorizationPolicy.cs
There was another issue in Policy tests that make them flaky. `LeafDevice.CreateAsync` appears to be not idempotent, so there is a race condition, when LeafDevice tries to connect before the policy is updated, and in case of failed authorization, it tries to delete and re-create the device. That screws up cached symmetric keys in EH. And since EH does not refresh the device scopes (and keys) more often that 2min, the test fails after several retries.
The solution is to not to use `LeafDevice` - not to remove the device in case of authorization error, but just retry again.
> Fix policy test flakiness (#4110)

- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/authentication/AuthAgentProtocolHead.cs
- edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/AuthAgentListenerTest.cs
- edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/MqttBrokerConnectorTest.cs
- edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/MqttBrokerProtocolHeadTest.cs
`MqttMiniServer` had multiple places with loops that try to make a progress forever even when the client disconnected.
`AuthProtocolHead.CloseAsync` method calls `IWebHost.StopAsync` which blocks not only the execution of the current test but also other tests that were running in parallel with it.
> [CI] enable MqttConnectorTest in CI pipeline

- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/DependencyManager.cs
- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/ExperimentalFeatures.cs
- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs
TL;DR (cherry-picked: https://github.com/Azure/iotedge/commit/40acc9603841b14cefc8451a017c291ac0abfafc)
Currently the protocol head could start up before the route configuration is setup on edgeHub. This causes the messages which are sent before the route is config to be permanently lost.
Background:
Historically, the edgeHub tries to download its twin to get the routings before it starts up the protocol heads, then it was waiting till the twin arrived, then it had the routings, then it started the protocol heads. With the new broker and nested scenario, the problem is that it needs the protocol heads up to get the twin. The twin comes through the MQTT broker, and one of the protocol heads handle the messages from the broker. The problem arises because protocol heads are up, but no twin …
> EdgeHub awaits for Twin in non-MQTT broker scenario (#4084)

- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/authentication/AuthAgentProtocolHead.cs
- edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/AuthAgentListenerTest.cs
- edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/MqttBrokerConnectorTest.cs
`MqttMiniServer` had multiple places with loops that try to make a progress forever even when the client disconnected.
`AuthProtocolHead.CloseAsync` method calls `IWebHost.StopAsync` which blocks not only the execution of the current test but also other tests that were running in parallel with it.
cherry-pick `a2524a8`
> [CI] enable MqttConnectorTest in CI pipeline (#4107)

- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/brokerConnection/MqttBrokerConnector.cs
- edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/MqttBrokerConnectorTest.cs
Fixed two tests that was either flaky or got hung:
- WhenReconnectThenResubscribes: this was not waiting for the second action to complete and sometimes checked the result 'too early'. Added a 'milestone' to wait at, so it goes to the assert part when the broker signals that it executed a certain action
- OfflineSendGetSentAfterReconnect: it never broke on a local desktop or raspberry pi with 4 cores enabled, however it got hung sometimes in CI or raspberry with 2 core enabled. The test becomes stable even after a tiny wait time between dropping the connection and sending the message (which needs to be handled with connection off)
Note, that this can be a sign of a real bug (not test bug) that if a 'send' operation happens in a very narrow window when the connection got dropped (not even …
> Fixed hanging CI tests for MqttBrokerConnector

- CHANGELOG.md
- versionInfo.json
Prepare for release 1.2.0-rc3 for which we will only be updating images. Updated changelog and versionInfo, but not the edgelet version.
> Prepare for 1.2.0-rc3 release

- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/DependencyManager.cs
- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/appsettings_hub.json
- edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.E2E.Test/DependencyManager.cs
- scripts/linux/runE2ETest.sh
- smoke/LeafDevice/details/Details.cs
- test/Microsoft.Azure.Devices.Edge.Test/Device.cs
- test/Microsoft.Azure.Devices.Edge.Test/DeviceWithCustomCertificates.cs
Cherry-pick #4095
Authentication mode is set as Scope by default. This is a breaking change for leaf devices which are not in scope of edge device. Customer can set the env variable to AuthenticationMode to CloudAndScope if they need to, going forward this option will be deprecated. Will follow up with Emmanuel to have this breaking change documented.
> Set default auth mode to Scope (#4095)

- doc/BuiltInMetrics.md
- edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/Agent.cs
- edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/AgentTests.cs
edgeAgent should save the current config with the corresponding version even when there is no update in the deployment but just the version update and report back to iothub.
> Update current config when plan is empty

- test/Microsoft.Azure.Devices.Edge.Test.Common/linux/PackageManagement.cs
iiot usually cleans up its packages on completion, but won't be able to do this if it crashes, times out, or is canceled. Update tests to remove these packages if encountered.
> Remove conflicting packages left by iiot runs

- builds/e2e/templates/e2e-setup.yaml
- scripts/local/test/DownloadIdentityService.ps1
Move the script that downloads aziot-identity-service from the E2E test YAML so it can be shared with the Connectivity test pipeline.
> Move 'Download aziot-identity-service' to separate file

- builds/ci/mqtt.yaml
Right now if someone wants to run MQTT CI on an arbitrary commit - they can't. The commit must contain changes in mqtt or builds folder.
Out other CI pipelines don't use "precondition task" to check if they need to run or not. I'm removing the precondition check from MQTT CI as well, but instead I'm adding "native" precondition check for `builds` and `mqtt` folders. This way it will be possible to start the pipeline manually, but it won't be auto-triggered unnecessarily.
> Use native precondition for MQTT CI (#4179)

- test/Microsoft.Azure.Devices.Edge.Test.Common/config/HubModuleConfigBuilder.cs
- test/Microsoft.Azure.Devices.Edge.Test/AuthorizationPolicy.cs
E2e tests broke after a recent commit that changed the way EdgeHub parses its config.
With the change, EdgeHub now needs the 1.2 schemaVersion set in order for the broker to be enabled.
This PR updates the schemaVersion for the e2e tests to 1.2, so that the broker can be enabled. It shouldn't have any negative effects, as 1.2 is backwards compatible.
During investigation we uncovered that the AuthorizationUpdatePolicy test has a bug where we don't set the second device to use MQTT, so it uses AMQP and bypasses the broker. This is fixed here too
> Update schemaVersion to 1.2 globally for e2e tests and fix bug in auth test

- .config/CredScanSuppressions.json
Resolves SDL pipeline issues caused by recent changes to edgelet.
- Add CredScan suppressions for credentials used in new edgelet tests.
- Removed Windows build and artifact publish jobs in the SDL pipeline config
> Fix SDL pipeline

- builds/misc/addons-release.yaml
Changes the use of $(version) to $(Build.BuildNumber) if $(version) is empty.
> Fix Add-ons pipeline

- builds/misc/base-images-publish.yaml
Make ARM32 Base Image Publication Pipeline Timeout to be 2hr
> Make ARM32 Base Image Publication Pipeline Timeout to be 2hr

- builds/misc/base-images-publish.yaml
Make ARM32 Base Image Publication Pipeline Timeout to be 2hr
> Make ARM32 Base Image Publication Pipeline Timeout to be 2hr (#4233)

- edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/ModuleClientProvider.cs
- edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.IoTHub.Test/ModuleClientProviderTest.cs
- edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudConnectionProvider.cs
- edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Test/CloudConnectionProviderTest.cs
SDK is started throwing if the caller explicitly passes in a webproxy for TCP only protocols.  This change omits the proxy for Amqp/Mqtt over TCP so we get the old behavior back.
> Don't use http proxy for Amqp/Mqtt over TCP only

- edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/storage/MessageStore.cs
- edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/storage/MessageStoreTest.cs
cherry-pick #4271
In some customer cases it happens that cleanup fails when it tries to update message store because value is not found in the db and throws InvalidOperationException. Catching the exception so it continues cleaning up otherwise it's not able to clean up messages for the endpoint.
> message store cleanup catch exception when message is updated (#4271)

- builds/e2e/templates/e2e-run.yaml
- e2e_deployment_files/nestededge_middleLayerBaseDeployment.json
- e2e_deployment_files/nestededge_topLayerBaseDeployment.json
- test/Microsoft.Azure.Devices.Edge.Test.Common/EdgeRuntime.cs
- test/Microsoft.Azure.Devices.Edge.Test.Common/LeafDevice.cs
- test/Microsoft.Azure.Devices.Edge.Test/Device.cs
- test/Microsoft.Azure.Devices.Edge.Test/SetupFixture.cs
This change adds a testcase that rotates the SAS key of the leaf device at runtime, and verifies that the client can use the new credentials to connect through the hierarchy to IoT Hub.
> Nested E2E - rotate SAS key of leaf device

- builds/e2e/longhaul.yaml
- builds/e2e/templates/longhaul-deploy.yaml
Adding checkout to azure pipelines for LongHaul. This should significantly speed up development, as we can now make changes to the script without having to build images (which takes 1.5 hours at the moment)
Only making this change for trc version since the other method (Analyzer) is going away
> Adding checkout repo to longHaul instead of artifacts

- scripts/linux/nested-edge-deploy-agent.sh
- test/Microsoft.Azure.Devices.Edge.Test.Common/DaemonConfiguration.cs
- test/Microsoft.Azure.Devices.Edge.Test.Common/IEdgeDaemon.cs
- test/Microsoft.Azure.Devices.Edge.Test.Common/LeafDevice.cs
- test/Microsoft.Azure.Devices.Edge.Test.Common/certs/CaCertificates.cs
- test/Microsoft.Azure.Devices.Edge.Test.Common/certs/FixedPaths.cs
- test/Microsoft.Azure.Devices.Edge.Test.Common/linux/EdgeDaemon.cs
- test/Microsoft.Azure.Devices.Edge.Test/Provisioning.cs
- test/Microsoft.Azure.Devices.Edge.Test/SetupFixture.cs
- test/Microsoft.Azure.Devices.Edge.Test/helpers/X509ManualProvisioningFixture.cs
Previous config files left by old tests would affect new test runs. Modifies the E2E tests to always start with the default config.
Also fixes a bug where only the first cert of a chain is parsed and added to the store.
> Ensure E2E tests start with clean config

- edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/KubeUtils.cs
- edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/edgedeployment/deployment/KubernetesDeploymentMapper.cs
- edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/edgedeployment/pvc/KubernetesPvcMapper.cs
- edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.IntegrationTest/EdgeDeploymentControllerTest.cs
- edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/KubeUtilsTest.cs
- edgelet/edgelet-kube/src/convert/mod.rs
- edgelet/edgelet-kube/src/convert/to_k8s.rs
- edgelet/edgelet-utils/src/lib.rs
An automated system created a PVC with a GUID name,  It should be valid, but the GUID started with a number, and the number was stripped from the PVC name when doing a volume mount, leaving the pod pending.
This change allows DNS labels (object names) to start with alphanumerics.
> [k8s] Allow alphanumerics to start K8s object names.

- edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/requests/RequestHandlerBase.cs
- edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/requests/RequestHandlerBaseTest.cs
- edge-util/src/Microsoft.Azure.Devices.Edge.Storage/SerDeExtensions.cs
- test/Microsoft.Azure.Devices.Edge.Test/EdgeAgentDirectMethods.cs
Fix issue calling GetModuleLogs using DirectMethod with a payload that contains parameters using RF3339 DateTime format.
> Fix GetModules call error using RFC3339 DateTime format.

- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/config/TwinConfigSource.cs
Faulty bridge settings makes edgehub complain and we never get the policy ready signal. I think we just need to log an error instead of a warning, which will indicate that the state isn't valid.
> EdgeHub: Log error when failure updating edgehub config

- edgelet/Makefile
- edgelet/contrib/config/linux/config.yaml
- edgelet/iotedge/src/main.rs
e4794aee0aa6c7d78bee83d62662d5935bf8f381 reverted the management and workload
sockets to be under `/var/lib/iotedge` on CentOS and
`/var/run/iotedge` everywhere else, but missed a few places.
> Fix CentOS package build.

- builds/e2e/connectivity.yaml
- builds/e2e/longhaul.yaml
- builds/e2e/nested-connectivity.yaml
- builds/e2e/nested-longhaul.yaml
- builds/e2e/stresstest.yaml
- builds/e2e/templates/e2e-setup.yaml
- builds/e2e/templates/nested-agent-deploy.yaml
IMO, we should always allow partially succeeded builds when downloading artifacts. This will block the possibility that we don't notice tests are running old bits.
> Relax artifact download requirements to allow partially succeeded builds

- test/modules/TestResultCoordinator/Settings.cs
Fixing typo in trc that breaks connectivity settings
> Fix typo in TestResultCoordinator

- test/Microsoft.Azure.Devices.Edge.Test.Common/LeafDevice.cs
- test/Microsoft.Azure.Devices.Edge.Test.Common/certs/CaCertificates.cs
- test/Microsoft.Azure.Devices.Edge.Test.Common/certs/FixedPaths.cs
Reverts a previous change that added the intermediate certs to the trust bundle. Only put the root CA cert in the trust bundle. The E2E tests were failing when intermediate certs were in the trust bundle, possibly because it wasn't validating the full chain.
> Revert to use only root CA as trust bundle

- mqtt/mqtt-bridge/src/bridge.rs
- mqtt/mqtt-bridge/src/client.rs
- mqtt/mqtt-bridge/src/settings.rs
- mqtt/mqtt-bridge/tests/common.rs
- mqtt/mqtt-bridge/tests/integration.rs
- mqtt/mqtt-bridge/tests/rpc.rs
- mqtt/mqtt-broker-tests-util/src/client.rs
- mqtt/mqtt-util/src/lib.rs
- test/modules/generic-mqtt-tester/src/tester.rs
Adds an integration test that verifies the bridge can work properly after being restarted.
Moves RPC integration tests to appropriate module `rpc`.
Makes `mqtt_util` types exported as the high-level crate types.
> [mqtt] Implement shutdown/restart integration test

- test/Microsoft.Azure.Devices.Edge.Test/PriorityQueues.cs
PriorityQueueModuleToHub end to end tests were flaky because we were getting some results from other tests.
This change makes sure all results we receive are from the current test by matching up a trackingId
> Stabilize PriorityQueueModuleToHub test

- test/Microsoft.Azure.Devices.Edge.Test/IoTEdgeCheck.cs
Before, this end to end test was failing because it creates a process that calls iotedge check. This check tries to pull down the diagnostics image and call iotedge check on it, but it cannot pull the image down because it doesn't have auth.
This PR logs into docker before the iotedge check call so that the process is authenticated.
> Fixing iotedge check e2e test by adding auth before check call

- mqtt/mqtt-broker/src/persist.rs
- mqtt/mqtt-broker/src/proptest.rs
- mqtt/mqtt-broker/src/session/state/map.rs
- mqtt/mqtt-broker/src/session/state/mod.rs
- mqtt/mqtt-broker/src/session/state/queue.rs
- mqtt/mqtt-broker/src/snapshot.rs
- mqtt/mqtt-broker/tests/broker_model.rs
- mqtt/mqtt-broker/tests/compliance.rs
- mqtt/mqtt-broker/tests/integration.rs
We have an issue where we are losing in-flight qos1 messages on restart. In this PR I have included `SessionState::waiting_to_be_acked` queue into `SessionSnapshot` and made sure it is being persisted on restart.
Main changes are in:
- mqtt/mqtt-broker/src/persist.rs
- mqtt/mqtt-broker/src/session/state/mod.rs
- tests
The rest is just plumbing.
You might ask that `SessionState::waiting_to_be_acked` covers only qos1, and qos2 is not covered completely and still prone to the same issue. But we are not going to support qos2 for GA and will fix it separately later.
> Persist in-flight queue on broker restart

- mqtt/mqtt-broker/src/persist.rs
- mqtt/mqtt-broker/src/proptest.rs
- mqtt/mqtt-broker/src/session/state/map.rs
- mqtt/mqtt-broker/src/session/state/mod.rs
- mqtt/mqtt-broker/src/session/state/queue.rs
- mqtt/mqtt-broker/src/snapshot.rs
- mqtt/mqtt-broker/tests/broker_model.rs
- mqtt/mqtt-broker/tests/compliance.rs
- mqtt/mqtt-broker/tests/integration.rs
We have an issue where we are losing in-flight qos1 messages on restart. In this PR I have included `SessionState::waiting_to_be_acked` queue into `SessionSnapshot` and made sure it is being persisted on restart.
Main changes are in:
- mqtt/mqtt-broker/src/persist.rs
- mqtt/mqtt-broker/src/session/state/mod.rs
- tests
The rest is just plumbing.
You might ask that `SessionState::waiting_to_be_acked` covers only qos1, and qos2 is not covered completely and still prone to the same issue. But we are not going to support qos2 for GA and will fix it separately later.
> Persist in-flight queue on broker restart (#4356)

- smoke/IotEdgeQuickstart/details/IotedgedLinux.cs
This is a hack to make device identity service work for nested edge. Please refer to [9171870](https://msazure.visualstudio.com/One/_workitems/edit/9171870) for details.
> Fixed quick start for nested device identity service

- mqtt/mqtt-bridge/src/client.rs
- mqtt/mqtt-bridge/src/controller/bridges.rs
- mqtt/mqtt-bridge/src/controller/mod.rs
- mqtt/mqtt-bridge/src/pump/messages.rs
- mqtt/mqtt-bridge/tests/integration.rs
- test for the case when upstream bridge is stopped and it should be recreated by controller
- return error in handle events if the client gets an error
- retry to create upstream bridge when new fails
> add bridge restart test

- test/modules/generic-mqtt-tester/src/lib.rs
- test/modules/generic-mqtt-tester/src/message_channel.rs
- test/modules/generic-mqtt-tester/src/tester.rs
- test/rust-test-util/test-result-reporting-client/src/lib.rs
- test/rust-test-util/test-result-reporting-client/src/models/test_result_dto.rs
Two changes:
- The logging can be improved by specifying the sequence number of the received message.
- Fixed the report format. The test type needs to be a string not an int, or report generation will fail.
> Generic Mqtt Test Module: Clean up logging and fix report format

- mqtt/mqtt-bridge/src/messages.rs
- mqtt/mqtt-bridge/src/pump/builder.rs
- mqtt/mqtt-bridge/src/pump/messages.rs
- mqtt/mqtt-bridge/src/pump/mod.rs
- mqtt/mqtt-bridge/src/upstream/rpc/local.rs
- mqtt/mqtt-bridge/src/upstream/rpc/remote.rs
- mqtt/mqtt-edgehub/src/command/handler.rs
- mqtt/mqtt3/src/client/mod.rs
- mqtt/mqtt3/src/client/subscriptions.rs
- mqtt/mqtt3/tests/subscriptions.rs
When edge deployed on several levels in nested scenarios there can be a lag between all rules are applied. In this case, lower level subscriptions can be rejected by the upper level. The lower level should keep retrying until it is subscribed.
cherry-pick `be3d482`
> [mqtt] Retry non-iothub subscription when rejected by server (#4249)

- mqtt/Cargo.lock
- mqtt/mqtt-bridge/Cargo.toml
- mqtt/mqtt-bridge/src/persist/mod.rs
- mqtt/mqtt-bridge/src/persist/waking_state/mod.rs
- mqtt/mqtt-bridge/src/persist/waking_state/ring_buffer/block.rs
- mqtt/mqtt-bridge/src/persist/waking_state/ring_buffer/error.rs
- mqtt/mqtt-bridge/src/persist/waking_state/ring_buffer/flush.rs
- mqtt/mqtt-bridge/src/persist/waking_state/ring_buffer/mod.rs
- mqtt/mqtt-bridge/src/persist/waking_state/ring_buffer/serialize.rs
* Adds ring buffer
* Fix dep ordering in Cargo.toml
* Restructure layout
* Add flush tests
* Fix clippy warn
* Fmt change only
* Add block validation tests
* Fix style for block
* Add Hint error
* Fix style in ring_buffer
* Move should_flush to impl
* Fix clippy errors
* Update crate versions
* Fix usings style
* Add deserialize owned
* Make flush use duration
* Update block and data
* Reorganize errors
* Clean up RingBuffer
* millis_elapsed to elapsed
* Fix fmt error
* Update storage error to have 'Caused by'
Co-authored-by: Denis Molokanov <dmolokanov@users.noreply.github.com>
* Adds caused by to error msgs
Co-authored-by: Denis Molokanov <dmolokanov@users.noreply.github.com>
> Adds a ring buffer to MQTT bridge (#4304)

- test/connectivity/modules/NetworkController/CellularController.cs
- test/connectivity/modules/NetworkController/LinuxTrafficControlController.cs
- test/connectivity/modules/NetworkController/OfflineController.cs
- test/connectivity/modules/NetworkController/Program.cs
- test/connectivity/modules/NetworkController/SatelliteController.cs
- test/connectivity/modules/NetworkController/Settings.cs
Modified network controller to use IOTEDGE_PARENTHOSTNAME to set the network rules so that connectivity is set for connecting to parent device. If not in nested environment the parent env won't be set so it uses IOTEDGE_IOTHUBHOSTNAME.
> Use parenthostname in network controller to set up rules

- builds/ci/edgelet.yaml
- builds/ci/mqtt.yaml
- builds/e2e/longhaul.yaml
- builds/e2e/stresstest.yaml
- builds/misc/images-mqtt.yaml
- builds/misc/mqtt-perf.yaml
Missed a few in the last change, adding the var to suppress the security error now that we've moved our custom nuget packages to Azure Artifacts stream.
> Update more pipelines on nuget security error

- builds/mariner/SPECS/azure-iotedge/azure-iotedge.spec
After commit a34e0ed, the iotedge CLI fails in Mariner because IOTEDGE_HOST was not set during compilation, so the CLI has the wrong path to iotedged's management endpoint.
To fix this, we set IOTEDGE_HOST prior to running `make install`. It was already being set prior to `make release`.
> Fix iotedge CLI in mariner build

- CHANGELOG.md
Update the CHANGELOG to include the latest commits.
> Update release 1.1.0

- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Http/middleware/WebSocketHandlingMiddleware.cs
- edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.Http.Test/WebSocketHandlingMiddlewareTest.cs
- edge-modules/api-proxy-module/templates/nginx_default_config.conf
Add logic in the websocket middleware to check for client cert in the custom header that API proxy uses to forward the payload.
> Handle thumbprint auth through API proxy for WebSocket

- builds/checkin/watchdog.yaml
- builds/misc/images-mqtt.yaml
We don't really need to run the MQTT images pipeline if nothing changed in MQTT code.
> Run MQTT images pipeline only when MQTT code changes.

- edgelet/contrib/config/linux/config.yaml
- edgelet/contrib/config/linux/debian/config.yaml
- edgelet/contrib/config/windows/config.yaml
- edgelet/edgelet-docker/config/unix/default.yaml
- edgelet/edgelet-docker/config/windows/default.yaml
This change updates the default agent tag in config.yaml to 1.1.
Cherry-pick a4faab5f62f96fa813d19a73bba0ddf92c72edf8 and update 1.1-specific Windows config.yaml.
> Config yaml 1.1

- builds/e2e/nested-longhaul.yaml
- builds/e2e/templates/nested-longhaul-deploy-amd64.yaml
- builds/e2e/templates/nested-parent-vm-setup.yaml
Remove transport type from agent groups for NestedLongHaul (and soon to be NestedConnectivity since it uses a shared file, nested-parent-vm-setup.yaml) now that agent groups are in their respective subnets correctly.
> Remove transport type from agent groups

- mqtt/mqtt-edgehub/src/topic/translation.rs
M2M messages are being sent in the form of:
"devices/device_1/modules/module_a/inputs/some_parameters"
because of that structure, a client can subscribe either for
"devices/device_1/modules/module_a/#" or
"devices/device_1/modules/module_a/inputs/#"
the C# SDK choses the first form, and because of that the current implementation handles that. However, it turned out that there are clients using the second form, and that is ignored.
this PR makes handle both versions
> support M2M subscription with both cases of /input/ included or not

- test/Microsoft.Azure.Devices.Edge.Test.Common/IotHub.cs
- test/Microsoft.Azure.Devices.Edge.Test/AuthorizationPolicy.cs
- test/Microsoft.Azure.Devices.Edge.Test/Device.cs
- test/Microsoft.Azure.Devices.Edge.Test/DeviceWithCustomCertificates.cs
- test/Microsoft.Azure.Devices.Edge.Test/EdgeAgentDirectMethods.cs
- test/Microsoft.Azure.Devices.Edge.Test/Metrics.cs
- test/Microsoft.Azure.Devices.Edge.Test/Module.cs
- test/Microsoft.Azure.Devices.Edge.Test/PlugAndPlay.cs
- test/Microsoft.Azure.Devices.Edge.Test/PriorityQueues.cs
- test/Microsoft.Azure.Devices.Edge.Test/X509Device.cs
- test/Microsoft.Azure.Devices.Edge.Test/helpers/ManualProvisioningFixture.cs
- test/Microsoft.Azure.Devices.Edge.Test/helpers/SasManualProvisioningFixture.cs
- test/Microsoft.Azure.Devices.Edge.Test/helpers/X509ManualProvisioningFixture.cs
New E2E testcase that disables and re-enables the Edge device first before trying to connect a leaf device.  This can be run in both single node and nested mode.
Nested E2E run:
https://msazure.visualstudio.com/One/_build/results?buildId=39737520&view=results
> Nested E2E - Disable/Reenable parent Edge

- scripts/local/test/DownloadIdentityService.ps1
Adds a better error message when the iot-identity-service commit can't be determined.
> Add better error message for DownloadIdentityService.ps1

- scripts/linux/nested-edge-deploy-agent.sh
The name of edgeHub server certs was changed in d0978bf63bdd5624543680424452ee5c08fe285a. Updates nested E2E tests with the new name.
> Fix server cert name in nested E2E

- edgelet/iotedge/src/check/checks/aziot_edged_version.rs
- edgelet/iotedge/src/check/checks/mod.rs
- edgelet/iotedge/src/check/checks/well_formed_config.rs
- Temporarily remove aziot-edged version check until we sort out where the version info for 1.2 will live
- Remove references to config.yaml, replace with broader "configuration" terminology
> [iotedge check] bugbash fixes

- builds/misc/packages-release.yaml
Introduce the dedicated Packages Release Pipeline
Currently our existing Azure-IoT-Edge-Core Edgelet Release pipeline is a GUI-based devops pipeline which has been working nicely for `iotedge` and `libiothsm` artifacts. Going forward starting with release/1.2-rc4, the `iotedge` and `libiothsm` are retired and replaced by the new Identity Service (IS). 
This pipeline is created to provide a support for the `aziot-edge` release artifact as a part of the new IS. We decided not the update the existing pipeline going forward because of its GUI-based property which is used across multiple branches (release1.1 & release1.2) in the release process. By updating the pipeline for release1.2 will inevitably break the release1.1 release.
Note: The RELEASE pipeline is almost identical to the BUILD …
> Introduce the dedicated Packages Release Pipeline

- builds/e2e/e2e.yaml
Set env variables to direct nuget caches to the data partition instead of to the rootfs
> EFLOW: Introduce environment variables for nuget operations

- edgelet/iotedge/src/config/apply.rs
- edgelet/iotedge/test-files/config/complex-agent-spec/certd.toml
- edgelet/iotedge/test-files/config/dps-symmetric-key/certd.toml
- edgelet/iotedge/test-files/config/dps-tpm/certd.toml
- edgelet/iotedge/test-files/config/dps-x509/certd.toml
- edgelet/iotedge/test-files/config/manual-connection-string-2/certd.toml
- edgelet/iotedge/test-files/config/manual-connection-string/certd.toml
- edgelet/iotedge/test-files/config/manual-x509/certd.toml
- edgelet/iotedge/test-files/config/moby-runtime-content-trust/certd.toml
- edgelet/iotedge/test-files/config/not-socket-activated-both-custom/certd.toml
- edgelet/iotedge/test-files/config/not-socket-activated-varlib/certd.toml
- edgelet/iotedge/test-files/config/not-socket-activated-varrun/certd.toml
- edgelet/iotedge/test-files/config/socket-activated-one-custom/certd.toml
Temporarily raise quickstart EdgeCA cert's expiry to 30 days.
Currently certd does not cap an issued cert's not-after to the issuer's.
This means a situation can happen where Edge Hub requests a module server cert
for 30 days and is granted one, but the Edge CA cert is valid for less than
30 more days. EH won't renew its cert until it's 5 minutes to expiry,
but for most of that time the full cert chain will be invalid because of
the expired issuer and modules would refuse to connect to it.
In fact, this is what happens with self-signed Edge CA as configured by
`iotedge config apply` in quickstart mode before this change, because
the expiry defaults to 1 day.
Until certd is fixed, for RC4 we decided to do the simpler workaround of
just raising the quickstart Edge CA's expiry to 30 days.
> Temporarily raise quickstart EdgeCA cert's expiry to 30 days.

- edgelet/contrib/centos/aziot-edge.spec
Fix typo of license type in aziot-edge.spec.
> Fix license type in aziot-edge.spec

- edge-modules/api-proxy-module/docker/linux/arm64v8/Dockerfile
It addresses the following bug: #9433402
[1.2-rc4BugBash] API proxy: arm64 images do not work
API does not work on arm64
Build:https://dev.azure.com/msazure/One/_build/results?buildId=39970527&view=logs&j=5e897c14-3122-5b03-9993-10a307d9da6f&t=be439baf-4cfc-5b62-e448-a0c93566f55e
Tested on arm64.
> Fixing arm64 image

- builds/misc/mqtt-perf.yaml
- builds/misc/templates/mqtt-perf-setup.yaml
- builds/misc/templates/mqtt-perf-test-case.yaml
There are few small improvements I propose for MQTT perf tests:
- use `--security-opt apparmor=unconfined` flag to disable apparmor that sometimes causes problems restarting the containers
- use `docker rm -f` && `docker run` instead of `docker restart`
- save image name into local file, for ease of use in later steps.
- make all stages always run even if previous failed.
> MQTT Perf Tests improvements.

- e2e_deployment_files/long_haul_deployment.template.json
- e2e_deployment_files/nestededge_bottomLayerBaseDeployment_connectivity_mqtt.template.json
- e2e_deployment_files/nestededge_bottomLayerBaseDeployment_long_haul_amqp.template.json
- e2e_deployment_files/nestededge_bottomLayerBaseDeployment_long_haul_mqtt.template.json
- e2e_deployment_files/nestededge_isa95_smoke_test_BaseDeployment.json
- e2e_deployment_files/nestededge_middleLayerBaseDeployment_amqp.json
- e2e_deployment_files/nestededge_middleLayerBaseDeployment_mqtt.json
- e2e_deployment_files/nestededge_topLayerBaseDeployment_amqp.json
- e2e_deployment_files/nestededge_topLayerBaseDeployment_mqtt.json
- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudConnectionProvider.cs
- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ServiceProxy.cs
- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/authenticators/DeviceScopeCertificateAuthenticator.cs
- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/authenticators/DeviceScopeTokenAuthenticator.cs
- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/Constants.cs
- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/DependencyManager.cs
- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/ExperimentalFeatures.cs
- edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Test/ServiceProxyTest.cs
- edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/ConnectionManagerTest.cs
- edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.E2E.Test/DependencyManager.cs
- test/Microsoft.Azure.Devices.Edge.Test.Common/EdgeRuntime.cs
There are two main changes in this PR:
- Enable nested edge by default
- Move `NestedEdgeEnabled` settings out of `experimentalFeatures` section.
To enable nested edge/broker you would need to have the following env vars in your deployment manifest:
```json
"edgeHub": {
"type": "docker",
"status": "running",
"restartPolicy": "always",
"settings": {
"image": "edgerelease.azurecr.io/microsoft/azureiotedge-hub:1.2.0-rc3-linux-amd64",
"createOptions": "{\"HostConfig\": {\"PortBindings\": {\"1883/tcp\": [{\"HostPort\": \"1883\"}], \"8883/tcp\": [{\"HostPort\": \"8883\"}],\"443/tcp\": [{\"HostPort\": \"443\"}],\"5671/tcp\": [{\"HostPort\": \"5671\"}]}}}"
},
"env": {
"experimentalFeatures__nestedEdgeEnabled": {
"value": "true"
},
"experimentalFeatures__mqttBrokerEnabled": {
"value": "true"
}, …
```
> Move NestedEdgeEnabled out of experimental features. (#4467)

- edgelet/Cargo.lock
- edgelet/contrib/debian/postrm
- edgelet/contrib/debian/preinst
Updates postrm so that apt purge fully removes all files used by aziot-edge and removes iotedge user.
This only applies to Debian, as CentOS (rpm) doesn't have a purge command.
> Update postrm to delete iotedge user on purge

- edgelet/Cargo.lock
- edgelet/contrib/debian/postrm
- edgelet/contrib/debian/preinst
Updates postrm so that apt purge fully removes all files used by aziot-edge and removes iotedge user.
This only applies to Debian, as CentOS (rpm) doesn't have a purge command.
> Update postrm to delete iotedge user on purge (#4533)

- scripts/local/test/DownloadIdentityService.ps1
If iot-identity-service has the same commit in multiple branches, duplicate artifacts will be found. Fix DownloadIdentityService to only consider the first artifact.
> Fix DownloadIdentityService for iot-identity-service branches

- mqtt/mqtt-broker/src/settings/size.rs
It looks like that in prev version of regex it is possible that `.*` can eval into a digit, which in turn will lead to a valid input :)
```
".*[0-9]{9}.*(k|K|m|M|g|G)?.*"
```
> Fix flaky proptest (#4539)

- tools/CACertificates/README.md
DPS registration id within the X.509 cert's CN is not case sensitive. Verified this against DPS API version 2018-11-01
> Remove obsolete DPS CN limitation in README

- edgelet/contrib/debian/postrm
Sometimes, `apt purge aziot-edge` fails because the `iotedge` user still has running processes during purge. Fix this by killing all processes running under the `iotedge` user before purging.
> Fix package purge when aziot-edged is running

- builds/checkin/rust-test-modules.yaml
- mqtt/mqtt-broker-tests-util/src/client.rs
I am fixing it to unblock the rust-test-module-checkin.
> Fix clippy errors in mqtt-broker-tests-util

- builds/e2e/nested-connectivity.yaml
- builds/e2e/nested-e2e.yaml
- builds/e2e/nested-longhaul.yaml
- builds/e2e/templates/nested-create-identity.yaml
- builds/e2e/templates/nested-longhaul-deploy-amd64.yaml
- builds/e2e/templates/nested-longhaul-deploy-arm32.yaml
- builds/e2e/templates/nested-longhaul-deploy-arm64.yaml
- builds/e2e/templates/nested-longhaul-deploy.yaml
- builds/e2e/templates/nested-parent-vm-setup.yaml
Fixes:
- Upstream protocol is incorrectly configured. It assigns the correct upstream protocol, but always reports amqp to log analytics. I fixed this and standardized the naming for upstream protocol across our yamls as ```upstream.protocol```.
- The addition of test name I made has a problem, as I thought we had two nested longhaul pipelines. Turns out these are duplicates and we have one nested longhaul pipeline that runs two longhaul tests. One for amqp upstream and one for mqtt upstream with broker. Therefore we need to plumb this information down not through pipeline vars, but hardcoded values in the nested longhaul yaml similar to upstream protocol.
> Nested Longhaul: Fix upstream protocol and test name

- builds/e2e/longhaul.yaml
- Fix NugetSecurity warning for Long Haul pipeline
> Fix NugetSecurity warning for Long Haul pipeline

- builds/e2e/isa-95-smoke-test.yaml
- builds/e2e/templates/nested-create-identity.yaml
- builds/e2e/templates/nested-parent-vm-setup.yaml
This PR fixes two things, but really they are the same issue:
- Existing bug in ISA95 smoke tests
- Bug I introduced yesterday in #4572 
The problem for both is that upstream protocol is not passed, or passed incorrectly.
This problem was masked by my testing, so I also made a change to fail the pipeline run if an error occurs making the identity. I do this with ```set -e```.
https://stackoverflow.com/questions/1378274/in-a-bash-script-how-can-i-exit-the-entire-script-if-a-certain-condition-occurs
> Nested Pipelines: Fix wrong casing for upstream protocol

- edgelet/iotedge/src/check/mod.rs
- edgelet/iotedge/src/main.rs
The proxy-uri parameter can be passed in via command line argument. If that isn't specified, the settings (if valid) will be searched for Edge Agent's https_proxy environment variable.
Either way, the value will be passed along to aziotctl, where the connection check will occur using the proxy URI.
Note that this depends on https://github.com/Azure/iot-identity-service/pull/158
> Add optional proxy argument to iotedge

- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/ConnectionManager.cs
- edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/ConnectionManagerTest.cs
There was an optimization on ConnectionManager so it did not do any action for subscription/unsubscription if the state did not change, to avoid excess communication to iothub. The status of a given subscription (e.g. for C2D messages) can be represented by three states: true, false or missing. Missing means that the subscription was never set, so the dictionary that stores the state has no information about it. When this happens that means that nothing has set the subscription yet, which means that no subscription exists to that topic. In this case when that subscription gets removed, that does not mean status change.
The original implementation handled this as a status change and executed a remove operation. This should not have caused any problems, however a bug in the C# SDK breaks …
> Fix: don't unsubscribe when there is no subscription registered

- edgelet/iotedge/src/check/mod.rs
- edgelet/iotedge/src/main.rs
The proxy-uri parameter can be passed in via command line argument. If that isn't specified, the settings (if valid) will be searched for Edge Agent's https_proxy environment variable.
Either way, the value will be passed along to aziotctl, where the connection check will occur using the proxy URI.
Note that this depends on https://github.com/Azure/iot-identity-service/pull/158
Cherry-pick of 6b0c6c5d8797462c7f6ca8c5c2d1cde4925c3279
> Add optional proxy argument to iotedge (#4590)

- edgelet/Cargo.lock
This aziot-identity-service version update is required due to the introduction of proxy-uri CLI argument within iotedge
> Bump aziot version

- edgelet/contrib/config/linux/config.yaml
- edgelet/contrib/config/linux/debian/config.yaml
- edgelet/contrib/config/windows/config.yaml
Also clarify what the service uses to detect reprovisioning when
`dynamic_reprovisioning` is true.
> Fix typo in `always_reprovision_on_startup` config.yaml docs.

- builds/checkin/rust-test-modules.yaml
- mqtt/mqtt-broker-tests-util/src/client.rs
I am fixing it to unblock the rust-test-module-checkin.
> Fix clippy errors in mqtt-broker-tests-util (#4574)

- edgelet/iotedge/src/check/checks/hostname.rs
Series of fix + improvement on iotedge check.
PR following: https://github.com/Azure/iotedge/pull/4608
Removing case sensitivity when checking hostname.
It created issue, like being unable to use fqdn if your hostname has a capital letter (if you use azure VMs).
> Remove case sensitivity in hostname check

- scripts/linux/nested-edge-deploy-agent.sh
For our nested longhaul tests, dynamic provisioning is set to true when it is not using dps. I don't think this config is used with any dps tests as the same config sets up manual provisioning. So it should be safe to update.
> Nested Tests: Default dynamic reprovisioning to false

- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/upstream/BrokeredCloudConnectionProvider.cs
- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/upstream/BrokeredCloudProxy.cs
Using mqtt broker upstream, after a disconnection to the parent device and connecting back, edge should pull the twin of the connected clients. This used to work by accident: there was a bug, which did not close existing cloud proxy objects, so they remained subscribed to connection events and forwarder those, so eventually twin manager received a notification that device_x regained its connection, which in turn pulled the twin.
Fixing this bug removed the accidental event forwarding of the dead object, and because on losing the connection these objects are removed, nothing forwarded events to twin manager for the individual devices.
This fix copies the solution of the legacy CloudConnection (ConnectToIotHub), which during proxy creation calls an explicit Open() method, which sends the …
> fix: after disconnect/connect, client twins should be pulled

- edgelet/Cargo.lock
- edgelet/edgelet-core/src/error.rs
- edgelet/iotedge/src/check/checks/connect_management_uri.rs
- edgelet/iotedge/src/check/checks/container_resolve_parent_hostname.rs
- edgelet/iotedge/src/check/checks/hostname.rs
- edgelet/iotedge/src/check/checks/mod.rs
- edgelet/iotedge/src/check/checks/parent_hostname.rs
- edgelet/iotedge/src/check/checks/up_to_date_config.rs
- edgelet/iotedge/src/check/mod.rs
- edgelet/iotedge/src/config/apply.rs
- edgelet/iotedge/src/error.rs
- edgelet/iotedge/src/main.rs
- edgelet/support-bundle/src/support_bundle.rs
This check verifies that the edged super config file (`/etc/aziot/edged/config.d/00-super.toml`) has a `last_modified` after `/etc/aziot/config.toml`. Prints a warning if `config.toml` was modified after `00-super.toml`, since that means the user probably forgot to run `iotedge config apply` after updating `config.toml`.
Example message:
```
‼ iotedge configuration up-to-date with config.toml - Warning
/etc/aziot/config.toml was modified after edged's config
You must run 'iotedge config apply' to update edged's config with the latest config.toml
```
> Add check up_to_date_config (#4596)

- mqtt/mqtt-bridge/src/persist/waking_state/ring_buffer/mod.rs
The Ring buffer currently doesn't read the whole file for determining where write and read pointers should be. It actually short-circuits out when write pointer is determined. This can allow for a case where messages cannot be sent and are instead written over. 
The scenario is as follows:
- RingBuffer is filled and write pointer wraps around
- Data is being batched and read pointer progresses beyond initial point
- A restart occurs which means RingBuffer needs to re-initialize
- RingBuffer finds write pointer before read pointer and doesn't continue to find read pointer
- More writes come in and write over data that was not sent as read pointer is behind write pointer after re-init.
> Fix RingBuffer initialization logic

- edgelet/Cargo.lock
- edgelet/aziot-edged/Cargo.toml
- edgelet/cert-client/Cargo.toml
- edgelet/edgelet-docker/Cargo.toml
- edgelet/edgelet-http-mgmt/Cargo.toml
- edgelet/edgelet-http-workload/Cargo.toml
- edgelet/identity-client/Cargo.toml
- edgelet/iotedge/Cargo.toml
Switches the cargo dependency from `main` to `release/1.2` of the iot-identity-service repo.
> Change i-i-s cargo dependency to release/1.2 branch

- mqtt/mqtt-bridge/src/persist/waking_state/ring_buffer/mod.rs
It is possible for a crash to occur where there are no deleted block but reads have occurred. In this case we would want to have read at write position on init as this should only happen if the buffer is full.
> Add test for rare RB init edge case

- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/upstream/BrokeredCloudConnectionProvider.cs
- edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/ConnectionEventTest.cs
so messages will be resent instead of dropping them
(cherry picked from commit b196a15e3dd3fb541d120f4f947c6557c518ed5c)
> Fix: throw transient error when edgeHubCore is disconnected from the broker (#4603

- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/ConnectionManager.cs
- edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/ConnectionManagerTest.cs
There was an optimization on ConnectionManager so it did not do any action for subscription/unsubscription if the state did not change, to avoid excess communication to iothub. The status of a given subscription (e.g. for C2D messages) can be represented by three states: true, false or missing. Missing means that the subscription was never set, so the dictionary that stores the state has no information about it. When this happens that means that nothing has set the subscription yet, which means that no subscription exists to that topic. In this case when that subscription gets removed, that does not mean status change.
The original implementation handled this as a status change and executed a remove operation. This should not have caused any problems, however a bug in the C# SDK breaks …
> Fix: don't unsubscribe when there is no subscription registered (#4594)

- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/upstream/BrokeredCloudConnectionProvider.cs
- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/upstream/BrokeredCloudProxy.cs
Using mqtt broker upstream, after a disconnection to the parent device and connecting back, edge should pull the twin of the connected clients. This used to work by accident: there was a bug, which did not close existing cloud proxy objects, so they remained subscribed to connection events and forwarder those, so eventually twin manager received a notification that device_x regained its connection, which in turn pulled the twin.
Fixing this bug removed the accidental event forwarding of the dead object, and because on losing the connection these objects are removed, nothing forwarded events to twin manager for the individual devices.
This fix copies the solution of the legacy CloudConnection (ConnectToIotHub), which during proxy creation calls an explicit Open() method, which sends the …
> fix: after disconnect/connect, client twins should be pulled (#4629)

- e2e_deployment_files/nestededge_bottomLayerBaseDeployment_long_haul_amqp.template.json
Nested Longhaul: Add debug logging for non-broker case.
This was missed when the deployment was created. Adding it now.
> Nested Longhaul: Add debug logging for non-broker case (#4607)

- scripts/linux/nested-edge-deploy-agent.sh
For our nested longhaul tests, dynamic provisioning is set to true when it is not using dps. I don't think this config is used with any dps tests as the same config sets up manual provisioning. So it should be safe to update.
> Nested Tests: Default dynamic reprovisioning to false (#4622)

- e2e_deployment_files/long_haul_deployment.template.json
- e2e_deployment_files/nestededge_bottomLayerBaseDeployment_connectivity_mqtt.template.json
- e2e_deployment_files/nestededge_bottomLayerBaseDeployment_long_haul_amqp.template.json
- e2e_deployment_files/nestededge_bottomLayerBaseDeployment_long_haul_mqtt.template.json
- e2e_deployment_files/nestededge_isa95_smoke_test_BaseDeployment.json
- e2e_deployment_files/nestededge_middleLayerBaseDeployment_amqp.json
- e2e_deployment_files/nestededge_middleLayerBaseDeployment_mqtt.json
- e2e_deployment_files/nestededge_topLayerBaseDeployment_amqp.json
- e2e_deployment_files/nestededge_topLayerBaseDeployment_mqtt.json
- scripts/linux/trcE2ETest.sh
- test/modules/TestResultCoordinator/TestReportUtil.cs
Current log rotation settings for longhaul are configured for pis. We need to have ample logs, especially on amd64 where we do most of our testing. I have added logic to the trcE2Escript.sh to set the log size differently depending on platform.
> Longhaul: Make log rotation less restrictive on amd64 (#4604)

- test/modules/DirectMethodSender/DirectMethodSenderBase.cs
- test/modules/Modules.Test/TestResultCoordinator/Reports/DirectMethod/DirectMethodLongHaulReportData.cs
- test/modules/Modules.Test/TestResultCoordinator/Reports/DirectMethod/DirectMethodLongHaulReportGeneratorTest.cs
- test/modules/TestResultCoordinator/Reports/DirectMethod/LongHaul/DirectMethodLongHaulReport.cs
- test/modules/TestResultCoordinator/Reports/DirectMethod/LongHaul/DirectMethodLongHaulReportGenerator.cs
Longhaul is seeing DeviceNotFound exceptions. We didn't used to see this. Bear and I think that this is because either:
- EdgeHub is taking a long time to restart
- The exception's transient field was flipped from true to false by the sdk
The fix here is to implement a tolerance to these exceptions, similarly to how we do with status code 0.
> Longhaul: Add threshold for device not found (#4642)

- edgelet/aziot-edged/src/app.rs
- edgelet/aziot-edged/src/error.rs
- edgelet/aziot-edged/src/lib.rs
- edgelet/aziot-edged/src/watchdog.rs
Removed allowed lints that were used to minimize conflicts during Module Runtime refactor and cleant up dead code
> Remove leftover unused lint exceptions

- edgelet/aziot-edged/src/app.rs
- edgelet/aziot-edged/src/error.rs
- edgelet/aziot-edged/src/lib.rs
- edgelet/aziot-edged/src/watchdog.rs
Removed allowed lints that were used to minimize conflicts during Module Runtime refactor and cleant up dead code
Cherry pick of 9d43de59301abfd187a5db80a34b830e0ea4ae4b
> Remove leftover unused lint exceptions (#4676)

- test/modules/TwinTester/TwinAllOperationsInitializer.cs
There is a new exception I haven't seen indicating transient network outages. I believe this to be the cause of some TwinTest errors we are seeing in longhaul.
Here is an example:
```
[2021-03-15 21:59:05.024 WRN] Error in periodic operation TwinTestStateUpdate
Microsoft.Azure.Devices.Common.Exceptions.IotHubException: The operation was canceled.
---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
---> System.Net.Sockets.SocketException (125): Operation canceled
--- End of inner exception stack trace ---
at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
at …
```
> TwinTester: Accommodate new exception indicating network failure (#4605)

- mqtt/mqtt-bridge/src/upstream/events/remote.rs
- mqtt/mqtt-bridge/src/upstream/rpc/mod.rs
- mqtt/mqtt-bridge/tests/common.rs
- mqtt/mqtt-bridge/tests/integration.rs
- mqtt/mqtt-bridge/tests/rpc.rs
- mqtt/mqtt-broker/benches/dispatch_messages.rs
- mqtt/mqtt-broker/benches/persist_broker_state.rs
For some reasons when EdgeHub starts up it make several concurrent attempts to subscribe to $iothub topics. It causes first attempt to succeed and the second one to fail with a timeout.
The changes to treat RPC subsctioption commands as individual even for the same topic.
cherry-pick `491fd97`
> [mqtt] handle RPC sub requests (#4602)

- edgelet/contrib/config/linux/default.toml
- edgelet/contrib/config/linux/template.toml
- edgelet/iotedge/src/config/super_config.rs
The official 1.2 agent image will be tagged upon release. For now, set the latest official agent image (1.2.0-rc4)
> Set default agent version to 1.2.0-rc4

- edgelet/contrib/config/linux/default.toml
- edgelet/contrib/config/linux/template.toml
- edgelet/iotedge/src/config/super_config.rs
The official 1.2 agent image will be tagged upon release. For now, set the latest official agent image (1.2.0-rc4)
Cherry-pick of d7ad36670f711eae30a0b920d9952a35e8303e21
> Set default agent version to 1.2.0-rc4 (#4702)

- builds/e2e/templates/connectivity-deploy.yaml
- builds/e2e/templates/longhaul-deploy.yaml
We updated the dashboard queries to accommodate for nested test pipelines. Because of this, dashboard expects some more contextual information to be sent up to display properly.
> Test Dashboard: Allow longhaul / connectivity pipelines to show with new dashboard queries

- edgelet/Cargo.lock
34e7a6c7253c7091a9949cdccbfee93fad5761fa exposed a bug in certd that set
the issuer name of self-signed certs to the subject name from the CSR
rather than the overridden common name in the certd config. So the Edge CA
would be issued with subject name "iotedge workload ca &lt;hostname&gt;" and
issuer "iotedge workload ca", which made it a non-self-signed cert.
This was fixed in certd in
https://github.com/Azure/iot-identity-service/commit/9c7c8deeb5efefb02f1d4db37766743bf75a9d65
> Fix self-signed edge-ca cert to use its subject name as the issuer name.

- test/Microsoft.Azure.Devices.Edge.Test/Provisioning.cs
- test/Microsoft.Azure.Devices.Edge.Test/SetupFixture.cs
- test/Microsoft.Azure.Devices.Edge.Test/helpers/Context.cs
- test/Microsoft.Azure.Devices.Edge.Test/helpers/ManualProvisioningFixture.cs
- test/Microsoft.Azure.Devices.Edge.Test/helpers/X509ManualProvisioningFixture.cs
Right now it is very hard to setup E2E test on a local box. Docs need updates and not all error messages are useful.
In this PR I'm trying to improve most of the cases where we can encounter E2E setup error.
> Make E2E setup errors actionable for developers.

- test/Microsoft.Azure.Devices.Edge.Test/Provisioning.cs
- test/Microsoft.Azure.Devices.Edge.Test/SetupFixture.cs
- test/Microsoft.Azure.Devices.Edge.Test/helpers/Context.cs
- test/Microsoft.Azure.Devices.Edge.Test/helpers/ManualProvisioningFixture.cs
- test/Microsoft.Azure.Devices.Edge.Test/helpers/X509ManualProvisioningFixture.cs
Right now it is very hard to setup E2E test on a local box. Docs need updates and not all error messages are useful.
In this PR I'm trying to improve most of the cases where we can encounter E2E setup error.
> Make E2E setup errors actionable for developers. (#4705)

- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/RoutingModule.cs
All items need to be resolved before awaiting, as the context is not valid when the thread resumes.
> Fix resolving BrokeredCloudProxyDispatcher

- edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/InvalidMountException.cs
- edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/edgedeployment/deployment/KubernetesDeploymentMapper.cs
- edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/edgedeployment/pvc/KubernetesPvcMapper.cs
- edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/KubernetesDeploymentMapperTest.cs
- edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/edgedeployment/pvc/KubernetesPvcMapperTest.cs
Most data coming from createOptions is applied to the PodSpec if set, but Mounts are a slightly different story, it has three critical fields, and the Type and Source must be set, or else we don't know how to handle the mount.
Creating an invalid mount in the Mounts section of createOptions was throwing a Null Reference exception, which appears to be marked as a fatal exception, and it causes edgeAgent to crash.  A better experience is to check the fields we need and throw a non-fatal exception.  This also lets us report back to the user what went wrong more clearly, doesn't crash edgeAgent, and allows for a graceful recovery once the problem is fixed.
I did do a check of the other mappers, and I am reasonably certain the mappers changed in this PR are the ones which will most likely …
> [k8s] Throw non-fatal exception if Mounts missing critical data.

- builds/e2e/templates/nested-agent-deploy.yaml
- e2e_deployment_files/nestededge_middleLayerBaseDeployment_amqp.json
- e2e_deployment_files/nestededge_topLayerBaseDeployment_amqp.json
- e2e_deployment_files/nestededge_topLayerBaseDeployment_mqtt.json
- scripts/linux/nested-edge-deploy-agent.sh
- smoke/IotEdgeQuickstart/details/IotedgedLinux.cs
- test/Microsoft.Azure.Devices.Edge.Test.Common/DaemonConfiguration.cs
- test/Microsoft.Azure.Devices.Edge.Test/helpers/SasManualProvisioningFixture.cs
- test/Microsoft.Azure.Devices.Edge.Test/helpers/X509ManualProvisioningFixture.cs
This PR is intended to bring back the nested pipeline to basic running state.
- Took the opportunity to use super config for the lvl 4 and lvl5 and use apt-get instead of dpckg
- The lvl4 and lvl5 was fixed the right way, however I was lacking the bandwidth to fix the quickstart + Microsoft.Azure.Devices.Edge.Test the right way. Just made a quick fix to get it to work
https://dev.azure.com/msazure/One/_build/results?buildId=40961617&view=logs&j=e8afecc0-c259-5cc1-62e0-5c5d1c2a3db4&t=f401ce77-605a-59dc-34fb-0bcc6cca03c5
> Fixing broken nested pipeline

- test/modules/TestResultCoordinator/Reports/DirectMethod/LongHaul/DirectMethodLongHaulReport.cs
In another PR i decreased the DeviceNotFound tolerance because I saw that on amd64 we didn't have it happen too often. I am restoring the old tolerance for two reasons:
- It looks like now it is teetering right on the edge of the tolerance causing longhaul tests to fail incorrectly.
- Arm devices will have a longer edgehub restart time and will thus have more DeviceNotFoundExceptions
> Longhaul: Increase direct method DeviceNotFound tolerance

- smoke/IotEdgeQuickstart/details/IotedgedLinux.cs
- test/Microsoft.Azure.Devices.Edge.Test.Common/DaemonConfiguration.cs
- test/Microsoft.Azure.Devices.Edge.Test.Common/linux/EdgeDaemon.cs
- test/Microsoft.Azure.Devices.Edge.Test/SetupFixture.cs
- test/Microsoft.Azure.Devices.Edge.Test/helpers/ManualProvisioningFixture.cs
Files left by previous runs would affect the current runs. Delete these files so that pipeline runs start fresh.
> Remove files created by previous pipeline runs

- edgelet/edgelet-docker/src/config.rs
- edgelet/iotedge/src/check/checks/check_agent_image.rs
- Replace `$upstream` in the Edge Agent image spec and auth config
with the parent hostname.
- Fix the version regex to use `'\.` instead of `.` to match `.`
- Fix the version check to not crash when the regex doesn't match the image,
and when the captures can't be parsed as version components.
> Fix check-agent-image-version check for nested Edge scenarios.

- edgelet/edgelet-docker/src/config.rs
- edgelet/iotedge/src/check/checks/check_agent_image.rs
Cherry-pick from master of 146f530520eed20aae4103f4b168d1db0aff1b1b
- Replace `$upstream` in the Edge Agent image spec and auth config
with the parent hostname.
- Fix the version regex to use `'\.` instead of `.` to match `.`
- Fix the version check to not crash when the regex doesn't match the image,
and when the captures can't be parsed as version components.
> Fix check-agent-image-version check for nested Edge scenarios. (#4742)

- edgelet/iotedge/src/main.rs
@arsing grepping for `iotedged` in `iotedge` includes references to `"iotedged workload ca my-device"`. Should this be renamed to something else as well?
> Remove references to 'iotedged' from `iotedge` help text

- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/AmqpWebSocketListener.cs
- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/IWebSocketListener.cs
- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Http/HttpProxiedCertificateExtractor.cs
- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Http/controllers/HttpRequestAuthenticator.cs
- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Http/middleware/WebSocketHandlingMiddleware.cs
- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/MqttWebSocketListener.cs
- edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.Http.Test/WebSocketHandlingMiddlewareTest.cs
For websockets connection the authentication needs to fail at subprotocol level to send the unauthorized to the client. 
It does the check in websockets middleware and if that fails it sets the Authenticator to NullAuthenticator. I think it is a little  weird, but otherwise would need to change the authenticator to receive the proxy token and do the proxy authentication there, better not to change it  now.
> Fix ws auth with cert over ApiProxy 

- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/NestedDeviceScopeApiClient.cs
- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/Constants.cs
- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Http/controllers/DeviceScopeController.cs
- edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.Http.Test/DeviceScopeControllerTest.cs
Issue: EdgeHub allows child EdgeHubs to get device/module information for the devices in their scope (l3/$edgeHub can ask for l3child information to l4/$edgeHub). But a child EdgeHub should not be able to ask for information on identities that are not its descendants. But the current code did not do this check. Consequently a child edgeHub (say l3/$edgeHub) can ask for information on an identity that is not its child (say l4child) and be able to receive it. 
Fix: Before returning the information to the requesting child, also check if the target device/module is one of its descendants.
> Fix getDeviceAndModuleOnBehalfOf to check if target device is in scope

- edgelet/aziot-edged/src/error.rs
- edgelet/aziot-edged/src/lib.rs
This change caches device provisioning state on each restart. This is used to compare the device provisioning result on each restart with the previous provisioning state, so that modules can be deleted if state has changed.
This fixes the issue of iotedge removing all modules on startup, even when provisioning state was the same.
Cherry-pick of d9be1e994cf556c27d991bf34cc8f9ad9754a9ea
> Cache device provisioning state (#4722)

- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Http/controllers/RegistryController.cs
- edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.Http.Test/RegistryControllerTest.cs
Issue: The Registry APIs exposed by the EdgeHub are used to CRUD module identities. 
For nested scenarios, special on-behalf-of APIs are supported, which allows the parent EdgeHub to CRUD module identities on behalf of the child. 
Imagine a topology like l5->l4->l3. If a module is added to l3, then the EdgeHub on l4 and l5 need to make the call to create the module on l3. For this they use the "on-behalf-of" api. Same applies to list/delete as well. 
But currently the code does not check if the caller is making the call on behalf of a descendant. This allowed, for example, l4, to CRUD modules on behalf of l5!
Fix:
Get the auth chain from the current EdgeHub to the target, and make sure the caller is on that auth chain. For example, then l4 makes a call to l5, to create a module on l3, …
> Registry API On-behalf-of calls auth check fix

- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/AmqpMessageConverter.cs
- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/SystemProperties.cs
- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/device/DeviceMessageHandler.cs
- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/routing/RoutingEdgeHub.cs
- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/ProtocolGatewayMessageConverter.cs
- edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.Amqp.Test/AmqpMessageConverterTest.cs
- edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/DeviceMessageHandlerTest.cs
- edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/routing/RoutingTest.cs
- edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.Mqtt.Test/ProtocolGatewayMessageConverterTest.cs
Issue: EdgeHub supports routing twin change notifications, which basically includes routing RP updates to other modules. The message that gets routed should have information about the device that sent the RP update. 
But because of a recent change in EH, this information got dropped. 
https://github.com/Azure/iotedge/issues/4689
Fix: Fix is to route the information about the device/module that sent the RP update to the receiving module.
> Send connection device Id information on twin change notifications

- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/AmqpWebSocketListener.cs
- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/IWebSocketListener.cs
- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Http/HttpProxiedCertificateExtractor.cs
- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Http/controllers/HttpRequestAuthenticator.cs
- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Http/middleware/WebSocketHandlingMiddleware.cs
- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/MqttWebSocketListener.cs
- edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.Http.Test/WebSocketHandlingMiddlewareTest.cs
For websockets connection the authentication needs to fail at subprotocol level to send the unauthorized to the client. 
It does the check in websockets middleware and if that fails it sets the Authenticator to NullAuthenticator. I think it is a little  weird, but otherwise would need to change the authenticator to receive the proxy token and do the proxy authentication there, better not to change it  now.
> Fix ws auth with cert over ApiProxy  (#4756)

- edge-modules/api-proxy-module/src/main.rs
- edge-modules/api-proxy-module/src/monitors/certs_monitor.rs
Fixes issue 9653726
At start up API proxy waits for the trust bundle and server cert before starting. 
However if we get them too close together, it will receive only one event.
There is a "debouncing" of event made by the signaling system:
`Notify provides two APIs. The default API debounces events (if the backend reports two similar events in close succession, Notify will only report one).`
2 possible fixes:
1. Easy fix: remove debouncing. One liner. Though I am not sure of the impact. 
2. Change a bit the starting strategy, wait the have both cert before sending 1 signal.
This PR implements strategy 2, because the fix only impact start up. Once API proxy is running code path is same as before.
Test:
Stop and restarted API proxy 150 times.
> Fix API proxy race condition

- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs
- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/CommonModule.cs
- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/RoutingModule.cs
When we connect upstream, we verify that identity is in scope. This is done in order to avoid poisoning telemetry queue with the telemetry from disabled devices.
On a fresh start, we may not yet received the scopes from the upstream, so we need to force add edgeHub in the cache so it is able to connect upstream. Later in the startup process, once we get the scopes from the upstream, this record is replaced.
> Add edgeHub identity to the scopes cache at the startup. (#4760)

- edge-modules/api-proxy-module/src/main.rs
- edge-modules/api-proxy-module/src/monitors/certs_monitor.rs
Fixes issue 9653726
At start up API proxy waits for the trust bundle and server cert before starting. 
However if we get them too close together, it will receive only one event.
There is a "debouncing" of event made by the signaling system:
`Notify provides two APIs. The default API debounces events (if the backend reports two similar events in close succession, Notify will only report one).`
2 possible fixes:
1. Easy fix: remove debouncing. One liner. Though I am not sure of the impact. 
2. Change a bit the starting strategy, wait the have both cert before sending 1 signal.
This PR implements strategy 2, because the fix only impact start up. Once API proxy is running code path is same as before.
Test:
Stop and restarted API proxy 150 times.
> Fix API proxy race condition (#4768)

- smoke/IotEdgeQuickstart/details/IotedgedLinux.cs
- test/Microsoft.Azure.Devices.Edge.Test.Common/DaemonConfiguration.cs
- test/Microsoft.Azure.Devices.Edge.Test.Common/linux/EdgeDaemon.cs
This is needed to remove old provisioning data that might affect the current test run.
> Set auto_reprovisioning_mode to AlwaysOnStartup in tests

- edgelet/edgelet-http-workload/src/server/cert/mod.rs
The logic for renewing the edge workload CA certificate was measuring expiration based on epoch instead of current time. Fixed the logic to look at current time instead.
Cherry-pick of 04e78bd850815303c613fd19292e6c1b231fec31
> Fix for expired CA certificate not renewing (#4798)

- mqtt/mqtt-bridge/src/bridge.rs
- mqtt/mqtt-bridge/src/messages.rs
- mqtt/mqtt-bridge/src/persist/loader.rs
- mqtt/mqtt-bridge/src/persist/mod.rs
- mqtt/mqtt-bridge/src/persist/publication_store.rs
- mqtt/mqtt-bridge/src/persist/waking_state/memory/error.rs
- mqtt/mqtt-bridge/src/persist/waking_state/memory/mod.rs
- mqtt/mqtt-bridge/src/persist/waking_state/memory/test.rs
- mqtt/mqtt-bridge/src/persist/waking_state/mod.rs
- mqtt/mqtt-bridge/src/persist/waking_state/ring_buffer/error.rs
- mqtt/mqtt-bridge/src/persist/waking_state/ring_buffer/mod.rs
- mqtt/mqtt-bridge/src/persist/waking_state/ring_buffer/test.rs
- mqtt/mqtt-bridge/src/pump/egress.rs
There is a bug in the MessageLoader which does not filter out publications after they've loaded from storage. It caused message duplicates to be sent to the $upstream sometimes out of order.
Adds a filtering step to prevent duplicates to be sent when a new batch is loaded.
Changes `fn remove(key)` -> `fn pop()` to reflect the fact we cannot remove publication by any key.
cherry-pick `0c0536a`
> [mqtt] Filter out publication duplicates in MessageLoader (#4745)

- mqtt/Cargo.lock
- mqtt/mqtt-bridge/src/persist/loader.rs
- mqtt/mqtt-bridge/src/persist/mod.rs
- mqtt/mqtt-bridge/src/pump/egress.rs
Previously egress part of the message pump was just logging an error and continue. 
These changes makes pump exit with corresponding error when persist or publish error occurred. That will lead to the whole chain to stop and restart `Egress -> Pump -> Bridge`.
Loader unexpected state error returned when loader has loaded keys off the new loaded batch instead of panic.
cherry-pick `08678d5`
> [mqtt] egress pump errors out when either persist or publish error occurred (#4790)

- test/Microsoft.Azure.Devices.Edge.Test.Common/DaemonConfiguration.cs
- test/Microsoft.Azure.Devices.Edge.Test/SetupFixture.cs
Adds the Edge Agent image and container registry specified in context.json to aziot-edged's config.toml.
> Fix usage of edgeAgent from context.json

- edge-modules/api-proxy-module/docker/linux/arm32v7/Dockerfile
- edge-modules/api-proxy-module/docker/linux/arm64v8/Dockerfile
Updating base image for API proxy arm32 and aarch64.
Test:
https://dev.azure.com/msazure/One/_build/results?buildId=41155753&view=results
Deployed in nested hierarchy of PI with Tier1 OS (Raspbian stretch)
No anomaly observed.
> Updating base image (#4795)

- edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/KubernetesEnvironmentOperator.cs
In what looks like a merge error, "task" is awaited twice in KubernetesEnvironmentOperator. This may have the effect of silently shutting down the Environment operator when the "ListPods" fails in specific ways.
> Remove extraneous "await" on task.

- edge-util/src/Microsoft.Azure.Devices.Edge.Util/ClientTokenProvider.cs
- edge-util/src/Microsoft.Azure.Devices.Edge.Util/edged/version_2019_01_30/WorkloadClient.cs
- edge-util/test/Microsoft.Azure.Devices.Edge.Util.Test/ClientTokenProviderTest.cs
EdgeHub makes a call to the Workload API SignAsync to get a token every time it needs one. If too many such calls are made, some of them could fail. 
This code adds logic to cache a previously obtained token, and reuse it. The cache duration is half of the token expiry duration, after which it should get a fresh token.
> EdgeHub: Add caching to TokenProvider

- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/NestedDeviceScopeApiClient.cs
HttpClient has default timeout to 100seconds and when it times out it throws TaskCanceledException and call is not retried.
This change is setting timeout to 5 min for http client and uses TimeoutAfter which throws TimeoutException
> update http client timeout for scope sync

- tools/BaseImageUpdate/baseImage.ps1
Update base image update script to not include `generic-mqtt-tester` base image.
> Update base image update script to not include `generic-mqtt-tester` base image.

- edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs
- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/EdgeHubCertificates.cs
- edge-util/src/Microsoft.Azure.Devices.Edge.Util/CertificateHelper.cs
While processing manifest trust bundle, check if its empty as its an optional field and configure accordingly. It avoids crashing of modules if its not set.
> [fix] check for empty string while processing manifest trust bundle

- test/modules/Relayer/MessageHandlerContext.cs
- test/modules/Relayer/Program.cs
- test/modules/Relayer/Settings.cs
Currently there is a test bug where edgehub will duplicate a message from loadGen to relayer (acceptable behavior). This duplication causes the TRC to have duplicate expected results, which it is not configured to handle. The TRC will intentionally fail the tests for duplicate expected results, so this test bug results in a test failure for acceptable behavior.
The best fix I think is to filter the duplicates in the relayer test module up to some threshold. I have introduced ```DuplicateMessageAuditor``` in order to filter these duplicates.
Copied from DuplicateMessageAuditor abstraction:
```
// Sometimes EdgeHub itself will duplicate a message when sending to this module.
// When this happens, we don't want to report two expected results to the TRC, as
// the TRC intentionally will fail …
```
> Longhaul: Filter duplicate results in relayer (#4682)

- tools/BaseImageUpdate/baseImage.ps1
Update base image update script to not include `generic-mqtt-tester` base image.
Cherry-picked: https://github.com/Azure/iotedge/commit/0b6bace379d6a4241c6b44af1970d88cd5838b13
> Update base image update script to not include `generic-mqtt-tester`

- e2e_deployment_files/long_haul_deployment.template.json
- e2e_deployment_files/nestededge_bottomLayerBaseDeployment_long_haul_amqp.template.json
- e2e_deployment_files/nestededge_bottomLayerBaseDeployment_long_haul_mqtt.template.json
We should run with debug logs enabled for edge agent in longhaul. Since we have log rotation configured this should be fine.
> Longhaul: Run with debug logs for edge agent

- mqtt/Cargo.lock
- mqtt/edgelet-client/Cargo.toml
- mqtt/edgelet-client/src/lib.rs
- mqtt/edgelet-client/src/workload/client.rs
- mqtt/mqtt-util/Cargo.toml
- mqtt/mqtt-util/src/client_io.rs
Long waited upgrade to a new major version (v2) of `percent-encoding` crate
> [mqtt] upgrade percent-encoding to v2

- mqtt/Cargo.lock
- mqtt/mqttd/Cargo.toml
- mqtt/mqttd/src/tracing/edgehub.rs
- mqtt/mqttd/src/tracing/format.rs
- mqtt/mqttd/src/tracing/mod.rs
Bring back edgehub-like tracing logs after upgrade.
I added additional features which adds styling to log entries by it looks bag for logs inside container. It can be enabled with adding `ansi` feature when compiled
> [mqtt] Make tracing looks like edgehub logs again

- test/modules/Modules.Test/TestResultCoordinator/Reports/CountingReportGeneratorTest.cs
- test/modules/Modules.Test/TestResultCoordinator/Reports/CountingReportTest.cs
- test/modules/Modules.Test/TestResultCoordinator/Reports/TwinCountingReportGeneratorTest.cs
- test/modules/Modules.Test/TestResultCoordinator/TestReportUtilTest.cs
- test/modules/TestResultCoordinator/Reports/CountingReport.cs
- test/modules/TestResultCoordinator/Reports/CountingReportGenerator.cs
… (#4684)
We need to account for duplicate expected results in our tests. The test report operates with an assumption that expected results are unique and actual results can be duplicated. When duplicate expected results happen (due to product issues), the test report makes it seem like we are missing some actual results. But we need to make it explicit that there are duplicate expected results, which should not be happening in our tests.
Here is what I mean. Imagine the following scenario:
```
Message 0 sent
Message 1 sent
Message 1 sent
Message 2 sent
~ time passes ~
Message 0 received
Message 1 received
Message 1 received
Message 2 received
``` 
In the TRC here are the expected / actual datastructures:
```
Expected: 0->1->1->2
Actual: 0->1->1->->2
```
When the TRC is processing the …
> TestResultCoordinator: Explicitly fail for duplicate expected results (#4684)

- test/modules/Modules.Test/TestResultCoordinator/Reports/CountingReportGeneratorTest.cs
- test/modules/Modules.Test/TestResultCoordinator/Reports/CountingReportTest.cs
- test/modules/Modules.Test/TestResultCoordinator/TestReportUtilTest.cs
- test/modules/TestResultCoordinator/Reports/CountingReport.cs
- test/modules/TestResultCoordinator/Reports/CountingReportGenerator.cs
In longhaul sometimes product bugs happen where actual results get misordered such that the following case happens:
```
Expected: 1 -> 2 -> 3 -> 4 -> 5-> 6 -> 7
Actual: 1 -> 2 -> 3 -> 4 -> 2 -> 5 -> 6 -> 7
```
The current test logic assumes that misordered actual results are not possible, and will fail to match results 5, 6, and 7 treating them as unmatched. This renders the TRC report useless for any result after the first misordered actual result. 
Instead of this behavior we want it to match all these results, but report that there was one misordered actual result. I have added logic to detect these misordered actual results to the counting report. If this situation occurs it will fail the tests.
> Longhaul: Track misordered actual results

- edgelet/edgelet-http/Cargo.toml
- edgelet/edgelet-http/src/lib.rs
- edgelet/edgelet-http/src/windows.rs
- edgelet/iotedge-proxy/src/routine.rs
- edgelet/kube-client/examples/pod-list.rs
schannel and native-tls require a PKCS#12 blob of the device ID certificate
to use it as a TLS client cert. Before this change, the blob was created
using openssl even on Windows. However, with such a blob, schannel creates
the private key on disk under the user's persisted keys directory.
Since iotedged runs as LocalSystem, this was
C:\ProgramData\Microsoft\Crypto\RSA\S-1-5-18
It's empirically known that schannel doesn't create the disk file if
the private key is marked as "exportable". Since "exportable" is
a Windows-specific attribute, openssl doesn't have any way to set it.
So this commit uses winapi to create the PKCS#12 blob instead.
Other changes:
- Revert two uses of single-threaded tokio runtime back to multi-threaded.
deb2753bc2e36bf2355ddb9427262e5d93d96d72 accidentally changed …
>  Fix Windows construction of identity cert PKCS#12 blob to not leak keys to disk.

- builds/e2e/e2e.yaml
- builds/e2e/proxy/configure_runner.sh
- builds/e2e/templates/e2e-run.yaml
- edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2020_07_07/ModuleManagementHttpClient.cs
- test/Microsoft.Azure.Devices.Edge.Test/EdgeAgentDirectMethods.cs
- test/Microsoft.Azure.Devices.Edge.Test/IoTEdgeCheck.cs
- test/Microsoft.Azure.Devices.Edge.Test/PlugAndPlay.cs
- Re-enable E2E pipeline job to run tests in proxy environment
- Fixed some tests to run using Websockets transport (which is generally the case for E2E tests)
- Improve UploadSupportBundle test reliability in self-host environment by reducing requested log time range
- Fixed typo in traces within UploadSupportBundle product code
- Filtered out Nested Edge tests and temporarily filtered out tests that timeout in proxy environment
> Re-enable E2E proxy test

- builds/e2e/templates/e2e-setup.yaml
- test/Microsoft.Azure.Devices.Edge.Test.Common/config/EdgeConfigBuilder.cs
- test/Microsoft.Azure.Devices.Edge.Test.Common/config/HubModuleConfigBuilder.cs
- test/Microsoft.Azure.Devices.Edge.Test.Common/config/ModuleConfigBuilder.cs
- test/Microsoft.Azure.Devices.Edge.Test/GenericMqtt.cs
- test/Microsoft.Azure.Devices.Edge.Test/PlugAndPlay.cs
- test/Microsoft.Azure.Devices.Edge.Test/PriorityQueues.cs
- test/Microsoft.Azure.Devices.Edge.Test/helpers/Context.cs
- test/Microsoft.Azure.Devices.Edge.Test/helpers/MqttBrokerUtil.cs
- test/Microsoft.Azure.Devices.Edge.Test/helpers/TestResultCoordinatorUtil.cs
- test/README.md
- test/modules/generic-mqtt-tester/src/lib.rs
- test/modules/generic-mqtt-tester/src/message_channel.rs
- test/modules/generic-mqtt-tester/src/message_initiator.rs
- test/modules/generic-mqtt-tester/src/settings.rs
- test/modules/generic-mqtt-tester/src/tester.rs
This PR is adding an E2E test for custom mqtt topics using the existing ```genericMqttTester``` image we run in longhaul. 
This test will deploy edgehub with the broker enabled and two genericMqttTester modules. One genericMqttTester module will be in initiate mode and the other will be in relay mode. The initiate mode module will publish on an mqtt topic ```initiate/1``` and the relaying module will subscribe to this topic. When the relaying module receives a message, it will publish it back on ```relay/1```. The initiating module will be subscribed on this ```relay/1``` topic and will report to the TRC when it receives the message.
In addition to adding the test it:
1. Refactors shared logic into util abstractions for cleaner code. Specifically adding the broker/TRC to the deployment. …
> E2E: Add regression test for custom mqtt topics

- edgelet/iotedged/src/lib.rs
Removes all containers after a device reprovision. This is done because identities for containers might no longer be valid after the reprovision. Edgelet will refresh the identities on its next run.
Resolves #4458
> Delete all containers after reprovision

- test/modules/generic-mqtt-tester/Cargo.lock
- test/modules/generic-mqtt-tester/Cargo.toml
- test/modules/generic-mqtt-tester/src/lib.rs
- test/modules/generic-mqtt-tester/src/main.rs
- test/modules/generic-mqtt-tester/src/message_channel.rs
- test/modules/generic-mqtt-tester/src/message_initiator.rs
- test/modules/generic-mqtt-tester/src/tester.rs
- test/rust-test-util/test-result-reporting-client/Cargo.toml
Upgrades `generic-mqtt-tester` to tokio1 ecosystem.
Use local dependencies from local path instead of pinning
> [mqtt] generic-mqtt-tester tokio1 upgrade

- edge-util/src/Microsoft.Azure.Devices.Edge.Util/Logger.cs
- edge-util/test/Microsoft.Azure.Devices.Edge.Util.Test/LoggerTest.cs
This is to address [security bug in logging](https://msazure.visualstudio.com/One/_workitems/edit/9554724)
According to the bug, we can use the `j` format specifier to reduce to a single-line JSON string. Also, from documentation we can apply this on the outputTemplate itself: https://github.com/serilog/serilog/wiki/Formatting-Output
> Resolve security concern in logging

- builds/e2e/templates/e2e-run.yaml
- test/Microsoft.Azure.Devices.Edge.Test/AuthorizationPolicy.cs
- test/Microsoft.Azure.Devices.Edge.Test/GenericMqtt.cs
- test/Microsoft.Azure.Devices.Edge.Test/MqttBridgeConfig.cs
- test/Microsoft.Azure.Devices.Edge.Test/PlugAndPlay.cs
Three things in this PR:
1. Our nested E2E tests are running broker-specific tests without the broker which is causing test failures (i.e. BridgeConfigUpdate). We need to implement a filter so that we don't run these broker specific tests without the broker enabled. I named this filter ```BrokerRequired```.
2. I am also adding a filter to the PlugAndPlay (```LegacyMqttRequired```)tests to only run with the legacy mqtt protocol head. These currently have very confusing logic around an extra broker enabled flag that always gets ignored. A filter will work much better.
3. Some tests were manually being filtered because of an outstanding PBI. The PBI is now done so I have removed the manual filter.
I think in general we should move to replace these manual test filters with Category filters. I …
> Nested E2E: Add filters for broker-specific tests

- test/Microsoft.Azure.Devices.Edge.Test.Common/linux/PackageManagement.cs
I want to enable aziot-edge install from Microsoft prod. This is useful for dev box scenarios where we don't care about specific version of runtime, but fine with the latest officially published.
This is first PR from a possible series of PRs to make our E2E tests dev box friendly.
> [E2E]: Enable aziot-edge install from Microsoft prod

- e2e_deployment_files/nestededge_bottomLayerBaseDeployment_long_haul_mqtt.template.json
- test/modules/generic-mqtt-tester/src/message_channel.rs
- test/modules/generic-mqtt-tester/src/settings.rs
- test/modules/generic-mqtt-tester/src/tester.rs
We originally decided to have a relaying structure for the custom mqtt tests where there is a module sending messages upstream on the bottom edge and a message relaying these same messages back down on the middle edge. The purpose of this is so that all test modules that reported to the TRC could sit on the bottom layer. This leant itself towards a simpler test setup because:
- the test modules on the upper edge device did not need to know the ip address of the lower edge
- the test modules on the upper edge device did not need to worry about transient errors when making http requests to the TRC on the bottom edge
- the TRC on the bottom edge device did not need to have its ports bound to the host
There is a problem though because the middle level edge is not actually generating its own …
> Custom Mqtt Test Module: Add Initiate and Receive modes

- CodeCoverage.runsettings
- builds/checkin/dotnet.yaml
- builds/ci/dotnet.yaml
- builds/misc/images-release.yaml
- builds/misc/images.yaml
- builds/templates/install-dotnet2.yaml
- edge-modules/functions/samples/EdgeHubTrigger-Csharp/EdgeHubTriggerCSharp.csproj
- edge-modules/functions/samples/README.md
- edge-modules/functions/samples/docker/linux/amd64/Dockerfile
- edge-modules/functions/samples/docker/linux/arm32v7/Dockerfile
- edge-modules/functions/samples/docker/windows/amd64/Dockerfile
- scripts/linux/buildBranch.sh
- test/Microsoft.Azure.Devices.Edge.Test/Module.cs
Reverts Azure/iotedge#4856
I believe this change broke CI and checkin pipeline. https://dev.azure.com/msazure/One/_build/results?buildId=41761951&view=results
> Revert "Update functions to 3.0"

- edgelet/Cargo.lock
- edgelet/edgelet-http-workload/src/server/cert/mod.rs
v3 is correct for certificates (`X509`) but not for CSRs (`X509Req`).
> Fix Edge CA and module cert CSRs to use version 0 (v1) instead of non-existent version 2 (v3).

- edgelet/Cargo.lock
- edgelet/iotedge/src/config/apply.rs
- edgelet/iotedge/test-files/config/ca-certs-est/certd.toml
- edgelet/iotedge/test-files/config/ca-certs-est/keyd.toml
Fix a bug where the EST auth certs for the Edge CA cert were using the IDs of the device ID cert.
> iotedge config apply: fix auth certs for EST-issued Edge CA

- edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Edgelet.Docker.Test/CombinedEdgeletConfigProviderTest.cs
- edge-modules/azure-monitor/src/ExampleDeployment.json
- edge-modules/azure-monitor/src/IotHubUpload/IotHubUpload.cs
- edge-modules/azure-monitor/src/README.md
- edge-modules/azure-monitor/src/Settings.cs
Introducing new option to trasnsform/flatten the Metrics prior to publish as IoT Messages.
**Publishing with transform option OFF:**
[{
"TimeGeneratedUtc": "<time generated>",
"Name": "<prometheus metric name>",
"Value": <decimal value>,
"Label": {
"<label name>": "<label value>"
}
}, {
"TimeGeneratedUtc": "2020-07-28T20:00:43.2770247Z",
"Name": "docker_container_disk_write_bytes",
"Value": 0.0,
"Label": {
"name": "AzureMonitorForIotEdgeModule"
}
}]
**Publishing with transform option ON:**
{
"TimeGeneratedUtc": "<time generated>",
"edge_device": "<device bame>",
"instance_number": "<instance number>",
"<prometheus metric name>": {
"value": <decimal value>,
"from": "<value of: 'from', 'module_name', or 'id' if exists>",
"from_route_output": "<value of: 'from_route_output', 'route_output', …
> Metrics transform option

- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/config/BridgeConfig.cs
- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/config/BrokerConfigValidator.cs
- edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/config/BrokerPropertiesValidatorTest.cs
- mqtt/mqtt-bridge/src/config_update.rs
- mqtt/mqtt-bridge/src/controller/bridges.rs
- mqtt/mqtt-bridge/src/controller/mod.rs
Context: We need to properly handle EdgeHub faulty bridge configuration.
After some offline discussion, there are two scenarios that we identified:
- First time deployment: if wrong config is set, EdgeHub should reject the twin, report the error via LastDesiredStatus and stop. It should not proceed with startup and open any public ports b/c we are running the risk of losing messages.
- Subsequent deployments: if wrong config is set, EdgeHub should reject the twin, report LastDesiredStatus and continue with previous configuration. This is (I believe) existing behavior.
In this PR I have updated bridge config validation to allow empty settings for `$upstream` bridge and improved error messages.
Also, removed unnecessary `BridgeUpdate::name()` property in favor of `BridgeUpdate::endpoint()`
> Update bridge config validation. (#4788)

- test/Microsoft.Azure.Devices.Edge.Test/GenericMqtt.cs
- test/modules/generic-mqtt-tester/README.md
- test/modules/generic-mqtt-tester/src/tester.rs
I accidentally broke end to end tests when adding a new mode to the custom mqtt test module. I took this as an opportunity to address some of Roberts comments on my cherry pick I didn't address before. Also fixed the README.
> Custom Mqtt Test Module: Restore E2E tests (#4913)

- doc/devguide.md
This change resolves issue #4917. I added periods at the end of the notes section for each dependency in the "Run Integration Tests"
> Added consistent grammar to notes section

- e2e_deployment_files/long_haul_deployment.template.json
- e2e_deployment_files/nestededge_bottomLayerBaseDeployment_long_haul_amqp.template.json
- e2e_deployment_files/nestededge_bottomLayerBaseDeployment_long_haul_mqtt.template.json
- scripts/linux/trcE2ETest.sh
Simple fix needed to remove connectivity specific settings from TRC env vars in longhaul deployment.
> Longhaul: Remove connectivity specific `VerificationDelay` from TRC (#4901)

- builds/e2e/connectivity.yaml
- builds/e2e/longhaul.yaml
1. Reinstitute LongHaul IotHub for both SingleNode for testing
2. Consolidate KeyVault variables so the same type of tests are sharing the same IoTHub.
Remark: With the keyVault variable consolidation (2), a developer can now inject his own keyVault into the pipeline to have any of the test pipeline connect upstream to his/her own IoTHub. The two required "secrets" in the developer's keyVaults are `IotHub-ConnStr` (IoTHub Connection String) and `IotHub-EventHubConnStr` (IoTHub's built-in EventHub Endpoint Connection String)
> Update the KeyVault for Test pipelines

- kubernetes/charts/edge-kubernetes/templates/iotedged-deployment.yaml
- kubernetes/charts/edge-kubernetes/values.yaml
This will allow the users to set the loglevel on iotedged pod for debugging purposes. 
Default is "info" for iotedged.
> [k8s] Add iotedged.data.runtimeLogLevel to helm chart settings.

- edgelet/Cargo.lock
- edgelet/iotedge/src/config/import/mod.rs
- edgelet/iotedge/test-files/config/dps-x509/identityd.toml
- edgelet/iotedge/test-files/config/dps-x509/old-config.yaml
- edgelet/iotedge/test-files/config/dps-x509/super-config.toml
The `iotedge config import` tool will now support 1.1 configuration where registration_id was optional for DPS X.509 provisioning.
This PR is dependent on https://github.com/Azure/iot-identity-service/pull/212
> Registration ID is optional in super-config

- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/twin/ReportedPropertiesValidator.cs
- edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/twin/ReportedPropertiesValidatorTest.cs
Add validation for null props inside objects inside arrays.
Since IoT Hub does not support patch operations on arrays (if you want to update array, you need to replace it), they don't allow null values or null properties inside arrays. EdgeHub, on the other hand, allows that. So, validation can pass on the EdgeHub side, but the update will be rejected by the hub. This situation allows for sending bad payloads, that blocks any further twin updates unless bad property is removed/cleared.
> Add validation for null props inside objects inside arrays. (#4896)

- edge-modules/azure-monitor/src/MetricsScrapeAndUpload.cs
- edge-modules/azure-monitor/src/Program.cs
The metrics collector built by the azure monitor team copied some test-specific logic from our metrics collector used for testing. I am removing it as we don't intend to provide this feature for obsv1.
> Metrics Collector: Remove test-specific additional tags logic

- edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/CbsNode.cs
- edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/TokenHelper.cs
- edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/authenticators/CloudTokenAuthenticator.cs
- edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/authenticators/DeviceScopeTokenAuthenticator.cs
- edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/authenticators/TokenCacheAuthenticator.cs
- edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Http/middleware/AuthenticationMiddleware.cs
- edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Test/DeviceScopeTokenAuthenticatorTest.cs
- edge-util/src/Microsoft.Azure.Devices.Edge.Util/SharedAccessSignature.cs
- edge-util/src/Microsoft.Azure.Devices.Edge.Util/SharedAccessSignatureAuthrorizationRule.cs
- edge-util/src/Microsoft.Azure.Devices.Edge.Util/SharedAccessSignatureConstants.cs
- edge-util/src/Microsoft.Azure.Devices.Edge.Util/StringValidationHelper.cs
- edge-util/test/Microsoft.Azure.Devices.Edge.Util.Test/SharedAccessSignatureTest.cs
This is a cherry-pick of https://github.com/Azure/iotedge/pull/4943
This adds a subset of the code from https://github.com/Azure/azure-iot-sdk-csharp for SharedAccessSignature directly into our repo. This will also need to be cherry-picked into 1.1 and 1.2.
Todo:
> Adds SharedAccessSignature to repo with fix for vulnerability (#4943)

- builds/misc/images.yaml
- builds/misc/metrics-collector-images-publish.yaml
- builds/misc/metrics-collector-images-release.yaml
Adding images release and publish pipelines for the metrics collector. Approach was taken from the implementation we have in `master` branch for the api proxy.
> Metrics Collector: Release and publish pipelines

- edgelet/api/README.md
- edgelet/api/managementVersion_2020_07_07.yaml
- edgelet/api/managementVersion_2021_05_11.yaml
- edgelet/doc/devguide.md
- edgelet/edgelet-core/src/module.rs
- edgelet/edgelet-docker/src/runtime.rs
- edgelet/edgelet-http-mgmt/src/client/module.rs
- edgelet/edgelet-http-mgmt/src/server/module/logs.rs
- edgelet/management/docs/Identity.md
- edgelet/management/docs/IdentityApi.md
- edgelet/management/docs/IdentitySpec.md
- edgelet/management/docs/ModuleApi.md
- edgelet/management/docs/ModuleSpec.md
- edgelet/management/docs/SystemInfo.md
- edgelet/management/docs/SystemInformationApi.md
- edgelet/management/src/apis/module_api.rs
- Allow Management socket to accept `timestamps` option to be pass through docker socket API.
- Update the documents for the latest API version
- The latest API is being manually added since there is a gigantic out-of-sync between the template interface `managementVersion_2020_07_07.yaml` and `/edgelet/management` generated code.
> Introduce `Timestamps` Option via mgmt.sock

- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/DeviceScopeIdentitiesCache.cs
- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/identity/service/ServiceIdentity.cs
- edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/DeviceScopeIdentitiesCacheTest.cs
cherry-pick #4889 
Edgehub version 1.1 didn't have DeviceScope and ParentScopes in storage and updating to 1.2 fails to start edgeHub because reading from cache fails. 
Fix is to check the service identity that was read from storage for current device (from actorDeviceId) and if the DeviceScope is empty that means it is a restore from older version (edge devices should always have DeviceScope) and set the value for DeviceScope from device details (deviceId and generationId). For leaf devices it sets DeviceScope and ParentScopes to the edge device scope because if the device was in store it must be a child of the edge device and sync from cloud will update the leaf device in case it was removed as child.
This fixes #4828
> Restore device scopes from older store (version < 1.2) (#4889)

- edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/logs/LogsProcessor.cs
- edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/logs/LogsProvider.cs
- edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/versioning/ModuleManagementHttpClientVersioned.cs
- edge-util/src/Microsoft.Azure.Devices.Edge.Util/uds/HttpChunkedStreamReader.cs
Cherry-picked: https://github.com/Azure/iotedge/commit/2b650a8b90d5b51299ef24c002e5af39c481c253
TL;DR - This PR chances the behavior of `GetModuleLogs` method to better facilitate the portal experience. 
Previous, when the `GetModuleLogs` is triggered from the azure portal with `tail + since + until`, all the 3 options are passed to Docker API management to fetch the log. The Docker API does the following: 
1. Fetch the log of the module
2. Apply `tail` to the log
3. Apply the `since` and `until` to the log
This results in an empty log most of the time which is not a desirable behavior. 
This PR changes the `GetModuleLogs` when the `tail + since + until` are specified together by doing the following:
1. Fetch Docker API with `since + until` log option
2. `tail` the returning log using …
> Update `GetModuleLogs` method when `tail + since + until` options are provided

- edgelet/api/README.md
- edgelet/api/managementVersion_2021_05_11.yaml
- edgelet/doc/devguide.md
- edgelet/edgelet-core/src/module.rs
- edgelet/edgelet-docker/src/runtime.rs
- edgelet/edgelet-http-mgmt/src/client/module.rs
- edgelet/edgelet-http-mgmt/src/server/module/logs.rs
- edgelet/management/docs/Identity.md
- edgelet/management/docs/IdentityApi.md
- edgelet/management/docs/IdentitySpec.md
- edgelet/management/docs/ModuleApi.md
- edgelet/management/docs/ModuleSpec.md
- edgelet/management/docs/SystemInfo.md
- edgelet/management/docs/SystemInformationApi.md
- edgelet/management/src/apis/module_api.rs
Cherry-pick: https://github.com/Azure/iotedge/commit/37c661bcbae1b2b2506e54d102a14ea1b6f8bb3c
- Allow Management socket to accept `timestamps` option to be pass through docker socket API.
- Update the documents for the latest API version
- The latest API is being manually added since there is a gigantic out-of-sync between the template interface `managementVersion_2020_07_07.yaml` and `/edgelet/management` generated code.
> Introduce `Timestamps` Option via mgmt.sock 

- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/storage/MessageStore.cs
- edge-hub/src/Microsoft.Azure.Devices.Routing.Core/checkpointers/Checkpointer.cs
- edge-util/src/Microsoft.Azure.Devices.Edge.Storage.RocksDb/ColumnFamilyDbStore.cs
- edge-util/src/Microsoft.Azure.Devices.Edge.Storage/DbStoreDecorator.cs
- edge-util/src/Microsoft.Azure.Devices.Edge.Storage/EncryptedStore.cs
- edge-util/src/Microsoft.Azure.Devices.Edge.Storage/EntityStore.cs
- edge-util/src/Microsoft.Azure.Devices.Edge.Storage/IKeyValueStore.cs
- edge-util/src/Microsoft.Azure.Devices.Edge.Storage/ISequentialStore.cs
- edge-util/src/Microsoft.Azure.Devices.Edge.Storage/InMemoryDbStore.cs
- edge-util/src/Microsoft.Azure.Devices.Edge.Storage/KeyValueStoreMapper.cs
- edge-util/src/Microsoft.Azure.Devices.Edge.Storage/NullKeyValueStore.cs
- edge-util/src/Microsoft.Azure.Devices.Edge.Storage/SequentialStore.cs
- edge-util/src/Microsoft.Azure.Devices.Edge.Storage/TimedEntityStore.cs
cherry-pick: https://github.com/Azure/iotedge/pull/4952
> Cherry-pick to Release/1.1: Fix edgehub queue len metric (#4952)

- edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Edgelet.Test/commands/CreateOrUpdateCommandTest.cs
Hello,
This pull request is _very simple_ and aims to reduce the technical debt. It specifically targets the "IEnumerable LINQs should be simplified" [rule](https://rules.sonarsource.com/csharp/RSPEC-2971)  in SonarQube.
> Fix SonarQube's "IEnumerable LINQs should be simplified" / Code Smell

- edgelet/Cargo.lock
- edgelet/edgelet-core/Cargo.toml
- edgelet/edgelet-docker/src/settings.rs
Updates deps where possible to avoid `cargo audit` errors. Currently, edgelet is using a parse_duration crate that has a security vulnerability but no safe upgrade! So, FYI on that...
> Edgelet RUSTSEC dep update

- builds/e2e/e2e.yaml
- builds/e2e/templates/e2e-run.yaml
- builds/e2e/templates/e2e-setup.yaml
- builds/mariner/SPECS/rust/rust.spec
- builds/misc/images.yaml
- builds/misc/packages.yaml
- builds/misc/templates/image-linux-rust-jobs.yaml
- edgelet/build/linux/package-mariner.sh
- edgelet/build/windows/install.ps1
- edgelet/hsm-sys/azure-iot-hsm-c/CMakeLists.txt
- edgelet/hsm-sys/azure-iot-hsm-c/tests/CMakeLists.txt
- test/Microsoft.Azure.Devices.Edge.Test.Common/EdgeLogs.cs
- test/Microsoft.Azure.Devices.Edge.Test.Common/EdgeModule.cs
- test/Microsoft.Azure.Devices.Edge.Test.Common/Microsoft.Azure.Devices.Edge.Test.Common.csproj
- test/Microsoft.Azure.Devices.Edge.Test.Common/ProcessEx.cs
- test/Microsoft.Azure.Devices.Edge.Test.Common/linux/OsPlatform.cs
- test/Microsoft.Azure.Devices.Edge.Test.Common/windows/EdgeDaemon.cs
- test/Microsoft.Azure.Devices.Edge.Test.Common/windows/OsPlatform.cs
Prior to this change, the Azure DevOps pipelines described by YAML files in this repo ran on either (1) Microsoft-hosted Linux and Windows agents or (2) custom-built agents hosted and maintained by the product team. The Microsoft-hosted agents are great because someone else manages their maintenance, but they're also shared among many teams so availability can be a problem. The custom-built agents have better availability but require more care and attention.
To get better availability and control with a reduced maintenance burden, this change converts the YAML pipelines to refer to 1ES-hosted agents (1ES is Microsoft's internal engineering system). These agents are defined by the product team but are maintained by 1ES.
This change only impacts three pipelines: Build Images (images.yaml), …
> Update v1.1 YAML pipelines to 1ES-hosted agents

- test/rust-test-util/test-result-reporting-client/Cargo.lock
Updates dependencies that violate RUSTSEC
<details>
<summary>Cargo Audit</summary>
```
Scanning Cargo.lock for vulnerabilities (79 crate dependencies)
Crate:         hyper
Version:       0.13.9
Title:         Multiple Transfer-Encoding headers misinterprets request payload
Date:          2021-02-05
ID:            RUSTSEC-2021-0020
URL:           https://rustsec.org/advisories/RUSTSEC-2021-0020
Solution:      Upgrade to >=0.14.3 OR >=0.13.10, <0.14.0 OR >=0.12.36, <0.13.0
Dependency tree:
hyper 0.13.9
└── trc-client 0.1.0
Crate:         net2
Version:       0.2.37
Warning:       unmaintained
Title:         `net2` crate has been deprecated; use `socket2` instead
Date:          2020-05-01
ID:            RUSTSEC-2020-0016
URL:           https://rustsec.org/advisories/RUSTSEC-2020-0016 …
```
> test-result-reporting-client update RUSTSEC deps

- tools/check_submodules/Cargo.lock
Updates lock file with deps that do not have security issues
<details>
<summary> Cargo Audit </summary>
```
Crate:         smallvec
Version:       0.6.12
Title:         Buffer overflow in SmallVec::insert_many
Date:          2021-01-08
ID:            RUSTSEC-2021-0003
URL:           https://rustsec.org/advisories/RUSTSEC-2021-0003
Solution:      Upgrade to >=0.6.14, <1.0.0 OR >=1.6.1
Dependency tree:
smallvec 0.6.12
└── unicode-normalization 0.1.8
└── idna 0.1.5
└── url 1.7.2
└── git2 0.7.5
└── check_submodules 0.1.1
Crate:         failure
Version:       0.1.6
Warning:       unmaintained
Title:         failure is officially deprecated/unmaintained
Date:          2020-05-02
ID:            RUSTSEC-2020-0036
URL:           https://rustsec.org/advisories/RUSTSEC-2020-0036
Dependency tree: …
```
> check_submodules update RUSTSEC deps

- builds/e2e/templates/e2e-run.yaml
The end-to-end test logs are published as artifacts in the pipeline run, and have names like `logs-end-to-end-{buildnum}-linux-amd64-iotedged-ubuntu18.04-amd64`. As we add more jobs to the pipeline, we can't tell the logs apart by their names (e.g. we now have two Ubuntu 18.04 jobs, two Ubuntu 20.04 jobs, and two Windows jobs). 
This update changes the names to something like `logs-end-to-end-{buildnum}-ubuntu-1804-docker`, based on the job name. It should make it easier to tell published logs apart from one another.
Note something similar was already done in the main branch, see #3722.
> Rename end-to-end test log artifacts

- CHANGELOG.md
Includes 
* Fix Diagnostics Module's Websocket behind proxy. [6b32f3c](https://github.com/Azure/iotedge/commit/6b32f3c7b3f492aa12e418013844e46540bed9d5)
For the release
> Prepare for Release1.1.3 (part 2)

- test/modules/generic-mqtt-tester/docker/linux/arm32v7/Dockerfile
- test/modules/generic-mqtt-tester/docker/linux/arm64v8/Dockerfile
Fixing this:
https://ubuntu.com/security/notices/USN-4906-1
I pushed the new base images already. This PR is to bump the base image versions so the new base image is used.
> Fix security vulnerability in mqtt test module

- test/modules/generic-mqtt-tester/docker/linux/arm32v7/Dockerfile
- test/modules/generic-mqtt-tester/docker/linux/arm64v8/Dockerfile
Fixing this:
https://ubuntu.com/security/notices/USN-4906-1
I pushed the new base images already. This PR is to bump the base image versions so the new base image is used.
> Fix security vulnerability in mqtt test module (#5045)

- builds/e2e/templates/nested-longhaul-deploy.yaml
A change I made to single node longhaul broke nested longhaul deployment. I made a silly error when doing the test checks, otherwise I would have caught it.
The fix is to remove the twin update frequency param, as this parameter has been removed from the `runTrcE2ETest.sh`
> Nested Longhaul Tests: Fix nested longhaul deployment

- e2e_deployment_files/nestededge_bottomLayerBaseDeployment_long_haul_mqtt.template.json
Fixing a typo in the `generic-mqtt-tester` TestScenario enum.
> Nested Longhaul Tests: Fix typo in test scenario

- edgelet/edgelet-docker/src/runtime.rs
**Context:**
We use [Sysinfo](https://docs.rs/sysinfo/0.18.0/sysinfo/) crate to get host metrics and processes info. By default it keeps `/proc/...` files open for perf optimizations. Unfortunately, there could be many processes/threads in the host system, so `sysinfo` can consume a lot of FDs.
**Solution:**
After looking into details of `sysinfo`, I found out that we can limit the number of FDs it can use.
Also, maybe we don't need to refresh everything if we don't use that?
> Limit sysinfo crate FDs usage.

- edgelet/Cargo.lock
- edgelet/aziot-edged/src/lib.rs
- edgelet/identity-client/src/client.rs
- edgelet/iotedge/src/system.rs
- Clear the provisioning state cache when a reprovision is triggered.
- Request reprovisioning if edged cannot get device information on startup.
Depends on https://github.com/Azure/iot-identity-service/pull/229
> Fix provisioning behavior when DPS changes

- edgelet/edgelet-docker/src/runtime.rs
**Context:**
We use [Sysinfo](https://docs.rs/sysinfo/0.18.0/sysinfo/) crate to get host metrics and processes info. By default it keeps `/proc/...` files open for perf optimizations. Unfortunately, there could be many processes/threads in the host system, so `sysinfo` can consume a lot of FDs.
**Solution:**
After looking into details of `sysinfo`, I found out that we can limit the number of FDs it can use.
Also, maybe we don't need to refresh everything if we don't use that?
> Limit sysinfo crate FDs usage. (#5055)

- e2e_deployment_files/long_haul_deployment.template.json
- e2e_deployment_files/nestededge_bottomLayerBaseDeployment_long_haul_amqp.template.json
- e2e_deployment_files/nestededge_bottomLayerBaseDeployment_long_haul_mqtt.template.json
- scripts/linux/trcE2ETest.sh
- test/modules/DirectMethodSender/DirectMethodSenderBase.cs
- test/modules/DirectMethodSender/Program.cs
- test/modules/TestResultCoordinator/Reports/DirectMethod/Connectivity/DirectMethodConnectivityReportGenerator.cs
- test/modules/TestResultCoordinator/TestReportUtil.cs
- test/modules/generic-mqtt-tester/src/lib.rs
- test/modules/generic-mqtt-tester/src/message_channel.rs
- test/modules/generic-mqtt-tester/src/message_initiator.rs
- test/modules/load-gen/DefaultMessageSender.cs
This PR contains these improvements:
1. Bump edgehub log rotation size (arm will very soon have a separate deployment where it will be fixed)
2. Disable debug logs for edge agent
3. Explicitly catch unauthorized exceptions for direct method tests (uncovered one instance with 1.2.1 testing)
4. Move test event delays to beginning of the sequence, so if an operation fails it is not immediately retried.
5. Restore compression for log upload
6. GenericMqttTester: Don't fail out for transient dns errors
> Nested Longhaul Tests: Various small improvements 

- edge-util/src/Microsoft.Azure.Devices.Edge.Util/uds/HttpChunkedStreamReader.cs
- edge-util/src/Microsoft.Azure.Devices.Edge.Util/uds/HttpUdsMessageHandler.cs
We can do a better job of disposing UDS for Workload Client.
> Properly dispose UDS for Workload Client. (#5035)

- test/modules/MetricsValidator/src/tests/ValidateDocumentedMetrics.cs
Skip the "twin signing" metrics for E2E tests until manifest signing is put into the tests.
These metrics are only generated when manifest signing is enabled and not all tests will have manifest signing turned on.
> Skip the "twin signing" metrics for E2E tests

- edge-util/src/Microsoft.Azure.Devices.Edge.Util/uds/HttpUdsMessageHandler.cs
In my previous pr #5035 I tried to optimize disposing of UDS. That fix was incorrect, since we rely on the fact that Stream is still open when we return `HttpResponseMessage` from `SendAsync`. Later, the consumer of `SendAsync` will dispose the `HttpResponseMessage` and it will in turn dispose the `Stream` and `Socket`.
> Don't dispose stream too early.

- edge-util/src/Microsoft.Azure.Devices.Edge.Util/uds/HttpUdsMessageHandler.cs
In my previous pr #5035 I tried to optimize disposing of UDS. That fix was incorrect, since we rely on the fact that Stream is still open when we return `HttpResponseMessage` from `SendAsync`. Later, the consumer of `SendAsync` will dispose the `HttpResponseMessage` and it will in turn dispose the `Stream` and `Socket`.
> Don't dispose stream too early. (#5097)

- edgelet/Makefile
- edgelet/contrib/centos/00-aziot-edged.preset
- edgelet/contrib/centos/aziot-edge.spec
Enables aziot-edged during postinstall so that it starts automatically.
> Enable aziot-edged in CentOS package

- builds/misc/addons-publish.yaml
- builds/misc/addons-release.yaml
- builds/misc/images-release.yaml
- scripts/linux/buildImage.sh
- scripts/linux/buildManifest.sh
In #5109 we missed a comma. Even though the builds still worked we need to clean it up. 
Also there was some script help that I mistakenly did not remove.
> Docker login: Removing typo and not-needed script help

- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/brokerConnection/MqttBrokerConnector.cs
so operation will be retried if no mqttclient exists.
The problem occurred when EdgeHub was shutting down but a message was being sent upstream. As the protocol head was stopped, that cleared the mqttclient client, so the send operation in SendAsync() threw an 'Exception' instance, which was not retriable by CloudEndpoint, so it just skipped the message.
> Fixed exception type in BrokerConnection::SendAsync, 

- builds/e2e/templates/e2e-run.yaml
`continueOnError: true` has one unfortunate side effect - it marks the step as `Warning` instead of `Error`. It can lead to some confusion and inability to easily retry the pipeline.
I'd like to revert the change where we mark failed tests as warnings. If we need any other steps to run after failed tests, we should use `condition: succeededOrFailed()` on those steps.
> Mark tests as failed on failure. (#5105)

- tools/IoTEdgeDevOps/DevOpsLib/BugQueryGenerator.cs
- tools/IoTEdgeDevOps/DevOpsLib/BuildManagement.cs
- tools/IoTEdgeDevOps/VstsPipelineSync/VstsBuildBatchUpdate.cs
For the bug opening changes, it will be cleaner if we refactor the sync job to promote cleaner modifications.
Currently the reverse callstack for the relevant part of the sync job works like this:
```
- RunAsync
- foreach branch
- ImportVstsBuildsData
- ImportVstsBuildsDataForSpecificDefinition
- GetBuildsAsync(definition)
- UpsertToDB
- Get the most recent build timestamp, track this, then pass it all the way up the callstack to store in double hashmap
```
It will be cleaner if we get the builds and update the most recent timestamps upfront in some encapsulated function. Then we can pass the list of bugs into the ImportVstsBuildsDataForSpecificDefinition and whatever function I create in a future PR to automatically log bugs. Here is what the new reverse callstack looks like:
```
- …
```
> Devops Sync Job: Refactor to facilitate incoming bug opening automation changes

- test/modules/MetricsValidator/src/tests/ValidateDocumentedMetrics.cs
Skipped `edgeAgent_created_pids_total` metric for ARM32
> E2E: Skipped `edgeAgent_created_pids_total` metric for ARM32

- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/upstream/BrokeredCloudProxyDispatcher.cs
- edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/BrokeredCloudProxyDispatcherTest.cs
instead of using 0 (which is a result of uninitialized status property)
> fix: in case of error, propagate back error code of edgeHub  (#4929)

- tools/IoTEdgeDevOps/DevOpsLib/BugQueryGenerator.cs
- tools/IoTEdgeDevOps/DevOpsLib/BuildManagement.cs
- tools/IoTEdgeDevOps/DevOpsLib/VstsModels/VstsBuild.cs
- tools/IoTEdgeDevOps/VstsPipelineSync/VstsBuildBatchUpdate.cs
- tools/IoTEdgeDevOps/VstsPipelineSync/db/dbo.UpsertVstsBuild.sql
- tools/IoTEdgeDevOps/VstsPipelineSync/db/dbo.VstsBuild.sql
For the devops sync job we only want to open bugs for scheduled builds. This is because devs often misconfigure or try weird things with manual builds.
In order to accomplish this we need to add to the builds database a field for if the build was scheduled or not. I played around with the api and the easiest way to do this is to check who the build is requested for. If it is requested by `` then it is a scheduled build.
> Devops Sync Job: Add WasScheduled field to database of builds

- edgelet/iotedge/src/check/checks/storage_mounted_from_host.rs
This adds a helpful addition to container state check. This does not try to determine if a deployment has reached the device or not, as that would involve some sort of communication with portal. So, log message improvement is likely best we can do.
> Improve log message for container state

- e2e_deployment_files/connectivity_deployment.template.json
- e2e_deployment_files/dm_module_to_module_deployment.json
- e2e_deployment_files/edgehub_restart_deployment.template.json
- e2e_deployment_files/long_haul_deployment.template.json
- e2e_deployment_files/module_to_functions_deployment.template.json
- e2e_deployment_files/module_to_module_deployment.template.json
- e2e_deployment_files/nestededge_bottomLayerBaseDeployment_connectivity_mqtt.template.json
- e2e_deployment_files/nestededge_bottomLayerBaseDeployment_long_haul_amqp.template.json
- e2e_deployment_files/nestededge_bottomLayerBaseDeployment_long_haul_mqtt.template.json
- e2e_deployment_files/nestededge_isa95_smoke_test_BaseDeployment.json
- e2e_deployment_files/nestededge_middleLayerBaseDeployment_amqp.json
- e2e_deployment_files/nestededge_middleLayerBaseDeployment_mqtt.json
- e2e_deployment_files/nestededge_topLayerBaseDeployment_amqp.json
- e2e_deployment_files/nestededge_topLayerBaseDeployment_mqtt.json
- e2e_deployment_files/quickstart_deployment.template.json
- e2e_deployment_files/runtime_only_deployment.template.json
- e2e_deployment_files/stress_deployment.template.json
- test/Microsoft.Azure.Devices.Edge.Test.Common/EdgeRuntime.cs
We need to resolve an s360 error for non tls 1.2 violations in our test environment. I am switching all tests to use tls 1.2 via edgehub environment.
Relevant config added in #2052.
> Testing: Apply tls 1.2 settings for all tests

- test/modules/MetricsValidator/src/tests/ValidateDocumentedMetrics.cs
Skipped `edgeAgent_created_pids_total` metric for ARM32
> E2E: Skipped `edgeAgent_created_pids_total` metric for ARM32 (#5134)

- builds/checkin/dotnet.yaml
- edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/IRuntimeInfoProvider.cs
- edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/logs/ILogMessageParser.cs
- edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/logs/LogMessageParser.cs
- edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/logs/LogsProvider.cs
- edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/logs/ModuleLogFilter.cs
- edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Docker/RuntimeInfoProvider.cs
- edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/IModuleManager.cs
- edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/ModuleManagementHttpClient.cs
- edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/RuntimeInfoProvider.cs
- edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/versioning/ModuleManagementHttpClientVersioned.cs
- edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/blob/AzureBlobRequestsUploader.cs
- edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/KubernetesRuntimeInfoProvider.cs
- edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/logs/LogsProcessorTest.cs
- edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/logs/LogsProviderTest.cs
- edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/logs/LogsRequestToOptionsMapperTests.cs
- edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/requests/LogsRequestHandlerTests.cs
- edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/requests/LogsUploadRequestHandlerTest.cs
- edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Docker.Test/RuntimeInfoProviderTest.cs
- edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Edgelet.Test/ModuleManagementHttpClientTest.cs
- edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Edgelet.Test/RuntimeInfoProviderTest.cs
- edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.IoTHub.Test/stream/LogsStreamRequestHandlerTest.cs
- edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.IntegrationTest/DummyModuleManager.cs
- test/Microsoft.Azure.Devices.Edge.Test/EdgeAgentDirectMethods.cs
Context:
It generates the attached file, if a module does not use the prescribed logging format (which most module do not), the timestamp is 0. This makes the logs not very useful. The timestamp irrespective of logging format is actually available from Docker log API.
Solution: 
This PR issues `timestamps` from edgeAgent via mgmt.sock to prepending the returning log with timestamp.  edgeAgent then parse the timestamp & return the value in json format to portal.
Note: 
This feature requires https://github.com/Azure/iotedge/pull/4970
> Use Docker Timestamp When Log Timestamp is not Available in JSON log (#4981)

- edgelet/api/README.md
- edgelet/api/managementVersion_2021_05_11.yaml
- edgelet/doc/devguide.md
- edgelet/edgelet-core/src/module.rs
- edgelet/edgelet-docker/src/runtime.rs
- edgelet/edgelet-http-mgmt/src/client/module.rs
- edgelet/edgelet-http-mgmt/src/server/module/logs.rs
- edgelet/management/docs/Identity.md
- edgelet/management/docs/IdentityApi.md
- edgelet/management/docs/IdentitySpec.md
- edgelet/management/docs/ModuleApi.md
- edgelet/management/docs/ModuleSpec.md
- edgelet/management/docs/SystemInfo.md
- edgelet/management/docs/SystemInformationApi.md
- edgelet/management/src/apis/module_api.rs
- Allow Management socket to accept `timestamps` option to be pass through docker socket API.
- Update the documents for the latest API version
- The latest API is being manually added since there is a gigantic out-of-sync between the template interface `managementVersion_2020_07_07.yaml` and `/edgelet/management` generated code.
> Introduce `Timestamps` Option via mgmt.sock (#4970)

- CodeCoverage.runsettings
- builds/checkin/dotnet.yaml
- builds/ci/dotnet.yaml
- builds/templates/install-dotnet2.yaml
- edge-modules/functions/samples/EdgeHubTrigger-Csharp/EdgeHubTriggerCSharp.csproj
- edge-modules/functions/samples/README.md
- edge-modules/functions/samples/docker/linux/amd64/Dockerfile
- edge-modules/functions/samples/docker/linux/arm32v7/Dockerfile
- edge-modules/functions/samples/docker/windows/amd64/Dockerfile
- scripts/linux/buildBranch.sh
- scripts/linux/runTests.sh
- scripts/windows/build/Publish-Branch.ps1
This reverts commit 3ab67a3a199f1bb47123f59f3310eb902f13f823.
Filters out bin folder when running tests to fix the tests failure issue. It's not clear why only in some runs the bin folder has the test dlls and not the runtimeconfig.json files which is causing the tests run to fail. Other times it was passing because the bin folder didn't contain the test dlls when running on different pipeline agent (but using same dotnet sdk and everything else looked the same)
> Update functions to 3.0 (#4910)

- edgelet/Cargo.lock
- edgelet/contrib/centos/aziot-edge.spec
- edgelet/contrib/debian/control
- edgelet/docker-rs/src/models/host_config.rs
- edgelet/edgelet-docker/src/runtime.rs
One of the review changes for the privileged flag, changing the CapAdd and CapDrop fields to Vec instead of Option<Vec> causes the all calls to docker to fail. I believe this is because it serializes as `null` instead of not being serialized at all. 
Changing it back to an option fixes the issue.
This also bumps the apt packages dependency to IS 1.2.1. This change is already in release/1.2, but got skipped in master
> Fix Privileged Flag

- builds/e2e/connectivity.yaml
- builds/e2e/e2e.yaml
- builds/e2e/nested-connectivity.yaml
- builds/e2e/nested-e2e.yaml
During a recent cherry pick from 1.2 -> master, we included an improvement to the triggers. This improvement worked but it set the branch setting to be "release/1.2". I am fixing this here so that the setting is "master".
> DevOps Triggers: Fix trigger setting for branch to be "master"

- tools/IoTEdgeDevOps/DevOpsLib/VstsModels/VstsBuild.cs
- tools/IoTEdgeDevOps/VstsPipelineSync/VstsBuildBatchUpdate.cs
- tools/IoTEdgeDevOps/VstsPipelineSync/docker/linux-amd64/Dockerfile
The main fix in this PR is changing the filter for date is by `QueueTime` to `FinishTime`. Using `QueueTime` will lead to problems for builds who take longer than 1 hr to complete.
I also improved the logic around filtering and also improved the logging.
> DevOps Sync Job: Improve and clean up filters, improve logging

- builds/checkin/dotnet.yaml
- edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/IRuntimeInfoProvider.cs
- edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/logs/ILogMessageParser.cs
- edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/logs/LogMessageParser.cs
- edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/logs/LogsProvider.cs
- edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/logs/ModuleLogFilter.cs
- edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Docker/RuntimeInfoProvider.cs
- edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/IModuleManager.cs
- edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/ModuleManagementHttpClient.cs
- edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/RuntimeInfoProvider.cs
- edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/versioning/ModuleManagementHttpClientVersioned.cs
- edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/blob/AzureBlobRequestsUploader.cs
- edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/KubernetesRuntimeInfoProvider.cs
- edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/logs/LogsProcessorTest.cs
- edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/logs/LogsProviderTest.cs
- edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/logs/LogsRequestToOptionsMapperTests.cs
- edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/requests/LogsRequestHandlerTests.cs
- edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/requests/LogsUploadRequestHandlerTest.cs
- edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Docker.Test/RuntimeInfoProviderTest.cs
- edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Edgelet.Test/ModuleManagementHttpClientTest.cs
- edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Edgelet.Test/RuntimeInfoProviderTest.cs
- edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.IoTHub.Test/stream/LogsStreamRequestHandlerTest.cs
- edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.IntegrationTest/DummyModuleManager.cs
- test/Microsoft.Azure.Devices.Edge.Test/EdgeAgentDirectMethods.cs
Derived from https://github.com/Azure/iotedge/pull/4981
Context:
It generates the attached file, if a module does not use the prescribed logging format (which most module do not), the timestamp is 0. This makes the logs not very useful. The timestamp irrespective of logging format is actually available from Docker log API.
Solution: 
This PR issues `timestamps` from edgeAgent via mgmt.sock to prepending the returning log with timestamp.  edgeAgent then parse the timestamp & return the value in json format to portal.
Note: 
This feature requires https://github.com/Azure/iotedge/pull/5172
> Use Docker Timestamp When Log Timestamp is not Available in JSON log.

- edgelet/iotedge/src/check/checks/container_connect_upstream.rs
- edgelet/iotedge/src/check/mod.rs
This adds a new CheckOutput that is for skipping a check but as a success. The goals of this pr are as follows:
* Proxy should only be used for port 443 since it is http_proxy. Test on port 8883 and 5671 should be run with no proxy, even if it is defined.
* If a user uses websocket, then we should not error if test fails on port 8883 and 5671. It is a perfectly fine configuration if that port is closed
* If a user uses MQTT, then we should only error if test fails on 8883 and only warn on 5671
* If a user uses AMQP, then we should only error if test fails on 5671and only warn on 8883
The first one in the list seems to have been done previously, but if that is believed to not be the case I will add it here. Manual testing was done to verify work. If there is a way to add more interesting …
> Update connectivity check on ports to skip checks when not needed

- edgelet/aziot-edged/src/lib.rs
- edgelet/aziot-edged/src/workload_manager.rs
- edgelet/edgelet-http/src/lib.rs
Implement throttling mechanism to prevent spamming of workload socket.
Test:
Created a separate module and ran the following command with the module.
seq 1 30000 | xargs -I % -P 1000 curl --unix-socket /var/run/iotedge/workload.sock  http://127.0.0.1/modules?api-version=2020-07-07 &> /dev/null&
I could not reproduce the broken pipe error but I could see parallelism go up to high 80s.
By adding the throttling it is limited to ~10
> Implement throttling mechanism to prevent spamming of workload socket

- tools/BaseImageUpdate/baseImage.ps1
- tools/snitch/snitcher/docker/windows/amd64/Dockerfile
Automate OS image update for AMD64
> Automate OS image update for AMD64

- test/Microsoft.Azure.Devices.Edge.Test/helpers/TestResultCoordinatorUtil.cs
This prints the test result json instead of an unhelpful json parse error
> Catch parse error in e2e test

- edgelet/edgelet-docker/src/runtime.rs
We made some changes to the system resource collection, where we called slightly different sysinfo apis in an attempt to optimize. This led to what I am guessing is a bug in the sysinfo crate. 
We can quickly resolve it if we roll back the commit that made these sysinfo modifications. However we should also keep the main improvement which was to set the open file descriptor limit.
> Fix host cpu metric incorrectly reported at 100%

- edgelet/edgelet-docker/src/runtime.rs
We made some changes to the system resource collection, where we called slightly different sysinfo apis in an attempt to optimize. This led to what I am guessing is a bug in the sysinfo crate. 
We can quickly resolve it if we roll back the commit that made these sysinfo modifications. However we should also keep the main improvement which was to set the open file descriptor limit.
> Fix host cpu metric incorrectly reported at 100% (#5204)

- edgelet/support-bundle/src/support_bundle.rs
Listing modules when generating a support bundle requires the management socket. If the management socket has not started, then the support bundle request blocks forever.
This PR adds a timeout to management socket requests to prevent the request from hanging.
> Add timeout to support bundle calls

- e2e_deployment_files/long_haul_deployment_constrained.template.json
- e2e_deployment_files/nestededge_middleLayerBaseDeployment_mqtt.json
- e2e_deployment_files/nestededge_topLayerBaseDeployment_amqp.json
- e2e_deployment_files/nestededge_topLayerBaseDeployment_mqtt.json
Need to make some fixes to some deployment files to fix their tls1.2 configurations. We should explore making this the default for edgehub, but it is potentially a breaking change which needs to be discussed in more detail. For now we are fixing it in the deployment files.
There are some remaining tls1.2 errors in http endpoints that this change won't fix. Still investigating those.
> S360: Fix Tls1.2 errors in deployment files

- e2e_deployment_files/long_haul_deployment_constrained.template.json
- e2e_deployment_files/nestededge_middleLayerBaseDeployment_mqtt.json
- e2e_deployment_files/nestededge_topLayerBaseDeployment_amqp.json
- e2e_deployment_files/nestededge_topLayerBaseDeployment_mqtt.json
Need to make some fixes to some deployment files to fix their tls1.2 configurations. We should explore making this the default for edgehub, but it is potentially a breaking change which needs to be discussed in more detail. For now we are fixing it in the deployment files.
There are some remaining tls1.2 errors in http endpoints that this change won't fix. Still investigating those.
> S360: Fix Tls1.2 errors in deployment files (#5225)

- builds/misc/images-publish.yaml
Upgrade Image Publication Pipeline. 
I added a new nice to have feature here as well: 
- Safe guard ensuring the input build image version is correct with what specified in /versionInfo.json. (So we don't accidentally grab 1.1.4 image and publish as 1.2.4 to MCR)
- One button click and done. A user no longer need to fill in miscellaneous parameters which prone to error. The pipeline will look into the repo & construct those parameters for you.  
- Utilized 1ES-Hosted pool for image build consistency.
> Upgrade Image Publication Pipeline

- test/Microsoft.Azure.Devices.Edge.Test/helpers/TestResultCoordinatorUtil.cs
This prints the test result json instead of an unhelpful json parse error
> Catch parse error in e2e test (#5214)

- edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.csproj
- edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/DeploymentSecretBackupTest.cs
- edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/EdgeDeploymentCommandTest.cs
- edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/KubernetesEnvironmentOperatorTest.cs
- edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/KubernetesServiceMapperTest.cs
- edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/edgedeployment/EdgeDeploymentOperatorTest.cs
- edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/edgedeployment/service/KubernetesServiceMapperTest.cs
Update to latest k8s client to address vulnerabilities in dependencies.
> [k8s] update k8s client.

- edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/logs/LogsProvider.cs
- edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/MetricsScraper.cs
- edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/ProxyReadinessProbe.cs
This another attempt to find and fix a potential issue where we don't dispose sockets in time.
For `GetModuleLogs` operation, we provide `HttpCompletionOption.ResponseHeadersRead` when calling `HttpClient.SendAsync()`. In this case, the response is not loaded into memory at once, but instead can be streamed. It implies, that we also need to properly dispose the stream so the connection is released ASAP.
> Make sure to dispose HttpContentStream when done reading module logs.

- edge-modules/azure-monitor/CHANGELOG.md
Updating the changelog with the commits going into the 1.0.1 release. When this commit lands I will tag the metrics collector release on the 1.1 branch.
> Metrics Collector Release: Update Changelog

- edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.E2E.Test/Cloud2DeviceTest.cs
- edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.E2E.Test/TwinDiffE2ETest.cs
Removed a tests which tested the same actions as another test that was left.
Test was flaky because sometimes the c2d message was sent in the same time the device was disconnected and sometimes edgeHub received it and immediately the device proxy was not available. Fixed to check the device in IotHub that the device was disconnected before sending C2D message.
> Remove redundant tests and wait for device to be disconnected

- builds/e2e/connectivity.yaml
- builds/e2e/nested-connectivity.yaml
- builds/e2e/nested-e2e.yaml
Disable automatic triggers in favor of periodic triggers for:
1. Nested E2E
2. Connectivity
3. Nested Connectivity
Once this is checked in I will add the periodic triggers through the DevOps interface.
> Medium Duration Tests: Disable automatic triggers in favor of periodic triggers

- builds/e2e/nested-longhaul.yaml
Nested longhaul is misconfigured for the release 1.2 branch. Fixing this so that scheduled runs work.
> Nested Longhaul Tests: Fix scheduled runs

- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/AmqpMessageConverter.cs
- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/Constants.cs
- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/DeviceClientMessageConverter.cs
- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/SystemProperties.cs
- edge-hub/core/src/Microsoft.Azure.Devices.Routing.Core/SystemProperties.cs
- edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.Amqp.Test/AmqpMessageConverterTest.cs
- edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Test/DeviceClientMessageConverterTest.cs
- edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.Mqtt.Test/ProtocolGatewayMessageConverterTest.cs
This adds support for the new ComponentName message property to edgeHub. This is a property used by pnp devices and was added to the SDK already
> Add ComponentName to message properties (#5234)

- edge-modules/functions/binding/src/Microsoft.Azure.WebJobs.Extensions.EdgeHub/Microsoft.Azure.WebJobs.Extensions.EdgeHub.csproj
- edge-modules/functions/samples/EdgeHubTrigger-Csharp/EdgeHubTriggerCSharp.csproj
Microsoft.NET.Sdk.Functions Uses an webjobs extension for http which has an older version of Microsoft.AspNetCore.Http and System.Text.Encodings.Web. Needed to update those packages to use 2.1.22 and 4.5.1 respectively to fix security warning.
> Update functions packages

- builds/e2e/connectivity.yaml
- builds/e2e/longhaul.yaml
- builds/e2e/nested-connectivity.yaml
- builds/e2e/nested-e2e.yaml
- builds/e2e/nested-longhaul.yaml
Setting up a daily morning and a daily nightly schedule for the following pipelines:
- Connectivity
- Nested Connectivity
- Nested E2E
- Longhaul
- Nested Longhaul
Since Nested Connectivity and Nested E2E share agents I have offset the start times by 6 hours.
Followed instructions from here:
https://docs.microsoft.com/en-us/azure/devops/pipelines/process/scheduled-triggers?view=azure-devops&tabs=yaml
> Medium Duration Tests: Add scheduled triggers through yaml

- builds/e2e/nested-longhaul.yaml
In #5264 I made a typo and added a duplicate `trigger` and `pr` block. Removing it here.
> Nested Longhaul Test: Fix duplicate trigger

- edge-modules/api-proxy-module/readme.md
- edge-modules/api-proxy-module/src/monitors/config_parser.rs
- edge-modules/api-proxy-module/templates/nginx_default_config.conf
Changing ssl protocols and ciphers.
If user don't define anything, nothing will be added and default config will be used.
If use define the env vars NGINX_DEFAULT_TLS   then it will appear like this in the config:
> Changing ssl protocols and ciphers

- edge-modules/api-proxy-module/docker/linux/amd64/Dockerfile
Run API proxy as unprivileged user.
Removing unneeded mapping.
> Run API proxy as unprivileged user

- edgelet/iotedge/src/main.rs
Add logic to append a timestamp of the the format "YYYY_MM_DD_HH_MI_SS_TMZ" to the default support
bundle filename. The --output option works as before and this change only applies when a desired
filename is not provided.
> Add timestamp to the default support-bundle filename

- builds/e2e/templates/e2e-run.yaml
- builds/e2e/templates/e2e-setup.yaml
- test/Microsoft.Azure.Devices.Edge.Test/helpers/TestResultCoordinatorUtil.cs
- test/connectivity/modules/NetworkController/Program.cs
The test `PriorityQueueModuleToHubMessages` was failing behind a proxy for the following reasons:
1. The network controller in the deployment was not setup with the proxy environment variable `https_proxy`
2. The network controller in the deployment was using a hacky configuration. It used a module client but overrode the `IOTEDGE_GATEWAYHOSTNAME` with empty string so that it would connect itself directly to iothub.  Since the `ModuleClient` was not initialized with a `TransportType` compatible with a proxy, the module never connected to iothub and hung.
3. Even once the network controller was configured with fixes for the above, it needed further proxy support in order to correctly apply the network rules to the proxy ip address, rather than iothub.
All of these issues are now fixed. I …
> E2E Tests: Re-enable priority proxy tests 

- edge-util/src/Microsoft.Azure.Devices.Edge.Util/Microsoft.Azure.Devices.Edge.Util.csproj
- edgelet/Cargo.lock
- tools/check_submodules/Cargo.lock
- tools/snitch/Cargo.lock
- tools/snitch/snitcher/Cargo.toml
Updates the following dependencies to resolve Component Governance issues:
- prometheus-net in edgelet-util
- http, hyper, failure, and linked-hash-map in edgelet
- smallvec in check_submodules
- http, hyper, rand_core, smallvec, and spin in snitch
> Update packages for Component Governance

- mqtt/Cargo.lock
- mqtt/mqtt-broker-tests-util/Cargo.toml
- mqtt/mqtt-broker/Cargo.toml
- mqtt/mqttd/Cargo.toml
- mqtt/mqttd/src/tracing/edgehub.rs
- mqtt/mqttd/src/tracing/format.rs
- mqtt/mqttd/src/tracing/generic.rs
This updates smallvec to 1.6.1 to fix a component governance security issue. It does so by updating tracing-subscriber to 0.2.
> RUSTSEC: Update smallvec for component governance

- builds/e2e/connectivity.yaml
- builds/e2e/nested-connectivity.yaml
- builds/e2e/nested-e2e.yaml
We need to decrease the frequency of these triggers so that we can also run scheduled builds on master branch.
> Devops Scheduled Test Triggers: Decrease frequency of triggers

- edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Docker/CombinedDockerConfigProvider.cs
- edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs
- edgelet/aziot-edged/src/lib.rs
- edgelet/edgelet-core/src/module.rs
- edgelet/edgelet-docker/src/config.rs
- edgelet/iotedge/src/check/checks/check_agent_image.rs
$upstream support for container address.
1. Support in azure portal
2. Support in aziot-edged
Tests:
Created a registry on lvl5 with a password then put $upstream in config and $upstream in portal. Checked that image got pulled.
Put a wrong password in portal, checked images failed with unauthorized (to confirm image were getting pulled from the right place)
> $upstream support for container registry address (#4932)

- edge-modules/MetricsCollector/docker/linux/amd64/Dockerfile
- edge-modules/MetricsCollector/docker/linux/arm32v7/Dockerfile
- edge-modules/MetricsCollector/docker/linux/arm64v8/Dockerfile
- edge-modules/MetricsCollector/docker/windows/amd64/Dockerfile
With the new version of prometheus, we now need to use aspnet base images for anything taking a dep on edge agent diagnostics csproj
> Test Metrics Collector: Use aspnet base image

- builds/e2e/templates/e2e-setup.yaml
I accidentally added this functionality back but it should stay removed.
> E2E Tests: Remove legacy method of running specific build (#5389)

- test/modules/generic-mqtt-tester/README.md
- test/modules/generic-mqtt-tester/src/settings.rs
Switched to is_none() rather than is_err() before merging my earlier PR. This addresses the problem.
> Custom Mqtt Tests: Fix error from optional topic suffix 

- test/connectivity/scripts/connectivityTest.sh
We were missing `directMethodSender3` in the connectivity log output
> Update logging for connectivity test output

- e2e_deployment_files/nestededge_middleLayerBaseDeployment_amqp.json
- e2e_deployment_files/nestededge_middleLayerBaseDeployment_mqtt.json
- e2e_deployment_files/nestededge_middleLayer_connectivity_mqtt.json
- e2e_deployment_files/nestededge_middleLayer_e2e_amqp.json
- e2e_deployment_files/nestededge_middleLayer_long_haul_mqtt.json
- e2e_deployment_files/nestededge_topLayerBaseDeployment_amqp.json
- e2e_deployment_files/nestededge_topLayerBaseDeployment_mqtt.json
We need to use tls 1.2 for api proxy to silence S360 flags.
> Nested Tests: Use tls 1.2 for api proxy

- tools/CACertificates/README.md
Readme.md updates to resolve https://msazure.visualstudio.com/One/_workitems/edit/10341855/?triage=true
> Update CACertificates links to docs

- edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Test/CloudProxyTest.cs
- edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.E2E.Test/EdgeToDeviceMethodTest.cs
- edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.E2E.Test/InMemoryDbStoreLimitsTest.cs
- edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.E2E.Test/TelemetryTest.cs
- edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.E2E.Test/TwinDiffE2ETest.cs
Disabling these CI tests as they are known to be flaky.  We can re-enable them later. Bugs are created to track each category.
> CI: Disable flaky tests

- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/ServiceIdentityTree.cs
Fixing #5155, it is now possible to connect device module through edgeHub as well as creating new modules.
Test:
Connected module through edgeHub using SAS token
Created new module through edgeHub.
> Create identities for leaf (#5381)

- edgelet/aziot-edged/src/workload_manager.rs
Fixed typo
Fix messages that cast away by unwrap_or(())
Added clean up of listener in case module is removed before being stopped.
> Fix logs, improved clean up

- builds/e2e/templates/e2e-run.yaml
- test/Microsoft.Azure.Devices.Edge.Test/Device.cs
- test/Microsoft.Azure.Devices.Edge.Test/DeviceWithCustomCertificates.cs
- test/Microsoft.Azure.Devices.Edge.Test/EdgeAgentDirectMethods.cs
- test/Microsoft.Azure.Devices.Edge.Test/Metrics.cs
- test/Microsoft.Azure.Devices.Edge.Test/Module.cs
- test/Microsoft.Azure.Devices.Edge.Test/PriorityQueues.cs
- test/Microsoft.Azure.Devices.Edge.Test/Provisioning.cs
- test/Microsoft.Azure.Devices.Edge.Test/X509Device.cs
We need to disable some flaky E2E tests to make sure we are getting good signal from the pipelines. These work items to re-enable are tracked with bugs.
> E2E: Disable flaky tests

- builds/e2e/connectivity.yaml
- builds/e2e/templates/connectivity-deploy.yaml
Migrate the single node connectivity test pipeline from self-hosted devops agents to 1ES-hosted agents.
> Use 1ES hosted agent for amd64 single-node connectivty tests

- edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.E2E.Test/Cloud2DeviceTest.cs
This test is flaky still in the CI pipeline so I am disabling:
Receive_C2D_SingleMessage_ShouldSucceed
> CI: Disable Receive_C2D_SingleMessage_ShouldSucceed

- builds/misc/metrics-collector-images-publish.yaml
Migration to 1ES host agent pool in the pipeline Metrics Collector Publish Release Images.
> Use 1ES hosted agent for Linux and Windows build.

- builds/misc/images-release.yaml
This only affects the Windows job because the Linux jobs use Microsoft hosted agents.
> Migrate images-release pipeline to use 1es agents

- test/Microsoft.Azure.Devices.Edge.Test/EdgeAgentDirectMethods.cs
This test was fixed to lookup the sas key from kv in PR https://github.com/Azure/iotedge/pull/3868.
However, the test was not enabled.
> Enable e2e test: TestUploadModuleLogs

- builds/e2e/connectivity.yaml
The 'Download Edge Artifacts' and 'Download Image Artifacts' tasks used the
edgelet.package.branchName and images.branchName variables, respectively but
instead needed to use the appropriate resource variables (which were being specified
in the resources sectin of the YAML but not used at all)
> Download artifacts based on pipeline 'resources'

- edge-util/src/Microsoft.Azure.Devices.Edge.Util.Metrics/Microsoft.Azure.Devices.Edge.Util.Metrics.csproj
One of our dependencies, prometheus-net.AspNetCore, has a transitive dependency on a vulnerable version of System.Text.Encodings.Web. Updating prometheus-net.AspNetCore wouldn't change anything, so the recommended approach is to make an explicit reference to the patched version of System.Text.Encodings.Web, to override the transitive version.
I used `dotnet list package --include-transitive` before and after the change to verify that the transitive dependency is replaced by the explicit dependency within the project.
> Patch a vulnerability in System.Text.Encodings.Web

- scripts/linux/trcE2ETest.sh
prior to this change, logs from several edge system services were omitted in pipeline output when tests failed
> Print all system logs when conn tests fail

- edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/MqttBrokerConnectorTest.cs
This test is flaky in our CI pipeline so let's disable it.
> Disable flaky broker `WhenReconnectsThenResubscribes` test

- builds/e2e/e2e.yaml
- builds/e2e/templates/e2e-run.yaml
- edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/MqttBrokerConnectorTest.cs
Proxy tests are currently timing out so disabling them until we fix the issue. It looks to be some agent issue, but not sure from cursory investigation.
> E2E: Disable proxy tests

- edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Test/CloudProxyTest.cs
- edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.E2E.Test/TwinDiffE2ETest.cs
- test/Microsoft.Azure.Devices.Edge.Test/GenericMqtt.cs
- test/Microsoft.Azure.Devices.Edge.Test/IoTEdgeCheck.cs
This test transiently failed with a weird error. Seems like a weird error to happen transiently.  Would expect every run. 
```
thread 'tokio-runtime-worker' panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/time/driver/handle.rs:79:13
```
Also disabling `SendMessageBatch` and `IotEdgeCheck` (flaky on arm). Disabling until fixed.
> Disable flaky `TwinDiff`, `SendMessageBatch`, `GenericMqttTelemetry`, and `IotEdgeCheck (arm-only)`

- edgelet/Cargo.lock
- edgelet/iotedge/src/config/import/mod.rs
https://github.com/Azure/iot-identity-service/pull/278 updated the common super config to allow registration ID to be optional. Update the cargo dependency to pull this change into `iotedge config apply`.
Also pull in the change to make registration ID optional for DPS-X509 provisioning.
Fixes #5488
> Update cargo dependencies

- builds/e2e/e2e.yaml
- edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Docker.Test/RuntimeInfoProviderTest.cs
- edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.IoTHub.Test/EdgeAgentConnectionTest.cs
- edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Test/CloudProxyTest.cs
- edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.E2E.Test/EdgeHubConnectionTest.cs
- edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.E2E.Test/EdgeToDeviceMethodTest.cs
- edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.E2E.Test/TelemetryTest.cs
- edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.E2E.Test/TwinDiffE2ETest.cs
- test/Microsoft.Azure.Devices.Edge.Test/EdgeAgentDirectMethods.cs
- test/Microsoft.Azure.Devices.Edge.Test/X509Device.cs
These tests are flaky so disabling. Some of these are redundant given coverage in other areas. So we can honestly delete them when needed. (Thinking the `RemovePropertySuccess` and `SendMessageBatchTest` tests)
> Disable flaky CI and E2E tests

- edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Test/CloudProxyTest.cs
- edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.E2E.Test/TwinDiffE2ETest.cs
- test/Microsoft.Azure.Devices.Edge.Test/GenericMqtt.cs
- test/Microsoft.Azure.Devices.Edge.Test/IoTEdgeCheck.cs
Cherry pick.
This test transiently failed with a weird error. Seems like a weird error to happen transiently.  Would expect every run. 
```
thread 'tokio-runtime-worker' panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/time/driver/handle.rs:79:13
```
Also disabling `SendMessageBatch` and `IotEdgeCheck` (flaky on arm). Disabling until fixed.
> Disable flaky `TwinDiff`, `SendMessageBatch`, `GenericMqttTelemetry`, and `IotEdgeCheck (arm-only)` (#5501)

- builds/e2e/e2e.yaml
- builds/e2e/templates/e2e-run.yaml
- builds/e2e/templates/e2e-setup.yaml
- builds/misc/images.yaml
- builds/misc/packages.yaml
- scripts/linux/generic-rust/install.sh
- test/Microsoft.Azure.Devices.Edge.Test.Common/EdgeDevice.cs
- test/Microsoft.Azure.Devices.Edge.Test.Common/EdgeLogs.cs
- test/Microsoft.Azure.Devices.Edge.Test.Common/EdgeModule.cs
- test/Microsoft.Azure.Devices.Edge.Test.Common/IotHub.cs
- test/Microsoft.Azure.Devices.Edge.Test.Common/Microsoft.Azure.Devices.Edge.Test.Common.csproj
- test/Microsoft.Azure.Devices.Edge.Test.Common/OsPlatform.cs
- test/Microsoft.Azure.Devices.Edge.Test.Common/Process.cs
- test/Microsoft.Azure.Devices.Edge.Test.Common/ProcessEx.cs
- test/Microsoft.Azure.Devices.Edge.Test.Common/ProcessResults.cs
- test/Microsoft.Azure.Devices.Edge.Test.Common/linux/EdgeDaemon.cs
- test/Microsoft.Azure.Devices.Edge.Test.Common/linux/OsPlatform.cs
- test/Microsoft.Azure.Devices.Edge.Test/Device.cs
- test/Microsoft.Azure.Devices.Edge.Test/IoTEdgeCheck.cs
- test/Microsoft.Azure.Devices.Edge.Test/PriorityQueues.cs
- test/Microsoft.Azure.Devices.Edge.Test/SetupFixture.cs
- test/Microsoft.Azure.Devices.Edge.Test/helpers/SasManualProvisioningFixture.cs
Cherry pick bffddf69dc39efe9b2c0607752b7172f419568b2 and ca519d4e3929eaf8647fbcf40ef2e2e5a11f2a49 from release/1.2. See those commits for details. Note, however, that I had to revert the end-to-end pipeline to continue using MS-hosted and custom agents for now, because test results are inconsistent using our 1ES-hosted agents, and it's not yet clear why (these same agents work fine in release/1.2). We'll need to do more investigation.
I've confirmed that the Build Images, Edgelet Packages, and End-to-end Test pipelines all pass with these changes.
> Update YAML pipelines to 1ES-hosted agents

- builds/e2e/isa-95-smoke-test.yaml
- builds/e2e/nested-e2e.yaml
A recent change (1b4b446895824ef66e5947ef7872dd2fa8b09ea9) added a requirement that callers of the template `builds/e2e/templates/e2e-setup.yaml` need to define a default value for the variable 'verbose'. This value gets used when creating the context.json file that passes information to the end-to-end tests. The change added the definition of 'verbose' to `e2e.yaml`, but failed to add it to isa-95-smoke-test.yaml, which also calls the template.
This change updates isa-95-smoke-test.yaml with a default value for 'verbose'. I've confirmed the pipeline succeeds with this change.
> Define 'verbose' var in missed e2e-setup.yaml caller

- edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/ModuleManagementHttpClient.cs
When we create many modules during a short time-period, apparently iot hub throttles the operation and identityd/edged/edgeAgent does not handle this well. Until the correct solution is developed, this temporary change has been made to slow down requests and enable scenarios with many modules.
> Temporary solution to get around the iot-hub throttling problem

- edgelet/Cargo.lock
- edgelet/edgelet-docker/src/runtime.rs
- edgelet/iotedge/src/client.rs
By default, `hyper` uses connection pool that can grow till `usize::MAX`. This, we believe, could cause some issues when heavy [GetModuleLogs](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-retrieve-iot-edge-logs?view=iotedge-2020-11) are frequently executed.
Also, connection pool does not have benefits for local UDS connections anyways.
> Disable connection pooling for docker client.

- edgelet/aziot-edged/src/main.rs
- edgelet/aziot-edged/src/watchdog.rs
- edgelet/aziot-edged/src/workload_manager.rs
If /var/lib/aziot/edged/mnt is missing, aziot-edged fails to start because of a `No such file or directory` error. It is fine to just create this directory on startup.
Since the directory is now created on startup, it's no longer necessary to create it in the watchdog.
> Fix aziot-edged startup when mnt is missing

- edgelet/iotedge/src/list.rs
Tokio-refactor `iotedge list` drops uptime because of missing return value.
> Fix missing uptime in iotedge list

- e2e_deployment_files/connectivity_deployment.template.json
- scripts/linux/trcE2ETest.sh
- smoke/IotEdgeQuickstart/details/IotedgedLinux.cs
Default to debug level logs during Single-node and Nested Connectivity tests. This change applies to edgeAgent and aziot system services (i.e. aziot-edged, aziot-keyd, aziot-certd, and aziot-identityd).
Also, start docker and aziot* logs at the test start time. Previously docker logs from previous runs would show up and most of the aziot* logs would be missing from the start of the run.
> Default connectivity tests to debug level logs

- e2e_deployment_files/connectivity_deployment.template.json
- scripts/linux/trcE2ETest.sh
- smoke/IotEdgeQuickstart/details/IotedgedLinux.cs
Default to debug level logs during Single-node and Nested Connectivity tests. This change applies to edgeAgent and aziot system services (i.e. aziot-edged, aziot-keyd, aziot-certd, and aziot-identityd).
Also, start docker and aziot* logs at the test start time. Previously docker logs from previous runs would show up and most of the aziot* logs would be missing from the start of the run.
> Cherry-pick: Default connectivity tests to debug level logs (#5540)

- edge-modules/functions/samples/docker/linux/amd64/Dockerfile
- test/Microsoft.Azure.Devices.Edge.Test/Module.cs
Functions runtime sample failed to start with exception: Unhandled exception. System.UnauthorizedAccessException: Access to the path '/proc/1/map_files' is denied.
---> System.IO.IOException: Operation not permitted
This started to happen after the upgrade of functions base image to 3.0 which has an updated dotnet core image. Fix adds WORKDIR /app to Dockerfile (to set the working directory for all the subsequent Dockerfile instructions).
> fix functions sample on centos

- edgelet/Cargo.lock
- edgelet/contrib/centos/aziot-edge.spec
- edgelet/contrib/debian/control
- edgelet/iotedge/test-files/config/ca-quickstart/certd.toml
- edgelet/iotedge/test-files/config/complex-agent-spec/certd.toml
- edgelet/iotedge/test-files/config/dps-no-reprovisioning-flags/certd.toml
- edgelet/iotedge/test-files/config/dps-symmetric-key/certd.toml
- edgelet/iotedge/test-files/config/dps-tpm/certd.toml
- edgelet/iotedge/test-files/config/dps-x509/certd.toml
- edgelet/iotedge/test-files/config/imported-master-encryption-key/certd.toml
- edgelet/iotedge/test-files/config/manual-connection-string-2/certd.toml
- edgelet/iotedge/test-files/config/manual-connection-string/certd.toml
- edgelet/iotedge/test-files/config/manual-x509/certd.toml
- edgelet/iotedge/test-files/config/moby-runtime-content-trust/certd.toml
- edgelet/iotedge/test-files/config/nested-edge/certd.toml
- edgelet/iotedge/test-files/config/not-socket-activated-both-custom/certd.toml
- edgelet/iotedge/test-files/config/not-socket-activated-varlib/certd.toml
- edgelet/iotedge/test-files/config/not-socket-activated-varrun/certd.toml
- edgelet/iotedge/test-files/config/socket-activated-one-custom/certd.toml
- Update aziotctl version to 1.2.3 & aziotd version to 1.2.3
Ref: https://github.com/Azure/iot-identity-service/commit/55434733d5d3a73f67b9e70998c38da5b7190901
- Update certd.toml config in tests to reflect the structure serialization changes in IIS 1.2.3 ( https://github.com/Azure/iot-identity-service/commit/3637eada145a720259c4e0744b0b551c8da04b10#diff-2988409407e7eb06011181dd65063f3c52c7201272be8c3af4b8479d65baebd3R228-R240 )
Note: This is a workaround in Rust TOML library where a complex structure needs to be resided last in the struct.
> Update to 1.2.3 IIS components

- test/modules/Modules.Test/TestResultCoordinator/Reports/DirectMethod/DirectMethodReportDataWithSenderAndReceiverSource.cs
- test/modules/TestResultCoordinator/Reports/CountingReport.cs
- test/modules/TestResultCoordinator/Reports/DirectMethod/DirectMethodReport.cs
- test/modules/TestResultCoordinator/Reports/DirectMethod/DirectMethodReportGenerator.cs
This PR is a in the same spirit as #5512, however not nearly the same number of changes is needed. These things have been done for 1.1:
- Direct method report accounts for duplicate direct methods received. This really only affected nested connectivity with the broker, but the logic has been made and reviewed so I thought it was good to add it to 1.1 anyway in case we see some weird regression in the future.
- Add tolerance for NetworkOnFailure for connectivity tests. We will fail the tests if we pass less than 90% of direct methods.
- Add tolerance for missing messages. I saw one instance where we were missing a two messages. Does not reproduce often.
> Connectivity Tests: Fix test logic and add tolerances

- edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.E2E.Test/Cloud2DeviceTest.cs
- test/Microsoft.Azure.Devices.Edge.Test/Device.cs
These tests are flaky so I am disabling. They cannot be failing due to a product bug as the commit they fail for reverts 1ES, and does not touch product code.
> CI / E2E: Disable flaky tests (#5556)

- test/Microsoft.Azure.Devices.Edge.Test/Module.cs
- test/Microsoft.Azure.Devices.Edge.Test/PlugAndPlay.cs
Disabling these flaky tests in CI / E2E. They cannot be failing due to a product bug as the commit they fail for is behind a commit where all the tests pass.
> CI / E2E: Disable flaky tests

- edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Test/CloudProxyTest.cs
Disabling flaky cloud proxy test suite. Bug is already logged for re-enabling.
> CI: Disable cloud proxy test suite

- edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Test/CloudProxyTest.cs
Disabling flaky test. Bug is already logged.
> CI: Disable flaky cloud proxy null receiver test

- edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Test/CloudProxyTest.cs
Cherry pick: #5562
Disabling flaky cloud proxy test suite. Bug is already logged for re-enabling.
> CI: Disable cloud proxy test suite (#5562)

- test/modules/Modules.Test/TestResultCoordinator/Reports/DirectMethod/DirectMethodReportDataWithSenderAndReceiverSource.cs
- test/modules/TestResultCoordinator/Reports/DirectMethod/DirectMethodReportGenerator.cs
In the earlier PR #5542, we started allowing duplicate results in connectivity. This was initially done to get around issues from the report becoming unreadable when the duplicates happen. But this case only happens in nested so we don't need this change in 1.1 branch.
> Connectivity Tests: Don't allow duplicates

- test/doc/one-time-setup.md
Address case inconsistencies for mentions of IoT Hub to distinguish
between references to the service (Iot Hub) and references to a service instance (Iot hub)
> Address case inconsistencies for mentions of IoT Hub 

- edgelet/edgelet-core/src/module.rs
- edgelet/edgelet-docker/src/runtime.rs
- edgelet/edgelet-docker/tests/runtime.rs
- edgelet/iotedged/src/workload_manager.rs
In 1.1.5 we fixed an issue with windows build. Windows would not create container if the socket doesn't exist.
However, the socket was created in "start" which comes after "create" of containers, so 1.1.5 would not work properly on windows if socket didn't exist beforehand.
The fix was to move the socket creation in "create" stage, this however creates another issue.
The server for the workload API starts in the create stage and get stopped when the container is stopped.
However, when a container is stopped, it is still "created" so it can be restarted without going through the "create" stage.
So stopping a module would kill the workload API server and restarting it, would make it running again but would not start the workload server because it is created in "create".
In the 1.1.5 fix, …
> fix stopping module in 1.1.6

- builds/e2e/connectivity.yaml
Manually triggered connectivity test pipeline runs on release/1.1 are defaulting to artifacts from the master branch for Build Images and Edgelet Packages. This is a mistake and they should be using artifacts from release/1.1 by default.
> Default to release/1.1 branch for conn test pipeline resources

- edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.E2E.Test/EdgeToDeviceMethodTest.cs
these tests sometimes did not see the device/module, probably because the fix-timed delay was not always enough
> Added connection-check for direct method test

- test/Microsoft.Azure.Devices.Edge.Test/GenericMqtt.cs
- test/Microsoft.Azure.Devices.Edge.Test/PriorityQueues.cs
- test/Microsoft.Azure.Devices.Edge.Test/helpers/TestResultCoordinatorUtil.cs
- test/modules/generic-mqtt-tester/src/message_initiator.rs
Two issues fixed with custom mqtt tests in E2E pipeline:
1. The custom mqtt test module would stop a bit too early in the case where it was sending fixed number of messages. Fixed by adding a wait of 60 seconds for any slow telemetry to come back.
2. On arm the test modules take a bit too long to come up. This causes the test to exceed time threshold. Changing the TRC validation logic to periodically poll the endpoint.
> E2E: Avoid flakiness in custom mqtt tests (#5467)

- edge-modules/functions/binding/src/Microsoft.Azure.WebJobs.Extensions.EdgeHub/ModuleClientCache.cs
Update TempFilterFunc binding protocol to Amqp_Tcp_Only to fix E2E test failure with DotNetty update.
Ref: (#5571)
> Update TempFilterFunc binding protocol to Amqp_Tcp_Only 

- edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Docker.Test/RuntimeInfoProviderTest.cs
- edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.IoTHub.Test/EdgeAgentConnectionTest.cs
- test/Microsoft.Azure.Devices.Edge.Test/X509Device.cs
I have run these tests over 20 times, some with all tests enabled. While some of the other flaky tests failed, these passed every time.
> Re enable some flaky tests

- builds/e2e/e2e.yaml
- test/Microsoft.Azure.Devices.Edge.Test.Common/windows/EdgeDaemon.cs
In a failed end-to-end test run on Windows earlier today, I noticed that all test failures looked like this:
```
Error Message:
System.InvalidOperationException : Cannot stop iotedge service on computer '.'.
----> System.ComponentModel.Win32Exception : The service cannot accept control messages at this time.
Stack Trace:
at System.ServiceProcess.ServiceController.Stop()
at Microsoft.Azure.Devices.Edge.Test.Common.Windows.EdgeDaemon.InternalStopAsync(CancellationToken token) in D:\a\_work\1\s\test\Microsoft.Azure.Devices.Edge.Test.Common\windows\EdgeDaemon.cs:line 107
at Microsoft.Azure.Devices.Edge.Test.Common.Windows.EdgeDaemon.ConfigureAsync(Func`2 config, CancellationToken token, Boolean restart) in D:\a\_work\1\s\test\Microsoft.Azure.Devices.Edge.Test.Common\windows\EdgeDaemon.cs:line …
```
> Make tests resilient to Windows service manager errors

- builds/misc/images.yaml
This is to correct the accidental removal of this when the following PR was merged:
Parallelize build-images pipeline (#5547)
> Use buildx for building API Proxy on ARM

- edgelet/contrib/config/linux/config.yaml
- edgelet/contrib/config/linux/debian/config.yaml
- edgelet/contrib/config/windows/config.yaml
This adds a section for the allow_elevated_docker_permissions flag to the default config.yaml
> add allow_elevated_docker_permissions to config

- test/Microsoft.Azure.Devices.Edge.Test.Common/DaemonConfiguration.cs
- test/Microsoft.Azure.Devices.Edge.Test/Provisioning.cs
Fixes DpsX509 when run alone, as it previously relied on a previous test to generate certs.
> Generate TestCertificates in DpsX509 test

- edgelet/aziot-edged/src/workload_manager.rs
- edgelet/edgelet-http/Cargo.toml
- edgelet/edgelet-http/src/unix.rs
Fix for https://github.com/Azure/iotedge/issues/5672, https://github.com/Azure/iotedge/issues/5505 , https://github.com/Azure/iotedge/issues/5693
Restarting iotedge many time lead to the following permission issues:
This doesn't seem to happen in 1.1.6. I tried many times but could not get it to fail however some customer experienced the same symptoms so this is most likely an issue across version.
The fact that it seems to fail more on some setup is something we could not explain.
Tests:
1.  Tried all of those. A few times manually (3-5 times), a cycle of hundreds time each with a script (Ubuntu + Centos).
For each test we check that all module are up and running, that permissions and user are correct and that there is a listener on the socket:
1.1 sudo iotedge system restart
1.2 sudo …
> Fix workload socket denied

- edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/Startup.cs
The Java clients do not handle the Kestrel WebSocket Ping (KeepAlive) gracefully and can put the client into a bad state. This change sets the interval to Zero which disables the WebSocket Ping (KeepAlive).
This change should be safe because underlying AMQP and MQTT protocols have already built-in Keep Alive mechanisms. Also, IoT Hub does not support/send WebSocket Ping as well, that's why the issue is reproducible only with Edge Hub.
The plan will be to correctly support this in the Java clients going forward but the best remediation that will have the biggest impact is to turn these off and have the edge act similarly to the hub.
Cherry-pick #5689
> Remove WebSocket Ping KeepAlives (#5623) (#5689)

- edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/Microsoft.Azure.Devices.Edge.Agent.Diagnostics.csproj
- edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/Microsoft.Azure.Devices.Edge.Agent.IoTHub.csproj
- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/Microsoft.Azure.Devices.Edge.Hub.Core.csproj
- edge-modules/MetricsCollector/MetricsCollector.csproj
- edge-modules/SimulatedTemperatureSensor/SimulatedTemperatureSensor.csproj
- edge-modules/functions/binding/src/Microsoft.Azure.WebJobs.Extensions.EdgeHub/Microsoft.Azure.WebJobs.Extensions.EdgeHub.csproj
- samples/dotnet/EdgeDownstreamDevice/EdgeDownstreamDevice.csproj
- samples/dotnet/EdgeX509AuthDownstreamDevice/EdgeX509AuthDownstreamDevice.csproj
- smoke/LeafDevice/LeafDevice.csproj
- test/Microsoft.Azure.Devices.Edge.Test.Common/Microsoft.Azure.Devices.Edge.Test.Common.csproj
- test/modules/CloudToDeviceMessageTester/CloudToDeviceMessageTester.csproj
- test/modules/DirectMethodReceiver/DirectMethodReceiver.csproj
- test/modules/DirectMethodSender/DirectMethodSender.csproj
- test/modules/EdgeHubRestartTester/EdgeHubRestartTester.csproj
- test/modules/MetricsValidator/MetricsValidator.csproj
- test/modules/ModuleLib/Microsoft.Azure.Devices.Edge.ModuleUtil.csproj
- test/modules/ModuleRestarter/ModuleRestarter.csproj
- test/modules/Relayer/Relayer.csproj
- test/modules/TemperatureFilter/TemperatureFilter.csproj
- test/modules/TwinTester/TwinTester.csproj
- test/modules/load-gen/load-gen.csproj
1.36.2 had a bug causing a call get stuck if the object was disposed during the call (which could happen during connectivity problems)
> Updated SDK from 1.36.2 to 1.36.3 to fix connectivity issues

- edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudProxy.cs
- edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ConnectivityAwareClient.cs
- edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ExceptionMapper.cs
- edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Test/CloudProxyTest.cs
Iot-hub does not disconnect in case of fail over and edgeHub keeps sending messages/operations. These operations fail with a specific error and never recover.
Added some logic to filter exceptions, so when the error message arrives that is thrown by the "old" server (the server serving before fail-over), EdgeHub disconnect and the new connection attempt will find the new server.
cherry pick of #5669
> Fix: detect fail-over from iot hub/sdk behavior and disconnect from hub

- edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/config/ConfigUpdater.cs
- edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs
There is still an interdependency between the configuration fetch task and the protocol heads in the nested case. The pertinent PR is #5515.
> [release/1.1] Revert EdgeHub configuration waiting

- test/Microsoft.Azure.Devices.Edge.Test/Metrics.cs
Validate metrics was disabled due to a github issue. The issue is now resolved so I am reenabling the test.
Waiting on this run before merge:
https://dev.azure.com/msazure/One/_build/results?buildId=48470933&view=ms.vss-test-web.build-test-results-tab
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes all the commits in the PR to a …
> E2E: Reenable validate metrics

- builds/checkin/edgelet.yaml
- builds/checkin/mqtt.yaml
- edgelet/doc/devguide.md
- edgelet/docker-rs/src/lib.rs
1. Enable Code Coverage Checks for MQTT with initial check-in gate of 84%
2. cargo-tarpaulin was updated recently to fix the bug I had opened (https://github.com/xd009642/tarpaulin/issues/846). Set exclude at lib.rs instead of at yaml. This allows to manage excludes in the code instead of yaml.
3. Added documentation for running Rust Code Coverage Check locally
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR …
> Enable MQTT Code Coverage and Documentation for Running Code Coverage Locally

- test/Microsoft.Azure.Devices.Edge.Test/Module.cs
There is a problem with twin updates on temp sensor due to this bug:
https://msazure.visualstudio.com/One/_queries/query/55cd7165-8f3f-4dfd-b36c-f010dae42e2a/
Until this is fixed we should remove this twin update from the temp sensor test. Waiting on this E2E run before merge:
https://dev.azure.com/msazure/One/_build/results?buildId=48470895&view=results
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to …
> E2E: Stabilize temp sensor tests by removing twin updates

- builds/e2e/templates/e2e-run.yaml
- test/Microsoft.Azure.Devices.Edge.Test/Module.cs
I thought we could mitigate this SDK issue in our tests, but it seems worse than previously thought:
https://github.com/Azure/azure-iot-sdk-csharp/issues/2223
We thought ModuleClient would recover on subsequent reconnects, but it never recovers. I have tried fiddling with the delays, removing the explicit `OpenAsync`, allowing more reconnect attempts, etc. Nothing seems to stabilize this flakiness. I didn't resort to changing the protocol as I believe our tests should use the default (and I believe most stable) Amqp_Tcp_Only. 
I feel like the loose thread here for further investigation is the fact that our Longhaul Tests don't suffer from this issue. So it seems like something specific to the TempSensor module might be at play.
For this PR, I have disabled the TempSensor test on windows …
> E2E: Disable Temp Sensor Test on Windows

- test/modules/TestResultCoordinator/Reports/CountingReport.cs
Connectivity tests are failing due to amqp connected c2d test module failing the test. This is a legitimate failure. Previously we thought only mqtt connected modules were affected. We need to add a tolerance for amqp connected modules. So in this PR I make the existing tolerance protocol agnostic.
Waiting on this connectivity test for merge:
https://msazure.visualstudio.com/One/_build/results?buildId=48718095&view=results
- [ x] I have read the [contribution guidelines](https://github.com/azure/iotedge#contributing).
- [ x] Title of the pull request is clear and informative.
- [x ] Description of the pull request …
> Connectivity Tests: Make c2d tolerance protocol agnostic

- edge-agent/docker/linux/amd64/Dockerfile
The base image version in release/1.1 and release/1.2 is alpine 3.14. 
**Testing Notes:**
Built the image locally.
> Update base image to alpine 3.14 (edge-agent/amd64)

- nuget.config
We added a nuget.config file some time back because we needed to pull from multiple nuget feeds: the regular public feed and an internal feed needed occasionally/temporarily for special drops of the IoT SDK. When Microsoft began scanning for config files that might be subject to a substitution attack, we took a few different steps over time to ensure compliance.
Now we're beginning to see warnings in our pipeline because our config file points to the public feed, _even though its the only configured feed_. I suspect the scans are geared towards internal projects using OSS, rather than for public-facing projects which are themselves OSS.
Since we don't need any special feeds, I believe we can avoid the pipeline warnings by removing the config file altogether.
> Remove nuget.config to address pipeline warnings

- builds/e2e/connectivity.yaml
- builds/e2e/templates/connectivity-deploy.yaml
This reverts commit 4852689781ca3e9d912accbd1921ec7a59ca18f2.
Fix to use 1ES Agent was made in #5798 
Waiting for this run to complete before merging the change in
Pipeline Run : https://msazure.visualstudio.com/One/_build/results?buildId=48819597&view=results
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes all the commits in the …
> Use 1ES hosted agent for amd64 single-node connectivity tests

- builds/checkin/e2e-checkin.yaml
- builds/e2e/templates/e2e-run.yaml
- builds/e2e/templates/e2e-setup.yaml
Changes Had to be ported manually from #5826. The location of the changes are the same 
1. 1.1 Uses powershell instead of bash for running E2E Setup (Because of Windows Environment)
2.  Difference in Build Images Process in 1.1 as compared to master
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes all the commits in the PR to a …
> Modify How Dotnet is Accessed during E2E Run

- edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/versioning/ModuleManagementHttpClientVersioned.cs
- edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Edgelet.Test/ModuleManagementHttpClientTest.cs
Revert Changes by PR #5801, Time Stamp handling needs to be handled in the edgelet code. This change broke the Portal Log Viewing since since and until time can take unix as well as simple language time
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes all the commits in the PR to a single commit. The net effect is that entire PR …
> Revert Changes to Handle Validation of Since and Until Time

- doc/devguide.md
- scripts/linux/setupContainerDebugger.sh
Add a script for setting up the Visual Studio debugger in an Edge container/module. Also, update the Dev Guide to document how to use the script and VSCode to attach a debugger to the edgeAgent container/module.
This script and documented steps have been tested on an Ubuntu18.04 dev machine running a local build of aziot-edge v1.2. In this test, VSCode was running on the dev machine and was able to successfully attach its debugger to the Edge Agent container. 
_Note: We use the kodiakhq bot to merge PRs …
> Cherry-pick: Add script and documentation for attaching VSCode debugger to a container/module

- builds/e2e/isa-95-smoke-test.yaml
- builds/e2e/templates/lock-test-agents.yaml
- builds/e2e/templates/nested-get-secrets.yaml
- builds/e2e/templates/unlock-test-agents.yaml
- scripts/linux/nestedAgentLock.sh
Cherry-pick #5836
This PR changes the PAT secret to be the one used elsewhere in the repository. It also adds an initial check that the script can retrieve agent data from the devops api, so the root cause will be more obvious if it happens again. 
I tested the fail path locally and the success path in the pipeline:
https://dev.azure.com/msazure/One/_build/results?buildId=49243483&view=results
_Note: We use the kodiakhq …
> Nested Tests: Agent lock resiliency (#5836)

- edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/versioning/ModuleManagementHttpClientVersioned.cs
- test/Microsoft.Azure.Devices.Edge.Test.Common/IotHub.cs
- test/Microsoft.Azure.Devices.Edge.Test/EdgeAgentDirectMethods.cs
The goal of this PR is to handle return code correctly when calling get module logs. 
Earlier Behavior
1. A Request to Edgelet component with an incorrect argument, returned a Bad Request but was never handled and lead to Stream Parsing failure when trying to parse module logs , giving a cryptic error
New Behavior
1. Edge-Agent checks the correct HTTP Status code before trying to parse the Module Log Response
Testing
1. Added Test Case for both Happy-Path and Bad-Path in TestGetModuleLogs Test in E2E Test …
> Handle Return Code From Get Module Logs Failure

- edge-modules/api-proxy-module/src/main.rs
Added a delay between nginx restarts to avoid spamming the log file.
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes all the commits in the PR to a single commit. The net effect is that entire PR becomes a single commit. Please follow the best practices mentioned [here](https://chris.beams.io/posts/git-commit/#:~:text=The%20seven%2 …
> Add delay between nginx crashes

- edgelet/edgelet-http-workload/src/server/cert/identity.rs
- edgelet/edgelet-http-workload/src/server/cert/mod.rs
- edgelet/edgelet-http-workload/src/server/cert/server.rs
- edgelet/edgelet-http-workload/src/server/mod.rs
Since `certd` cannot override the DN of EST-issued certificates, EST-issued edge CAs have the same DN for every device (`/CN=iotedged workload ca`). This quickly becomes problematic in scenarios with larger numbers of devices. This PR is an approximate backport of the edge CA DN parameterization in master, which appends the device ID to the common name. For example, a device with ID `my_device` would request an edge CA certificate with DN `/CN=iotedged workload ca my_device`.
Motivated by #5782.
> Add device ID to edge CA common name

- edgelet/iotedge/src/check/checks/container_engine_is_moby.rs
- edgelet/iotedge/src/check/checks/mod.rs
- edgelet/iotedge/src/check/mod.rs
As per discussion with moby team, we are removing the check for moby in iotedge because we won't be able to rely on "+azure" in the version forever.
That check however " if moby_runtime_uri != "npipe://./pipe/iotedge_moby_engine"" is still valid, but only for windows.
So the moby check was removed altogether for linux and just the check  if moby_runtime_uri != "npipe://./pipe/iotedge_moby_engine" was kept for windows.
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are …
> Removing moby check

- mqtt/mqtt-bridge/src/upstream/rpc/remote.rs
- mqtt/mqtt-bridge/tests/rpc.rs
- mqtt/mqtt-edgehub/src/topic/translation.rs
- mqtt/mqtt-edgehub/tests/edgehub_authorizer.rs
- mqtt/mqtt-edgehub/tests/translation.rs
It's been brought to our attention that we use incorrect parameter name. It should be `$rid`. 
**Note: this change only affect tests. The actual topic translation functionality works fine.**
I propose this test just to avoid confusion in the future where someone can look at the test and get the wrong impression about parameter name.
This PR does not require additional test coverage.
> Use proper name for $rid parameter.

- edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/Constants.cs
- edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/EdgeletCommandFactory.cs
- edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/commands/PrepareUpdateCommand.cs
- edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs
- edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/modules/EdgeletModule.cs
Cherry pick: https://github.com/Azure/iotedge/pull/5876
* Workload socket fix
TEST:
Used the script to perform the test:
[test_new_flag.txt](https://github.com/Azure/iotedge/files/7651550/test_new_flag.txt)
Without flag
[prepare_module_on.txt](https://github.com/Azure/iotedge/files/7651556/prepare_module_on.txt)
With flag disabling prepare module on
[prepare_module_off.txt](https://github.com/Azure/iotedge/files/7651557/prepare_module_off.txt)
Both works.
So I checked in the journal logs to verify that the script is correctly reproducing the issue. It does, we see the "conflict" with current operation. However, since in 1.2 we create the socket in start, so it doesn't matter if socket was removed in create.
```
Pulling image via tag mcr.microsoft.com/media/video-analyzer:1...
Successfully …
```
> Fix: Workload socket issue for concurrent module create (#5876)

- mqtt/mqtt-bridge/src/upstream/rpc/remote.rs
- mqtt/mqtt-bridge/tests/rpc.rs
- mqtt/mqtt-edgehub/src/topic/translation.rs
- mqtt/mqtt-edgehub/tests/edgehub_authorizer.rs
- mqtt/mqtt-edgehub/tests/translation.rs
It's been brought to our attention that we use incorrect parameter name. It should be `$rid`. 
**Note: this change only affect tests. The actual topic translation functionality works fine.**
I propose this test just to avoid confusion in the future where someone can look at the test and get the wrong impression about parameter name.
This PR does not require additional test coverage.
> Use proper name for $rid parameter. (#5898)

- test/Microsoft.Azure.Devices.Edge.Test/EdgeAgentDirectMethods.cs
- test/Microsoft.Azure.Devices.Edge.Test/PriorityQueues.cs
As I previously did in `ValidateMetrics` test (#5807), I propose to decrease the timeout for direct method calls in E2E tests. 
The idea is that sometimes the direct methods time out on Hub side for no apparent reason (see my recent investigation in [this bug](https://msazure.visualstudio.com/One/_workitems/edit/12801305)). Having shorter timeouts (120+80sec) will give our tests the ability to retry one more time before the whole test times out (300sec)
This is test change, so no extra test coverage required.
> Decrease direct methods timeout in E2E tests.

- edgelet/edgelet-docker/test/linux/config.d/empty.toml
- edgelet/edgelet-docker/test/linux/sample_settings_with_proxy_uri.toml
- edgelet/iotedge/src/check/checks/mod.rs
- edgelet/iotedge/src/check/checks/proxy_settings.rs
- edgelet/iotedge/src/check/mod.rs
This change introduces a new check in iotedge check called proxy-settings. The new check verifies consistent proxy settings in IoT Edge daemon, IoT Edge agent and Moby daemon.
The following unit tests are added:
- test check::tests::proxy_settings_all_set_should_succeed_test ... ok
- test check::tests::proxy_settings_iot_edge_agent_not_set_should_fail_test ... ok
- test check::tests::proxy_settings_iot_edge_deamon_not_set_should_fail_test ... ok
- test check::tests::proxy_settings_identity_deamon_not_set_should_fail_test ... ok
- test check::tests::proxy_settings_mismatching_values_should_fail_test ... ok
- test check::tests::proxy_settings_moby_deamon_not_set_should_fail_test ... ok
- test check::tests::proxy_settings_none_set_should_succeed_test ... ok
The new functionality is tested:
- …
> Cherry pick - release 1.2: Iotedge check proxy-settings (#5581)

- test/Microsoft.Azure.Devices.Edge.Test.Common/linux/PackageManagement.cs
Straight cherry-pick:  This change will enable aziot-edge install from Microsoft prod. This is useful for scenarios where we don't care about specific version of runtime, but are fine with the latest officially published.
The use case for 1.2 is to make the release process simpler, when it comes to base images updates.
> [E2E]: Enable aziot-edge install from Microsoft prod (#4881)

- edge-util/docker/linux/arm32v7/Dockerfile
- edge-util/docker/linux/arm64v8/Dockerfile
It looks like if I use ubuntu 20.04 as a base for the RocksDB build,
it pulls in the incorrect version of glibc. The dotnet containers are 
based on bionic, so dropping down to 18.04 should
allow the libsrocksdb to be loaded.
Ran E2E test again, and checked for the exception I saw earlier. The storage is created cleanly.
> Rocksdb build for arm needs Ubuntu 18

- builds/e2e/e2e.yaml
- builds/e2e/templates/e2e-run.yaml
- builds/e2e/templates/e2e-setup.yaml
- doc/NotaryContentTrust.md
- test/Microsoft.Azure.Devices.Edge.Test.Common/DaemonConfiguration.cs
- test/Microsoft.Azure.Devices.Edge.Test.Common/EdgeRuntime.cs
- test/Microsoft.Azure.Devices.Edge.Test.Common/TomlDocument.cs
- test/Microsoft.Azure.Devices.Edge.Test.Common/certs/CaCertificates.cs
- test/Microsoft.Azure.Devices.Edge.Test.Common/linux/EdgeDaemon.cs
- test/Microsoft.Azure.Devices.Edge.Test/ContentTrust.cs
- test/Microsoft.Azure.Devices.Edge.Test/ManifestSigning.cs
- test/Microsoft.Azure.Devices.Edge.Test/SetupFixture.cs
- test/Microsoft.Azure.Devices.Edge.Test/helpers/Context.cs
- test/Microsoft.Azure.Devices.Edge.Test/helpers/ManifestTrustSetupFixture.cs
E2E content trust setup contains the following changes for enablement
1. Set up of content trust registry containing a notary signed image and an unsigned image
2. Enable Edge Daemon with content trust feature by configuring the edged and certd toml files with its certificates
3. Addition of content trust azure container registry and its credentials are updated to both E2E checkin and E2E core test pipelines along with the registry Root CA
4. Notary installation in /usr/bin in the pipeline infrastructure
5. Deploy the signed and unsigned container images modules
6. Update in the document to use the right Notary version and also configuring in the super-config.toml
> [E2E] Content Trust E2E setup and testing

- edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/EdgeAgentConnection.cs
- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/config/TwinConfigSource.cs
Disable chaining verification in EA and EH as there is known bug in the way the certs are processed after a deployment is set. Util a fix is made, disabling it for now. Also the chaining verification is done already in the Manifest signer client so it doesn't needed for now.
> Disable chaining verification in EA and EH

- builds/misc/images-release.yaml
TL;DR -- Add Microsoft.Azure.WebJobs.Extensions*.nupkg to be part of the published artifact.
The artifact is used as part of the Azure Function dependency.
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes all the commits in the PR to a single commit. The net effect is that entire PR becomes a single commit. Please follow the best …
> Add nupkg as part of publish-linux

- edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.E2E.Test/TelemetryTest.cs
Cherry pick: #5945
This CI test is flaky, but is also redundant as the scenario is also covered in our E2E suite. 
The root cause of the flake is that when the module client is disconnected, sometimes the amqp session is no longer there so the SDK will throw an exception when closing the ModuleClient. We could refactor this test to avoid this, but it seems less error-prone to rely on just the existing E2E test to cover this scenario.
Test run with changes:
https://dev.azure.com/msazure/One/_build/results?buildId=50188304&view=results …
> CI: Disable flaky SendTelemetry test (#5945)

- edgelet/contrib/config/linux/template.toml
- edgelet/edgelet-http-workload/src/module/cert/mod.rs
- edgelet/iotedge/src/check/mod.rs
- edgelet/iotedge/src/config/apply.rs
- edgelet/iotedge/test-files/config/ca-certs-est/certd.toml
- edgelet/iotedge/test-files/config/ca-quickstart/certd.toml
- edgelet/iotedge/test-files/config/complex-agent-spec/certd.toml
- edgelet/iotedge/test-files/config/dps-no-reprovisioning-flags/certd.toml
- edgelet/iotedge/test-files/config/dps-symmetric-key/certd.toml
- edgelet/iotedge/test-files/config/dps-tpm/certd.toml
- edgelet/iotedge/test-files/config/dps-x509/certd.toml
- edgelet/iotedge/test-files/config/imported-master-encryption-key/certd.toml
- edgelet/iotedge/test-files/config/manifest-trust-bundle/certd.toml
- edgelet/iotedge/test-files/config/manual-connection-string-2/certd.toml
- edgelet/iotedge/test-files/config/manual-connection-string/certd.toml
- edgelet/iotedge/test-files/config/manual-x509/certd.toml
- edgelet/iotedge/test-files/config/moby-runtime-content-trust/certd.toml
- edgelet/iotedge/test-files/config/nested-edge/certd.toml
- edgelet/iotedge/test-files/config/not-socket-activated-both-custom/certd.toml
- edgelet/iotedge/test-files/config/not-socket-activated-varlib/certd.toml
- edgelet/iotedge/test-files/config/not-socket-activated-varrun/certd.toml
- edgelet/iotedge/test-files/config/socket-activated-one-custom/certd.toml
This affects the certd config generated by running `iotedge config apply`,
as well as a new Edge CA cert issued when the current one expires *and*
the common name has not been set explicitly in certd config already.
Fixes #5937
Ref #4740
Also fix iotedge-check tests to not require sudo access.
Ref https://github.com/Azure/iotedge/pull/5927#issuecomment-1007806386
> Change default common name of Edge CA cert to "aziot-edge CA"

- builds/e2e/e2e-release.yaml
- builds/e2e/templates/e2e-run-base-image-update.yaml
- builds/e2e/templates/e2e-setup-base-image-update-release.yaml
- builds/misc/images-release-base-image-update.yaml
- test/Microsoft.Azure.Devices.Edge.Test.Common/linux/PackageManagement.cs
This is a standalone Release pipeline, intended to simplify the existing internal release process.
To wit:
- It eliminates the need to run a separate pipeline to build test images by removing external dependences,
- It only builds images that are needed, either for the release or for testing purposes, and
- It obviates the need for running manual checks/smoke tests by running E2E tests on the Release bits (which isn't something we were doing before).
This change also adds Ubuntu 20.04 support (to account for a change in directory structure).
**Testing Notes:**
> Custom Release pipeline for simplifying Release process on Base image updates for release/1.1

- builds/e2e/templates/e2e-run-base-image-update.yaml
- builds/e2e/templates/e2e-run-metrics-collector.yaml
- builds/e2e/templates/e2e-run.yaml
It can sometimes be that builds succeed but the resulting artifacts lead
to test timeouts, for example if edgeHub crashes upon execution.
Unconditionally publishing logs would make it easier to debug these
cases.
> [release/1.1] Unconditionally publish logs

- builds/e2e/templates/e2e-run.yaml
It can sometimes be that builds succeed but the resulting artifacts lead
to test timeouts, for example if edgeHub crashes upon execution.
Unconditionally publishing logs would make it easier to debug these
cases.
> [master] Unconditionally publish logs

- edge-util/src/Microsoft.Azure.Devices.Edge.Util/CertificateHelper.cs
(cherry picked from commit 56f2d77e31188381252411b260cab92eaefbcfda)
> added workaround for windows-certificate import problem

- edgelet/doc/devguide.md
The PR adds Instructions on how to run edge daemon locally. The goal is to provide these instructions as part of compatibility check tool in case the target OS is missing systemd support
I tested this on an ubuntu 20.04 VM without systemd support
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes all the commits in the PR to a single …
> Add Instructions to Run Azure IoT Edge Daemon Locally

- edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/Microsoft.Azure.Devices.Edge.Agent.Diagnostics.csproj
- edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/Microsoft.Azure.Devices.Edge.Agent.IoTHub.csproj
- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/Microsoft.Azure.Devices.Edge.Hub.Core.csproj
- edge-modules/MetricsCollector/MetricsCollector.csproj
- edge-modules/SimulatedTemperatureSensor/SimulatedTemperatureSensor.csproj
- edge-modules/functions/binding/src/Microsoft.Azure.WebJobs.Extensions.EdgeHub/Microsoft.Azure.WebJobs.Extensions.EdgeHub.csproj
- samples/dotnet/EdgeDownstreamDevice/EdgeDownstreamDevice.csproj
- samples/dotnet/EdgeX509AuthDownstreamDevice/EdgeX509AuthDownstreamDevice.csproj
- smoke/LeafDevice/LeafDevice.csproj
- test/Microsoft.Azure.Devices.Edge.Test.Common/Microsoft.Azure.Devices.Edge.Test.Common.csproj
- test/Microsoft.Azure.Devices.Edge.Test/Module.cs
- test/modules/CloudToDeviceMessageTester/CloudToDeviceMessageTester.csproj
- test/modules/DirectMethodReceiver/DirectMethodReceiver.csproj
- test/modules/DirectMethodSender/DirectMethodSender.csproj
- test/modules/EdgeHubRestartTester/EdgeHubRestartTester.csproj
- test/modules/MetricsValidator/MetricsValidator.csproj
- test/modules/ModuleLib/Microsoft.Azure.Devices.Edge.ModuleUtil.csproj
- test/modules/ModuleRestarter/ModuleRestarter.csproj
- test/modules/Relayer/Relayer.csproj
- test/modules/TemperatureFilter/TemperatureFilter.csproj
- test/modules/TwinTester/TwinTester.csproj
- test/modules/load-gen/load-gen.csproj
Update Microsoft.Azure.Devices.Client version to 1.36.4 which includes fix for dotnetty bug where it created threads in foreground instead of background. The bug in dotnetty caused issue with certificate renewal in edgeHub because the process is not terminated when UpstreamProtocol is Mqtt.
Tested manually that certificate renewal works.
> Update Microsoft.Azure.Devices.Client from 1.36.3 to 1.36.4 (#6115)

- builds/e2e/templates/e2e-setup.yaml
Based on two recent pipeline failures on ARM32 Raspberry Pis, the ValidateMetrics test needs more time to complete. Kusto logs were examined and they indicated that the ValidateMetrics direct method call succeeded within 30 seconds of the test timing out and failing.  Therefore, extending the timeout by 2 minutes should be more than enough time to fix this issue.
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR …
> Fix ValidateMetrics e2e test by increasing timeout

- builds/e2e/e2e.yaml
- builds/e2e/templates/e2e-setup.yaml
The TestGetModuleLogs test occasionally fails, not because it does something wrong but because it simply doesn't have time to finish all the stuff it's trying to do. This change increases the end-to-end test timeout to 8 minutes for Windows. It also increases the overall test time allotment to 120 minutes (default is 60). We really don't need to double the allotment, but arm32v7 will already take this long so it won't hurt to double (as opposed to picking some arbitrarily smaller value).
TestGetModuleLogs has only failed twice for this reason in the last couple of weeks, so it's hard to know whether this corrects the problem. But as long as this doesn't break anything, we'll make this change and see if flaky runs disappear over time.
This checklist is used to make sure that common …
> Increase test timeout for Windows

- edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/Microsoft.Azure.Devices.Edge.Agent.Diagnostics.csproj
- edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/Microsoft.Azure.Devices.Edge.Agent.IoTHub.csproj
- edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/Microsoft.Azure.Devices.Edge.Hub.Core.csproj
- test/Microsoft.Azure.Devices.Edge.Test/Module.cs
Reference dotnetty.common 0.7.1 to force using this version because it has a fix for bug introduced in 0.7.0 which client SDK uses. Bug causes edgeHub process to not be terminated for certificate renewal when UpstreamProtocol is Mqtt
Tested manually that edgeHub shutdown works when UpstreamProtocol is Mqtt and added e2e test for Mqtt.
> add dotnetty.common reference to 0.7.1

- edgelet/Cargo.lock
- edgelet/edgelet-http/Cargo.toml
- edgelet/edgelet-test-utils/Cargo.toml
- tools/snitch/snitcher/Cargo.toml
For Windows, or edgelet code depends on three repositories whose default branches were renamed:
Azure/hyperlocal-windows
Azure/mio-uds-windows
Azure/tokio-uds-windows
In various Cargo.toml files, we weren't specifying the crate's branch, so cargo was assuming "master". In the case of mariner builds, the rename caused build failures because the vendored crate no longer matches the patched crate. This change updates all Cargo.toml references to explicitly name the branch.
I confirmed that the edgelet packages build passes with these changes.
> Update Windows crate dependencies following branch rename

- scripts/linux/buildImage.sh
Workaround for `docker buildx` using in correct ARM arch for image build
I have manually run the image build and verify that all the arch images are correctly built.
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes all the commits in the PR to a single commit. The net effect is that entire PR becomes a single commit. Please follow …
> Workaround for `docker buildx` using in correct ARM arch for image build

- scripts/linux/buildImage.sh
Our pipeline for building Docker images occasionally builds aarch64 images on top of arm32v7 base images. This behavior is intermittent, and we've only noticed it when building the diagnostics image (used by `iotedge check`).
I was able to reproduce this behavior locally. If I built the diagnostics image for arm32v7 first, then when I built for aarch64 it would be based on arm32v7. If I built for aarch64 first, then when I built for arm32v7 it would be based on aarch64.
I identified three ways to fix the problem:
1. Clear the buildx cache between each docker build with `docker buildx prune --all --force`
2. Create a new builder instance with `docker buildx create --name {name}; docker buildx use {name}`. Note that with this option, I could use the _single_ builder instance for both …
> Fix aarch64 diagnostics module build

- builds/e2e/templates/unlock-test-agents.yaml
- scripts/linux/nestedAgentLock.sh
Nested E2E Test had a one-off problem where it failed to unlock an agent, but succeeded in the subsequent unlock attempt. Enhancing this lock/unlock logic.
- Bump retries
- Log error in case of failed POST
Changes running:
https://dev.azure.com/msazure/One/_build/results?buildId=52735964&view=results
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit …
> Nested E2E: Enhance lock/unlock logic

- builds/checkin/edgelet.yaml
- builds/ci/edgelet.yaml
The fix we needed was merged into upstream a long time ago.
Ref: https://github.com/cross-rs/cross/issues/52
Ref: https://github.com/cross-rs/cross/commit/249500e9a1f953d7eeca8a8b744e3aa1a10f64e6
> Revert usage of arsing/cross to upstream cross 0.2

- platform-validation/scripts/aziot-compatibility.sh
- scripts/linux/buildImage.sh
Checking package managers like apt-get, yum, rpm, dpkg. 
apt-get installs the default dependencies like ca-certificates. When apt-get is not present, an additional check is also made.
> [Tools] Package manager check and CA cert check

- builds/e2e/e2e.yaml
This change moves our arm64 end-to-end tests to use preview 1ES-hosted agent pools instead of Raspberry Pis. The job runs a lot faster, and it reduces the physical hardware we have to maintain. The tradeoff is that, while arm64 agents are in preview, there are limitations we have to work around by adding ugly script directly into the job yaml. We should be able to remove it soon, when arm64 agents become generally available.
I ran the end-to-end test pipeline a few times and made sure it passed.
> Use 1ES-hosted agent pool for arm64 end-to-end tests

- platform-validation/scripts/aziot-compatibility.sh
* Updated the directory path to be queried from OpenSSL instead of /etc/ca-certificates
* Updated to check if the directory is empty for determining if the ca-certificates are installed.
* Update skip counter and add wrap_skip function
> Update CA cert check to query certificates directory from OpenSSL

- .github/.kodiak.toml
In the main branch, we've set up the kodiak tool to remove the PR template text from merge commits. This change brings the same behavior to the release/1.1 branch.
> Remove PR template body from commits

- test/Microsoft.Azure.Devices.Edge.Test.Common/linux/PackageManagement.cs
Some E2E tests are failing for "Network is down" error - @damonbarry pointed out that this is apt-get returning error 100.
The logs say apt-get is failing because another process has the lock, and it appears to be `unattended-upgr`- automatic updates.
There's an apt option (`DPkg::Lock::Timeout`) that lets us wait on the lock. This option should work on apt-get versions 1.9.11 or later, but experimentation shows this only works for "install" and not "update."  So it may not fix all problems.
I also (manually) confirmed this option is ignored for apt-get versions lower than this, so this won't fix test failures on 18.04, but I don't think we have `unattended-upgr` running on our 18.04 systems.
A successful E2E test run will show this doesn't break E2E tests.
This checklist is used to make …
> E2E tests: Allow apt-get to wait up to 5 minutes on lock.

- test/Microsoft.Azure.Devices.Edge.Test.Common/linux/PackageManagement.cs
Allow apt-get to wait up to 5 minutes on lock. 
This option should work on apt-get Version 1.9.11 or later,
but experimentation shows this only works for "install" and not "update" so it may not fix all problems
> Allow apt-get to wait up to 5 minutes on lock. (#6259)

- mqtt/edgelet-client/src/workload/client.rs
- mqtt/edgelet-client/src/workload/models/cert_response.rs
- mqtt/edgelet-client/src/workload/models/identity_cert.rs
- mqtt/edgelet-client/src/workload/models/server_cert.rs
- mqtt/edgelet-client/src/workload/models/sign_request.rs
- mqtt/edgelet-client/src/workload/models/trust_bundle.rs
- mqtt/mqtt-bridge/src/pump/builder.rs
- mqtt/mqtt-broker-tests-util/src/client.rs
- mqtt/mqtt-broker/src/broker.rs
- mqtt/mqtt-broker/src/persist.rs
- mqtt/policy/src/core/builder.rs
> [main] Add must_use attributes to methods returning Self

- builds/e2e/templates/e2e-setup.yaml
- mqtt/policy/src/core/builder.rs
Manifest Trust Setup build step isn't using proxy env vars. Fixing.
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes all the commits in the PR to a single commit. The net effect is that entire PR becomes a single commit. Please follow the best practices mentioned [here](https://chris.beams.io/posts/git-commit/#:~:text=The%20seven%20 …
> E2E: Fix proxy Manifest Trust Setup build step

- edgelet/Cargo.lock
- edgelet/edgelet-core/src/lib.rs
- edgelet/edgelet-http-mgmt/src/device_actions/reprovision.rs
- edgelet/edgelet-http-mgmt/src/identity/create_or_list.rs
- edgelet/edgelet-http-mgmt/src/identity/delete_or_update.rs
- edgelet/edgelet-http-mgmt/src/module/create_or_list.rs
- edgelet/edgelet-http-mgmt/src/module/delete_or_get_or_update.rs
- edgelet/edgelet-http-mgmt/src/module/prepare_update.rs
- edgelet/edgelet-http-workload/src/module/cert/identity.rs
- edgelet/edgelet-http-workload/src/module/cert/server.rs
- edgelet/edgelet-http-workload/src/module/data/decrypt.rs
- edgelet/edgelet-http-workload/src/module/data/encrypt.rs
- edgelet/edgelet-http-workload/src/module/data/sign.rs
- rust-toolchain.toml
This is our monthly toolchain upgrade to the latest stable version. Since iotedge/edgelet is a binary package, we want to be tracking Rust compiler releases closely in the event a stdlib vulnerability is found. We do not pin to "stable", however, since that has caused pipeline breakage when some code patterns are made illegal (like in the upgrade from 1.47 to 1.48 [^0]) or, more often, clippy lints are added.
- Change from `cloned()` to `copied()` since we can and to work around ICE: rust-lang/rust-clippy#8662
[^0]: https://github.com/rust-lang/rust/blob/master/RELEASES.md#compatibility-notes-11
Namely, the point on `mem::uninitialized`.
> [main] Upgrade to latest Rust version

- edgelet/build/windows/openssl.ps1
When building edgelet, the HSM components need a local installation of OpenSSL to link against. In our "iotedged Checkin" pipeline (and probably elsewhere) we build OpenSSL from source using vcpkg. A couple weeks ago, vcpkg updated their OpenSSL scripts to build 3.0 instead of 1.1.1. We see build errors in our pipelines when attempting to link against OpenSSL 3.0.
This change pins the vcpkg port of openssl to a specific commit (1.1.1n). The approach is recommended [here](https://vcpkg.io/en/docs/about/faq.html#how-do-i-use-different-versions-of-a-library-on-one-machine). This allows us to continue building edgelet the way we were before. We only need to do this in `release/1.1` as our architecture is quite different in 1.2.
This checklist is used to make sure that common guidelines for a …
> Fix openssl build on windows

- builds/e2e/templates/e2e-run-metrics-collector.yaml
In a recent change, the string that filters out a single end-to-end test to run in the metrics collector release pipeline was inadvertently changed, a victim of search and replace. ;)
> Fix reference to MetricsCollector end-to-end test

- builds/e2e/e2e.yaml
Debian 9 is EOL and we will not have tier 1 support in the next LTS so we can remove the E2E test. …
> Remove debian 9 E2E test job

- edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/SystemInfo.cs
- edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/SystemInfoTest.cs
The recent PR for adding arbitrary device product information (#6089) changed the structure of Microsoft.Azure.Devices.Edge.Agent.Core.SystemInfo, which in turn affected the metrics sent upstream.  While it is no longer feasible with the current regime of passing through extra properties to restore the old property names verbatim, we can at least flatten the additional properties to restore the general shape of the serialized information.  There is also a new test verifying that the flattening occurs as expected.
> [release/1.2] Flatten additional properties of metrics

- edgelet/iotedge/src/check/checks/check_openssl.rs
- edgelet/iotedge/src/check/checks/mod.rs
Openssl functionality is tested to see if the platform is capable of creating self signed certs. 
Note: openssl functions do not write any files to the disk so no clean up is needed.
> Add Openssl check in Iotedge check

- test/Microsoft.Azure.Devices.Edge.Test.Common/LeafDevice.cs
- test/modules/CloudToDeviceMessageTester/CloudToDeviceMessageReceiver.cs
We want to change our approach with retries for these reasons:
1. We stopped seeing IoTHubCommunicationException in the last four runs off of main, when previously this was very unstable for a long time. Did not expect this so we should remove this retry to be sure it is absolutely needed. We can add it back later (with ideally some more specific exception message catching) if needed.
2. We want to catch the known dotnet 6 SDK issues we have bugs logged for on them. I'd rather take a conservative approach here though and only catch the ones that directly affect connectivity tests for sure.
- Work in progress or not …
> Connectivity Tests: Change retry approach in C2D receiver

- builds/e2e/e2e-release.yaml
- builds/e2e/templates/e2e-run-base-image-update.yaml
- builds/e2e/templates/e2e-setup-base-image-update-release.yaml
This PR removes the Manifest trust feature from the Base image update release pipeline.
> Remove manifest trust from base image update release pipeline

- scripts/linux/publishReleasePackages.sh
- `packages.microsoft.com` can take up to 30 minutes to show up in GA. We should increase the validation to pass up until then. If it continues to fail after 30 minutes, we have a bigger issue and should contact Linux Repo team.
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes all the commits in the PR to a single commit. The net …
> Increase the validation timeout for PMC package upload

- scripts/linux/publishReleasePackages.sh
- `packages.microsoft.com` can take up to 30 minutes to show up in GA. We should increase the validation to pass up until then. If it continues to fail after 30 minutes, we have a bigger issue and should contact Linux Repo team.
Cherry-picked: https://github.com/Azure/iotedge/commit/5f9a1eb9acc944076ec3f7bb9fd4862092bda2c6
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description …
> Increase the validation timeout for PMC package upload 

- edgelet/aziot-edged/src/error.rs
- edgelet/aziot-edged/src/main.rs
systemd only restarts aziot-edged when it returns a nonzero exit code due to its configuration being restart "on-failure". Fixes aziot-edged when restarting due to reprovisioning so that it returns an nonzero exit code.
> Fix exit code when restarting due to reprovision

- builds/misc/packages-release.yaml
- scripts/linux/github/updateLatestVersion.sh
- scripts/linux/publishReleasePackages.sh
- Integrate the script from (https://github.com/Azure/iotedge/pull/6343) with the pipeline to automagically increment & tag the github branch for /azure-iotedge repository
- Fix the bug when the release page uses a whole changelog instead of parsing correctly.
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes all the commits in the …
> Github Release Page and Tagging Automation for /azure-iotedge

- builds/misc/templates/build-packages.yaml
- edgelet/build/linux/package-mariner.sh
Reverts Azure/iotedge#6375. This change should be fixed in the pipelines now, so we can add this back. This also makes the Mariner 2.0 use prod since there appears to be an issue in the preview repo right now.
>  add back"Mariner ARM64 Build [Squashed]"

- builds/checkin/edgelet.yaml
- edgelet/build/linux/install.sh
cargo tarpaulin is pinned to the latest 0.18.x version in release/1.1
However, it doesn't pin its upstream dependences to certain versions. 
What's currently happening is that a change to[ libz-sys ](https://crates.io/crates/libz-sys/versions)5 days ago, has caused that version (1.1.18) to be pulled in and break the cargo tarpaulin compile.
This PR ensures that only locked upstream dependences are pulled in for the cargo tarpaulin compile.
> Lock cargo tarpaulin upstream dependences to a specific version

- builds/checkin/edgelet.yaml
cargo tarpaulin doesn't pin its upstream dependences to certain versions.
This runs the risk that a change/update to an upstream dependency might be pulled in and end up breaking the cargo tarpaulin compile. This isn't a problem right now, but with 1.3 being cut, this is likely to be a problem down the line.
This PR ensures that only locked upstream dependences are pulled in for the cargo tarpaulin compile.
> [1.3] Lock cargo tarpaulin upstream dependences to a specific version

- builds/checkin/e2e-checkin.yaml
- builds/ci/dotnet.yaml
- builds/e2e/compare-compatibility.yaml
- builds/e2e/connectivity.yaml
- builds/e2e/e2e.yaml
- builds/e2e/isa-95-smoke-test.yaml
- builds/e2e/nested-e2e.yaml
- builds/misc/images.yaml
- builds/misc/packages.yaml
- builds/service/service-deployment.yaml
The SCCA task can fail the builds if it detects Dockerfiles in our repo that reference external images. We're working on a solution with the SCCA team that will meet the needs of our open-source project. In the meantime, we're disabling this task on their recommendation.
I used the Build Images pipeline to confirm that the SCCA task passes when the `DisableDockerDetector` variable is set in the pipeline.
> Disable SCCA task

- builds/checkin/edgelet.yaml
Straight cherry-pick of https://github.com/Azure/iotedge/pull/6392
cargo tarpaulin is pinned to the latest 0.18.x version in release/1.1
However, it doesn't pin its upstream dependences to certain versions. 
What's currently happening is that a change to[ libz-sys ](https://crates.io/crates/libz-sys/versions)5 days ago, has caused that version (1.1.18) to be pulled in and break the cargo tarpaulin compile.
This PR ensures that only locked upstream dependences are pulled in for the cargo tarpaulin compile.
> Lock cargo tarpaulin upstream dependences to a specific version (#6392)

- builds/e2e/templates/e2e-run.yaml
- builds/e2e/upgrade-scenarios.yaml
Fixes the artifact suffix so that System.JobName is only used when upgrade scenario tests are run. Otherwise, it goes back to using System.PhaseName.
Changes have been tested by running E2E and upgrade scenario pipelines. …
> Fix E2E pipeline artifact name collision

- builds/e2e/templates/e2e-run.yaml
- builds/e2e/upgrade-scenarios.yaml
Fixes the artifact suffix so that System.JobName is only used when upgrade scenario tests are run. Otherwise, it goes back to using System.PhaseName.
Changes have been tested by running E2E and upgrade scenario pipelines. …
> Fix E2E pipeline artifact name collision 1.1

- builds/misc/packages-release.yaml
There is a known docker issue with Debian 10 which we will not support it as a tier 1 OS. However, some of our customers are still relying on our iot-identity-service components, which we are going to continue to support readily in Packages.Microsoft.Com for ARM32, Debian10.
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes all the …
> Publish ARM32 iot-identity-service artifacts for Debian10 in PMC

- builds/e2e/templates/e2e-run.yaml
- builds/e2e/upgrade-scenarios.yaml
Fixes the artifact suffix so that System.JobName is only used when upgrade scenario tests are run. Otherwise, it goes back to using System.PhaseName.
Changes have been tested by running E2E and upgrade scenario pipelines. …
> Fix E2E pipeline artifact name collision 1.2

- test/Microsoft.Azure.Devices.Edge.Test/EdgeAgentDirectMethods.cs
Mitigates the failure likelihood for the UploadSupportBundle E2E test by reducing the amount of data being uploaded. This should reduce the likelihood of timeout on resource constrained agents such as 32-bit Raspberry Pis. 
Also, the response and connection timeouts for both the UploadSupportBundle and GetTaskStatus direct methods have been set to the max allowed value of 300 seconds. This aligns with the values on the 1.2 branch.
These changes build on top of #6424, which allowed the tests to get farther (i.e. edgelet now gets the supportbundle GET request that it was not getting previously in observed failure scenarios).
I've run the pipeline 3 times and it succeeded each time.
- Description of …
> Mitigate upload support bundle test issues

- test/Microsoft.Azure.Devices.Edge.Test/EdgeAgentDirectMethods.cs
Mitigates E2E test failures on resource constrained agents such as the 32-bit Raspberry Pis. 
The timeout values on other branches (i.e. release/1.2 and release/1.1) are already set to 300, so this change aligns the main branch with the release branches.
A test pipeline was run and it was confirmed that all direct method tests passed.
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR …
> Increase E2E test direct method timeouts to 300 sec

- builds/misc/templates/build-packages.yaml
Fix the docker install required for the mariner package creation process.  This adds some additional time to wait for the 1ES agent to update before trying to install docker on the build machine. This also adds back the mariner package builds to the packaging piplines
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes all the commits …
> Fix Failing Install For Docker on Ubuntu aarch64 Agent 

- doc/IoTEdgeManifestTrust.md
- doc/NotaryContentTrust.md
- samples/dotnet/ManifestSignerClient/Readme.md
It was pointed to main branch instead of feature branch.
> Fix Document links for manifest trust that were broken

- edge-modules/metrics-collector/src/Settings.cs
Fixed configuration key of the experimental feature flag (a environment variable called "experimentalFeatures__AddIdentifyingTags" results in the key "experimentalFeatures:AddIdentifyingTags").
https://docs.microsoft.com/en-us/dotnet/core/extensions/configuration-providers#environment-variable-configuration-provider
Fixes my previous PR.
https://github.com/Azure/iotedge/pull/6114#discussion_r891470429
> Fixed configuration key of the experimental feature flag.

- builds/e2e/connectivity.yaml
- builds/e2e/isa-95-smoke-test.yaml
- builds/e2e/longhaul.yaml
- builds/e2e/nested-e2e.yaml
- builds/e2e/nested-longhaul.yaml
- builds/misc/mqtt-perf.yaml
- builds/service/service-deployment.yaml
Disable scheduled auto-trigger for all the pipelines in release/1.2 branch. 
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes all the commits in the PR to a single commit. The net effect is that entire PR becomes a single commit. Please follow the best practices mentioned [here](https://chris.beams.io/posts/git-commit/#:~:text=The%2 …
> Disabled scheduled autorun for test pipelines

- builds/e2e/connectivity.yaml
- builds/e2e/isa-95-smoke-test.yaml
- builds/e2e/longhaul.yaml
- builds/e2e/nested-e2e.yaml
- builds/e2e/nested-longhaul.yaml
- builds/e2e/upgrade-scenarios.yaml
- builds/service/service-deployment.yaml
This change makes several updates to schedule triggers in various pipelines to bring them up to date and make them more consistent with one another:
- Update triggers to target release/1.3 instead of release/1.2. Note that, given how [schedule triggers work](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/scheduled-triggers?view=azure-devops&tabs=yaml#branch-considerations-for-scheduled-triggers) in Azure pipelines, these changes in `main` won't actually impact the schedules in `release/1.2` or `release/1.3`. To do that, we'll need to make changes in the respective branches. #6453 covers `release/1.2`, and I'll merge this change into `release/1.3` as well.
- In cases where schedule triggers are found in other branches besides `main` for a given pipeline, bring those …
> Update scheduled triggers in pipelines

- edgelet/contrib/centos/aziot-edge.spec
- edgelet/contrib/enterprise-linux/aziot-edge.spec
It looks like yum rpmbuild now includes the `%{?dist}` to version string i.e. `1.3.0-1.el7`, `1.3.0-1.el8` instead of being `1.3.0-1`.
This change to update our edgelet spec to facilitate the version string difference.
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes all the commits in the PR to a single commit. The net effect is …
> Introduce the `%{?dist}` to the version string

- edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/Microsoft.Azure.Devices.Edge.Agent.Diagnostics.csproj
- edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Docker/Microsoft.Azure.Devices.Edge.Agent.Docker.csproj
- edge-modules/functions/samples/EdgeHubTrigger-Csharp/EdgeHubTriggerCSharp.csproj
- edge-util/src/Microsoft.Azure.Devices.Edge.Util/Microsoft.Azure.Devices.Edge.Util.csproj
- edge-util/test/Microsoft.Azure.Devices.Edge.Util.Test.Common/Microsoft.Azure.Devices.Edge.Util.Test.Common.csproj
- test/Microsoft.Azure.Devices.Edge.Test.Common/Microsoft.Azure.Devices.Edge.Test.Common.csproj
- test/modules/TwinTester/TwinTester.csproj
- test/modules/load-gen/load-gen.csproj
Update NewtonSoft to 13.0.1 to address CG and Dependabot alerts.
> Update NewtonSoft to 13.0.1

- edge-modules/edgehub-proxy/Cargo.lock
Change to address dependabot alert - https://github.com/Azure/iotedge/security/dependabot/3
> Update Tokio dependencies in edgehub-proxy to address dependabot alerts

- edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Integration.Test/AgentTestsBase.cs
I[ ran CI](https://msazure.visualstudio.com/One/_build/results?buildId=57914110&view=results) to validate #6508, but then decided to change the env var name per discussion with Bishal.
This regressed a test unexpectedly so fixing it here.
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes all the commits in the PR to a single commit. …
> Edge Agent: Stabilize ModulePriorityTest

- scripts/linux/buildImage.sh
- scripts/linux/buildRocksDb.sh
We recently started using the dockersource tool to generate the `--build-context` argument that gets passed to `docker buildx build` in our Docker image builds pipeline. Last week, it was moved to a new repo and renamed. This change updates our references to the tool. Without this change, image builds will fail because these scripts refer to a tool that no longer exists by the name 'dockersource'.
I ran the Build Images pipeline against these changes to exercise the script changes.
> Rename dockersource to gnarly

- edgelet/contrib/config/linux/template.toml
`aziot-tpmd` now has configuration options for TCTI loader string, DPS key storage index, and hierarchy authorization values. These are now included in the template configuration.
For technical discussion on the `aziot-tpmd` changes, see Azure/iot-identity-service#415.
> [main] Include tpmd configuration section from IIS

- edgelet/contrib/centos/aziot-edge.spec
- edgelet/contrib/debian/postrm
- edgelet/contrib/debian/preinst
- edgelet/contrib/enterprise-linux/aziot-edge.spec
- Delete edgeagentuser and edgehubuser during package purge
- Allow creation of edgeagentuser and edgehub user to fail during package install. edgeHub and edgeAgent will still work if their users don't exist on the host. The host will misidentify files owned by edgeHub and edgeAgent, but the modules will still work.
> Fix creation and cleanup of edgeagentuser and edgehubuser

- builds/misc/addons-release.yaml
- builds/misc/images-release-base-image-update.yaml
- builds/misc/images-release.yaml
- builds/misc/templates/build-images.yaml
- builds/misc/templates/image-linux.yaml
The script argument 'buildx_flag' was removed a458af376177adacb25349cc8f59df8aae9e1a15 but references weren't removed from the build pipelines. This change updates the pipelines.
I ran the Build Images pipeline to confirm that nothing bad happens.
> Remove unused 'buildx_flag' from pipelines

- builds/misc/images-release-base-image-update.yaml
The standard Docker images release pipeline was updated in 37234e02b500e6930d389275ac09a5aee80f7445, but the corresponding parts of the base images release pipeline were not updated. This change brings the two back in sync:
- References to old templates `dotnet2-globaljson.yaml` and `dotnet3-globaljson.yaml` are replaced with `force-dotnet21.yaml` and `restore-default-dotnet.yaml`, respectively
- The nuget package task is reordered for clarity
> Update base image release pipeline

- edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/planner/HealthRestartPlanner.cs
- edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/commandfactories/ExecutionPrerequisiteCommandFactory.cs
- edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/commandfactories/StandardCommandFactory.cs
- edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Integration.Test/test-configs/module-priority-test-config.json
I was doing some manual validation of my the Edge Agent feature I contributed in a prior PR:
https://github.com/Azure/iotedge/pull/6508
This validation turned up a bug relating to some side effects of how we restructured the command factories:
1. Update commands no longer are a GroupCommand with a PrepareUpdateCommand nested inside. This meant that on EdgeAgent update, new EdgeAgent image was not pulled before EdgeAgent went down.
2. Related to above, EdgeAgent needs dedicated PrepareUpdate command that will throw PrerequisiteException to block subsequent plan execution commands from running.
I have fixed both of these in this PR and added a test for when EdgeAgent container is updated with this feature flag on.
This checklist is used to make sure that common guidelines for a pull request …
> Edge Agent: Fix bug where Edge Agent is updated without backing image

- builds/e2e/connectivity.yaml
- builds/e2e/isa-95-smoke-test.yaml
- builds/e2e/longhaul.yaml
- builds/e2e/nested-e2e.yaml
- builds/e2e/nested-longhaul.yaml
- builds/misc/packages-release.yaml
- scripts/linux/github/updateLatestVersion.sh
This change updates schedule triggers in various pipelines to include the upcoming `release/1.4` branch instead of `release/1.3`. Note that, given how [schedule triggers work](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/scheduled-triggers?view=azure-devops&tabs=yaml#branch-considerations-for-scheduled-triggers) in Azure pipelines, these changes in `main` won't actually impact the schedules in `release/1.4` because the latter branch doesn't exist yet. But the schedules will light up as soon as the new branch is created.
This change also updates the Packages Release pipeline to point to the upcoming `release/1.4` branch of the Azure/iot-identity-service repo.
- Description of the …
> Update release/1.x references in pipelines

- builds/misc/packages.yaml
The edgelet packages pipeline runs every time a commit is merged to main. It should also run when commits are merged to release/1.4. This change updates the trigger spec to make that happen. Once this change is merged into main I'll also make sure it goes to release/1.4, since that's where the trigger will be evaluated.
> Fix packages pipeline CI trigger

- builds/e2e/templates/e2e-setup-base-image-update-release.yaml
- builds/e2e/templates/e2e-setup.yaml
Our end-to-end test pipeline references a key vault secret that allows the test agent to trust the dev-signed IoT Edge Windows installer (CAB). Since we don't publish a Windows CAB file in v1.2+, we no longer need the secret.
> Remove unused secret from test pipeline

- edgelet/Cargo.lock
- edgelet/aziot-edged/Cargo.toml
- edgelet/contrib/centos/aziot-edge.spec
- edgelet/contrib/debian/control
- edgelet/contrib/enterprise-linux/aziot-edge.spec
- edgelet/edgelet-core/Cargo.toml
- edgelet/edgelet-docker/Cargo.toml
- edgelet/edgelet-http-mgmt/Cargo.toml
- edgelet/edgelet-http-workload/Cargo.toml
- edgelet/edgelet-http/Cargo.toml
- edgelet/edgelet-image-cleanup/Cargo.toml
- edgelet/edgelet-settings/Cargo.toml
- edgelet/edgelet-test-utils/Cargo.toml
- edgelet/iotedge/Cargo.toml
- edgelet/iotedge/src/config/import/old_config/mod.rs
- edgelet/iotedge/src/config/super_config.rs
- platform-validation/scripts/aziot-compatibility.sh
- test/Microsoft.Azure.Devices.Edge.Test.Common/config/AgentModuleConfigBuilder.cs
- test/Microsoft.Azure.Devices.Edge.Test.Common/config/HubModuleConfigBuilder.cs
- test/Microsoft.Azure.Devices.Edge.Test/Image.cs
- test/Microsoft.Azure.Devices.Edge.Test/Metrics.cs
- test/Microsoft.Azure.Devices.Edge.Test/Module.cs
- test/Microsoft.Azure.Devices.Edge.Test/SetupFixture.cs
- test/doc/e2e.md
- versionInfo.json
Updating edgelet refs for release/1.4. Referenced Arnav's PR:
https://github.com/Azure/iotedge/pull/6460
Also contains changes from this PR, which we needed to combine PRs to avoid long checkin times for a time sensitive release:
https://github.com/Azure/iotedge/pull/6623
> Prepare for release 1.4.0

- builds/checkin/e2e-checkin.yaml
My recent update (96df97d) to unify the image and package builds introduced a regression. I removed the pipeline resources defined in e2e-checkin.yaml because I thought they were unused (my runs passed without them). But it turns out they _are_ needed in cases where either images or packages aren't built inline. This can happen when, for example, the PR that triggers the pipeline only made changes to one and not the other. The pipeline resources serve as the fallback source for either images or packages in this case.
> Add CI build as pipeline resource in E2E-Checkin pipeline

- builds/service/service-deployment.yaml
The service deployment pipeline runs an end-to-end scenario using released IoT Edge bits. Services like IoT Hub use it to test their latest releases against IoT Edge. Now that 1.4 has been released and will receive long-term support, this change updates the pipeline to use 1.4 bits instead of 1.1.
> Upgrade service deployment pipeline to 1.4

- builds/e2e/e2e-release.yaml
- builds/e2e/e2e.yaml
- builds/misc/metrics-collector-images-release.yaml
The arm64v8 jobs on pipelines in `main` were migrated from Raspberry Pi to 1ES-hosted agent VMs a while back, but the corresponding changes were never made in `release/1.1`, until now.
I verified that the end-to-end test pipeline passes with this change.
> Upgrade to 1ES-hosted arm64 agents in test/release pipelines

- test/Microsoft.Azure.Devices.Edge.Test/Metrics.cs
The `ValidateMetrics` end-to-end test deploys a module to the test device then removes it in order to bump a particular metric. It doesn't matter which module is used; we just need to add something then remove it. Currently, we've hardcoded `mcr.microsoft.com/azureiotedge-simulated-temperature-sensor:1.0`. Because that isn't one of the images listed in context.json, our test pipeline doesn't preload it on slow test devices, which means it has to be downloaded during the test, which eats into the test's timeout duration.
The `ValidateMetrics` test is consistently timing out on Raspberry Pi. Changing the test to use the tempSensor image from context.json _should_ speed up the test and prevent the timeouts.
I ran the end-to-end pipeline against these changes and `ValidateMetrics` passed on …
> Use preloadable temporary module in ValidateMetrics

- builds/e2e/e2e-release.yaml
When we migrated test pipelines over to use 1ES agents for arm64, we missed one in the `main` branch: the base image update  pipeline. This PR updates it to use a 1ES-hosted agent (Azure VM) instead of a Raspberry Pi from our lab.
> Test arm64 using 1ES agent in image release pipeline

- edge-modules/metrics-collector/src/ModuleClientWrapper.cs
- edge-modules/metrics-collector/src/Program.cs
- edge-modules/metrics-collector/src/Settings.cs
This PR:
1. Makes transport type configurable
2. Fixes bug where metrics collector will restart if cannot connect to EdgeHub when using AzureMonitor upload target. Now it will log a warning and continue in case of failed connection to EdgeHub. This connection is only used for internal diagnostics so it can be treated as recoverable.
Manually tested:
- Case where can switch between transport types
- Case where can work when opposite protocol head disabled in EdgeHub
- Case where can work when used protocol head disabled in EdgeHub and upload target is log analytics
- Case where won't work when used protocol head disabled in EdgeHub and upload target is iot message
- Description of the pull request …
> Metrics Collector: Support for configurable transport type

- edgelet/Cargo.lock
- edgelet/edgelet-core/src/lib.rs
- edgelet/edgelet-core/src/module.rs
- edgelet/edgelet-settings/src/base/aziot.rs
- edgelet/edgelet-settings/src/base/image.rs
- edgelet/edgelet-settings/src/base/mod.rs
- edgelet/edgelet-settings/src/base/module.rs
- edgelet/edgelet-settings/src/base/uri.rs
- edgelet/edgelet-settings/src/docker/network.rs
- edgelet/iotedge/src/check/checks/proxy_settings.rs
- edgelet/iotedge/src/check/checks/storage_mounted_from_host.rs
- edgelet/iotedge/src/check/mod.rs
- edgelet/support-bundle/src/support_bundle.rs
- rust-toolchain.toml
- test/rust-test-util/test-result-reporting-client/src/models/message_result.rs
This is our monthly toolchain upgrade to the latest stable version. Since the primary artifacts of this repository are binaries, we want to be tracking Rust compiler releases closely in the event a stdlib vulnerability is found. We do not pin to "stable", however, since that has caused pipeline breakage when some code patterns are made illegal (like in the upgrade from 1.47 to 1.48 [^0]) or, more often, clippy lints are added.
- `clippy::borrow_deref_ref`: remove unnecessary uses of `&*`
- `clippy::derive_partial_eq_without_eq`: derive `Eq` where possible
[^0]: https://github.com/rust-lang/rust/blob/1.48.0/RELEASES.md#compatibility-notes
Namely, the point …
> Upgrade to Rust 1.63

- builds/misc/images-release.yaml
We need to publish Diagnostics module for release 1.4.1 as the module is highly coupled with edgelet artifacts and self-help. 
The images were not part of the release 1.4.1; hence, the Diagonostic module was not updated causing a failure in the use cases.
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes all the commits in the PR to …
> Only publishing the Diagnostics image

- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/Microsoft.Azure.Devices.Edge.Hub.Core.csproj
- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/Microsoft.Azure.Devices.Edge.Hub.Mqtt.csproj
Fixes #6630.
DotNetty has an OOM bug that is fixed in v0.7.5. Two components in Edge Hub have a transitive dependency on DotNetty:
* Microsoft.Azure.Devices.Edge.Hub.Core via Microsoft.Azure.Devices.Client
* Microsoft.Azure.Devices.Edge.Hub.Mqtt via Microsoft.Azure.Devices.ProtocolGateway.Core.
The best approach is for our dependencies to update their reference to DotNetty, then we update our dependencies. In the meantime, we'll make explicit references to override the transitive versions.
I used `dotnet list package --include-transitive` before and after the change to verify that the transitive dependency is replaced by the explicit dependency in the two updated projects, and that transitive packages are at 0.7.5 throughout the rest of Edge Hub. It would work to _only_ add explicit …
> Update dependency to fix OOM bug

- edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/EdgeAgentConnection.cs
Fixes a bug causing newly provisioned devices to delay uploading reported properties to IoT Hub for an hour, resulting in "NA" and "Error" status in Azure Portal.
These changes have been tested by building an EdgeAgent image from this branch and specifying the image as the Default Edge Agent image in config.toml.
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the …
> Fix bug causing Edge Agent 1-hour delay in sending reported properties to IoT Hub

- test/modules/DirectMethodSender/DirectMethodLocalSender.cs
Set Connection Timeout and Response Timeout to max values of 5 minutes in DirectMethodSender test module used by the ModuleToModuleDirectMethod method. This should reduce the failure rate of the test on ARM32v7 platforms where direct methods can take a long time to complete.
To test this change a CI Build pipeline was run from this branch and then an E2E pipeline was run using the resulting artifacts.
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it …
> Mitigate ModuleToModuleDirectMethod e2e test failures

- edge-modules/api-proxy-module/src/main.rs
- edge-modules/api-proxy-module/src/utils/shutdown_handle.rs
- edgelet/Cargo.lock
- edgelet/edgelet-docker/src/runtime.rs
- edgelet/edgelet-http/src/modules.rs
- edgelet/iotedge/src/check/checks/proxy_settings.rs
- rust-toolchain.toml
This is our monthly toolchain upgrade to the latest stable version. Since the primary artifacts of this repository are binaries, we want to be tracking Rust compiler releases closely in the event a stdlib vulnerability is found. We do not pin to "stable", however, since that has caused pipeline breakage when some code patterns are made illegal (like in the upgrade from 1.47 to 1.48 [^0]) or, more often, clippy lints are added.
- `clippy::derive_partial_eq_without_eq`: derive `Eq` where possible
- `clippy::single_match_else`: replace `match` with `if let`
- `clippy::unused_async`: remove `async`
- `clippy::unused_self`: make function associated
- `clippy::unnecessary_wraps`: remove unnecessary wrapping `Result`
This checklist is used to make sure that common guidelines for a pull request …
> Upgrade to Rust 1.64

- edgelet/iotedge/src/check/checks/container_engine_logrotate.rs
Cherry-pick PR #6734
This PR will make iotedge check respect docker's journald logdriver as a valid log rotation setting.
See issue #6728 …
> Make iotedge check respect journald as valid log rotation setting

- builds/e2e/connectivity.yaml
- builds/e2e/nested-e2e.yaml
Reducing nested e2e schedule to once per week.
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes all the commits in the PR to a single commit. The net effect is that entire PR becomes a single commit. Please follow the best practices mentioned [here](https://chris.beams.io/posts/git-commit/#:~:text=The%20seven%20rules%20of%20a%20grea …
> Nested E2E: Reduce schedule to once a week

- edgelet/Cargo.lock
- edgelet/edgelet-core/src/module.rs
- edgelet/edgelet-settings/src/docker/config.rs
- edgelet/edgelet-settings/src/docker/network.rs
- edgelet/edgelet-utils/src/yaml_file_source.rs
- edgelet/iotedge/src/check/checks/aziot_edged_version.rs
- edgelet/iotedge/src/check/checks/container_connect_upstream.rs
- edgelet/iotedge/src/check/checks/mod.rs
- edgelet/iotedge/src/check/checks/proxy_settings.rs
- edgelet/iotedge/src/client.rs
- edgelet/iotedge/src/config/apply.rs
- edgelet/iotedge/src/config/mp.rs
- edgelet/support-bundle/src/shell_util.rs
- rust-toolchain.toml
This is our monthly toolchain upgrade to the latest stable version. Since the primary artifacts of this repository are binaries, we want to be tracking Rust compiler releases closely in the event a stdlib vulnerability is found. We do not pin to "stable", however, since that has caused pipeline breakage when some code patterns are made illegal (like in the upgrade from 1.47 to 1.48 [^0]) or, more often, clippy lints are added.
- `clippy::explicit_auto_deref`: remove redundant dereferences
- `clippy::manual_string_new`: replace `"".to_owned()` with `String::new()` and `.unwrap_or_default()`
- `clippy::needless_borrow`: remove unnecessary borrows
Switching to `let .. else` where appropriate was skipped in the interest of keeping the changeset small.
This checklist is used to make sure that …
> Upgrade to Rust 1.65

- builds/checkin/api-proxy.yaml
- builds/checkin/compatibility-tool-checkin.yaml
- builds/checkin/edgelet.yaml
- builds/ci/dotnet.yaml
- builds/misc/packages-release.yaml
We still have a few Azure DevOps pipelines in our codebase the use Microsoft-hosted agents, and most of them are using "ubuntu18.04" which will be deprecated soon. This change updates the remaining references to Ubuntu 20.04 1ES agents.
To test, I ran the affected pipelines against the PR (except the release pipeline, but it is very similar to the edgelet part of the CI build, which already uses Ubuntu 20.04 1ES agents) and confirmed that they succeed.
> Move remaining pipelines to 1ES agents

- builds/release/refresh-core-images.yaml
In another PR that cherry-picks d7322af6f93d7f0c2e66c189a5c624f6afeeec22 to main, @onalante-msft pointed out some jq logic that could be simplified. I'm applying that suggestion to release/1.4 first, then I'll cherry-pick both commits to main.
I tested the jq logic locally and confirmed that it produces the same results as before (actually, it produces the array of docker image tags in a different order than the existing code, but order isn't important).
> Simplify some jq logic in refresh-core-images.yaml

- builds/misc/templates/image-linux.yaml
Azure Pipelines recently had a bug where they changed the default checkout behavior to fetch depth = 1, which is more performant but can cause problems with merges. They rolled back the change, but in the meantime, I added `fetchDepth: 0` in many places to mitigate. Adding it to the images-linux.yaml template causes a problem with the metrics collector release pipeline. I'm not sure if the problem is another bug in Azure Pipelines or not, but regardless they've rolled back their original change so I'm able to revert images-linux.yaml.
I ran the metrics collector release pipeline and the Build CI pipeline to confirm that the problem is fixed and doesn't appear to cause regressions in other pipelines. …
> Fix metrics collector release in main

- builds/misc/templates/image-linux.yaml
Our Docker image build template (image-linux.yaml) was recently modified to optionally build the manifest list too, as an optimization. But due to a copy/paste error, the template always builds the manifest list for Edge Agent instead of honoring the `manifestTemplate` param. This change fixes that problem. Note that currently, this feature is only being used for the auto-refresh builds.
I confirmed in a test environment that these changes have the desired effect.
> Fix manifest lists in Docker image build template

- CHANGELOG.md
- versionInfo.json
An update was released today for .NET 6.0. Normally, this means that our auto-refresh pipeline would detect updated base images and automatically create a 1.4.7 release. However, I temporarily disabled the auto-refresh pipeline and created a release commit for two reasons:
1. We updated our Newtonsoft.Json Nuget dependency some time back to take a security fix, and we'd like to get that into the release.
2. There have been some minor fixes to the auto-refresh pipeline itself, which I'd like to exercise with this release.
Once this is merged, I'll manually run the auto-refresh pipeline to complete the release. Then I'll re-enable the pipeline schedule.
> Prepare for release 1.4.7

- builds/misc/templates/image-linux.yaml
This is effectively a missed change from #6847. In the Docker image build template, there are two other arguments to `buildManifest.sh` that should be drawing from the parameters but are not. This change updates the template to use the `namespace` and `version` parameters. Without this fix, we fail to build the diagnostics module's manifest list when its version doesn't match the latest core runtime modules.
> Fix manifest image build, pt. II

- edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Docker/DockerRuntimeModule.cs
- edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/TestRuntimeModule.cs
- edgelet/Cargo.lock
- edgelet/edgelet-http/src/modules.rs
- edgelet/edgelet-settings/src/base/image.rs
- edgelet/support-bundle/src/shell_util.rs
IoT Hub requires UTC timestamps to end with 'Z' (ISO 8601); otherwise, it will interpret the timestamp as local time. This PR changes aziot-edged and edgeAgent to serialize to ISO 8601.
> Use ISO 8601 for UTC timestamps sent to IoT Hub (#6832)

- builds/misc/templates/image-linux.yaml
- builds/release/detect-image-updates.yaml
- builds/release/metrics-collector-images-publish.yaml
- builds/release/refresh-metrics-collector-images.yaml
- builds/release/templates/publish-core-images.yaml
- scripts/linux/release-tools.sh
This change builds on work from 6e3ac3cf117e9f1b1de5b1e4e4014214923f189b and 81f2633c3dc4d7f5d8abc525d9223d07493a2cf4.
The Metrics Collector Docker images all target .NET 6.0 Alpine base images. When those images change, often due to important security updates, we need to respond quickly by refreshing our own images. Doing so allows our users to keep their deployments up to date.
This change introduces a fully automated release pipeline (`refresh-metrics-collector-images.yaml`) for our Metrics Collector images. It is patterned after the core images refresh pipeline (`refresh-core-images.yaml`), and there may be opportunities to refactor common code in the future. It is triggered when the detection pipeline (`detect-image-updates.yaml`) completes for the main branch and will refresh and …
> Add a pipeline to auto-refresh Metrics Collector

- builds/release/refresh-metrics-collector-images.yaml
The regular metrics collector release pipeline adds the 'latest' tag to the published multi-arch image, but that detail was missed in new refresh pipeline. This change adds it.
> Add 'latest' tag to metrics collector image

- edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/device/DeviceMessageHandler.cs
This fix is related to IcM 333616549:
- when sending higher amounts of M2M messages via MQTT to a module, it can happen (within a few hours) that reauthentication (following a token expiration) happens when a M2M message got forwarded to the module, but the ACK was not sent back.
- when a M2M message is being sent, there is a timeout of 30 sec (configurable) for the ACK
- when a connection is closed the ACK cannot be sent back
- when edge is waiting for an ACK, its message pump (to that given route/module) is blocked
The problem of the customer is that time-to-time the M2M messages get delayed for 30seconds (then it catches up with the messages accumulated during that 30seconds period). They drive some sort of dashboard and this behavior is not acceptable.
The root of the problem was that …
> Eliminating 30 sec delay when M2M acknowledgment is interrupted by disconnection (#6836)

- scripts/linux/buildImage.sh
Docker recently introduced [provenance attestation](https://docs.docker.com/build/attestations/slsa-provenance/) in buildx 0.10.0, which broke our multi-arch image builds. By default, `docker buildx build` now defaults to `--provenance true` which causes even single-architecture images to be built as a manifest list (aka multi-arch image consisting of one architecture, according to this GitHub issue [comment](https://github.com/docker/buildx/issues/1509#issuecomment-1378538197)). When we use our older manifest-tool to create a manifest from three single-arch images (amd64, arm32v7, and arm64v8), the tool fails because it can't create a manifest list that points to other manifest lists.
To mitigate, we'll disable provenance attestation for now. In the future we should look at updating how …
> Fix image builds

- edgelet/support-bundle/src/support_bundle.rs
Readers will require ZIP64 support[^1].  Without this, generating a
support bundle for devices with large amounts of logs in the requested
time period will fail.
[^1]: https://docs.rs/zip/0.6.3/zip/write/struct.FileOptions.html#method.large_file
> [edgelet] Enable >4GB files in support_bundle ZIP writer

- edgelet/Cargo.lock
- edgelet/edgelet-settings/src/base/image.rs
- edgelet/iotedge/src/client.rs
- edgelet/iotedge/src/restart.rs
Fix the `iotedge restart` command so that it sends a stop request followed by a start request. This is necessary so that workload sockets are properly notified of the restart.
> Fix iotedge restart command with workload sockets

- edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/metrics/DeploymentMetrics.cs
edgeAgent metrics for expected and actual running were reversed
> Fix running and expected running values in edgeAgent metrics

- edgelet/build/linux/package-mariner.sh
Cargo.lock files present in the vendor directory will cause Component Governance to incorrectly scan those dependencies. Remove these files to prevent this.
> Purge Cargo.lock files from Mariner vendor dir

- edgelet/Cargo.lock
- edgelet/iotedge/src/client.rs
- edgelet/iotedge/src/restart.rs
Fix the `iotedge restart` command so that it sends a stop request followed by a start request. This is necessary so that workload sockets are properly notified of the restart.
> Fix iotedge restart command with workload sockets (#6891)

- edgelet/build/linux/package-mariner.sh
package-lock.json files in the Mariner build dependencies get incorrectly scanned by Component Governance. Delete these files so they are not scanned.
> Delete package-lock.json files from CG scans

- builds/release/refresh-metrics-collector-images.yaml
This change works around a problem that is specific to some of our release pipelines, which, prior to publishing the images, test arm32v7 Docker images on arm64v8 hosts to avoid using Raspberry Pis.
The problem, which cropped up recently when Docker changed its manifest format to support provenance attestation, is this: our arch-specific Docker images used to be manifests but now they're manifest lists with two entries, one pointing to the arch-specific manifest and the other pointing to provenance data. Because of this change, when the test agent's Docker daemon pulls the image, it sees the manifest list and attempts to select the appropriate manifest by matching a platform in the list to the host platform. Since we're testing arm32v7 images on arm64v8 hosts, 'arm/v7' != 'arm64/v8' and …
> Fix Metrics Collector release

- builds/release/refresh-metrics-collector-images.yaml
A recent change (2254c5e4d0dab7cadd9da066fe302410611aac7d) to a Metrics Collector release pipeline calls `docker buildx imagetools inspect` against an image in an internal Docker registry. The call fails because it can't access the registry. This update adds a Docker login task to give it access.
> Give Metrics Collector release task access to registry

- builds/release/refresh-metrics-collector-images.yaml
- scripts/linux/moveImage.sh
Our script to copy an image from one registry to another uses the push/tag/pull pattern, which works fine in simple scenarios. But with recent changes to the structure of our Docker images (specifically, our arch-specific images are now technically multi-arch images with a single architecture in them, because of the way Docker now embeds provenance attestation information in images), it is better to use newer tooling that seamlessly handles all the variations.
This change replaces the docker pull, tag, and push calls in moveImage.sh with a single call to `docker buildx imagetools create`.
To test, I ran the script locally on my machine and confirmed that an image was copied between two of our internal registries.
This checklist is used to make sure that common guidelines for a pull …
> Use newer tooling to copy image between registries

- builds/misc/images-publish.yaml
We recently updated buildManifest.sh to expect the --tags argument in proper JSON format (e.g., `["1.4", "latest"]`). Previously tags were in sorta-kinda JSON (e.g., `['1.4', 'latest']`, single quotes instead of double). When running the publish pipeline I discovered that it still sent the --tags arg to buildManifest.sh in the old format. This change updates the pipeline to use the new format.
I tested the script changes locally to ensure they produce the right value for the --tags argument.
> Fix temp sensor tags in publish pipeline

- edgelet/iotedge/src/check/checks/aziot_edged_version.rs
- edgelet/iotedge/src/error.rs
Implement timeout feature for iotedge latest version check. Tested manually. Example of failure:
```
Configuration checks
--------------------
√ aziot-edged configuration is well-formed - OK
√ configuration up-to-date with config.toml - OK
√ container engine is installed and functional - OK
× configuration has correct URIs for daemon mgmt endpoint - Error
Unable to find image 'mcr.microsoft.com/azureiotedge-diagnostics:1.4.920230303.5' locally
docker: Error response from daemon: manifest for mcr.microsoft.com/azureiotedge-diagnostics:1.4.920230303.5 not found: manifest unknown: manifest tagged by "1.4.920230303.5" is not found.
See 'docker run --help'.
× aziot-edge package is up-to-date - Error
Error while fetching latest versions of edge components: HTTP request timed out
× container …
```
> Iotedge Check: Timeout for aka.ms latest version http request

- edgelet/Cargo.lock
- edgelet/edgelet-docker/Cargo.toml
- edgelet/edgelet-docker/src/runtime.rs
- edgelet/iotedge/Cargo.toml
- edgelet/iotedge/src/check/additional_info.rs
Cherry-pick from (#6943)
Fixes several bugs related to reported system RAM and swap values:
1. Units conversion bug introduced by a recent upgrade from sysinfo v0.25 to v0.27, resulting in edgeAgent_total_memory_bytes and edgeAgent_used_memory_bytes for "module_name=host" being 1024 times higher than the value previously reported in iotedge v1.4.3.
2. Long-standing bug in edgeAgent_total_memory_bytes and edgeAgent_used_memory_bytes for "module_name=host", where the reported values were 1.024 times higher than the actual values. This was caused by incorrectly treating the values returned by sysinfo v0.25 as KiB instead of KB.
3. Long-standing bug in system info reported by 'iotedge check', where the total_ram, total_swap, used_ram, and used_swap values were 1.024 times higher than the …
> Fix memory and swap values reported by 'iotedge check' and edge agent

- edge-modules/metrics-collector/src/Microsoft.Azure.Devices.Edge.Azure.Monitor.csproj
This change patches the following vulnerabilities:
```
[net6.0]:
Transitive Package           Resolved   Severity   Advisory URL
> System.Data.SqlClient      4.3.1      Moderate   https://github.com/advisories/GHSA-8g2p-5pqh-5jmc
> System.Drawing.Common      4.7.0      Critical   https://github.com/advisories/GHSA-rxg9-xrhp-64gj
> System.Net.Http            4.3.0      High       https://github.com/advisories/GHSA-7jgj-8wvc-jh57
> System.Net.Security        4.3.0      Moderate   https://github.com/advisories/GHSA-ch6p-4jcm-h8vh
High       https://github.com/advisories/GHSA-6xh7-4v2w-36q6
High       https://github.com/advisories/GHSA-qhqf-ghgh-x2m4
Moderate   https://github.com/advisories/GHSA-j8f4-2w4p-mhjc
```
To test, I did the following from a command line and confirmed no …
> Patch vulnerabilities in Metrics Collector dependencies

- edge-modules/api-proxy-module/Cargo.lock
- edge-modules/api-proxy-module/rust-sdk/azure-iot-mqtt/Cargo.lock
This updates api-proxy to fix this component governance issue: https://msazure.visualstudio.com/One/_componentGovernance/95664/alert/8360837?typeId=13438129&pipelinesTrackingFilter=0
> Component Governance Fix

- scripts/linux/trcE2ETest.sh
Weirdly, we see a run where support bundle retries are exhausted. Bumping the retries to 10. …
> Connectivity Tests: Bump Support Bundle Retries

- builds/e2e/templates/nested-create-identity.yaml
- e2e_deployment_files/nestededge_isa95_smoke_test_BaseDeployment.json
- edgelet/build/linux/package.sh
The JSON config we deploy in our ISA95 pipeline has an invalid entry--Edge agent's `https_proxy` environment variable should be embedded inside an `env` object, but it isn't. I recently upgraded the azure-iot extension to Azure CLI on one of the test agents, and newer versions of the extension validate the JSON config before sending it to IoT Hub, so the tests started failing. To test, I confirmed that the ISA95 smoke test pipeline passes with this change.
This also fixes a problem that cropped up yesterday in our RHEL 9 packages builds. We build inside an RHEL 9 container, and git received a major update in the container's backing image which caused a `git archive` call to fail because the container's user (uid 0) is different from the mounted source folder's owner (uid 1000). I added a …
> Fix test JSON and RHEL package build

- builds/release/detect-image-updates.yaml
- builds/release/refresh-core-images.yaml
Cherry-pick a0f89a381d025cdaa38ff02ff495208d1ba50674.
To test, I ran the auto-detect pipeline and core images auto-refresh pipeline in a test environment and confirmed they behave as expected. I didn't go as far as forcing an image update; the auto-detect pipeline simply ran through the logic and determined there were no images to update. The core images auto-refesh pipeline was triggered as expected and quit when it determined there was no work to be done. This scenario required the least effort and tested most of the changes. Via inspection, I have reasonable confidence in the remaining changes. I also tested all of the jq statements in isolation, to ensure they parse and/or generate the expected JSON. …
> Support new image structure in auto-detect pipeline

- edgelet/contrib/enterprise-linux/aziot-edge.spec
Adding a requires clause to spec for rhel8 "Requires: (moby-engine or docker-ce)", as well as moving check for docker group to %post.
- [ x] I have read the [contribution guidelines](https://github.com/azure/iotedge#contributing).
- [ x] Title of the pull request is clear and informative.
- [ x] Description of the pull request includes a concise summary of the enhancement or bug fix.
- [] Pull request includes test coverage for the included changes.
- [x ] local testing done.  
_Note: We use the kodiakhq …
> RHEL8 spec update to require moby-engine or docker-ce

- builds/release/templates/publish-core-images.yaml
- scripts/linux/release-tools.sh
We currently have two auto-refresh pipelines
- Core images (edgeAgent, edgeHub, tempSensor, diagnostics) operates out of the release/1.4 branch
- Metrics collector operates out of main
Because of this separation, the two pipelines are able to operate independently, with one exception: they both need to update `product-versions.json` in the Azure/azure-iotedge repo.
Both pipelines were triggered yesterday at roughly the same time due to an update in the .NET Alpine base images. The metrics collector pipeline updated `product-versions.json` first, so by the time the core images pipeline tried to update it, it was no longer updating the head commit and the push failed to merge.
This change fixes the problem by syncing the latest changes before updating the JSON file. I suppose we could also …
> Fix core refresh pipeline

- builds/e2e/connectivity.yaml
Support ended for the release/1.1 branch in December 2022. I'm removing the schedule trigger from the connectivity pipeline's YAML so it won't run anymore.
> Remove schedule trigger from connectivity pipeline

- builds/e2e/connectivity.yaml
- builds/misc/ci-build.yaml
- builds/misc/templates/build-images.yaml
Per Microsoft policy, we need to run CodeQL static analysis regularly in our builds. It will run automatically in main if we simply set a variable on the job where the actual build occurs. This change does that. It also sets up a weekly scheduled run, in part to make sure that CodeQL runs on a regular basis. Note this PR sets up the schedule for main and release/1.4 branches, but it will need to be cherry-picked to the release/1.4 branch for the schedule to take effect there.
I also made an unrelated change: I removed the release/1.1 branch from the connectivity pipeline's weekly schedule, as that version of the product has been out of support for six months.
To test, I ran the Build CI pipeline against this PR and confirmed that it passes. CodeQL will run when it gets merged to main. …
> Enable CodeQL in Build CI pipeline

- builds/e2e/e2e.yaml
We tried to enable 1ES-hosted Ubuntu 22.04 agents (amd64 and arm64) in the end-to-end test pipeline a few months back, but we had to revert to custom agents because 1ES support for Ubuntu 22.04 wasn't quite there yet. Problems with amd64 have been resolved, so this change reintroduces the Ubuntu 22.04 amd64 1ES-hosted agent to the pipeline. This will allow us to decommision the corresponding custom agent and shed the associated overhead. Ubuntu 22.04 arm64 is still not ready, so we'll continue to use a custom agent there.
To test, I verified that the end-to-end test pipeline successfully uses a 1ES-hosted Ubuntu 22.04 amd64 agent.
> Enable 1ES-hosted Ubuntu 22.04 amd64 agent

- edge-util/src/es6numberserializer/NumberFastDToABuilder.cs
The CodeQL analayzer for our GitHub repo is detecting one of our C# files (edge-util/src/es6numberserializer/NumberFastDToABuilder.cs) as Java because a comment in the file's header overrides the heuristic. This change removes the comment so that the file is correctly identified as C#.
To test, I ran the [github-linguist](https://github.com/github-linguist/linguist) tool locally (this is the tool CodeQL uses) and confirmed that, with this change, no Java files are detected.
BEFORE:
```bash
azureuser@damonb-amd64-1-vm:~/iotedge$ github-linguist
74.23%  9531426    C#
21.50%  2761148    Rust
3.58%   459096     Shell
0.37%   47878      PowerShell
0.12%   15563      Dockerfile
0.11%   13615      Makefile
0.04%   5689       ANTLR
0.03%   4142       Java
0.02%   2536       Roff
```
AFTER: …
> Remove Java header comment

- builds/misc/templates/build-packages.yaml
- edgelet/build/linux/package-mariner.sh
Mariner builds have started failing recently because they install an older version of go that fails a recently-introduced version check (see microsoft/CBL-Mariner#5960 and microsoft/CBL-Mariner#5981).
This change updates the version of go we're using. It also replaces the agent images used for Mariner builds, from one-off, unmaintained images to our standard agent images (with enough disk space to complete the build).
To test, I ran the CI Build pipeline and confirmed the Mariner builds (amd64, arm64) pass.
> Fix Mariner builds

- builds/e2e/isa-95-smoke-test.yaml
- builds/e2e/templates/nested-isa95-lock.yaml
- builds/e2e/templates/nested-isa95-unlock.yaml
In the setup scripts for the ISA95 smoke test pipeline, an Azure CLI command makes a bad assumption about the returned JSON, causing it to fail. The run does not abort at that point, but later when the corresponding cleanup scripts attempt to undo the earlier setup operation, that call fails and aborts the run with an error.
This change (1) forces the run to abort if the setup commands fail, and (2) fixes the setup command so that it can handle the more complex JSON result we're seeing. I also did some clean up and formatting of the command syntax for consistency.
To test, I ran the ISA95 Smoke Test pipeline, confirmed that it passed, and that the lock/unlock network scripts behaved as expected.
- …
> Fix ISA95 smoke test pipeline

- edgelet/Cargo.lock
Updates edgelet's iot-identity-service dependency to the commit that added the fix for a bug causing socket file removal to fail when attempted on a directory instead of a file. See https://github.com/Azure/iot-identity-service/pull/544 for more details.
I tested the aziot-edge package built from this branch on an Ubuntu 20.04 VM to confirm the fix works.
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to …
> Remove socket path if it is a directory instead of a file

- builds/e2e/connectivity.yaml
- builds/e2e/e2e.yaml
- builds/e2e/templates/lock-test-agents.yaml
- builds/misc/packages-release.yaml
- builds/misc/templates/build-packages.yaml
Some of our CI/test/release pipelines are using 1ES-hosted agent images which are either outdated or unmaintained. To clarify, the "unmaintained" images still receive OS security patches, but they were originally built by hand and are not managed by our internal automated processes.
- CI build uses an unmaintained agent image to build Mariner 2.0 arm64
- Connectivity tests use outdated agent images
- End-to-end tests use an unmaintained agent image to test Mariner 2.0 arm64
- Nested end-to-end tests use an outdated agent image for some early test setup logic
- Package release pipeline uses an outdated agent image and an unmaintained agent image for post-release smoke tests
This change updates outdated agent images to the latest Ubuntu, and updates unmaintained agent images to their …
> Use up-to-date, maintained agent images in pipelines

- snap/snapcraft.yaml
This (in conjunction with proper runtime interface connections) should resolve the check failures.
> snapping: add docker permissions to configure hook

- builds/checkin/e2e-checkin.yaml
- builds/ci/dotnet.yaml
- builds/e2e/connectivity.yaml
- builds/e2e/e2e.yaml
- builds/e2e/isa-95-smoke-test.yaml
- builds/e2e/longhaul.yaml
- builds/e2e/nested-e2e.yaml
- builds/e2e/nested-longhaul.yaml
- builds/misc/addons-publish.yaml
- builds/misc/addons-release.yaml
- builds/misc/ci-build.yaml
- builds/misc/images-publish.yaml
- builds/misc/images-release.yaml
- builds/misc/packages-release.yaml
- builds/release/detect-image-updates.yaml
- builds/release/refresh-core-images.yaml
- builds/service/service-deployment.yaml
Cherry-pick cc943a9bb3eda9da9dea3c232acae420702b1872.
Note that we didn't cherry-pick d64b4d2f9460b41cb36054f533da82d3a1e0e697 because we're only going to run CodeQL in the main branch, per the internal recommendation.
> Don't run CodeQL in the release branch

- edge-modules/functions/samples/EdgeHubTrigger-Csharp/EdgeHubTriggerCSharp.csproj
The Azure Functions module sample hasn't been updated in a while. It still depends on a .NET Core 3.1-based version of the Microsoft.NET.Sdk.Functions package. To remove our dependency on .NET Core 3.1 (which is out of support), this change upgrades the package to the latest version, which is based on .NET 6.0.
To test, I ran CI Build to get the bits, and then ran the end-to-end test pipeline. The test "TempFilterFunc" tests basic functionality of this sample.
> Upgrade Functions sample to remove dependency on .NET Core 3.1

- builds/misc/packages-release.yaml
- scripts/linux/publishReleasePackages.sh
A script in our packages release pipeline referenced a variable using ADO pipeline variable syntax, which isn't available within a bash script. ADO makes pipeline variables available to bash scripts as environment variables with a certain naming convention, so I fixed the script by using that syntax instead.
I ran the release pipeline and confirmed that it succeeded.
> Fix variable reference in packages release script

- builds/e2e/e2e.yaml
When we first created 1ES-hosted agents for Ubuntu 22.04, 1ES didn't support arm64 yet so we only enabled amd64. Any issues have since been resolved, so this change enables arm64 agents for the end-to-end test pipeline.
> Use 1ES-hosted agent for Ubuntu 22.04 arm64

- builds/checkin/edgelet.yaml
- builds/e2e/templates/e2e-run.yaml
- test/Microsoft.Azure.Devices.Edge.Test/IoTEdgeCheck.cs
- test/Microsoft.Azure.Devices.Edge.Test/helpers/DeviceProvisioningFixture.cs
Cherry-pick 0ab3c0117e5a499d83f0c566739278d93f5109e9
Also, updated invocations of `cargo install cross` to use `--locked` because a cross dependency recently bumped its MSRV to 1.70, but our release branch still uses 1.65.
> Don't `docker login` from IotEdgeCheck test

- edgelet/contrib/debian/control
Ref: Azure/iot-identity-service#578
> Add psmisc dependency to Debian package since the postrm script uses it.

- snap/hooks/configure
- snap/snapcraft.yaml
migrate to base: core22. this also entails a slight shift in snapcraft syntax (documented [here](https://forum.snapcraft.io/t/micro-howto-migrate-from-core20-to-core22/30188))
> bump snap base to core22

- edgelet/Cargo.toml
While individual crates default to resolver v2 if they are E2021, workspaces are virtual manifests with no edition so they continue to default to resolver v1. cargo raises a warning about this but only sometimes, so this wasn't easily noticeable.
This change fixes the workspace manifest to use resolver v2.
> Fix workspace manifest to use E2021 resolver.

- edge-modules/api-proxy-module/docker/linux/arm32v7/Dockerfile
- edge-modules/api-proxy-module/docker/linux/arm64v8/Dockerfile
- scripts/linux/buildAPIProxy.sh
- scripts/linux/cross-platform-rust-build.sh
The base image of the module container uses `arm32v7/nginx` and `arm64v8/nginx` which are based on Debian 12, which uses OpenSSL v3. Before this change, we were building the binary itself in an Ubuntu 20.04 container so it would link to OpenSSL v1.1 instead and fail to run inside the Debian 12 containers.
This change fixes the build script to use a Debian 12 base image instead.
> Change API Proxy module build to use Debian 12 base image for ARM images.

- builds/e2e/e2e.yaml
- builds/e2e/longhaul.yaml
- builds/mariner/SPECS/aziot-edge/aziot-edge.spec
- builds/misc/packages-release.yaml
- builds/misc/templates/build-packages.yaml
- edgelet/Cargo.toml
- edgelet/build/linux/package-mariner.sh
- edgelet/build/linux/package.sh
- edgelet/contrib/centos/aziot-edge.spec
- edgelet/contrib/debian/rules
- edgelet/contrib/enterprise-linux/aziot-edge.spec
- scripts/local/test/DownloadIdentityService.ps1
- test/Microsoft.Azure.Devices.Edge.Test.Common/linux/PackageManagement.cs
This change updates our build pipelines to build edgelet with full debug symbols, and then have the various packaging systems generate a separate symbols package for each distro. For the deb-based distros, the new package is something like `aziot-edge-dbgsym_{ver}_{arch}.deb` (`.ddeb` on Ubuntu). For the rpm-based distros, the new package is something like `aziot-edge-debuginfo-{ver}.{distro}.{arch}.rpm`.
This change also updates the test and release pipelines to handle the new packages. For the test pipelines, we don't want to copy/install the symbol packages. For the release pipeline, we _do_ want to sign and stage the symbol packages, but we only publish them to the GitHub release page for now, not to packages.microsoft.com.
To test, I ran the various pipelines to make sure the work as …
> Add debug symbols to packages

- snap/snapcraft.yaml
Make sure the docker executable is in the $PATH
> snapping: docker path fix

- edgelet/Cargo.lock
We haven't updated iotedge@main's reference to iot-identity-service in a little while. Automation uses the reference to figure out which identity service package to download for test scenarios, but when the reference gets too old, GitHub Actions deletes the packages. The change updates the reference.
The checks for this PR will give the needed test coverage.
- [X ] I have read the [contribution guidelines](https://github.com/azure/iotedge#contributing).
> Update to the latest identity service commit ref

- builds/misc/packages-release.yaml
- builds/misc/templates/build-packages.yaml
- snap/snapcraft.yaml
The change fixes a few problems with the snap builds and release:
1. Snaps weren't built with SNAPCRAFT_BUILD_INFO enabled, so they didn't generate SBOM info. I added the flag to snap builds. Note this isn't a problem for the azure-iot-identity snap because it's built using the snap action in our GitHub workflow, which automatically adds this option.
2. Snaps were published to the edge channel in the release build. This was intentional the first time, but we want to publish directly to the stable channel from now on.
To test, I ran the CI build pipeline and verified that the snaps have an SBOM.
> Fix problems with snap release

- builds/e2e/e2e.yaml
- builds/e2e/templates/e2e-clear-docker-cached-images.yaml
We changed a service connection in some of our pipelines and a hard-coded reference broke. This change updates the reference to a pipeline variable like all the other references in the repo.
Also, we have some special templates which are invoked in the end-to-end test pipeline from jobs that run on custom, stateful agents. The templates clean up build files and Docker images that may be hanging around from previous runs. Over time, we've switched several jobs to use stateless agents, but those jobs continue to invoke the templates. I removed references where they're no longer needed.
To test, I ran the end-to-end test pipeline and verified that it passed.
> Get service connection name from pipeline variable

- scripts/linux/release-tools.sh
When the auto-refresh pipeline runs to update core module images (Edge Agent, Edge Hub, Simulated Temperature Sensor, and Diagnostics) following a base image update, we generate boilerplate text that goes into the [changelog](https://github.com/Azure/iotedge/blob/release/1.4/CHANGELOG.md) and the [GitHub release](https://github.com/Azure/azure-iotedge/releases). For no good reason, the message in the changelog is slightly different from the message in the release page--specifically, we prepend some extra information in the release page.
This change makes the two changelogs consistent. It will allow us to use a single pipeline for both manual and auto-refresh releases. I also updated the comment headers in a couple bash script functions to make it clear that they are usefull in both …
> Update changelog creation in auto-refresh image releases

- snap/snapcraft.yaml
This ensures that the snap's `rustup` honors `rust-toolchain.toml`.
[damonbarry] To test, I ran the CI Build pipeline against these changes and confirmed that snap builds pass.
> Fix snap builds

- edgelet/Cargo.lock
- edgelet/Cargo.toml
- snap/snapcraft.yaml
There isn't currently a good way to package debuginfo and symbols for snaps. Since we're building with full symbols in cargo and they aren't being stripped out during the snap build, our snap packages are much larger than they should be. This change disables the [debug](https://doc.rust-lang.org/cargo/reference/profiles.html#debug) setting in the cargo release profile for snaps only.
To test, I built the amd64 snap locally with these changes. It went from 78 MB down to 21 MB. I also ran ran the end-to-end tests against built packages and confirmed everything passes.
> Turn off debug symbols for snaps

- builds/e2e/isa-95-smoke-test.yaml
- builds/e2e/templates/lock-test-agents.yaml
- builds/e2e/templates/nested-get-secrets.yaml
- builds/e2e/templates/unlock-test-agents.yaml
- builds/misc/packages-release.yaml
Update the following build pipelines to be using Service Principal for authentication to resources endpoints instead of using the Service Account PAT:
- Nested pipelines
- ISA95
- Build release 
 
_Note: We use the kodiakhq bot to merge PRs once the necessary checks and approvals are in place. When it merges a PR, kodiakhq converts the PR title to the commit title, PR description to the commit description, and squashes all the commits in the PR to a single commit. The net effect is that entire PR becomes …
> Update pipeline to be using Service Principal instead of Service Account PAT

- CHANGELOG.md
The changelog in main was quite stale, so I brought it up to date with the latest 1.4 release. Then I updated it for 1.5.0.
> Prepare for release 1.5.0

- builds/misc/templates/build-packages.yaml
- scripts/linux/github/updateLatestVersion.sh
The Mariner arm64 build is currently failing. When it builds identity service bits, it tries to populate the version by getting the latest 1.5.* tag from the identity service repo. There are no 1.5.* tags yet, so it sends an empty version which causes `make` to fail.
The root cause is that we bumped our release version in code much sooner than we normally do (i.e., the period of time between bumping the version in code and actually publishing the bits is usually hours, but this time it's a couple weeks).
The fix is to extract the version from checked-in sources rather than git tag, since the tag isn't set until after we release.
To test, I ran the CI Build pipeline and confirmed that Mariner arm64 passes. …
> Get identity service version from source instead of tag

- builds/service/service-deployment.yaml
- test/Microsoft.Azure.Devices.Edge.Test.Common/linux/PackageManagement.cs
This pipeline should probably have been updated in #7262 but was missed. This change:
- Updates the pipeline to look for test binaries in the net8.0 folder.
- Removes the code that registers packages.microsoft.com. The pipeline runners already have it, and they register it as signed with a specific keyring file, which may clash with the older style of registration found in the tests. With this change, we assume that the caller has registered the repo as a prerequisite.
I've tested that the pipeline passes with this change.
> Fix Service Deployment pipeline

- scripts/linux/release-tools.sh
I noticed a problem today when .NET released new base images and our pipelines automatically triggered to update our core images. The pipeline created a release commit (locally, on the agent) with the updated changelog and versionInfo.json, but the commit failed to merge with the head of the branch, meaning we'll probably need to investigate the source of the merge problem, fix it manually, and re-run the pipeline--that's all fine. The problem is that the script _did_ manage to tag the release commit and push it upstream, so the pipeline re-run will fail to push the tag unless we manually clear it.
This change helps us prevent this problem in the future. It moves the tag push _after_ the merge commit push. I made the same change for both the core images release and the metrics collector …
> Push release commit before pushing tag

- test/Microsoft.Azure.Devices.Edge.Test/IoTEdgeCheck.cs
There was a period of a few weeks between when we updated the version in the code to 1.5.0 and when we actually shipped 1.5.0. During that window of time, one of the end-to-end tests would have failed so we added a workaround. Now that we've shipped 1.5.0, this change removes the workaround.
I ran the end-to-end tests and verified that the IotEdgeCheck test passes.
> Remove temporary workaround in end-to-end test for iotedge check

- builds/e2e/compare-compatibility.yaml
- builds/e2e/nested-e2e.yaml
- builds/e2e/templates/nested-clean-identity.yaml
- builds/e2e/templates/nested-create-identity.yaml
- builds/e2e/templates/nested-deploy-config.yaml
- builds/e2e/templates/nested-isa95-lock.yaml
- builds/e2e/templates/nested-isa95-unlock.yaml
- scripts/linux/nested-edge-deploy-agent.sh
Cherry-picked: https://github.com/Azure/iotedge/commit/9b41182a50a564f582941177feeddbca3ed7e18a
- Remove the client secret
- Workaround the DevOps task where az cli cannot authorize itself within bash script in AzCLI task …
> Remove client secret usage in pipelines (#7291)

- builds/e2e/templates/nested-get-root-ca.yaml
- builds/e2e/templates/nested-get-secrets.yaml
The nested test pipelines (ISA-95 smoke tests, Nested end-to-end tests, Connectivity tests) download a blob and use its contents as the basis for some cert operations related to IoT Edge. It seems like we should be generating these files at runtime, but for now we simply need to be able to access the blob storage account without using shared keys.
This change embeds the `az storage blob download ...` command in the AzureCLI task so it has access to an identity via the service connection. Then it updates the command to authenticate using the available identity, rather than using a SAS token.
To test, I disabled shared key access on the storage account, then I ran the ISA-95 smoke tests and confirmed that they're able to download the blob (and the tests pass).
This checklist is used to make …
> Use AzureCLI task to download blob

- edge-util/docker/linux/Dockerfile
Docker has been throttling anonymous pull requests on their default docker.io registry for some time. We've avoided throttling by eliminated most of our references to base images on docker.io, but we still have one or two. Recently, one of the remaining references--the alpine image we use to build RocksDb in a container--has been getting throttled as well.
This change updates the Dockerfile we use to build RocksDb. It updates the base image to a mirrored version on mcr.microsoft.com.
To test, I ran the CI Build pipeline and confirmed that RocksDB is successfully built. I also ran the end-to-end test pipeline against the built binaries to confirm they behave as expected.
- Description of the pull …
> Upgrade alpine image for building rocksdb

- builds/checkin/e2e-checkin.yaml
- builds/e2e/e2e.yaml
- builds/e2e/templates/e2e-run.yaml
- builds/e2e/templates/e2e-setup.yaml
- builds/e2e/templates/get-storage-uri.yaml
As fallout from changes introduced by https://github.com/Azure/iotedge/pull/7309, the internal Core E2E tests pipeline was broken with the following error:
This PR fixes that pipeline by pulling out the storage URI generation into a template and by generating the URI only once and passing it to all the platforms.
For testing, I ran the checkin pipeline and the core E2E pipeline against these changes and the pipelines passed.
> Move storage URI generation to a template so agents don't need to be updated with azcli 2.x

- edgelet/contrib/snap/socat.sh
- snap/snapcraft.yaml
This is an attempt to fix the  docker proxy issues reported in #7255 using the approaches discussed there.
The issues are:
1. If `docker-proxy.sock` already exists, `socat` fails to start. I wasn't able to reproduce this, but adding `unlink-early` to the options passed to `socat`  should remove any existing file first, see [socat's man page](https://linux.die.net/man/1/socat).
> CWunlink-early
Unlinks (removes) the file before opening it and even before applying user-early etc.
2. There's a race condition where the snap starts before docker is up and running (occurs after restarts):
```
systemd[1]: Started Service for snap application azure-iot-edge.aziot-edged.
systemd[1]: Started Service for snap application azure-iot-edge.docker-proxy.
azure-iot-edge.aziot-edged[873]: Making …
```
> Fix docker-proxy startup issues

- builds/e2e/e2e.yaml
A previous PR introduced this bug, and this PR fixes it.
> Change variable name from amd64 to arm64 to disable mariner runs

- builds/e2e/nested-e2e.yaml
This PR introduces the use of short-lived SAS tokens to get an identity using the AzureCLI task. The use of shared keys to access the blob storage account is now discouraged, prompting this change.
This is the manually triggered test run for this PR:
> Add token support to nested E2E

- test/Microsoft.Azure.Devices.Edge.Test.Common/linux/PackageManagement.cs
Following a recent fix in our snap packages, our end-to-end tests started to fail. The tests need to install the azure-iot-edge snap with --devmode, at least until we get approval to auto-connect the daemon-notify interface (in progress).
This change updates the install command in the end-to-end tests to prevent failures. I ran the end-to-end test pipeline and confirmed this fixes the failures.
> Install snaps with devmode in end-to-end tests

- test/Microsoft.Azure.Devices.Edge.Test.Common/linux/EdgeDaemon.cs
A recent change updated the some logic in the end-to-end tests to match the main branch, but an important detail was missed. The result is that end-to-end tests fail on Raspberry Pi in the release/1.4 branch because the tests don't recognize the device's operating system. This change corrects that problem.
I confirmed that the tests pass on Raspberry Pi with this change.
> Fix end-to-end test failures on Raspberry Pi

- edgelet/contrib/snap/socat.sh
- snap/hooks/configure
- snap/snapcraft.yaml
A recent fix to the azure-iot-edge snap (#7330) changed the daemon type of the docker-proxy service to `notify` to resolve install/startup timing issues. With that fix, docker-proxy now waits until it can establish communication with Docker before calling `systemd-notify --ready` to resume and allow aziot-edged to start.
A problem was discovered once the updated snap was published to the marketplace. If a user installs the snap without --devmode, docker-proxy startup fails with: "Got notification message from PID nnnn, but reception only permitted for main PID mmmm". This happens because systemd expects the `systemd-notify --ready` command to run in the service's main process, but bash runs it in its own process. Systemd can be configured to allow other options, but snapd doesn't expose …
> Fix snap startup error

- edgelet/docker-rs/src/apis/client.rs
When edged sends an image pull request to dockerd, it expects dockerd to respond with the HTTP response status code and headers within 30s. The image pull itself does not need to complete within those 30s, just the initial start of the HTTP response, after which dockerd streams JSON events in the response to indicate the pull progress.
We have one customer whose device is unable to pull module images from their remote container registry. This is because dockerd needs to check whether the image exists on the ACR before it sends the HTTP response status code, and this check itself takes ~45s or so. When edged times out and abandons the request after 30s, dockerd has different behavior depending on whether the image tag is `latest` or not:
- If the image tag is `latest`, dockerd continues to …
> Increase dockerd client timeout from 30s to 60s.

- builds/e2e/e2e.yaml
- builds/e2e/nested-e2e.yaml
- builds/misc/templates/build-packages.yaml
- edgelet/Cargo.lock
- edgelet/build/linux/package.sh
- edgelet/doc/devguide.md
- test/Microsoft.Azure.Devices.Edge.Test.Common/linux/EdgeDaemon.cs
This change updates the build and tests pipelines to support Ubuntu 24.04 amd64 and arm64v8. Specifically,
- Add Ubuntu 24.04 amd64 and arm64v8 jobs to the end-to-end tests pipeline.
- Update iot-identity-service repo references in Cargo.lock so we pick up the right packages in the end-to-end tests.
- Add Ubuntu 24.04 amd64 and arm64v8 to the packages build pipeline and related scripts.
- Update markdown docs and comments as needed.
- Update end-to-end test code to support Ubuntu 24.04 packages.
To test, I ran the CI Build and end-to-end test pipelines and confirmed they pass.
> Add support for Ubuntu 24.04

- edgelet/Cargo.lock
- edgelet/build/linux/package-mariner.sh
Mariner builds recently started failing because the Mariner toolkit upgraded its go dependency requirement to 1.21. This change updates go in Mariner builds.
To test, I ran the CI Build pipeline and confirmed that Mariner builds pass.
> Upgrade go to 1.21 for Mariner toolkit

- builds/e2e/e2e.yaml
1ES has added support for Ubuntu 24.04 x64, so we no longer need to use a custom agent. This change updates the end-to-end test pipeline to use a 1ES-hosted agent.
I ran the end-to-end tests against this PR and confirmed that the Ubuntu 24.04 x64 job runs on a 1ES-hosted agent and passes.
> Enable 1ES agent for Ubuntu 24.04 x64 end-to-end tests

- builds/e2e/e2e.yaml
A recent PR converted the Ubuntu 24.04 x64 end-to-end test job to use an ephemeral 1ES-hosted agent instead of a stateful custom agent. With this conversion, we should have removed steps from the job that are only needed for stateful agents, but it was missed. This update removes the steps.
I ran the end-to-end test pipeline against this PR and confirmed that the steps are removed and the job still passes.
> Remove unnecessary steps from Ubuntu 24.04 end-to-end job

- builds/checkin/dotnet.yaml
- builds/ci/dotnet.yaml
- builds/e2e/compare-compatibility.yaml
- builds/e2e/connectivity.yaml
- builds/e2e/templates/e2e-setup.yaml
- builds/e2e/templates/longhaul-setup.yaml
- builds/e2e/templates/nested-get-secrets.yaml
- builds/misc/templates/build-packages.yaml
- builds/service/service-deployment.yaml
The AzureKeyVault@1 and PublishCodeCoverageResults@1 tasks for Azure pipelines are deprecated. This change updates both tasks in YAML files across the codebase. It also updates the BuildQualityChecks task to the latest version.
I confirmed that deprecation warnings disappear from the affected pipelines.
> Upgrade deprecated pipeline tasks

- edgelet/iotedge/src/check/checks/aziot_edged_version.rs
Bugfix `iotedge check` where IoTEdge uses the version of aziot-identity-service as aziot-edge version which results in 
```
‼ aziot-edge package is up-to-date - Warning
Installed IoT Edge daemon has version 1.5.10 but 1.5.3 is the latest stable version available.
```
even if the latest version of IoT Edge daemon is installed on the machine.
Root cause:
The IoTEdge queries
https://github.com/Azure/azure-iotedge/blob/main/product-versions.json
for the latest info on each of the component. Currently, IoTEdge parses the wrong `component` instead of getting the version of `aziot-edge`, it gets `aziot-identity-service` version. The aziot-identity-service version is then compared against the 
aziot-edge installed version if it is the latest version.
Manual test with custom build ID: 
This …
> Check `aziot-edge` component instead of `aziot-identity-service`

- edgelet/iotedge/src/check/checks/aziot_edged_version.rs
A recent update (ca5b8af2152e181c438f304ee9bd1fb5e0f546fc) to `iotedge check` code fixed the way we calculate the expected current version of aziot-edged. This change makes the corresponding update to an error message in that part of the code.
> Fix error message in 'iotedge check'

- builds/e2e/connectivity.yaml
- builds/e2e/isa-95-smoke-test.yaml
- builds/e2e/longhaul.yaml
- builds/e2e/nested-e2e.yaml
- builds/e2e/nested-longhaul.yaml
- builds/release/detect-image-updates.yaml
- builds/service/service-deployment.yaml
v1.4 LTS is EOL on November 12, 2024. This change removes any scheduled triggers for pipelines in the release/1.4 branch so they won't continue to run after the EOL date.
Other trigger types to consider:
- PR triggers won't be disabled. The core team won't be filing PRs against the release/1.4 branch after the EOL date, and if they did, it's not a big deal if a pipeline or two run (and potentially fail). PRs from the community don't trigger pipelines without an approver from the core team.
- CI triggers don't need to be disabled. Instead, we'll make the branch read-only so that no changes can be pushed.
- There are no pipelines in the release/1.4 branch that declare pipeline completion triggers.
- …
> Remove schedule triggers for release/1.4

- edge-util/test/Microsoft.Azure.Devices.Edge.Util.Test.Common/TokenHelper.cs
Several unit tests started failing after the new year due to a hard-coded timestamp that was supposed to represent a valid future time, but is now in the past. This change updates the test code to generate a timestamp that is one year in the future relative to DateTime.Now. I confirmed the unit tests pass once more.
> Fix hard-coded timestamp in unit tests

- builds/e2e/e2e.yaml
- builds/e2e/longhaul.yaml
- builds/e2e/templates/e2e-setup.yaml
- builds/e2e/templates/longhaul-setup.yaml
- builds/misc/templates/build-packages.yaml
In the packages build pipeline we have separate build jobs with a lot of duplicated YAML for building Mariner 2.0 amd64 vs. arm64. This change consolidates the separate jobs into a single matrix job. Note this also means we're now building identity service for amd64, not just arm64, for consistency (and because we'll eventually build identity service in this pipeline for all platforms, not just Mariner). This change should put us in a better position when we add support for Mariner 3.0 soon.
Additionally, this change fixes a bug: for Mariner arm64 we were already building the identity service bits but were always building them from the head of the main branch, even though the iotedge repo might be expecting bits built from an older commit. This change syncs the identity repo to the right …
> Consolidate Mariner build jobs into a single matrix

- builds/checkin/edgelet.yaml
Within the last few days the itoedged checkin pipeline has started failing in the code coverage job. I'm not sure what changed with rust or cargo or the cargo-tarpaulin tool, but the tool is no longer happy with the environment. I was able to fix it by sourcing the cargo environment instead of manually setting `CARGO="${CARGO_HOME:-"$HOME/.cargo"}/bin/cargo"`.
> Fix iotedged checkin pipeline

- edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Integration.Test/AgentTestsBase.cs
- edge-util/test/Microsoft.Azure.Devices.Edge.Util.Test.Common/TypeNameSerializationBinder.cs
[Bug 30973440](https://msazure.visualstudio.com/One/_workitems/edit/30973440) and [Bug 30973442](https://msazure.visualstudio.com/One/_workitems/edit/30973442)
CodeQL issue: https://liquid.microsoft.com/codeql/issues/621b3860-9992-462a-8a9d-0a24593f51a5?copilot_promptid=E91B0CE9-0C1B-4AC2-8A46-33F49B67E058
This commit addresses a potential security vulnerability **within our test code and infrastructure** related to JSON deserialization by enhancing the type handling mechanism.
**Issue:**
The previous deserialization configuration was using `TypeNameHandling.Auto` in Newtonsoft.Json.  `TypeNameHandling.Auto` allows for automatic deserialization of types based on `$type` metadata embedded in the JSON.  If an attacker can control the JSON input, they can potentially inject malicious `$type` …
> Fix: Enhance JSON Deserialization Security - Mitigate TypeNameHandling Vulnerability

- builds/e2e/isa-95-smoke-test.yaml
- builds/e2e/nested-e2e.yaml
- builds/e2e/templates/e2e-clean-all-images.yaml
- builds/e2e/templates/nested-clean-identity.yaml
This change impacts the the Nested End-to-end Tests and ISA-95 Smoke Test pipelines. It deletes Docker containers and images when the pipelines complete so they don't hang around on the custom pipeline agent and potentially trigger warnings during vulnerability scans.
Note that, for the ISA-95 Smoke Test pipeline, I had to move the network unlock logic to a new location. The new logic to clean images needs to reacquire the custom L3/L4/L5 agents, however I found that the Azure Pipelines service lost it's connection to the agents so it couldn't assign them jobs unless I unlocked the network first. This actually makes more sense anyway; the Run_ISA95_test job starts by locking the network and ends by unlocking it. It's more symmetric now.
I also found that two expected variables in the …
> Clean up images when nested pipelines complete

- builds/checkin/api-proxy.yaml
- builds/checkin/dotnet.yaml
- builds/checkin/e2e-checkin.yaml
- builds/checkin/edgelet.yaml
- builds/ci/dotnet.yaml
- builds/misc/templates/build-images.yaml
- builds/misc/templates/build-packages.yaml
- builds/misc/templates/build-rocksdb.yaml
- builds/release/detect-image-updates.yaml
- builds/service/service-deployment.yaml
We recently upgraded several agents in our build pipelines from Ubuntu 20.04 to 24.04. It turns out that 1ES support for Ubuntu 24.04 is still in preview--I think this is why we're seeing lots of agent restarts. We're having to rerun pipelines several times to get a passing result.
This change downgrades agents to Ubuntu 22.04, which is supported by 1ES. In my testing, this eliminates the problem of agent restarts and makes our pipelines more reliable.
To test, I ran all the impacted pipelines and ensured they pass (checkin pipelines, CI build and test pipelines, Detect image updates, and Service deployment). I also ran the end-to-end tests against the bits from the CI build, and confirmed they pass. …
> Downgrade 1ES agents to Ubuntu 22.04

- builds/e2e/e2e.yaml
This change updates the Ubuntu 24.04 arm64 job in the end-to-end tests to use a 1ES-hosted agent instead of a custom agent. We created the corresponding 1ES-hosted image a while back but it didn't work because 1ES-internal software didn't support Ubuntu 24.04 arm64 at the time. That problem has since been resolved, so we can switch over now and decommision the custom agent VM we've been maintaining.
> Use 1ES-hosted agent for Ubuntu 24.04 arm64

- edge-modules/api-proxy-module/docker/linux/amd64/Dockerfile
- edge-modules/api-proxy-module/docker/linux/arm32v7/Dockerfile
- edge-modules/api-proxy-module/docker/linux/arm64v8/Dockerfile
The ADO release pipeline for this image ends up losing the +x mode bits on the binary because it uses ADO tasks that round-trip the binary through a .zip.
This went unnoticed in CI like the ISA95 pipeline, because those rely on images built by the regular build-images pipeline that does not have this problem, because it uses tasks that round-trip through a .tar instead.
> Fix API Proxy module build to mark the entrypoint executable.

- builds/release/detect-image-updates.yaml
For a given multi-platform image (say, Edge Agent or API Proxy), we currently auto-refresh the image only when _all_ corresponding base images are out of date. The _all_ vs. _any_ distinction isn't important for our .NET based images because they only have one (multi-platform) base image anyway. But API Proxy consists of three platform-specific images built from different base images. We need to refresh API Proxy when _any_ base image is out of date, otherwise vulnerabilities in, say, the arm64 image will go unpatched until there are also security patches for vulnerabilities in the arm32 and amd64 images.
This change updates our detection pipeline logic to mark a multi-platform image for refresh if any of its constituent base images are out of date.
To test, I ran the detection pipeline …
> Rebuild API Proxy when any arch-specific base image is out of date
